Add an Animation Resource
rupali-codes/LinksHub pull request #1011
Opened 2023-06-11 10:57 UTC by Sriparno08

## Fixes #982

## Changes proposed

I have added an animation resource to the website.

## Screenshots

![Screenshot 2023-06-11 162710](https://github.com/rupali-codes/LinksHub/assets/89148144/4b3c43a0-6767-43af-a09e-d2e3558bd5d5)

## Note to reviewers

This PR is part of GSSoC'23.

2023-06-11 14:11 UTC, CBID2 requested changes
Hi @Sriparno08! :) I gave a suggestion on how to improve your description! :)

2023-06-11 14:11 UTC, CBID2 commented on database/frontend/animations.json
> +        "description": "Animista is a CSS animation library and a place where you can play with a collection of ready-made CSS animations and download only those you will use.",
[Proofreading]
```suggestion
        "description": "Animista is a library where you can play with a collection of ready-made CSS animations.",
```

2023-06-11 15:12 UTC, Sriparno08 commented on database/frontend/animations.json
> +        "description": "Animista is a CSS animation library and a place where you can play with a collection of ready-made CSS animations and download only those you will use.",
Okay, let me fix it.

2023-06-11 15:13 UTC, Sriparno08 commented
Hey @CBID2, I have updated it. Have a look!

2023-06-11 16:41 UTC, CBID2 approved these changes
LGTM! :)

2023-06-11 17:04 UTC, ujjawaltyagii approved these changes

2023-06-11 19:35 UTC, rupali-codes submitted a review, later dismissed

2023-06-11 19:35 UTC, rupali-codes commented
@Sriparno08 could you please resolve conflicts?

2023-06-12 10:01 UTC, Sriparno08 commented
Fixed, @rupali-codes!

2023-06-12 11:07 UTC, rupali-codes approved these changes
thanks

2023-06-12 21:10 UTC, CBID2 approved these changes
LGTM! :)

2023-06-12 21:10 UTC, merged