remove silly mistakes like spelling mistakes, missing punctuation marks, grammatical mistakes
rupali-codes/LinksHub pull request #1012
Opened 2023-06-11 15:46 UTC by gulshanjakhon

## #1009

Closes #1009

## Changes proposed

## Screenshots
After removing all grammatical errors:

## Note to reviewers

I have carefully review all the code and find these silly mistakes, its difficult for me to take Screenshot having one minor error, so I open a PR.

2023-06-11 16:41 UTC, CBID2 requested changes
Hi @gulshanjakhon! :) I just made a proofreading suggestion. :)

2023-06-11 16:41 UTC, CBID2 commented on CONTRIBUTING.md
> +- [**Fork the Repo**](https://github.com/rupali-codes/LinksHub/fork). Then, create a branch for any issue that you are working on. Finally, commit to your work.
[Proofreading]
```suggestion
- [**Fork the Repo**](https://github.com/rupali-codes/LinksHub/fork). Then, create a branch for any issue that you are working on. Finally, start working! 😊
```

2023-06-11 17:11 UTC, gulshanjakhon commented
> 

hi @CBID2  please review now.

2023-06-11 17:15 UTC, CBID2 approved these changes
LGTM! :)

2023-06-11 17:20 UTC, gulshanjakhon commented
please assign gssoc23 label

Thank You

2023-06-11 21:34 UTC, CBID2 requested changes
Hi @gulshanjakhon! :) I just did another review of your pull request. There are some branch conflicts that need to be solved. Consider going to [Resolving a merge conflict on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) learn how to do that.

2023-06-12 04:30 UTC, gulshanjakhon commented
hey please check now

2023-06-12 04:33 UTC, CBID2 submitted a review, later dismissed
LGTM! 😀

2023-06-12 04:49 UTC, krishstwt approved these changes
LGTM

2023-06-12 11:18 UTC, rupali-codes commented on README.md
>  _We would love to have you, feel free to open issues and pull requests and Don't forget to leave a star⭐_
```suggestion
```

2023-06-12 21:13 UTC, CBID2 approved these changes
LGTM! :)

2023-06-13 18:06 UTC, ujjawaltyagii commented
> I'm just curious, why did you replace '*' with '-'? it does the same thing right?

@gulshanjakhon  ??
(also please resolve merge conflicts)

2023-06-13 18:07 UTC, ujjawaltyagii reviewed
@gulshanjakhon  ??
(also please resolve merge conflicts)

2023-06-13 18:49 UTC, gulshanjakhon commented
Hi @ujjawaltyagii @rupali-codes @CBID2 @krishstwt please review 
Thank you

2023-06-13 23:17 UTC, CBID2 submitted a review, later dismissed
LGTM!

2023-06-14 07:46 UTC, krishstwt reviewed
formatting issues 👍🏻

2023-06-14 07:46 UTC, krishstwt commented on database/other/podcasts.json
> +
this is a  empty line

```suggestion
```

2023-06-14 07:46 UTC, krishstwt commented on database/other/github.json
> +]
```suggestion
]

```

2023-06-14 07:46 UTC, krishstwt commented on database/frontend/online-code-editors.json
> +]
```suggestion
]

```

2023-06-14 08:08 UTC, CBID2 approved these changes
LGTM!

2023-06-14 09:32 UTC, gulshanjakhon commented
> formatting issues 👍🏻

resolve formatting issue

2023-06-15 07:32 UTC, merged