docs: add workflow to lock issue conversations
rupali-codes/LinksHub pull request #1023
Opened 2023-06-12 17:46 UTC by Anmol-Baranwal

## Fixes Issue

Resolved #966 

## Changes proposed

- Reference: https://github.com/dessant/repo-lockdown

## Code

```yml
name: 'Issue Lockdown'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3 # Reference: https://github.com/dessant/repo-lockdown
        with:
          close-issue: false
          process-only: 'issues'
          issue-labels: '🔒 locked'
          exclude-issue-labels: '🚀 ready'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we will add label as `🚀 ready`.
```

## Note to reviewers

- The bot will add the `🔒 locked` label before locking the conversation, and you can unlock the conversation by adding the `🚀 ready` label.
- If you prefer a different label, please let me know, and I will update it accordingly.

@rupali-codes 
Please review the workflow.

2023-06-12 17:49 UTC, CBID2 commented on .github/workflows/lock-issue.yml
> +            To reduce notifications, issues are locked. Your issue will be unlocked when we will add label as `🚀 ready`.
[Proofreading] 
```suggestion
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label, `🚀 ready`.
```

2023-06-12 17:50 UTC, CBID2 requested changes
Looks pretty good @Anmol-Baranwal! :) I just gave a suggestion on how to improve the issue comment.

2023-06-12 18:23 UTC, Anmol-Baranwal commented
Hi @ujjawaltyagii 
Since I am planning to add another workflow, I would like to provide it to you first, considering that I have already submitted a pull request for this issue. I kindly request you to let me know if you plan to work on implementing this feature, as it will undoubtedly be beneficial for the project.

This workflow will be an automated PR labeling system that will greatly simplify the pull request management process. By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`. Since I haven't come across this workflow before, it will be a significant contribution, and I encourage you to discuss it further with @CBID2 and @rupali-codes.

To implement this workflow, you will need to use two separate workflows: one for the main code and another for defining the conditions or values of different criteria. By dividing the workflow into these two parts, it allows for better organization and maintainability of the codebase.

2023-06-16 13:18 UTC, CBID2 commented
> Hi @ujjawaltyagii Since I am planning to add another workflow, I would like to provide it to you first, considering that I have already submitted a pull request for this issue. Please let me know if you plan to add this workflow, as it will undoubtedly be great for the project.
> 
> This workflow will be an automated PR labeling system that will greatly simplify the pull request management process. By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`. Since I haven't come across this workflow before, it will be a significant contribution, and I encourage you to discuss it further with @CBID2 and @rupali-codes.
> 
> To implement this workflow, you will need to use two separate workflows: one for the main code and another for defining the conditions or values of different criteria. By dividing the workflow into these two parts, it allows for better organization and maintainability of the codebase.

Hi @Anmol-Baranwal! :) For organizational purposes, I created two separate issues for the other workflows that you just suggested.

2023-06-17 10:04 UTC, rupali-codes approved these changes

2023-06-17 12:51 UTC, CBID2 approved these changes
LGTM!

2023-06-17 12:51 UTC, merged