feat: added git star button
rupali-codes/LinksHub pull request #1026
Opened 2023-06-12 18:40 UTC by Bhanuteja01

## Fixes Issue
Closes #768 

## Changes proposed
Added GitHub Star Button

## Screenshots
![Screenshot (9)](https://github.com/rupali-codes/LinksHub/assets/110540923/543674f3-7ff5-4cbe-a362-a100d2151780)

## Note to reviewers

2023-06-12 19:32 UTC, CBID2 approved these changes
Looks great @Bhanuteja01! :) I like the color on it

2023-06-12 19:44 UTC, krishstwt requested changes

2023-06-12 19:44 UTC, krishstwt commented on components/SocialMedia/SocialMediaIconsList.tsx
> +import { GitHubForkButton } from 'components/ForkButton/GitHubForkButton'
Everything looks great, but why was the code style of the document changed? Shouldn't that be a separate change/pr?

2023-06-12 19:51 UTC, Bhanuteja01 commented
> Looks great @Bhanuteja01! :) I like the color on it

thanks for appreciation

2023-06-13 16:02 UTC, rupali-codes reviewed
Thanks, but the color doesn't really match with LinksHub theme 👀

2023-06-13 19:42 UTC, CBID2 requested changes
Hi @Bhanuteja01. Your branch has merge conflicts, so I suggest solving them.

2023-06-14 02:17 UTC, Bhanuteja01 commented
> Thanks, but the color doesn't really match with LinksHub theme eyes

@rupali-codes  Should i change the colour or
Create issue to change the colour

2023-06-15 07:47 UTC, rupali-codes commented
> > Thanks, but the color doesn't really match with LinksHub theme eyes
> 
> @rupali-codes Should i change the colour or Create issue to change the colour

No, you don't have create new issue.

2023-06-15 07:54 UTC, rupali-codes commented on components/StarButton/GitHubStarButton.tsx
> +      <div className="inline-flex items-center px-4 py-1 text-sm font-semibold bg-transparent text-yellow-400 border border-yellow-400 border-transparent rounded-sm transition-colors shadow-md">
```suggestion
      <div className="inline-flex items-center px-4 py-1 text-sm bg-violet-500 text-white border border-dashed border-transparent rounded-sm transition-colors shadow-md hover:bg-transparent hover:border-violet-400 hover:text-violet-400">
```

Normal:
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/6089503a-683a-4b5e-8492-ca420bfc0543)

on Hover: 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/a9b74b35-3e66-4ef1-b790-96356f1a9af8)

2023-06-15 13:48 UTC, ujjawaltyagii approved these changes
Now It looks better !!

2023-06-16 11:16 UTC, CBID2 approved these changes
LGTM!

2023-06-16 11:16 UTC, merged