Add java in subcategory of Languages
rupali-codes/LinksHub pull request #1052
Opened 2023-06-15 19:26 UTC by devWonderkind

## Fixes Issue
#Closes 1051 

## Changes proposed

Add Subcategory Java in "Language" category
Add resource in Subcategory java of "Language"

## Screenshots

![linkshb](https://github.com/rupali-codes/LinksHub/assets/110322061/a123e532-becc-4ca5-aff9-2c89624f2f14)
 

## Note to reviewers

@CBID2 thanks for assigning the task. 
Please merge the PR.🙃

2023-06-15 19:27 UTC, CBID2 requested changes
Just need some improvement

2023-06-15 19:27 UTC, CBID2 commented on database/languages/java.json
> +        "description": "This is the official Java tutorial provided by Oracle, the company behind Java. It covers the basics of Java programming and provides comprehensive documentation on various Ja
[Proofreading]
```suggestion
        "description": "This is the official Java tutorial provided by Oracle, the company behind Java. It covers the basics of this programming language and provides comprehensive documentation on various Java topics.",
```

2023-06-17 10:12 UTC, rupali-codes approved these changes
thanks, lgtm

2023-06-17 12:52 UTC, CBID2 approved these changes
LGTM! :)

2023-06-17 12:52 UTC, merged