Added the cyberSecurity Field and related youtube channel vedios.
rupali-codes/LinksHub pull request #1095
Opened 2023-06-19 22:18 UTC by Owais24code

#928 Add the cybersecurity field
## Fixes Issue

## Changes proposed

- created a new folder in a database named cyberSecurity

- added files in the cyberSecurity folder 

 1. basic.json

1.  2. certificate.json

 3. tools.json
 4. platform.json

- created a new file inside the youtube folder

1. named cybersecurity and connected link some related youtube videos of cybersecurity.

- updated the files

1. types/index.ts
2. database/index.ts
3. database/data.ts

 ## Screenshots

## Note to reviewers

2023-06-22 06:56 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name": "THELINUXFOUNDATION",
```suggestion
        "name": "The Linux Foundation",
```

2023-06-22 06:56 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "description": "THELINUXFOUNDATION  is a website that provides complete knowledge of the linux operating system .",
```suggestion
        "description": "The Linux Foundation  is a website that provides complete knowledge of the linux operating system .",
```

2023-06-22 06:58 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name":"JAVAPOINT-COMPUTERNETWORK",
```suggestion
        "name":"Javatpoint Computer Network",
```

2023-06-22 06:59 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "description":"JAVAPOINT-COMPUTERNETWORK ,This is a complete Hub for mastering computer network",
```suggestion
        "description": "This platform covers all the concepts of computer network from basic-to-advanced level.",
```

2023-06-22 07:03 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "description":"OWASP gives details explaintion of cyber threat and how to rescue from it.",
```suggestion
        "description":"Owasp gives a detailed explanation of cyber threats and how to rescue from them.",
```

2023-06-22 07:04 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name":"OWASP-TOP-THREAT",
```suggestion
        "name":"Owasp",
```

2023-06-22 07:04 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name":"Malwarebytes",
```suggestion
        "name": "Malware Bytes",
```

2023-06-22 07:05 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "description":"Malwarebytes is website that provide information about malware and malicious software.",
```suggestion
        "description": "Malware Bytes is website that provides information about malware and malicious software.",
```

2023-06-22 07:06 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name":"CRYPTOGRAPHY-FORTINET",
```suggestion
        "name": "Fortinet",
```

2023-06-22 07:09 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "name":"CRYPTOGRAPHY-FORTINET",
Please remove this resource as it doesn't provide any specific context

2023-06-22 07:10 UTC, rupali-codes commented on database/cyberSecurity/basic.json
> +        "description":"TechTarget gives essential knowledge about Reverse Enginnering and about the stages of reverse engineering",
```suggestion
        "description": "TechTarget gives essential knowledge about Reverse Engineering and the stages of reverse engineering",
```

2023-06-22 07:11 UTC, rupali-codes commented on database/cyberSecurity/certificate.json
> +        "description":"CompTIA A+ is entry level certificate for the person who is new in cyber security field and it is also most recommend for beginner.",
```suggestion
        "description":"CompTIA A+ is entry level certificate for the person who is new in cyber security field and it is also  recommended for beginner.s",
```

2023-06-22 07:12 UTC, rupali-codes commented on database/cyberSecurity/certificate.json
> +        "description":"Cisco provides a computer network certificate to gain the knowledge of network and tools.",
```suggestion
        "description":"Cisco provides computer network certificates to gain the knowledge of networking and its tools.",
```

2023-06-22 07:13 UTC, rupali-codes commented on database/cyberSecurity/certificate.json
> +        "description":"Certified Ethical Hacker(CEH)  this certificate is help you gain good hand on skills on Ethical Hacking and knowledge about it .",
```suggestion
        "description":"Certified Ethical Hacker(CEH)  helps you to get good knowledge about Ethical Hacking.",
```

2023-06-22 07:14 UTC, rupali-codes commented on database/cyberSecurity/certificate.json
> +        "description":"CompTIA Security+ is mid level certificate for the person who has good basic knowledge in cyber security and it is also most recommend by professional.",
```suggestion
        "description":"CompTIA Security+ is mid level certificate for the person who have basic knowledge of cyber security.",
```

2023-06-22 07:15 UTC, rupali-codes commented on database/cyberSecurity/certificate.json
> +        "description":"CISSP is for the person who is interest in cloud security.",
```suggestion
        "description":"This certificate is recommended for the person who is interested in cloud security.",
```

2023-06-22 07:16 UTC, rupali-codes commented on database/cyberSecurity/platform.json
> +        "description":"HackTheBox platform provide learning experience with project on real world issue in cyber security and ethical hacking.",
```suggestion
        "description":"HackTheBox platform provides learning experience with projects on real world issues in cyber security and ethical hacking.",
```

2023-06-22 07:17 UTC, rupali-codes commented on database/cyberSecurity/platform.json
> +        "description":"Cybrary is accessible, affordable training platform provides curated career paths in cybersecurity, threat-informed training, and certification preparation.",
```suggestion
        "description":"Cybrary is accessible, affordable training platform that provides curated career paths in cybersecurity, threat-informed training and more",
```

2023-06-22 07:18 UTC, rupali-codes commented on database/cyberSecurity/tools.json
> +        "description":"Nmap known as Network Mapper is a free and open source utility for network discovery and security auditing",
```suggestion
        "description":"Nmap known as Network Mapper, is a free and open source utility for network discovery and security auditing",
```

2023-06-22 07:19 UTC, rupali-codes commented on database/cyberSecurity/tools.json
> +        "description":"Wireshark is a network packet analyzer, that capture live packet data from a network interface.",
```suggestion
        "description":"Wireshark is a network packet analyzer, that captures live packet data from a network interface.",
```

2023-06-22 07:19 UTC, rupali-codes commented on database/cyberSecurity/tools.json
> +        "description":"Metasploit is used as penetration testing tools, is a very powerful all-in-one tool for performing different steps of a penetration test.",
```suggestion
        "description":"Metasploit is used as penetration testing tool. Its a very powerful and  all-in-one tool for performing different steps of a penetration test.",
```

2023-06-22 07:20 UTC, rupali-codes commented on database/youtube/cybersecurity.json
> +        "description": "This channel shares knowledge about different cybersecurity, network threats and more in cybersecurity realted information.",
```suggestion
        "description": "This channel shares knowledge about different cybersecurity, network threats and more in cybersecurity related information.",
```

2023-06-22 07:21 UTC, rupali-codes commented on database/youtube/cybersecurity.json
> +        "description":"This channel provides knowledge about hacking , information security and also had free course related to ethical hacking.",
```suggestion
        "description":"This channel provides knowledge about hacking, information security and also have free courses for Ethical Hacking.",
```

2023-06-22 07:22 UTC, rupali-codes commented on types/index.ts
> +  | 'cyberSecurity'//owais
```suggestion
  | 'cyberSecurity'
```

2023-06-22 07:26 UTC, rupali-codes commented
Also, please format your code and resolve merge conflicts

2023-06-22 20:23 UTC, Owais24code commented
@rupali-codes Maam,
I have resolved all the conflicts and made the changes you listed above.
please review them and if they have not been updated please let me know.

2023-06-23 06:45 UTC, CBID2 requested changes
Made some proofreading suggestions

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/basic.json
> +        "description":"Owasp gives detailed explaintion of cyber threats and how to rescue from them.",
[Typos]
```suggestion
        "description":"Owasp gives detailed explanation of cyber threats and how to rescue people from them.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/basic.json
> +        "description": "TechTarget gives essential knowledge about Reverse Engineering and the stages of reverse engineering",
[Proofreading]
```suggestion
        "description": "TechTarget gives essential knowledge about Reverse Engineering",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/certificate.json
> +        "description":"CompTIA A+ is entry level certificate for the person who is new in cyber security field and it is also recommended for beginners.",
[Proofreading]
```suggestion
        "description":"CompTIA A+ provides entry-level certificates for beginners and people who just started their career in Cybersecurity.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/certificate.json
> +        "description":"Cisco provides computer network certificate to gain the knowledge of networking and its tools.",
```suggestion
        "description":"Cisco provides computer network certificate to help people gain the knowledge of networking and its tools.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/certificate.json
> +        "description":"Certified Ethical Hacker(CEH) helps you to get good knowledge about Ethical Hacking.",
[Question] How does this course teach this topic? Consider using this question to write a more detailed description of this resource.
```suggestion
        "description":"Certified Ethical Hacker(CEH) helps you learn about Ethical Hacking.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/certificate.json
> +        "description":"CompTIA Security+ is mid level certificate for the person who have basic knowledge of cyber security.",
```suggestion
        "description":"CompTIA Security+ is a mid-level certificate for the person who has basic knowledge about Cybersecurity.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/certificate.json
> +        "description":"This certificate is recommended for the person who is interested in cloud security.",
```suggestion
        "description":"This certificate is recommended for the person who is interested in learning about Cloud Security.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/platform.json
> +        "description":"Kali Linux is an open-source, Debian-based Linux distribution geared towards various information security tasks, such as Penetration Testing, Security Research, Computer Forens
```suggestion
        "description":"Kali Linux is an open-source, Debian-based Linux distribution product that is geared towards doing various information security tasks, such as Penetration Testing, Security Research, Computer Forensics, and Reverse Engineering.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/platform.json
> +        "description":"TryHackMe provides a hands on cybersecurity skill experience in real world.",
```suggestion
        "description":"TryHackMe provides people the opportunity to gain real hands-on experience in Cybersecurity.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/platform.json
> +        "description":"HackTheBox platform provides learning experience with projects on real world issues in cyber security and ethical hacking.",
```suggestion
        "description":"HackTheBox platform provides users an engaging learning experience with projects that focus on real-world issues in Cybersecurity and Ethical Hacking.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/platform.json
> +        "description":"Cybrary is accessible, affordable training platform that provides curated career paths in cybersecurity, threat-informed training and more.",
```suggestion
        "description":"Cybrary is an accessible, affordable training platform that provides curated career paths in Cybersecurity, threat-informed training, and more.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/tools.json
> +        "description":"Nmap known as Network Mapper, is a free and open source utility for network discovery and security auditing.",
```suggestion
        "description":"NMAP, also known as Network Mapper, is a free and open source utility for network discovery and security auditing.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/tools.json
> +        "description":"Burp Suite is a tool designed to support and speed up efficiency in penetration testing, CI/CD integration in DevOps with a proper reporting system.",
```suggestion
        "description":"Burp Suite is a tool designed to support and speed up efficiency in penetration testing and CI/CD integration in DevOps with a proper reporting system.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/cyberSecurity/tools.json
> +        "description":"Metasploit is used as penetration testing tools, Its a very powerful and all-in-one tool for performing different steps of a penetration test.",
```suggestion
        "description":"Metasploit is a very powerful all-in-one tool used for performing the different steps of a penetration test.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/youtube/cybersecurity.json
> +        "description": "This channel shares knowledge about different cybersecurity, network threats and more in cybersecurity related information.",
```suggestion
        "description": "This channel shares knowledge about different cybersecurity, network threats, and other cybersecurity-related information.",
```

2023-06-23 06:45 UTC, CBID2 commented on database/youtube/cybersecurity.json
> +        "description":"This channel provides knowledge about hacking, information security and also have free courses for Ethical Hacking.",
```suggestion
        "description":"This channel provides content about information security and free courses on Ethical Hacking.",
```

2023-06-23 14:12 UTC, Owais24code commented
@CBID2 @rupali-codes 
Corrected all proofreading errors and reviewed them.
please do a review.

2023-06-25 13:05 UTC, rupali-codes requested changes
Looks perfect though, could you please rename these files then we are ready to go!
* basic.json -> basics.json
* certificate.json -> certification.json
* platform.json -> resources.json _(since we already have resources.json, you may export it as cyberSecurityResources in **index.ts** file)_

Please let us know if you need any kinda help :)

2023-06-26 05:31 UTC, Owais24code commented
@rupali-codes  @CBID2 
made changes as you requested please review them and let me know if there are any more changes required to make.
thank you

2023-06-26 12:07 UTC, rupali-codes requested changes
can you please remove the checked files, because they are repetitive 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/9250fbcf-4616-4efc-bff1-a84ea8f5dc73)

2023-06-26 14:22 UTC, Owais24code commented
@rupali-codes done! deleted the file that was repetitive.

2023-06-27 03:09 UTC, CBID2 requested changes

2023-06-27 03:15 UTC, CBID2 submitted a review, later dismissed
LGTM

2023-06-27 08:25 UTC, rupali-codes reviewed
Please consider removing blank lines :)

2023-06-27 08:25 UTC, rupali-codes commented on database/data.ts
> +
```suggestion
```

2023-06-27 08:26 UTC, rupali-codes commented on database/index.ts
> +
```suggestion
```

2023-06-27 08:30 UTC, rupali-codes commented on types/index.ts
You have incorrectly updated this file, please checkout [this](https://github.com/rupali-codes/LinksHub/blob/main/types/index.ts) carefully.

2023-06-27 08:33 UTC, rupali-codes reviewed
Also, the _types_ should be updated as well, based on the previous files we have renamed. 

```sh
subcategory:
basic -> basics
certificate -> certification
platform -> resources
```

let me know if you need any kinda help :)

2023-06-30 09:46 UTC, k-deepak04 commented
@Owais24code please resolve the conflicts so that we can merge this pr

2023-06-30 16:26 UTC, Owais24code commented
@rupali-codes  @k-deepak04 Please review as, I have made all requested changes and resolved all the merge conflicts.

2023-06-30 16:37 UTC, Owais24code commented
@k-deepak04 
![Screenshot (1)](https://github.com/rupali-codes/LinksHub/assets/112776960/72776982-5df0-4196-9bf3-7716b6adcdab)

2023-06-30 20:02 UTC, k-deepak04 commented
@Owais24code it still has conflicts please resolve those

2023-07-01 08:52 UTC, Owais24code commented
> @Owais24code it still has conflicts please resolve those

@k-deepak04 can you please help with this "page is out of dated please start over" issue.

2023-07-01 20:51 UTC, Owais24code commented
@rupali-codes Sorry I cannot understand why PR merge has a problem and why vercel showing deployment failed.
can you please help me with this?
![Screenshot 2023-07-02 141939](https://github.com/rupali-codes/LinksHub/assets/112776960/7a32e369-f8bd-442d-9c8f-d9ac35c88694)

2023-07-02 05:38 UTC, k-deepak04 commented
> > @Owais24code it still has conflicts please resolve those
> 
> @k-deepak04 can you please help with this "page is out of dated please start over" issue.

@Owais24code I'd be happy to help you with the "page is out of date, please start over" issue. This error typically occurs when the webpage you are trying to access has expired or the information on the page is no longer valid. Here are a few steps you can try to resolve the problem:

Refresh the page: Sometimes, the error message appears due to a temporary issue. Try refreshing the page by pressing the F5 key or clicking the refresh/reload button on your browser.

Clear your browser cache: Cached files can sometimes cause conflicts and display outdated versions of web pages. Clearing your browser's cache can help resolve this issue. The process for clearing the cache varies depending on the browser you're using, but you can usually find the option in the browser's settings or preferences.

Try a different browser: If the issue persists, try accessing the page using a different web browser. This can help determine if the problem is specific to your current browser or if it's a more widespread issue.

Check for updates: Ensure that your browser is up to date. Outdated browser versions can sometimes cause compatibility issues with certain websites. Update your browser to the latest version available.

Contact the website owner: If none of the above steps resolve the issue, it's possible that the website itself is experiencing problems. Reach out to the website owner or administrator and inform them about the error you're encountering. They may be able to provide further assistance or fix the issue on their end.

try this

2023-07-02 06:05 UTC, rupali-codes commented
@Owais24code there you go
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/47145881-b587-421c-9175-c79dd6f4d277)

2023-07-03 03:56 UTC, CBID2 approved these changes
LGTM! :)

2023-07-03 11:53 UTC, k-deepak04 approved these changes

2023-07-03 17:30 UTC, closed without merging