chore: added resource for tailwindCSS in UI generators
rupali-codes/LinksHub pull request #1131
Opened 2023-06-24 06:05 UTC by kirtiraj22

## Fixes Issue : #1122 

## Changes proposed

- Added [Tailwind Awesome](https://www.tailwindawesome.com/?technology=3) to Frontend -> UI Generators

## Screenshots
![Screenshot (171)](https://github.com/rupali-codes/LinksHub/assets/83873093/bf7fd9ff-6d8d-4809-ad4f-bfef51f6e976)

## Note to reviewers
This PR is a part of **GSSoC'23**

2023-06-24 06:33 UTC, CBID2 commented on database/frontend/ui-generators.json
> +    "description":"Tailwind Awesome is a curated list of the best Tailwind templates & UI kits in the internet.",
[Typo]
```suggestion
    "description":"Tailwind Awesome is a curated list of the best Tailwind templates & UI kits on the internet.",
```

2023-06-24 06:33 UTC, CBID2 requested changes
Found a typo that needs to be changed.

2023-06-24 06:46 UTC, kirtiraj22 commented
Hey @CBID2, I have written the description based on the information provided on the Tailwind Awesome website itself!

you can checkout the website's description here [Tailwind Awesome](https://www.tailwindawesome.com/?technology=3)

2023-06-24 06:50 UTC, kirtiraj22 commented
hey @CBID2, I have made the required changes kindly review it!

2023-06-24 06:51 UTC, CBID2 commented
> Hey @CBID2, I have written the description based on the information provided on the Tailwind Awesome website itself!
> 
> 
> 
> you can check out the website's description here [Tailwind Awesome](https://www.tailwindawesome.com/?technology=3)

Hey @kirtiraj22. I saw the link you provided. I still recommend making the change. More often than not, a website’s content doesn't always present things correctly whether it’s grammar or information about a topic, so it's crucial to critically evaluate it before accepting it. 😄

2023-06-24 06:52 UTC, CBID2 approved these changes
LGTM! Remember, question the information you see as you find more resources! :)

2023-06-24 07:06 UTC, kirtiraj22 commented
> Collaborator
Apologies, I will ensure to be more cautious and evaluate the content thoroughly next time. 😄

2023-06-25 12:09 UTC, rupali-codes approved these changes
thanks, lgtm

2023-06-25 12:10 UTC, merged