Added youtube playlist link for android development
rupali-codes/LinksHub pull request #1146
Opened 2023-06-25 12:41 UTC by madhurafulkar

##1104
Closes #1104 

## Changes proposed

Added youtube playlist link for android development

## Screenshots
![Screenshot 2023-06-25 180723](https://github.com/rupali-codes/LinksHub/assets/120560129/0f8342fa-c4a5-46c1-8f06-40545b271376)

## Note to reviewers

2023-06-26 14:29 UTC, CBID2 requested changes
Hi @madhurafulkar! 😄 Aside from the proofreading error in my in-line comment, you are off to a great start.

2023-06-26 14:29 UTC, CBID2 commented on database/youtube/android.json
> +    "description": "This android tutorials in Hindi explains how android applications are built using Android studio. In this Android Java Course one can learn how android applications are built usin
[Typo]
```suggestion
    "description": "In this Android Java Course, one can learn how Android applications are built using programming in Java and XML.",
```

2023-06-27 04:31 UTC, CBID2 approved these changes
LGTM

2023-06-29 04:50 UTC, ujjawaltyagii approved these changes
lgtm

2023-06-29 04:59 UTC, merged