Update game-development.json
rupali-codes/LinksHub pull request #1153
Opened 2023-06-25 13:39 UTC by ojasaklechayt

## Fixes Issue
#1127

## Changes proposed
Added youtube playlist for the game development.

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/90605717/cf45af6d-e5b1-4c53-b4eb-54a1fc0d5e5c)

## Note to reviewers
I have asked to assign this to me in the issue itself.

2023-06-25 14:02 UTC, rupali-codes requested changes
could you please format the code?

2023-06-25 15:43 UTC, ojasaklechayt commented
> could you please format the code?

Where should I make the changes ?

2023-06-27 18:49 UTC, CBID2 commented on database/youtube/game-development.json
> +    "description": "Videos that look at the fundamental lessons of game design, applicable to pretty much every type of game. It is playlist created by Mark Brown a well know game developer",
[Proofreading]
```suggestion
    "description": "This playlist consists of videos where Mark Brown, a well-known game developer, teaches you the fundamental lessons of game design. These videos are applicable to pretty much every type of game.",
```

2023-06-27 18:50 UTC, CBID2 requested changes
Hi @ojasaklechayt! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly before making a pull request. Other than that, you're off to a great start! :)

2023-06-28 10:49 UTC, ojasaklechayt commented
> Hi @ojasaklechayt! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly before making a pull request. Other than that, you're off to a great start! :)

I have made the changes 👍🏽

2023-06-28 18:20 UTC, rupali-codes reviewed
could you please format the code _(the braces)_?

2023-06-29 09:02 UTC, ojasaklechayt commented
> could you please format the code _(the braces)_?

Done Ma'am

2023-06-29 11:49 UTC, rupali-codes approved these changes

2023-06-29 11:50 UTC, CBID2 approved these changes
Lgtm

2023-06-29 11:52 UTC, merged