Added PostgreSQL to backend/database by Parmesh Bhatt
rupali-codes/LinksHub pull request #1169
Opened 2023-06-26 05:50 UTC by Parmesh119

Closes #1132 

## Changes proposed
I have added the PostgreSQL/database in the backend category.
Please review it and If it is fine, please merge it to the main branch.

## Screenshots

## Note to reviewers

2023-06-27 01:37 UTC, CBID2 commented on database/backend/database.json
> +    "description": "PostgreSQL is a free, open-source relational database and it is handling structured data and widely used database management system. ",
[Proofreading] 
```suggestion
    "description": "PostgreSQL is a free, open-source relational database that handles structured data and a widely used database management system. ",
```

2023-06-27 01:54 UTC, CBID2 requested changes
Hi @Parmesh119! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through [Grammarly](https://www.grammarly.com/grammar-check) before making a pull request. Other than that, you're off to a great start! :)

2023-06-27 12:29 UTC, Parmesh119 commented
> Hi @Parmesh119! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through [Grammarly](https://www.grammarly.com/grammar-check) before making a pull request. Other than that, you're off to a great start! :)

Ok

2023-06-29 11:59 UTC, rupali-codes approved these changes

2023-06-29 13:03 UTC, CBID2 approved these changes
LGTM

2023-06-29 13:04 UTC, merged