Vue.js Documentation are Added Under Official Docs
rupali-codes/LinksHub pull request #1184
Opened 2023-06-28 05:45 UTC by Nishitbaria

Vue.js Documentation are Added in Official Docs in Resources

## Fixes Issue
Closes  #1181 

## Changes proposed

Official Documentation for Vuejs is added under Offical Docs Section
## Screenshots

## Note to reviewers

2023-06-29 07:06 UTC, Nishitbaria commented
@rupali-codes  Please review and merge  my pull request

2023-06-29 12:43 UTC, rupali-codes commented on database/resources/official-docs.json
> +    "description": "This page contains comprehensive documentation of Vue.js, it's the progressive JavaScript framework.",
```suggestion
    "description": "This page contains comprehensive documentation of Vue.js. Vue.js is an progressive JavaScript framework.",
```

2023-06-29 12:58 UTC, Nishitbaria commented
Hey @rupali-codes I make the Necessary changes

2023-06-29 14:50 UTC, CBID2 requested changes
Just a small proofreading error

2023-06-29 14:50 UTC, CBID2 commented on database/resources/official-docs.json
> +    "description": "This page contains comprehensive documentation of Vue.js. Vue.js is an progressive JavaScript framework.",
[Proofreading]
```suggestion
    "description": "This page contains comprehensive documentation of Vue.js, a progressive JavaScript framework.",
```

2023-06-30 05:20 UTC, CBID2 approved these changes
LGTM

2023-06-30 08:55 UTC, k-deepak04 approved these changes
LGTM

2023-06-30 08:55 UTC, merged