Adding 100 days of machine learning playlist
rupali-codes/LinksHub pull request #1198
Opened 2023-06-29 09:02 UTC by Pro-18

closes #1151

## Screenshots

![100](https://github.com/rupali-codes/LinksHub/assets/92087279/cbdfc24a-b37a-4e67-b938-838f12381e5d)

2023-06-29 12:58 UTC, rupali-codes reviewed
please don't commit changes of your previous PR. Also, work on one issue at a time and don't forget to checkout our contributing guidelines. Thanks

2023-07-01 05:43 UTC, k-deepak04 approved these changes

2023-07-01 05:44 UTC, k-deepak04 commented
@CBID2 please review this and merge it

2023-07-01 05:46 UTC, CBID2 requested changes
Hi @Pro-18! :) Just made a suggestion for improvement

2023-07-01 05:46 UTC, CBID2 commented on database/languages/python.json
> +        "description": "Live examples will help you learn Python. This tutorial covers file handling, various modules, Matplotlib, machine learning, MongoDB, and MySQL.",
[Proofreading]
```suggestion
        "description": "This Python tutorial covers file handling, various modules, Matplotlib, machine learning, MongoDB, and MySQL.",
```

2023-07-03 03:37 UTC, CBID2 commented
@Pro-18, please resolve the merge conflicts in your branch

2023-07-03 17:12 UTC, closed without merging

2023-07-07 11:45 UTC, rupali-codes commented
@Pro-18 are you still willing to work on this issue?