Added : AI Course by Prof. Mausam from IIT Delhi
rupali-codes/LinksHub pull request #1247
Opened 2023-07-07 16:38 UTC by PriyansuMaurya

## Fixes Issue
#1190

## Changes proposed

## Screenshots

## Note to reviewers

2023-07-08 14:27 UTC, CBID2 approved these changes
LGTM!

2023-07-08 18:03 UTC, k-deepak04 approved these changes

2023-07-09 14:44 UTC, rupali-codes requested changes
@PriyansuMaurya could you please rename the file to _artificial-intelligence.json_ from _ai.json_. Also, please update the subcategory from _ai_ to _artificial-intelligence_

2023-07-09 16:14 UTC, rupali-codes approved these changes

2023-07-09 16:18 UTC, merged