Added youtube resource for android development
rupali-codes/LinksHub pull request #1251
Opened 2023-07-08 04:32 UTC by madhurafulkar

## Fixes Issue

Closes #1148 

## Changes proposed

Added youtube resource for android development

## Screenshots

![Screenshot 2023-07-08 100011](https://github.com/rupali-codes/LinksHub/assets/120560129/e98e3da2-8673-40c5-a1ec-74ec0967e7f7)

## Note to reviewers

2023-07-08 14:25 UTC, CBID2 requested changes
Just made a proofreading suggestion. Other than that, good start! :)

2023-07-08 14:25 UTC, CBID2 commented on database/youtube/android.json
> +    "description": "In this Android Java Course you can learn complete Android Development by Full Stack Android Developer",
[Proofreading]
```suggestion
    "description": "In this Android Java Course, you learn Android Development to become a Full Stack Android Developer",
```

2023-07-09 14:47 UTC, rupali-codes approved these changes
lgtm

2023-07-09 16:37 UTC, CBID2 approved these changes
LGTM! 😊

2023-07-10 18:53 UTC, merged