fossbytes
rupali-codes/LinksHub pull request #1268
Opened 2023-07-09 12:40 UTC by Shreya111111

## Fixes Issue
fixes #1255

## Changes proposed
Added fossbytes platform under resource section in blogs.

## Screenshots

![Screenshot 2023-07-09 180914](https://github.com/rupali-codes/LinksHub/assets/95047638/acf01c5d-a9cf-4966-88ed-2cbf91976cc0)

## Note to reviewers
Kindly review it under gssoc'23

2023-07-09 12:42 UTC, Shreya111111 commented
@CBID2 and @k-deepak04 kindly review issue #1255 and pr #1268 under gssoc'23

2023-07-09 18:00 UTC, k-deepak04 submitted a review, later dismissed

2023-07-10 06:49 UTC, Shreya111111 commented
@rupali-codes kindly review and merge the PR

2023-07-10 10:22 UTC, CBID2 commented on database/resources/blogs.json
> +    "description": "Fossbytes is a technology news and information platform that focuses on delivering the latest insights on various aspects of the tech world.",
[Proofreading]
```suggestion
    "description": "Fossbytes is a platform that focuses on delivering the latest insights on various aspects of the tech world.",
```

2023-07-10 10:30 UTC, Shreya111111 commented on database/resources/blogs.json
> +    "description": "Fossbytes is a technology news and information platform that focuses on delivering the latest insights on various aspects of the tech world.",
ok

2023-07-10 11:24 UTC, Shreya111111 commented
@k-deepak04 I have made some changes said by @CBID2 kindly re-review it

2023-07-10 18:26 UTC, Shreya111111 commented
@k-deepak04 can plz review this again as i have made some changes

2023-07-10 18:34 UTC, k-deepak04 approved these changes

2023-07-10 18:35 UTC, k-deepak04 commented
@Shreya111111 done

2023-07-10 19:11 UTC, Shreya111111 commented
@rupali-codes can u kindly review and merge this

2023-07-11 16:23 UTC, CBID2 commented
There's some conflicts that need to fix

2023-07-11 17:39 UTC, Shreya111111 commented
@CBID2 I think that was another PR . In this PR,I  changed everything that you mentioned

2023-07-11 17:43 UTC, Shreya111111 commented
Done necessary additions and deletions
![Screenshot 2023-07-11 231206](https://github.com/rupali-codes/LinksHub/assets/95047638/4f4da92f-88c7-43c4-94f7-cb4333fefd22)

2023-07-11 18:18 UTC, CBID2 commented
> Done necessary additions and deletions
> 
> ![Screenshot 2023-07-11 231206](https://github.com/rupali-codes/LinksHub/assets/95047638/4f4da92f-88c7-43c4-94f7-cb4333fefd22)
> 
> 
@Shreya111111 
![proof](https://github.com/rupali-codes/LinksHub/assets/105683440/c7bebea8-0506-411d-9474-c600853f7c0b)

2023-07-11 21:55 UTC, CBID2 requested changes
Hi @Shreya111111! :) Your branch still has merge conflicts.

2023-07-12 11:49 UTC, closed without merging