Added description in i button.
rupali-codes/LinksHub pull request #1294
Opened 2023-07-14 09:55 UTC by PiyushK79

Fixes issue #1284 

Added descriptions for all categories.
@rupali-codes Please review it and merge it with the main branch.

2023-07-15 02:26 UTC, CBID2 approved these changes
LGTM! :)

2023-07-15 15:20 UTC, k-deepak04 requested changes
@PiyushK79 deployment is failing, @rupali-codes please provide him related message so that he can figure out what's going wrong.

2023-07-19 06:00 UTC, rupali-codes commented
@PiyushK79 hope this helps

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/84e9f73a-f3eb-4f91-9991-16d7c893d53e)

2023-07-19 06:37 UTC, PiyushK79 commented
Alright, I will look into it.

2023-07-23 11:24 UTC, Anmol-Baranwal requested changes
@PiyushK79 

According to me, this is what causing the issue.

Adjust the parenthesis due to conflicting from the wrapped ones.

This would likely fix the issue.

2023-07-23 11:24 UTC, Anmol-Baranwal commented on components/TopBar/CategoryDescriptions.ts
> +  hosting: 'Web hosting is an online service that makes your website's content accessible on the internet. When you purchase a hosting plan, you are renting space on a physical server to store all th
```suggestion
  hosting: 'Web hosting is an online service that makes your websites content accessible on the internet. When you purchase a hosting plan, you are renting space on a physical server to store all the files and data.',
```

2023-07-25 09:26 UTC, rupali-codes approved these changes
thanks, lgtm

2023-07-25 09:27 UTC, merged