feat: Interviewbit
rupali-codes/LinksHub pull request #1338
Opened 2023-07-19 04:24 UTC by NarendraKoya999

## Fixes Issue No : #1305 

## Changes proposed

- **Added Interviewbit Object in online-code-editors.json File in frontend Category for Learn and Practice Programming with Different Programming Languages using Online IDE Editor**

## Screenshots

## Note to reviewers

- **Additionally, This Interviewbit also Provides Bunch of Topics like DSA, Cheatsheets, Interview Questions**

2023-07-19 07:39 UTC, NarendraKoya999 commented
Hi @CBID2 . I have raised PR. Please check and Review on It. If Merged, Please add appropriate Labels to that PR

2023-07-19 12:38 UTC, CBID2 requested changes
Made some suggestions on how to improve your descriptions @NarendraKoya999

2023-07-19 12:38 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "Everything you need to crack your Next Tech Interview",
[Typo]
```suggestion
    "description": "Everything you need to crack your next tech interview is provided in this website",
```

2023-07-19 12:42 UTC, CBID2 approved these changes
LGTM! :)

2023-07-20 17:04 UTC, k-deepak04 approved these changes

2023-07-20 17:05 UTC, merged