Added Good First Issues Tool In The Open Source Tools Subcategory
rupali-codes/LinksHub pull request #1349
Opened 2023-07-19 07:18 UTC by tayyab-ilyas

## Closes #1330 

## Changes proposed

- Added the good first issue tracker tool in the opensource tools subcategory.

## Screenshots

<img width="1118" alt="linksHub1" src="https://github.com/rupali-codes/LinksHub/assets/110786036/4564cfc8-4fb1-43f3-b1ef-6cd5267a46d1">

## Note to reviewers

2023-07-19 12:44 UTC, CBID2 requested changes
Made a suggestion on how to improve your description @tayyab-ilyas! :)

2023-07-19 21:22 UTC, tayyab-ilyas commented on database/open_source/tools.json
> +    "description":"Looking for good first issues according to your tech stack? This website will help you find them.",
thank you @CBID2

2023-07-20 04:26 UTC, CBID2 approved these changes
LGTM! :)

2023-07-20 21:34 UTC, tayyab-ilyas commented
hey @rupali-codes , can you review this? thanks!

2023-07-21 10:25 UTC, k-deepak04 approved these changes

2023-07-21 10:26 UTC, merged