chore: Added Quine Resources
rupali-codes/LinksHub pull request #1351
Opened 2023-07-19 11:19 UTC by Avdhesh-Varshney

## Fixes Issue - 1188

Closes #1188 

## Changes proposed

Added quine resources

https://www.youtube.com/playlist?list=PLnCV5fTAsUgpaLMY_Z8FqPxZ89v-_pcfY

## Screenshots

## Note to reviewers

2023-07-19 11:19 UTC, Avdhesh-Varshney commented
@rupali-codes @CBID2 please review this pr

2023-07-19 12:33 UTC, CBID2 approved these changes
LGTM!

2023-07-25 09:33 UTC, rupali-codes commented on database/open_source/blogs.json
> +    "subcategory": "opensource_blogs"
```suggestion
    "subcategory": "open-source-blogs"
```

2023-07-25 09:34 UTC, rupali-codes commented on database/open_source/blogs.json
> +    "category": "opensource",
```suggestion
    "category": "open source",
```

2023-07-25 13:29 UTC, k-deepak04 requested changes
do the needful naming convention cahnges suggested

2023-07-25 20:20 UTC, k-deepak04 approved these changes

2023-07-26 04:10 UTC, k-deepak04 commented
@rupali-codes plz review and merge this

2023-07-30 22:33 UTC, CBID2 approved these changes
LGTM! :)

2023-07-30 22:34 UTC, merged