Add Passportjs
rupali-codes/LinksHub pull request #1353
Opened 2023-07-19 20:06 UTC by AlfiyaSiddique

## Fixes Issue
Issue #1333 
closes #1333

## Changes proposed
Add the Passport authentication middleware in the backend authentication category

## Screenshots

![1](https://github.com/rupali-codes/LinksHub/assets/86224794/9ee6bd8d-7c02-4b30-a1fb-f2c6594515a9)

## Note to reviewers
Please merge this pr with gssoc23 labels

2023-07-20 00:58 UTC, CBID2 requested changes
Hi @AlfiyaSiddique. I provided a suggestion on how to improve your description.

2023-07-20 00:58 UTC, CBID2 commented on database/backend/authentication.json
> +    "description": "Passport is authentication middleware for Node.js. Extremely flexible and modular, Passport can be unobtrusively dropped in to any Express-based web application. A comprehensive s
```suggestion
    "description": "Passport is authentication middleware for Node.js. Extremely flexible and modular, this tool can be unobtrusively dropped in to any Express-based web application. It also provides a comprehensive set of strategies support authentication for a username and password, Facebook, Twitter, and more.",
```

2023-07-20 06:33 UTC, AlfiyaSiddique commented
@CBID2 Thanks for the suggestions. 👍🏻
Improved the description

2023-07-20 11:41 UTC, CBID2 requested changes
Made another suggestion for improvement

2023-07-20 11:41 UTC, CBID2 commented on database/backend/authentication.json
> +    "description": "Passport is authentication middleware for Node.js. Extremely flexible and modular, this tool can be unobtrusively dropped in to any Express-based web application. It also provides
[Proofreading]
```suggestion
    "description": "Passport is authentication middleware for Node.js. Extremely flexible and modular, this tool can be unobtrusively dropped in to any Express-based web application. It also provides a comprehensive set of support authentication strategies for usernames, passwords, Facebook, Twitter, and more.",
```

2023-07-20 13:42 UTC, AlfiyaSiddique commented
Did the changes @CBID2

2023-07-21 02:49 UTC, CBID2 approved these changes
LGTM! :)

2023-07-21 07:37 UTC, AlfiyaSiddique commented
> LGTM! :)

Yeah, then can you please merge this PR!!

2023-07-22 03:49 UTC, CBID2 commented
> > LGTM! :)
> 
> 
> 
> Yeah, then can you please merge this PR!!

Two approvals are required for PRs to be merged. Please be patient.

2023-07-22 11:31 UTC, k-deepak04 approved these changes

2023-07-22 11:32 UTC, merged