Added resourcs for react
rupali-codes/LinksHub pull request #1364
Opened 2023-07-21 08:01 UTC by karthiknadar1204

## Fixes Issue #1239 

## Changes proposed

Added resources for react js.

## Screenshots

## Note to reviewers

2023-07-22 03:47 UTC, CBID2 requested changes
Just added a proofreading suggestion. Other than that, you're off to a great start! :)

2023-07-22 03:47 UTC, CBID2 commented on database/frontend/react.json
> +    "description": "In this hindi video series by Thapa technical, topics ranging from props to react hooks are covered while working on simple projects to gain first hand experience working with rea
[Proofreading] 
```suggestion
    "description": "In this Hindi video series by Thapa technical, topics ranging from props to react hooks are covered while working on simple projects to gain first hand experience with React.",
```

2023-07-23 06:52 UTC, karthiknadar1204 commented
will correct it and push the changes again thank you @CBID2

2023-07-23 08:34 UTC, karthiknadar1204 commented
@CBID2 Have pushed the changes again, please check now

2023-07-23 08:35 UTC, karthiknadar1204 reviewed
Done

2023-07-25 00:20 UTC, CBID2 submitted a review, later dismissed
Great job @karthiknadar1204! :) You just need one more approved review before merging occurs! :)

2023-07-25 03:35 UTC, k-deepak04 submitted a review, later dismissed

2023-07-25 03:35 UTC, k-deepak04 commented
@karthiknadar1204 please resolve the conflicts

2023-07-25 03:43 UTC, karthiknadar1204 commented
Done @k-deepak04

2023-07-26 04:05 UTC, k-deepak04 commented
@karthiknadar1204 deployment is failing plz check.

2023-07-27 02:56 UTC, karthiknadar1204 commented
should i open another pr?

2023-07-27 23:10 UTC, CBID2 commented
This PR is closed because #1399 solved it.

2023-07-27 23:10 UTC, closed without merging