feat: Added Software Testing YouTube Videos Details in testing.js File
rupali-codes/LinksHub pull request #1388
Opened 2023-07-26 09:47 UTC by NarendraKoya999

## Fixes Issue No's : #1345 #1346  #1347 

## Changes proposed

- Added `Software Testing Course YouTube Video` details in `testing.js File in youtube Folder`.
- YouTube channels named as `Software Testing Mentor, Automation Step by Step and EDUREKA(Testing)` 
## Screenshots

## Note to reviewers

- I have linked All related Testing related Issues raised by Me and also combined together with this PR 
- Please Notify Them @rupali-codes

2023-07-27 07:12 UTC, rupali-codes requested changes
Hi, can you please make the description a little longer?

2023-07-27 07:15 UTC, NarendraKoya999 commented
> Hi, can you please make the description a little longer?

Sure, I will do that?

2023-07-30 22:46 UTC, CBID2 approved these changes
Made some tweaks to your descriptions. Other than that, well done! :)

2023-07-31 03:45 UTC, NarendraKoya999 commented
> Made some tweaks to your descriptions. Other than that, well done! :)



> Made some tweaks to your descriptions. Other than that, well done! :)

If you don't mind Please add level 2 OR Level 3 Label to This PR. Because of If one resource is added, You can given level 1. But, I added 6 Resources in One PR. Please Taken my Humble Request @CBID2

2023-07-31 03:47 UTC, CBID2 commented
> > Made some tweaks to your descriptions. Other than that, well done! :)
> 
> 
> 
> 
> 
> 
> 
> > Made some tweaks to your descriptions. Other than that, well done! :)
> 
> 
> 
> If you don't mind Please add level 2 OR Level 3 Label to This PR. Because of If one resource is added, You can given level 1. But, I added 6 Resources in One PR. Please Taken my Humble Request @CBID2  

Sorry @NarendraKoya999. The rules state that adding links are level one, so we have to adhere to that.

2023-07-31 03:48 UTC, NarendraKoya999 commented
> > > Made some tweaks to your descriptions. Other than that, well done! :)
> > 
> > 
> > > Made some tweaks to your descriptions. Other than that, well done! :)
> > 
> > 
> > If you don't mind Please add level 2 OR Level 3 Label to This PR. Because of If one resource is added, You can given level 1. But, I added 6 Resources in One PR. Please Taken my Humble Request @CBID2
> 
> Sorry @NarendraKoya999. The rules state that adding links are level one, so we have to adhere to that.

Ok. No Problem @CBID2

2023-08-01 12:08 UTC, rupali-codes commented on database/youtube/testing.json
> +    "description": "This channel is for everyone who wants to learn Manual testing and Automation Testing for FREE. The reason he has made this channel is to educate people who want to learn an easy
```suggestion
    "description": "This channel is for everyone who wants to learn Manual testing and Automation Testing for FREE. ",
```

2023-08-01 12:18 UTC, rupali-codes approved these changes

2023-08-01 12:18 UTC, merged

2023-08-01 12:20 UTC, NarendraKoya999 commented
Hi @rupali-codes . Please Look into 4 unassigned Pending Issues as soon as possible