Updated the youtube section
rupali-codes/LinksHub pull request #1394
Opened 2023-07-27 08:45 UTC by anshulsoni4

## fixes Data Structures playlist with c++ #1229

Closes #1229 

## Changes proposed

Added the DSA playlist  using the c++ language

## Screenshots

## Note to reviewers

2023-07-27 14:29 UTC, k-deepak04 commented
@anshulsoni4 please resolve the conflicts, rebase your branch with the main one.

2023-07-27 23:34 UTC, CBID2 approved these changes
Hi @anshulsoni4. I made a few tweaks, but other than that, you did a good job! :) Now, you just have to wait for another review before your PR can be merged! :)

2023-07-29 04:36 UTC, anshulsoni4 commented
> Hi @anshulsoni4. I made a few tweaks, but other than that, you did a good job! :) Now, you just have to wait for another review before your PR can be merged! :)

thanks man!

2023-07-30 03:13 UTC, CBID2 requested changes
Hi @anshulsoni4! :) There are some merge conflicts in your branch so I highly recommend solving them.

2023-07-30 07:35 UTC, anshulsoni4 commented
> Hi @anshulsoni4! :) There are some merge conflicts in your branch so I highly recommend solving them.

pls check now

2023-07-30 14:13 UTC, CBID2 approved these changes
LGTM

2023-07-31 09:15 UTC, rupali-codes commented on database/youtube/data-structures.json
> +
```suggestion
```

2023-07-31 11:15 UTC, anshulsoni4 commented
done now pls check @rupali-codes

2023-07-31 15:25 UTC, CBID2 approved these changes
LGTM

2023-08-01 07:41 UTC, anshulsoni4 commented
can you merge the changes ?

2023-08-01 12:14 UTC, rupali-codes approved these changes

2023-08-01 12:15 UTC, merged