bootstrap is added
rupali-codes/LinksHub pull request #1433
Opened 2023-07-30 06:14 UTC by Sushilverma002

## #1370 

## Changes proposed

## Screenshots

## Note to reviewers

2023-07-30 17:09 UTC, CBID2 commented on database/frontend/bootstrap.json
> +        "description": "Get started with Bootstrap, the world most popular framework for building responsive, mobile-first sites, with jsDelivr and a template starter page.",
```suggestion
        "description": "Get started with Bootstrap, the world's most popular framework for building responsive mobile-first sites with jsDelivr and a template starter page.",
```

2023-07-30 17:11 UTC, CBID2 requested changes
Hi @Sushilverma002 ! :) I pointed out some typos and proofreading errors that need to be fixed. Also, the deployment has failed for some reason so I suggest waiting for @rupali-codes' review.

2023-07-31 08:39 UTC, rupali-codes reviewed
Hi @Sushilverma002 can you please go through CONTRIBUTING guidelines once?

2023-07-31 08:43 UTC, rupali-codes requested changes
* update your branch with `linkshub:main`
* you don't have to create a NEW subcategotry, please add this under [resources/official-docs,json](https://github.com/rupali-codes/LinksHub/blob/main/database/resources/official-docs.json)

2023-07-31 12:48 UTC, closed without merging