open source blog added
rupali-codes/LinksHub pull request #1440
Opened 2023-07-30 17:26 UTC by S-ishita

## Fixes Issue
closes #1439 

## Changes proposed

## Screenshots
![Screenshot from 2023-07-30 22-55-08](https://github.com/rupali-codes/LinksHub/assets/104543751/a9498b77-285b-4404-845f-a3c8402ea9ad)

## Note to reviewers

2023-07-30 17:29 UTC, CBID2 approved these changes
Great job @S-ishita! 😄 LGTM! 😄

2023-07-31 05:43 UTC, k-deepak04 submitted a review, later dismissed

2023-07-31 05:43 UTC, k-deepak04 commented
@S-ishita please resolve the conflicts

2023-07-31 08:36 UTC, rupali-codes approved these changes
thanks, lgtm

2023-08-01 15:11 UTC, CBID2 requested changes

2023-08-01 15:11 UTC, CBID2 commented on database/open_source/blogs.json
> +    "description": " A complete guide to beginner's open source journey...",
```suggestion
    "description": " A complete guide to beginner's open source journey.",
```

2023-08-01 15:12 UTC, CBID2 approved these changes
Just made a tweak to your description @S-ishita. It looks great now

2023-08-03 13:19 UTC, rupali-codes approved these changes

2023-08-03 13:20 UTC, merged