react resources
rupali-codes/LinksHub pull request #1449
Opened 2023-07-31 05:25 UTC by karthiknadar1204

## Fixes Issue #1374 

## Changes proposed

Added resources for react
## Screenshots

## Note to reviewers

2023-07-31 08:24 UTC, rupali-codes commented on database/frontend/react.json
> +    "description": "In this Hindi video series, you will basics of the framework while creating projects on the go for better understanding of concepts and their working.",
```suggestion
    "description": "In this series, you will learn basics of the React.js while creating projects on the go for better understanding of concepts and their working.",

```

2023-07-31 08:25 UTC, rupali-codes commented
@karthiknadar1204 please add _closes #issue_number_ in the description of this PR

2023-07-31 08:27 UTC, karthiknadar1204 commented
#1374

2023-07-31 18:04 UTC, karthiknadar1204 commented
@rupali-codes

2023-08-01 04:29 UTC, karthiknadar1204 commented
will push the changes again in a bit.
Thank you

2023-08-01 06:09 UTC, karthiknadar1204 commented
@rupali-codes Have pushed the changes

2023-08-01 14:58 UTC, CBID2 requested changes

2023-08-01 14:58 UTC, CBID2 commented on database/frontend/react.json
> +    "description": "In this series, you will basics of React.js while creating projects on the go for better understanding of concepts and their working.",
```suggestion
    "description": "In this series, you will learn the basics of React.js while creating projects to gain a better understanding of concepts and their working.",
```

2023-08-01 14:59 UTC, CBID2 approved these changes
Hi @karthiknadar1204! I made a few tweaks to your description, so it looks good now! :)

2023-08-02 14:42 UTC, rupali-codes approved these changes
lgtm

2023-08-02 14:43 UTC, merged