added Wes Bos youtube in webdevlepment section
rupali-codes/LinksHub pull request #1495
Opened 2023-08-05 03:07 UTC by Prajwal0225

## Fixes Issue

Closes #1270

2023-08-05 03:41 UTC, CBID2 requested changes
Made a suggestion. Otherwise, good start

2023-08-05 03:41 UTC, CBID2 commented on database/youtube/web-development.json
> +    "description": "This this the best website to learn javascript by building 30 projects in 30 days.",
```suggestion
    "description": "This this the best website to learn JavaScript. Building 30 projects in 30 days.",
```

2023-08-06 00:40 UTC, CBID2 approved these changes
Hi @Prajwal0225! :) There were still some errors that I found in your description, so I revised them. In the future, I suggest running your descriptions through an app like [Grammarly](https://www.grammarly.com/grammar-check) before turning them into PRs.

2023-08-06 11:25 UTC, k-deepak04 approved these changes

2023-08-06 11:26 UTC, merged