computer books added
rupali-codes/LinksHub pull request #1503
Opened 2023-08-06 04:58 UTC by S-ishita

## Fixes Issue
closes #1499 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-06 10-28-02](https://github.com/rupali-codes/LinksHub/assets/104543751/b5fdfc21-9467-426e-ae3d-fedfcb7ac2ef)

## Note to reviewers

2023-08-06 11:36 UTC, k-deepak04 commented
@S-ishita please resolve the conflicts

2023-08-07 13:42 UTC, CBID2 requested changes
Just made a suggestion for improvement

2023-08-07 13:42 UTC, CBID2 commented on database/resources/e-book.json
> +    "description": "Links to Free Computer, Mathematics, Technical Books all over the World",
```suggestion
    "description": "This website provides free computer, mathematics, technical books to developers all over the world",
```

2023-08-07 16:04 UTC, k-deepak04 approved these changes

2023-08-07 16:04 UTC, merged