Add image resource
rupali-codes/LinksHub pull request #1504
Opened 2023-08-06 05:31 UTC by Sriparno08

## Fixes Issue

Closes #1497 

## Changes proposed

I have added a new image resource to the website.

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/89148144/d60e229a-6d69-4ddc-93ab-19afe66a9de0)

## Note to reviewers

This PR is part of GSSOC'23.

2023-08-07 13:45 UTC, CBID2 requested changes
Just found a typo that needs fixing @Sriparno08

2023-08-07 13:45 UTC, CBID2 commented on database/frontend/images.json
> +    "description": "Adobe Stock includes a wide range of stock photos, stock photography & royalty-free images.",
```suggestion
    "description": "Adobe Stock includes a wide range of stock photos, stock photography,& royalty-free images.",
```

2023-08-07 14:04 UTC, Sriparno08 commented
Fixed it, @CBID2!

2023-08-07 15:10 UTC, CBID2 approved these changes
Well done

2023-08-07 16:03 UTC, k-deepak04 approved these changes

2023-08-07 16:11 UTC, merged

2023-08-08 07:01 UTC, Sriparno08 commented
Hey @CBID2 @k-deepak04, can you please assign the labels to this PR for GSSoC'23?