Update SECURITY.md
rupali-codes/LinksHub pull request #1555
Opened 2023-08-10 12:30 UTC by abhisar-yadav

Improved the framing of statements 
## Fixes 
Closes #1509 
Relates to #1553 & #1554

2023-08-10 12:43 UTC, CBID2 requested changes
Hi @abhisar-yadav. I made some suggestions. Note: "open source" is the correct spelling.

2023-08-10 12:43 UTC, CBID2 commented on SECURITY.md
> +This document outlines the security policy for the [Linkshub](https://linkshub.vercel.app/) open-source project that provides links to websites for courses across the internet. The policy is intended
```suggestion
This document outlines the security policy for the [Linkshub](https://linkshub.vercel.app/) open source project that provides links to websites for courses across the internet. The policy is intended to provide guidelines and procedures for reporting, triaging, and addressing security vulnerabilities in the project.
```

2023-08-10 12:43 UTC, CBID2 commented on SECURITY.md
> +The security policy covers the codebase and documentation of the open-source project, as well as the external links to websites for courses.
```suggestion
The security policy covers the codebase and documentation of the open source project, as well as the external links to websites for courses.
```

2023-08-10 18:32 UTC, k-deepak04 commented
@abhisar-yadav have you made the changes requested by @CBID2 ?

2023-08-10 22:19 UTC, CBID2 approved these changes
LGTM

2023-08-11 15:37 UTC, rupali-codes approved these changes

2023-08-11 15:38 UTC, merged