joseph smith added
rupali-codes/LinksHub pull request #1556
Opened 2023-08-10 12:56 UTC by S-ishita

## Fixes Issue
closes #1502 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-10 18-24-04](https://github.com/rupali-codes/LinksHub/assets/104543751/757e02ef-943b-4c3b-b051-9a4b51a0aafa)

## Note to reviewers

2023-08-10 18:31 UTC, k-deepak04 commented
@S-ishita resolve the conflicts

2023-08-11 04:43 UTC, CBID2 requested changes

2023-08-11 04:43 UTC, CBID2 commented on database/youtube/web-development.json
> +    "description": "Learn programming and building with languages like HTML,CSS ,PHP and much more.",
```suggestion
    "description": "Learn programming and building with languages like HTML,CSS ,PHP, and much more.",
```

2023-08-11 04:43 UTC, CBID2 approved these changes
LGTM

2023-08-13 07:19 UTC, rupali-codes approved these changes
thanks, lgtm

2023-08-13 07:19 UTC, merged