feat: Added GraphQL in backend database Category
rupali-codes/LinksHub pull request #1574
Opened 2023-08-10 17:33 UTC by NarendraKoya999

## Fixes Issue #1384 

## Changes proposed

- **Added GraphQL Details in database sub category in backend Category**

## Screenshots

## Note to reviewers

2023-08-10 17:51 UTC, CBID2 requested changes
Made a tweak to your description

2023-08-10 17:51 UTC, CBID2 commented on database/backend/database.json
> +    "description": "GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to
```suggestion
    "description": "GraphQL provides a comprehensive description of the data in your API, which gives clients the power to ask for exactly what they need and nothing more and make it easier to evolve APIs over time. It also enables powerful developer tools.",
```

2023-08-10 22:27 UTC, CBID2 approved these changes
LGTM

2023-08-13 07:53 UTC, rupali-codes approved these changes
lgtm

2023-08-13 07:53 UTC, merged