coding blocks added
rupali-codes/LinksHub pull request #1577
Opened 2023-08-10 17:47 UTC by S-ishita

## Fixes Issue
closes #1566 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-10 23-17-37](https://github.com/rupali-codes/LinksHub/assets/104543751/049327d2-4ae6-4c25-8d18-c1bc05d1d570)

## Note to reviewers

2023-08-10 17:49 UTC, CBID2 requested changes
Just made a tweak @S-ishita

2023-08-10 17:49 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "In addition to the IDE with code completion, you can also create an account to save your code on the server, and also share it with others.",
```suggestion
    "description": "In addition to the IDE with code completion, you can also create an account to save your code on the server and share it with others.",
```

2023-08-10 22:37 UTC, CBID2 approved these changes
LGTM

2023-08-13 07:55 UTC, rupali-codes commented
@S-ishita could you please resolve merge conflicts?

2023-08-19 17:25 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

> I have resolved the merge conflicts.

2023-08-19 17:26 UTC, Anmol-Baranwal commented
@CBID2 
Review and merge this.

Let's clean up the issues and PRs.

2023-08-19 17:43 UTC, CBID2 commented
> @CBID2 
> 
> Review and merge this.
> 
> 
> 
> Let's clean up the issues and PRs.

Yup

2023-08-19 17:43 UTC, CBID2 approved these changes
LGTM

2023-08-19 17:43 UTC, merged