feat: Added Python Official Docs Details in resources Section
rupali-codes/LinksHub pull request #1579
Opened 2023-08-10 17:54 UTC by NarendraKoya999

## Fixes Issue #1385 

## Changes proposed
- **Added Python Official Docs Details in officialdocs Sub Category in resources category.**

## Screenshots

## Note to reviewers

2023-08-10 22:38 UTC, CBID2 requested changes

2023-08-10 22:38 UTC, CBID2 commented on database/resources/official-docs.json
> +    "description": "Python's documentation, tutorials, and guides are constantly evolving.Get started here, or scroll down for documentation broken out by type and subject.",
```suggestion
    "description": "Python's documentation, tutorials, and guides are constantly evolving.  Get started here, or scroll down for documentation categorized by type and subject.",
```

2023-08-10 22:38 UTC, CBID2 approved these changes
LGTM

2023-08-13 10:30 UTC, rupali-codes commented on database/resources/official-docs.json
> +    "description": "Python's documentation, tutorials, and guides are constantly evolving.  Get started here, or scroll down for documentation categorized by type and subject.",
```suggestion
    "description": "It's the official documentation of Python. Start your journey here, or explore categorized resources covering language basics, libraries, web development, data science, AI, and more. ",
```

2023-08-19 17:27 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-08-19 17:48 UTC, merged