atcoder added
rupali-codes/LinksHub pull request #1580
Opened 2023-08-10 17:55 UTC by S-ishita

## Fixes Issue
closes #1563 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-10 23-24-00](https://github.com/rupali-codes/LinksHub/assets/104543751/78460c17-f8ed-4672-b716-b716f9343ee3)

## Note to reviewers

2023-08-10 22:29 UTC, CBID2 requested changes

2023-08-10 22:29 UTC, CBID2 commented on database/competitive_programming/platforms.json
> +    "description": "AtCoder is a programming contest site for anyone from beginners to experts.",
```suggestion
    "description": "AtCoder is a programming contest site for beginners to experts.",
```

2023-08-10 22:29 UTC, CBID2 approved these changes
LGTM

2023-08-13 10:31 UTC, rupali-codes commented
@S-ishita could you please improve title of your all PRs and resolve the conflicts as well :)

2023-08-15 11:38 UTC, rupali-codes approved these changes

2023-08-15 11:45 UTC, merged