cs academy added
rupali-codes/LinksHub pull request #1587
Opened 2023-08-11 03:38 UTC by S-ishita

## Fixes Issue
closes #1583 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-11 09-06-38](https://github.com/rupali-codes/LinksHub/assets/104543751/caa3e654-3823-4904-a8e0-2c96a3e7a746)

## Note to reviewers

2023-08-11 04:44 UTC, CBID2 requested changes

2023-08-11 04:44 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "In addition to code compilation and execution, it consists of workspaces",
```suggestion
    "description": "In addition to code compilation and execution, this source consists of workspaces",
```

2023-08-11 04:45 UTC, CBID2 approved these changes
LGTM

2023-08-15 11:33 UTC, rupali-codes submitted a review, later dismissed

2023-08-15 11:34 UTC, merged