neso academy added
rupali-codes/LinksHub pull request #1588
Opened 2023-08-11 03:44 UTC by S-ishita

## Fixes Issue
closes #1515 

## Changes proposed

## Screenshots
![Screenshot from 2023-08-11 09-11-32](https://github.com/rupali-codes/LinksHub/assets/104543751/84e55baa-10b8-4e39-b568-148c95775882)

## Note to reviewers

2023-08-11 04:41 UTC, CBID2 requested changes

2023-08-11 04:41 UTC, CBID2 commented on database/youtube/computer-science.json
> +    "description": " Covers various topics related to field of computer science like Engineering Lectures,School Syllabus,Competitive Exams",
```suggestion
    "description": " Covers various topics related to field of computer science like Engineering Lectures,School Syllabus, and Competitive Exams",
```

2023-08-11 04:41 UTC, CBID2 approved these changes
LGTM

2023-08-15 11:31 UTC, rupali-codes approved these changes

2023-08-15 11:32 UTC, merged