added footer
rupali-codes/LinksHub pull request #160
Opened 2023-02-09 05:06 UTC by Aadarsh805

## Fixes Issue
Closes #117 

## Screenshots
![Screenshot from 2023-02-09 10-26-33](https://user-images.githubusercontent.com/95094057/217722947-5395cdb6-862c-458e-b4fe-2a8961642121.png)

## Note to reviewers
Suggest changes if any

2023-02-09 06:28 UTC, rupali-codes commented on components/Footer/Footer.tsx
> +      <p className="text-lg text-white ">
we are not using `white` anywhere in the project. so just update it with `text-gray-200`

2023-02-09 06:30 UTC, rupali-codes reviewed
Also, can we make background `blur` instead of using this `solid` color?

2023-02-09 06:40 UTC, Aadarsh805 commented
> Also, can we make background `blur` instead of using this `solid` color?

something like this?
![108 (3)](https://user-images.githubusercontent.com/95094057/217736925-1d8341a9-732c-4836-b5c5-6491e20a2884.png)

2023-02-09 06:43 UTC, rupali-codes commented
Hmm.

> > Also, can we make background `blur` instead of using this `solid` color?
> 
> something like this? ![108 (3)](https://user-images.githubusercontent.com/95094057/217736925-1d8341a9-732c-4836-b5c5-6491e20a2884.png)

Looks good tho, but wud hv been better if cud just make it within right container. If not, just commit the changes

2023-02-09 06:48 UTC, Aadarsh805 commented
maybe what we can do is instead of keeping it fixed, I add the footer static inside the right container and make cards container have a fixed height just above to the footer
something like that
let me try

2023-02-09 08:31 UTC, rupali-codes commented
> maybe what we can do is instead of keeping it fixed, I add the footer static inside the right container and make cards container have a fixed height just above to the footer something like that let me try

Okay

2023-02-10 05:28 UTC, Aadarsh805 commented
closes #161 as well

2023-02-10 05:35 UTC, Aadarsh805 commented
here's how it looks on mine

[screen-capture (17).webm](https://user-images.githubusercontent.com/95094057/218009377-3aad7ff5-b590-4866-bad2-460414adc1b8.webm)

2023-02-10 18:28 UTC, rupali-codes requested changes
Great work Aadarsh. But having 2 small issues: 
1. It's showing 2 scrollbars 

![image](https://user-images.githubusercontent.com/78981177/218168437-87413be8-53a9-4a05-800e-53fcb342592f.png)

2. Ig it should not be fixed this way, what i meant is when user reaches the end of the page, then we should display this footer. And for initial state (when no category is selected) it should be at the bottom of the page just like it's now.

2023-02-10 18:29 UTC, rupali-codes commented
> closes #161 as well

And thanks for this 😊

2023-02-10 20:02 UTC, Aadarsh805 commented
> Great work Aadarsh. But having 2 small issues:
> 
> 1. It's showing 2 scrollbars
> 
> ![image](https://user-images.githubusercontent.com/78981177/218168437-87413be8-53a9-4a05-800e-53fcb342592f.png)
> 
> 2. Ig it should not be fixed this way, what i meant is when user reaches the end of the page, then we should display this footer. And for initial state (when no category is selected) it should be at the bottom of the page just like it's now.

I actually fixed the bigger scrollbar, that's exactly what is being addressed in this issue #161, I'll look on it again must be because of smaller screen size ig
and I'll try to implement it the other way as you suggested
One question, do we want the top bar fixed? i suggest it should be

2023-02-11 05:40 UTC, rupali-codes commented
@Aadarsh805 I guess not for desktop but we can fix it t top for other devices(phone, tabs). Cz' we have sidebar in desktop so there's no need for it necessarily

2023-02-11 09:24 UTC, Aadarsh805 commented
Updated

[screen-capture (19).webm](https://user-images.githubusercontent.com/95094057/218250753-aa3b7679-a0e8-4a4c-8338-8507047da982.webm)

2023-02-11 14:25 UTC, rupali-codes approved these changes
Thank you so much Aadarsh, appreciate it. Now it looks perfect.

2023-02-11 14:26 UTC, merged