feat: added drafter files
rupali-codes/LinksHub pull request #1603
Opened 2023-08-19 16:16 UTC by tamalCodes

## Fixes Issue

Closes #1601 

## Changes proposed

New automation has been added for drafting a release, on pushes/PR merges to the `main` branch and based on a custom template `.github\release-drafter.yml`, release notes will be generated automatically and the versions will be bumped accordingly.

2023-08-19 16:17 UTC, tamalCodes commented
Hi there, please let me know the labels based on which you would like to bump the versions for a patch, feature, and breaking changes.

2023-08-19 17:18 UTC, CBID2 requested changes
Hi @tamalCodes. Is there a way you can add a line where contributor's names are shown in the release? It'd be helpful for job interviews

2023-08-19 20:32 UTC, tamalCodes commented
Hi @CBID2 , so with the changes that are done in this PR, we will be having the username along with their PR (that was squash-merged into the main branch), they are also visible in the contributor's section of the release with these they can show case !


![image](https://github.com/rupali-codes/LinksHub/assets/72851613/a16fcccc-65cf-4d71-8360-a9ab85938b18)

2023-08-19 23:49 UTC, CBID2 submitted a review, later dismissed
LGTM! :)

2023-08-20 09:27 UTC, tamalCodes commented
> LGTM! :)

Thanks for the review. There are some more changes that can/need to be done on the PR.

 - Update the label (please let me know the labels based on which you would like to bump the versions for a patch, feature, and breaking changes) OR this can be done later by the repo owner.
 - If the action fails do check if the `secrets.GITHUB_TOKEN` has enough permission in the repo.
 - Else you can always make a different secret and use that.

2023-08-21 06:44 UTC, rupali-codes commented
> Hi there, please let me know the labels based on which you would like to bump the versions for a patch, feature, and breaking changes.

patch and feature

2023-08-21 16:07 UTC, rupali-codes approved these changes
looks perfect to me :)

2023-08-21 16:08 UTC, merged