New golang tutorial added by freecodecamp.org
rupali-codes/LinksHub pull request #1611
Opened 2023-08-20 21:02 UTC by subhadeepbanerjee2003

## Changes proposed

- **New golang tutorial added by freecodecamp.org**

## Screenshots
![Screenshot from 2023-08-20 22-12-28](https://github.com/rupali-codes/LinksHub/assets/116381157/7c9854ba-0ac3-4aa2-bc58-f640f29aedc8)

## Note to reviewers

*I hope this small change will add value to the users and please give suggestions if further edit or modification needed*

2023-08-20 21:08 UTC, CBID2 requested changes
Hi @subhadeepbanerjee2003! :) Other than the suggestions I presented, your PR is off to a great start.

2023-08-20 21:08 UTC, CBID2 commented on database/languages/golang.json
> +    "description": "Learn the Go programming language in this full course for beginners. You'll practice writing performant, idiomatic Go with these hands-on lessons and challenges.",
```suggestion
    "description": "In this beginner-level Golang course, you'll practice writing performant, idiomatic Go with these hands-on lessons and challenges.",
```

2023-08-20 21:15 UTC, subhadeepbanerjee2003 commented
@CBID2 i have done you can check as per your time thanks :)

2023-08-20 21:25 UTC, CBID2 approved these changes
LGTM

2023-08-21 02:44 UTC, subhadeepbanerjee2003 commented
@Anmol-Baranwal @rupali-codes please check

2023-08-21 08:32 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

> Btw 9hr Tutorial :)

> I would suggest codecademy to learn Go

2023-08-21 08:35 UTC, merged

2023-08-21 08:35 UTC, Anmol-Baranwal commented
@subhadeepbanerjee2003 
I am merging it for now. Just keep the structure consistent from next time.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/cae56f47-81bb-4a35-a73a-189236d625e7)

2023-08-21 09:48 UTC, subhadeepbanerjee2003 commented
Ok thanks and I will surely keep the structure in mind