Added description for programming languages:
rupali-codes/LinksHub pull request #1621
Opened 2023-08-23 14:18 UTC by the-shivam-gupta

The tooltip description for the following languages
    1.Cpp
    2.Kotlin
    3.Rust
    4.Dart
    5.Java
has been added.

## Fixes Issue
#1617

## Changes proposed

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/109647722/c63f2269-b0c3-4066-b6c3-e092ba787bc7)

## Note to reviewers

2023-08-24 16:48 UTC, k-deepak04 submitted a review, later dismissed

2023-08-24 17:41 UTC, rupali-codes submitted a review, later dismissed
looks good to me

2023-08-25 13:30 UTC, CBID2 requested changes

2023-08-25 13:30 UTC, CBID2 commented on components/TopBar/CategoryDescriptions.ts
> +  dart: "Dart is a programming language primarily used for building web and mobile applications, with a focus on client-side development. It's the language behind the Flutter framework, allowing deve
[Typo]
```suggestion
  dart: "Dart is a programming language primarily used for building web and mobile applications with a focus on client-side development. It's the language behind the Flutter framework, allowing developers to create cross-platform apps with a single codebase. Dart offers features like a Just-In-Time (JIT) compiler for development speed and an Ahead-Of-Time (AOT) compiler for production performance optimization.",
```

2023-08-25 13:31 UTC, CBID2 approved these changes
LGTM

2023-08-25 13:32 UTC, CBID2 commented
> @CBID2 
> 
> Please review this. 

Going to need your approval @Anmol-Baranwal

2023-08-25 13:35 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-08-25 13:35 UTC, merged