modified description for  "Learn Go Programming" tutorial by programiz
rupali-codes/LinksHub pull request #1622
Opened 2023-08-23 16:14 UTC by subhadeepbanerjee2003

## Fixes Issue

- I have changed the description for `"Learn Go Programming" tutorial by programiz`

**Closes issue id #1613**

## Changes proposed

 ```
 },
  {
    "name": "Learn Go Programming",
    "description": "This playlist contains all the concepts of Golang along with two mini projects",
    "description": "Our Go tutorials will guide you to learn Go Programming one step at a time",
    "url": "https://www.programiz.com/golang",
    "category": "languages",
    "subcategory": "golang"
```

## Screenshots
![Screenshot from 2023-08-23 21-38-06](https://github.com/rupali-codes/LinksHub/assets/116381157/dbf00267-6a45-4ce2-81d1-ad57de4592da)

## Note to reviewers

- **`NOTE` :: If you want to modify the description please let me know.**

2023-08-23 16:18 UTC, subhadeepbanerjee2003 commented
@Anmol-Baranwal @CBID2 check my pr and the code base and let me know if there is any scope of improvement?

2023-08-23 18:36 UTC, Anmol-Baranwal commented
I will check the resource later. Then I will let you know.

> What was wrong in the previous description?

2023-08-23 18:52 UTC, subhadeepbanerjee2003 commented
@Anmol-Baranwal the previous description was the description of the other tutorial which was unfortunately added.

2023-08-24 14:00 UTC, Anmol-Baranwal commented
@CBID2 @rupali-codes 

Please review this.

2023-08-24 16:47 UTC, k-deepak04 approved these changes

2023-08-25 15:09 UTC, CBID2 commented on database/languages/golang.json
> +    "description": "Our Go tutorials will guide you to learn Go Programming one step at a time",
```suggestion
    "description": "Our Go tutorials will guide you in learning the programming one step at a time",
```

2023-08-25 15:18 UTC, subhadeepbanerjee2003 commented
@CBID2 yah I have reviewed it and done the necessary.

2023-08-25 15:23 UTC, CBID2 requested changes
Still needs improvement @subhadeepbanerjee2003. I highly recommend clicking on the commit button that appears in my comment. It will speed things up and you might get a Github badge for it.

2023-08-25 15:23 UTC, CBID2 commented on database/languages/golang.json
> +    "description": "Our Go tutorials will guide you in learning the programming one step at a time",
```suggestion
    "description": "Our Go tutorials will guide you in learning the programming language one step at a time",
```

2023-08-25 15:40 UTC, subhadeepbanerjee2003 commented
@CBID2 now can you check if the changes reflected?

2023-08-25 17:13 UTC, CBID2 commented
Your turn @Anmol-Baranwal

2023-08-25 18:31 UTC, Anmol-Baranwal commented
> Still needs improvement @subhadeepbanerjee2003. I highly recommend clicking on the commit button that appears in my comment. It will speed things up and you might get a Github badge for it.

I can directly add it when merging😅

2023-08-25 18:33 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-08-25 18:33 UTC, merged

2023-08-26 03:15 UTC, subhadeepbanerjee2003 commented
Thanks @Anmol-Baranwal