Added Odin Project
rupali-codes/LinksHub pull request #1626
Opened 2023-08-24 16:54 UTC by mrigank590

## Fixes Issue

Closes #1623

## Changes proposed

Added Odin Project link

## Screenshots

<img width="224" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/101625174/420119bf-dc64-4fe0-bc4c-33de84eb12e4">

## Note to reviewers

In the issue I had selected the wrong subcategory "fonts" while I should have selected "React Js"

2023-08-25 15:08 UTC, CBID2 requested changes
Made a few suggestions on how to improve it @mrigank590

2023-08-25 15:08 UTC, CBID2 commented on database/frontend/react.json
> +    "description": "It is a free, open-source online coding curriculum. It offers courses covering web development basics, JavaScript, and Ruby on Rails. The curriculum is supported by an open-source
```suggestion
    "description": "The Odin Project is a free, online coding curriculum maintained by the open source community. It offers courses covering web development basics, JavaScript,Ruby on Rails, job search strategies. It also has a Discord community of nearly 718,000 learners.",
```

2023-08-26 15:27 UTC, CBID2 approved these changes
LGTM

2023-08-27 06:59 UTC, Anmol-Baranwal reviewed
@rupali-codes 

Please give your opinion regarding the category since this includes both the backend and frontend topics.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/9030a8a8-6cdb-4edc-b5e6-3e5baebda298)

2023-08-27 18:37 UTC, mrigank590 commented
@Anmol-Baranwal this is the same case with Fullstack Open so i was thinking of making a new category of fullstack, with which i am almost done but how will i make changes to this pull request for that?
i haven't used github much so yeah

2023-08-27 18:45 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal this is the same case with Fullstack Open so i was thinking of making a new category of fullstack, with which i am almost done but how will i make changes to this pull request for that? i haven't used github much so yeah

Don't worry. We will not ask you to make a new category. Also, if you want to create one, just tag any of the moderators. And we will help you out with anything, whether it's github or code.

2023-08-27 19:07 UTC, mrigank590 commented
> > @Anmol-Baranwal this is the same case with Fullstack Open so i was thinking of making a new category of fullstack, with which i am almost done but how will i make changes to this pull request for that? i haven't used github much so yeah
> 
> Don't worry. We will not ask you to make a new category. Also, if you want to create one, just tag any of the moderators. And we will help you out with anything, whether it's github or code.

actually i am almost done with making a new category and i will put a new issue tomorrow 
and one more stupid question where i can check who the moderators are?

2023-08-27 19:33 UTC, Anmol-Baranwal commented
> > > @Anmol-Baranwal this is the same case with Fullstack Open so i was thinking of making a new category of fullstack, with which i am almost done but how will i make changes to this pull request for that? i haven't used github much so yeah
> > 
> > 
> > Don't worry. We will not ask you to make a new category. Also, if you want to create one, just tag any of the moderators. And we will help you out with anything, whether it's github or code.
> 
> actually i am almost done with making a new category and i will put a new issue tomorrow and one more stupid question, where can i check who the moderators are?

I knew you would ask this.

It's not listed, which we will do for sure.

You can tag the moderators by their names: just use `@name` and you will get the option

> `rupali-codes` `k-deepak04` `CBID2` `Anmol-Baranwal`

2023-09-03 12:39 UTC, rupali-codes commented
> @rupali-codes
> 
> Please give your opinion regarding the category since this includes both the backend and frontend topics.
> 
> ![image](https://user-images.githubusercontent.com/74038190/263513103-9030a8a8-6cdb-4edc-b5e6-3e5baebda298.png)

its **database**

2023-09-05 21:05 UTC, Gdakgdak22 approved these changes

2023-09-06 06:51 UTC, rupali-codes approved these changes
lgtm

2023-09-06 06:53 UTC, merged

2023-09-06 13:10 UTC, Anmol-Baranwal commented
@rupali-codes 
He didn't change the subcategory, like this is still in react.

> I'm just confirming.