Reduced the fontSize for the small devices
rupali-codes/LinksHub pull request #1637
Opened 2023-08-29 14:01 UTC by the-shivam-gupta

To optimise for smaller devices, the font size for the copyright section has been reduced.

## Fixes Issue
#1625

## Changes proposed

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/109647722/6806b32e-5424-487a-990f-4bc0cabaeae3)

## Note to reviewers

2023-08-30 08:53 UTC, rupali-codes commented on components/Footer/Footer.tsx
> +    <footer className="z-10 mb-4 flex w-full items-baseline justify-center rounded-lg py-2 backdrop-blur-md sm:py-3 text-sm md:text-base lg:text-lg xl:text-xl">
```suggestion
    <footer className="z-10 mb-4 flex w-full items-baseline justify-center rounded-lg py-2 backdrop-blur-md sm:py-3 text-sm">
```

2023-08-30 13:47 UTC, CBID2 approved these changes
Hi @the-shivam-gupta! I applied @rupali-codes' suggestions. Things look pretty good! :) LGTM! :)

2023-08-30 19:19 UTC, Anmol-Baranwal requested changes
I think it would be better to align this in center. It would be helpful for everyone and make sure to give it some padding from both sides.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e66ed206-cf11-413b-97e9-5b01f235be4d)

2023-08-31 14:34 UTC, the-shivam-gupta commented
@Anmol-Baranwal, I have made the changes please review it.

2023-08-31 17:31 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

> Thanks for the changes.

2023-09-01 14:14 UTC, the-shivam-gupta commented
@rupali-codes, review it

2023-09-01 18:08 UTC, CBID2 approved these changes
LGTM

2023-09-01 18:10 UTC, merged

2023-09-01 18:13 UTC, CBID2 commented
Thanks for contributing @the-shivam-gupta! If you stay updated on LinksHub's progress, join our [Discord](https://discord.com/invite/NvK67YnJX5)! :) We loved to see more of your ideas! 😊