Added "Edabit"
rupali-codes/LinksHub pull request #1645
Opened 2023-09-01 19:01 UTC by Vijaykv5

#1302 

## Changes proposed

Added "Edabit" to the CodeEditors in website

## Screenshots

## Note to reviewers

2023-09-01 19:09 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "Edabit is a Platform to Learn Programming with 10,000+ challenges through Interactive Console Editor",
```suggestion
    "description": "Edabit is a platform to Learn Programming with 10,000+ challenges through Interactive Console Editor",
```

2023-09-01 19:10 UTC, CBID2 requested changes
Hi @Vijaykv5! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-09-01 19:19 UTC, CBID2 approved these changes
LGTM

2023-09-01 20:04 UTC, Anmol-Baranwal commented
@Vijaykv5 
How is this a online code editor?

2023-09-01 20:06 UTC, Vijaykv5 commented
> @Vijaykv5 How is this a online code editor?

Its a platform for learning with programming languages. Also provides a code editor for the same

2023-09-01 20:29 UTC, Anmol-Baranwal commented
> > @Vijaykv5 How is this a online code editor?
> 
> Its a platform for learning with programming languages. Also provides a code editor for the same

What do you think? @CBID2

2023-09-01 20:32 UTC, CBID2 commented
> > > @Vijaykv5 How is this a online code editor?
> 
> > 
> 
> > Its a platform for learning with programming languages. Also provides a code editor for the same
> 
> 
> 
> What do you think? @CBID2 

Hmmm good question @Anmol-Baranwal. Since it has a IDE and it seems to be where people put their focus the most, I think it's worth adding to that category

2023-09-01 20:34 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

> As per the suggestion of @CBID2

2023-09-01 20:36 UTC, CBID2 commented
> 🚀 Looks good to me.
> 
> > As per the suggestion of @CBID2

@Anmol-Baranwal, I actually changed my mind. You brought up a good point on Edabit being more of a learning platform. I think it should go in the...Other Resources category.

2023-09-01 20:40 UTC, CBID2 commented on database/frontend/online-code-editors.json
>      "category": "frontend",
```suggestion
    "category": "other",
```

2023-09-01 20:41 UTC, CBID2 commented on database/frontend/online-code-editors.json
>      "subcategory": "online-code-editors"
```suggestion
    "subcategory": "other-resources"
```

2023-09-01 20:42 UTC, CBID2 requested changes
Hi @Vijaykv5. I changed the categories a bit since the resource seems more like a learning platform

2023-09-02 05:15 UTC, CBID2 commented on database/frontend/online-code-editors.json
>      "category": "frontend",
You forgot this one @Vijaykv5

2023-09-02 05:17 UTC, CBID2 approved these changes
LGTM

2023-09-02 05:18 UTC, CBID2 commented
@Anmol-Baranwal, this is ready for another review.

2023-09-02 07:24 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-09-02 07:28 UTC, merged