Added CodinGame
rupali-codes/LinksHub pull request #1647
Opened 2023-09-03 07:59 UTC by Vijaykv5

## Fixes Issue

## Changes proposed

Added CodinGame Website Link for Practice & Learn Programming with Interactive Challenges

## Screenshots

## Note to reviewers

2023-09-03 16:37 UTC, CBID2 requested changes
Welcome back @Vijaykv5! :) Your PR is off to a great start. However, the description could use some clarification, so I provided some suggestions on how to help you. :)

2023-09-03 16:37 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "A website to learn and practice programming with interactive challenges in different programming languages ",
[Proofreading] The description was a bit unclear. Consider using the below suggestion to help you: 
```suggestion
    "description": "This is a great website to learn and practice your coding skills. It provides interactive challenges in different programming languages ",
```

2023-09-03 20:23 UTC, CBID2 approved these changes
Well done @Vijaykv5! :) You need another approved review! :)

2023-09-03 20:51 UTC, Anmol-Baranwal reviewed
An online code editor is a web-based tool that allows users to write, edit, and run code directly in a web browser. It provides a convenient environment for developers to write and test their code without the need for installing and setting up a local development environment.

Code editors typically include features like syntax highlighting, code completion, version control integration, debugging tools, and the ability to run the code within the editor itself.

On the other hand, CodinGame is primarily a programming game platform that offers coding challenges and competitions.

@rupali-codes 
is the category correct?

2023-09-04 16:48 UTC, Vijaykv5 commented
> An online code editor is a web-based tool that allows users to write, edit, and run code directly in a web browser. It provides a convenient environment for developers to write and test their code without the need for installing and setting up a local development environment.
> 
> Code editors typically include features like syntax highlighting, code completion, version control integration, debugging tools, and the ability to run the code within the editor itself.
> 
> On the other hand, CodinGame is primarily a programming game platform that offers coding challenges and competitions.
> 
> @rupali-codes is the subcategory correct?

Yeah right?

2023-09-06 07:01 UTC, rupali-codes commented
> An online code editor is a web-based tool that allows users to write, edit, and run code directly in a web browser. It provides a convenient environment for developers to write and test their code without the need for installing and setting up a local development environment.
> 
> Code editors typically include features like syntax highlighting, code completion, version control integration, debugging tools, and the ability to run the code within the editor itself.
> 
> On the other hand, CodinGame is primarily a programming game platform that offers coding challenges and competitions.
> 
> @rupali-codes is the subcategory correct?

i think so

2023-09-06 07:01 UTC, rupali-codes approved these changes

2023-09-06 07:02 UTC, merged