fix: improve accessibility of scripts
rupali-codes/LinksHub pull request #1650
Opened 2023-09-03 21:09 UTC by CBID2

## Fixes Issue
Closes #1464 

## Changes proposed

This PR adds ordered lists (`<ol>`) around the GitHub buttons and social media icons in the `SocialMediaIconsList` component, making the code more accessible for screen readers.

## Screenshots

## Note to reviewers
Hey @Anmol-Baranwal. I've never really worked with Typescript before, so feel free to make the necessary adjustments.

2023-09-04 18:37 UTC, Anmol-Baranwal requested changes
Check the order. This might be causing error in deployment.

2023-09-04 18:37 UTC, Anmol-Baranwal commented on components/SocialMedia/SocialMediaIconsList.tsx
>          </li>
```suggestion
          </li>
        </ol>
```

2023-09-04 18:41 UTC, CBID2 commented
> Check the order. This might be causing error in deployment.

Just made the change @Anmol-Baranwal! :) It worked! :)

2023-09-04 19:34 UTC, Anmol-Baranwal approved these changes
Glad it worked :)

2023-09-17 20:10 UTC, CBID2 commented
Hey @rupali-codes. Can you merge this please?

2023-09-18 12:34 UTC, rupali-codes approved these changes

2023-09-18 12:35 UTC, rupali-codes commented
> Hey @rupali-codes. Can you merge this please?

Sure, sorry for being late

2023-09-18 12:35 UTC, merged