Update colors.json
rupali-codes/LinksHub pull request #1679
Opened 2023-09-18 15:41 UTC by prjctimg

Closes issue #1677

Added [huetiful-js](https://github.com/prjctimg/huetiful) to the Frontend category under the "colors" subcategory

2023-09-18 16:40 UTC, CBID2 requested changes
Hi @prjctimg. Your PR is off to a great start! I just have a suggestion on how you can improve it

2023-09-18 16:40 UTC, CBID2 commented on database/frontend/colors.json
> +     "description": "JavaScript library for simple color manipulations based on the Culori API. With over 50 utilities, it allows you to filter and sort color collections and query different properti
```suggestion
     "description": "This is a JavaScript library for simple color manipulations based on the Culori API. With over 50 utilities, Huetiful allows you to filter and sort color collections and query different properties of color as well as generate different palettes.", 
```

2023-09-18 21:55 UTC, CBID2 submitted a review, later dismissed
Well done @prjctimg! :) LGTM! :)

2023-09-19 14:49 UTC, rupali-codes reviewed
@prjctimg it looks perfect though, but could you please format the code?

2023-09-19 16:05 UTC, prjctimg commented
Code has been formatted using default prettier config

2023-09-20 11:20 UTC, rupali-codes approved these changes

2023-09-20 11:21 UTC, merged