Added the link to the blog to the Machine learning projects with sour…
rupali-codes/LinksHub pull request #1713
Opened 2023-09-30 20:38 UTC by digpatel123

Closes #1700

2023-09-30 21:06 UTC, CBID2 requested changes
Hi @digpatel123! :) I made a suggestion on how you can improve your description

2023-09-30 21:06 UTC, CBID2 commented on database/resources/blogs.json
> +    "description": "In this article, you’ll find the top 100+ latest projects and Ideas on Machine Learning which are beneficial for both beginners as well experienced professionals. These projects a
```suggestion
    "description": "In this article, you’ll find the top 100+ latest projects and ideas on Machine Learning,which are beneficial for both beginners and experienced professionals. These projects are also helpful for the students looking to start their journey in Machine Learning and Data Science.",
```

2023-10-01 11:55 UTC, CBID2 commented on database/resources/blogs.json
> +    "description": "In this article, you’ll find the top 100+ latest projects and ideas on Machine Learning,which are beneficial for both beginners and experienced professionals. These projects are a
```suggestion
    "description": "In this article, you’ll find the top 100+ latest projects and ideas on Machine Learning,which are beneficial for both beginners and experienced professionals. These projects are also helpful for  students looking to start their journey in Machine Learning and Data Science.",
```

2023-10-01 11:55 UTC, CBID2 requested changes
I gave more feedback! :) Keep it up

2023-10-02 21:39 UTC, CBID2 approved these changes
Well done @digpatel123! :) Now, you just need another approval check! :)

2023-10-04 11:59 UTC, rupali-codes approved these changes

2023-10-04 11:59 UTC, merged