issue resolved fix:1725
rupali-codes/LinksHub pull request #1726
Opened 2023-10-01 11:10 UTC by yashnirmal

Closes #1725 

## Changes proposed

the data-tooltip-id , data-tooltip-content, data-tooltip-place were shifted to the children Icon

## Screenshots
<img width="421" alt="Screenshot 2023-10-01 at 4 39 42 PM" src="https://github.com/rupali-codes/LinksHub/assets/78169683/7ac5dda3-8949-4504-a5be-e4a61e7816dd">

2023-10-01 11:46 UTC, CBID2 commented
Hi @yashnirmal. Welcome to LinksHub! :) This issue has not been assigned to nor approved yet, so I'm closing this pull request for now. Once we approve & assign you to this issue, your pull request will be reopened. While you wait, please refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project! 😊 We can’t wait to work with you! 😊👍🏾

2023-10-02 11:20 UTC, Anmol-Baranwal commented
@CBID2 
I've assigned him the issue and included the corresponding labels, we can now move forward with this.

2023-10-02 13:51 UTC, CBID2 approved these changes
LGTM

2023-10-02 15:13 UTC, Anmol-Baranwal requested changes
@yashnirmal 
There is a border on focus, please remove that.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c8b1d7d2-71d5-4052-90de-7ac737fe7781)

It seems weird, else everything works.

2023-10-04 17:29 UTC, yashnirmal commented
> @yashnirmal There is a border on focus, please remove that.
> 
> ![image](https://user-images.githubusercontent.com/74038190/272010466-c8b1d7d2-71d5-4052-90de-7ac737fe7781.png)
> 
> It seems weird, else everything works.

Hey @Anmol-Baranwal I have made the change to fix this. Let me know if any thing else is there

2023-10-04 20:29 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me. 

> Everything else is good. Thanks for the changes.

2023-10-04 22:08 UTC, CBID2 approved these changes
Well done @yashnirmal! 😊

2023-10-04 22:11 UTC, merged