feat: Add Hugo link
rupali-codes/LinksHub pull request #1774
Opened 2023-10-03 13:47 UTC by R055A

Closes #1709 

## Changes proposed

Add link for Hugo framework website to the 'Other' category under a new subcategory named 'Other Tools' (URL: other/other-tools)

## Screenshots

![one](https://github.com/rupali-codes/LinksHub/assets/14985050/2b83c741-1db4-4d74-9645-b3cb1adce004)

![two](https://github.com/rupali-codes/LinksHub/assets/14985050/17e695fb-ae18-4f04-a503-fb1ec2f6aef3)

## Note to reviewers

Hacktoberfest

2023-10-03 14:04 UTC, CBID2 requested changes
Hi @R055A! :) Just made some adjustments to the description. Other than that, you're off to a great start! :)

2023-10-03 14:04 UTC, CBID2 commented on database/other/other-tools.json
> +    "description": "Hugo is a popular open-source static site generator that offers blistering speed, robust content management, shortcodes, built-in templates, multilingual and i18n support, and mor
```suggestion
    "description": "If you're looking for a framework to help you build your documentation site quickly, check out Hugo. It allows you to output your content in multiple formats, including JSON or AMP as well as provides shortcodes to simplify your Markdown files.",
```

2023-10-04 02:13 UTC, CBID2 submitted a review, later dismissed
Well done @R055A! :) @Anmol-Baranwal, it's your turn! :)

2023-10-04 06:56 UTC, Anmol-Baranwal reviewed
@CBID2 
Rather than creating a new subcategory, can't we add this in `Dev Tools` subcategory in 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/cf6f6cb2-597a-4687-a327-5cedde815bac)

What do you think?

2023-10-04 07:08 UTC, CBID2 commented
> @CBID2 
> 
> Rather than creating a new subcategory, can't we add this in `Dev Tools` subcategory in 
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/cf6f6cb2-597a-4687-a327-5cedde815bac)
> 
> 
> 
> What do you think?

I don't know @Anmol-Baranwal. My intention with technical writing subcategory is to create a hub of tools where people who have that role can find what they need, especially since they are not often spotlighted in conversations about roles to pursue in tech.

2023-10-04 07:27 UTC, Anmol-Baranwal commented
> I don't know @Anmol-Baranwal. My intention with technical writing subcategory is to create a hub of tools where people who have that role can find what they need, especially since they are not often spotlighted in conversations about roles to pursue in tech.

See the image below.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/caa1bc36-5abb-4fe4-9881-3a599bcc4066)


It is in `Other/other tools` not `technical writing`

2023-10-04 12:55 UTC, CBID2 commented
> > I don't know @Anmol-Baranwal. My intention with technical writing subcategory is to create a hub of tools where people who have that role can find what they need, especially since they are not often spotlighted in conversations about roles to pursue in tech.
> 
> 
> 
> See the image below.
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/caa1bc36-5abb-4fe4-9881-3a599bcc4066)
> 
> 
> 
> 
> 
> It is in `Other/other tools` not `technical writing`

Thanks for pointing that out @Anmol-Baranwal! :) I still want it in `Technical Writing/Tools` though.

2023-10-04 14:07 UTC, CBID2 commented
Yeah @R055A. When I raised this issue, that option was not in the issue for it. There's a PR that's going to address it soon. For now, just add it to that category.

2023-10-05 05:35 UTC, CBID2 commented
> technical-writing/tools

technical-writing/tools @R055A

2023-10-05 05:55 UTC, Anmol-Baranwal requested changes
@R055A 
Change the category of `Hugo` to `Technical Writing/Technical Writing Tools` and remove this subcategory `Other Tools` as mentioned in the image below.

Remove it from here:

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a542521a-0de4-4b82-8ff8-42817c8d96c7)


and add it here:

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/146b4ad8-6eab-420d-93fa-c65d64768952)

2023-10-05 16:14 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me. 

> @R055A thanks for the changes.

2023-10-05 16:15 UTC, CBID2 approved these changes
Well done @R055A

2023-10-05 16:15 UTC, merged