Add lucide icons link
rupali-codes/LinksHub pull request #1823
Opened 2023-10-05 18:51 UTC by itaim18

closes #1822 

## Changes proposed

Added the link as another object in `database/frontend/icons.json`

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/37772742/775dad5d-b1f0-4aeb-b91e-1945a8580a88)

2023-10-05 19:08 UTC, CBID2 commented
Hi @itaim18. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode so I can review your issue. In the future, please wait until your issue has been approved and assigned to you before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

2023-10-05 19:12 UTC, itaim18 commented
Oh sure!😅
Yet, it's a good resource which I have used in way too many projects to avoid it for your dictionary.
Definitely right about that approval protocol :)

2023-10-05 19:14 UTC, CBID2 commented on database/frontend/icons.json
> +    "description": "Lucide is a Beautiful & consistent icon toolkit made by the community.",
[proofreading] Interesting resource! :)  However, when you're describing your resources, avoid doing things like capitalizing words that are not at the beginning of a sentence (programming languages are an exception to this). It makes descriptions unclear.  
```suggestion
    "description": "Lucide is a beautiful & consistent icon toolkit made by the community.",
```

2023-10-05 19:15 UTC, CBID2 requested changes
Hi @itaim18! :)  I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-10-05 19:21 UTC, CBID2 commented
> Oh sure!😅 Yet, it's a good resource which I have used in way too many projects to avoid it for your dictionary. Definitely right about that approval protocol :)

Great @itaim18! :) Tag me, @Anmol-Baranwal, or @rupali-codes when you're ready

2023-10-05 19:23 UTC, itaim18 commented
On it!

2023-10-05 23:00 UTC, itaim18 commented
@CBID2 Ready!

2023-10-06 01:45 UTC, CBID2 approved these changes
Well done @itaim18! :) @Anmol-Baranwal, it's your turn! :)

2023-10-06 09:35 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-06 09:39 UTC, merged