Adding link in Icons section
rupali-codes/LinksHub pull request #1825
Opened 2023-10-05 18:53 UTC by Prakhar-Shankar

## Fixes Issue

Closes #1824 

## Changes proposed

Added a link in Icons section

## Note to reviewers

Would love to add more contributions.

2023-10-05 18:59 UTC, CBID2 commented
Hi @Prakhar-Shankar! :) Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode so I can review your issue. In the future, please wait until your issue has been approved and assigned to you before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

2023-10-05 19:05 UTC, CBID2 commented on database/frontend/icons.json
> +    "description": "Simple and clean SVG icon pack with the code to support Rails, Sprockets, Node.js, Gulp, Grunt and CDN.",
[proofreading] There's a missing comma after "Grunt" 
```suggestion
    "description": "Simple and clean SVG icon pack with the code to support Rails, Sprockets, Node.js, Gulp, Grunt, and CDN.",
```

2023-10-05 19:06 UTC, CBID2 requested changes
Hi @Prakhar-Shankar! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or spell check before making a pull request. Other than that, you're off to a great start! :)

2023-10-05 19:24 UTC, Prakhar-Shankar commented
> Hi @Prakhar-Shankar! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or spell check before making a pull request. Other than that, you're off to a great start! :)

Hi, thank you for the suggestion. I will take care of this in the future.

2023-10-06 07:22 UTC, rupali-codes approved these changes

2023-10-06 07:22 UTC, rupali-codes commented
> Reference in ne

Its alright :)

2023-10-06 07:23 UTC, merged