Adding keycloak
rupali-codes/LinksHub pull request #1865
Opened 2023-10-06 18:59 UTC by Prakhar-Shankar

## Fixes Issue

Closes #1864 

## Changes proposed

Keycloak is a authentication service provider.
Adding this in category - `Backend`,  sub-category- `Authentication`

2023-10-06 19:02 UTC, CBID2 commented
Hi @Prakhar-Shankar. Welcome to LinksHub! :) Even though you've raised an issue, it has not been approved or assigned to you yet. For now, your PR will be in draft mode, and once it's approved, you'll get a review.  In the future, please wait until your issue has been approved and assigned to you before you submit a pull request. Happy Contributing! 😊

2023-10-06 19:06 UTC, CBID2 commented on database/backend/authentication.json
> +    "description": "Add authentication to applications and secure services with minimum effort. There is no need to deal with storing or authenticating users. Keycloak provides user federation, stron
[proofreading/suggestion] So far, this description describes the function of Keycloak. However, the first two sentences describing authentication in general terms make that point unclear.  
```suggestion
    "description": "Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.",
```

2023-10-06 19:08 UTC, CBID2 requested changes
Hi @Prakhar-Shankar! :) I pointed out a suggestion in my inline comment. In the future, consider focusing more on the resource's purpose when describing them (and running them through a tool like Grammarly for grammar errors) before making a pull request. Other than that, you're off to a great start! :)

2023-10-06 19:30 UTC, CBID2 approved these changes
Well done @Prakhar-Shankar! :) @Anmol-Baranwal, it's your turn.

2023-10-06 19:32 UTC, Prakhar-Shankar commented
> Well done @Prakhar-Shankar! :) @Anmol-Baranwal, it's your turn.

Thank you for the encouragement.

2023-10-06 19:34 UTC, CBID2 commented
> > Well done @Prakhar-Shankar! :) @Anmol-Baranwal, it's your turn.
> 
> Thank you for the encouragement.

Anytime my friend! :)

2023-10-07 06:42 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-07 06:43 UTC, merged