[Enhancement] : Added Social Media icons in README.md
rupali-codes/LinksHub pull request #1891
Opened 2023-10-08 06:12 UTC by shelar1423

Added social media icons in the Socials  section of README.md to make it look more appealing.
before:
![image](https://github.com/rupali-codes/LinksHub/assets/82649533/66767941-7ac3-495f-bfe1-0d65668c9c09)

After:
![image](https://github.com/rupali-codes/LinksHub/assets/82649533/2c2a7f45-b08e-4883-9c03-93745062448f)

2023-10-08 06:33 UTC, CBID2 commented
Hi @shelar1423. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode so I can review your issue. In the future, please wait until your issue has been approved and assigned to you before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to this project. Happy Contributing! 😊

2023-10-08 06:53 UTC, shelar1423 commented
Hey @CBID2 sorry for this one will take of this next time , so can I now create this issue and then raise PR after assigned to it by closing this current pr?

2023-10-08 06:54 UTC, CBID2 commented
Sure

2023-10-08 07:06 UTC, shelar1423 commented
@CBID2 done, kindly assign me the issue,thank you

2023-10-08 07:41 UTC, shelar1423 commented
@CBID2 hey could you change the issue title i actully did but it is not reflecting on my side..

2023-10-08 07:45 UTC, CBID2 approved these changes
Looks good! @Anmol-Baranwal, you're up! :)

2023-10-08 07:46 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-08 07:47 UTC, merged

2023-10-08 07:48 UTC, CBID2 commented
Congratulations @shelar1423! You made your first PR! :)

2023-10-08 07:48 UTC, Anmol-Baranwal requested changes
Please update the twitter handle

2023-10-08 07:48 UTC, Anmol-Baranwal commented on README.md
> +- Follow us on [X (Twitter) ](https://twitter.com/the_linkshub) <img src="https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/x-social-media-logo-icon.png" alt="Discord" widt
```suggestion
- Follow us on [X (Twitter) ](https://twitter.com/linkshubdotdev) <img src="https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/x-social-media-logo-icon.png" alt="Discord" width="25" height="25"  align="center"> 
```

2023-10-08 07:49 UTC, Anmol-Baranwal commented
@CBID2 
Should we revert the commit?

2023-10-08 07:50 UTC, CBID2 commented
> @CBID2 
> 
> Should we revert the commit?

Why @Anmol-Baranwal?

2023-10-08 07:51 UTC, Anmol-Baranwal commented
@CBID2 
No worries, don't do it.

2023-10-08 11:38 UTC, shelar1423 commented
hey @Anmol-Baranwal i would like to work on isse #1703  but the conversation there is locked

2023-10-09 07:00 UTC, Anmol-Baranwal commented
> hey @CBID2 @Anmol-Baranwal i would like to work on isse #1703 but the conversation there is locked

I have already raised a PR for that.