added a nlp section section
rupali-codes/LinksHub pull request #1932
Opened 2023-10-10 12:16 UTC by Arnabhit

Fixes Issue
Closes  #1919 

## Changes proposed

I Have added a subcategory Natural Language Processing under the category AI. 

## Screenshots

![Screenshot (63)](https://github.com/rupali-codes/LinksHub/assets/113552756/8c7a07aa-5c87-433f-b575-700bbd098a88)

![Screenshot (62)](https://github.com/rupali-codes/LinksHub/assets/113552756/9815d10d-d9d1-4191-baf4-c5342fd0b3ef)

2023-10-10 12:30 UTC, CBID2 requested changes
Made some suggestions @Arnabhit

2023-10-10 12:30 UTC, CBID2 commented on database/artificial_intelligence/natural-language-processing.json
> +        "description": "This course starts with the basics of text processing including basic pre-processing, spelling correction, language modeling, Part-of-Speech tagging, Constituency and Dependen
```suggestion
        "description": "This course teaches the basics of text processing, including  pre-processing, spelling correction, language modeling, Part-of-Speech tagging, Constituency and Dependency Parsing, Lexical Semantics, distributional Semantics, and topic models.",
```

2023-10-10 13:30 UTC, Arnabhit commented on database/artificial_intelligence/natural-language-processing.json
> +        "description": "This course starts with the basics of text processing including basic pre-processing, spelling correction, language modeling, Part-of-Speech tagging, Constituency and Dependen
i have done it .Please review it

2023-10-10 20:20 UTC, Anmol-Baranwal requested changes
Shorten the subcategory name to nlp, people who know will understand it.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/6f0ffa29-6cbd-45fd-950e-e19edb75ce2c)

Also, there should be no `-` between the name which happened due to this

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ff98f3f7-c075-43f7-a176-f75b140c8fc2)

2023-10-10 20:59 UTC, Arnabhit commented
ok i will do it

2023-10-10 21:07 UTC, Anmol-Baranwal commented
@Arnabhit 
Please take your time, no need to rush. We will review whenever you have made the changes.

2023-10-11 06:21 UTC, Arnabhit commented
ok thank you

2023-10-11 16:43 UTC, Arnabhit commented
done

2023-10-11 18:01 UTC, CBID2 commented on database/artificial_intelligence/NLP.json
> +        "description": " Fast.ai's Code-First Introduction to Natural Language Processing for beginner's.",
```suggestion
        "description": " Fast.ai's Code-First Introduction to Natural Language Processing for beginners.",
```

2023-10-11 18:02 UTC, CBID2 commented on database/artificial_intelligence/NLP.json
> +        "name": "Free Code Camp",
```suggestion
        "name": "freeCodeCamp",
```

2023-10-11 18:02 UTC, CBID2 commented on database/artificial_intelligence/NLP.json
> +        "description": "Provides NLP tutorials for Machine Learning Beginners",
```suggestion
        "description": "Provides NLP tutorials for Machine Learning beginners",
```

2023-10-11 18:03 UTC, CBID2 requested changes
Hi @Arnabhit! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-10-12 14:26 UTC, Arnabhit commented
done 🥲🥲

2023-10-12 18:29 UTC, Anmol-Baranwal reviewed
@rupali-codes 
Can you check why we can't access the description of it?

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c0c548a4-d709-40a0-ab7f-df90f46f3877)

Other than that, everything seems fine.

2023-10-12 19:58 UTC, Arnabhit commented
I am also not able to click the description icon. I am not able to do it. Can you plz help

2023-10-13 07:49 UTC, Anmol-Baranwal commented
@Arnabhit 
Just add a description in `TopBar/CategoryDescriptions.ts`. We will resolve the bug internally.

2023-10-13 19:22 UTC, Arnabhit commented
added the description

2023-10-13 23:12 UTC, CBID2 approved these changes
Looks good

2023-10-14 07:30 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-14 17:56 UTC, rupali-codes commented
> @rupali-codes Can you check why we can't access the description of it?
> 
> ![image](https://user-images.githubusercontent.com/74038190/274697940-c0c548a4-d709-40a0-ab7f-df90f46f3877.png)
> 
> Other than that, everything seems fine.

it was the name, it should be as per the URL but without dash or anything

2023-10-14 17:56 UTC, rupali-codes approved these changes
lgtm

2023-10-14 17:57 UTC, merged