chore: Add Hindi CSS YouTube Playlist (#1935)
rupali-codes/LinksHub pull request #1938
Opened 2023-10-10 17:45 UTC by JoyelJohny

## Fixes Issue

closes #1935

## Changes proposed

Added YouTube Playlist for in depth tutorial on CSS in hindi language

## Screenshots

## Note to reviewers

2023-10-10 20:22 UTC, Anmol-Baranwal requested changes
Some minor changes.

2023-10-10 20:23 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-10 21:19 UTC, CBID2 approved these changes
Well done @JoyelJohny! :) @rupali-codes, it's your turn! :)

2023-10-12 09:53 UTC, rupali-codes approved these changes

2023-10-12 09:53 UTC, merged