Added DSA category
rupali-codes/LinksHub pull request #1940
Opened 2023-10-11 05:40 UTC by ayushrakesh

## Fixes #1896 

## Changes proposed

Added DSA as a new category and subcategory - DSA-articles.

2023-10-11 06:57 UTC, Anmol-Baranwal commented
@rupali-codes @CBID2 
What do you think? After placement Prep, adding a dsa for this seems overkill. Since there is one for youtube as well.

Let me know what you think.

2023-10-11 12:13 UTC, ayushrakesh commented
> Reference

Hello, I think it will be betterif we add new seperate section for DSA, although it is a huge topic and it needs many resources (videos+documentation+articles+other-stuffs like new trends).

2023-10-11 12:47 UTC, Anmol-Baranwal commented
@ayushrakesh 
Let @CBID2 and @rupali-codes decide.

2023-10-11 15:22 UTC, ayushrakesh commented
> I think that'll be helpful.

Ok thanks

2023-10-12 18:12 UTC, Anmol-Baranwal commented
@ayushrakesh 
Why did you close this?

2023-10-13 16:07 UTC, ayushrakesh commented
> @ayushrakesh Why did you close this?

I have reopened the pull request, please merge it.

2023-10-13 17:46 UTC, Anmol-Baranwal requested changes
Please do these changes in this PR.

2023-10-13 17:46 UTC, Anmol-Baranwal commented on database/DSA/DSAarticles.json
> +      "name": "Best way to solve DSA problems!!- Become a pro",
```suggestion
      "name": "Mastering DSA Problem Solving: How to Become a Pro",
```

2023-10-13 17:46 UTC, Anmol-Baranwal commented on database/DSA/DSAarticles.json
> +      "description": "The article you linked to on Medium, titled -Best Way to Solve DSA Problems: Become a Pro, likely provides insights and guidance on how to excel in solving Data Structures and A
```suggestion
      "description": "This article offers valuable insights and guidance on excelling in Data Structures and Algorithms (DSA) problem-solving.",
```

2023-10-13 17:54 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-14 03:20 UTC, CBID2 approved these changes
Well done @ayushrakesh!😊 @rupali-codes and @Anmol-Baranwal, you're up! 😊

2023-10-14 04:35 UTC, ayushrakesh commented
> Well done @ayushrakesh!😊 @rupali-codes you're up! 😊

So you have commit changes?,,I don't have to change more ?

2023-10-14 07:49 UTC, Anmol-Baranwal commented
@ayushrakesh 
No, you don't have to make any changes. It is good and ready to merge if all the maintainers find it valid.

2023-10-14 17:38 UTC, rupali-codes commented
@ayushrakesh please be patient, don't close the PR. It may take sometime for us to review the PRs.

2023-10-14 17:48 UTC, merged