Add new link
rupali-codes/LinksHub pull request #1952
Opened 2023-10-11 17:06 UTC by Atul72

#1942

## Fixes Issue

Add new javascript link

## Screenshots

I did't set it up locally, just add the link. 

## Note to reviewers
Kindly add this PR.

2023-10-11 17:51 UTC, CBID2 commented on database/languages/javascript.json
>    }
[proofreading] As mentioned in the guidelines [here](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#appending-new-links-), you need to add a `language` field in your source is not in English.  
```suggestion
    "name": "javascript Beginning To Mastery",
    "description": "This playlist makes you a advance javascript programmer. Teach everything from beginning to advance level in Hindi.",
    "url": "https://youtube.com/playlist?list=PLwgFb6VsUj_n15Cg_y2ULKfsOR1XiQqPx&si=UJyXUgEH0_94SpYj",
    "category": "languages",
    "subcategory": "javascript",
    "language": "hindi"
  }
```

2023-10-11 17:57 UTC, CBID2 requested changes
Hi @Atul72! :) You're off to a great start! :) You forgot to add some fields and there were a few punctuation errors, so refer to my inline comment to help you. In the future, I highly recommend reading the guidelines in our Contributing Guide to format your resources and running your descriptions of them through Grammarly before submitting them as PRs.

2023-10-11 17:58 UTC, CBID2 approved these changes
Well done @Atul72! :) @rupali-codes and @Anmol-Baranwal, you're up! :)

2023-10-11 18:00 UTC, CBID2 approved these changes
:)

2023-10-12 06:49 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-12 09:44 UTC, rupali-codes approved these changes
All good!

2023-10-12 09:45 UTC, merged