add redux tutorial link
rupali-codes/LinksHub pull request #1961
Opened 2023-10-11 18:39 UTC by Tusharrgrg

## Fixes Issue

Closes #1944

## Changes proposed

Added a Redux Toolkit in english tutorial link.

## Screenshots
I haven't set it up locally; I just added the link.

## Note to reviewers

Please consider merging this pull request.

2023-10-11 22:41 UTC, CBID2 commented on database/frontend/react.json
> +    "description": "In this tutorial series on Redux Toolkit for beginners, we dive into the what, why and the how.",
[proofreading] just a typo
```suggestion
    "description": "In this beginner-level tutorial series on Redux Toolkit, we dive into the what, why, and the how.",

```

2023-10-11 22:44 UTC, CBID2 requested changes
Hi @Tusharrgrg! :) I pointed out a couple of proofreading errors in my inline comment. In the future, consider running your descriptions through Grammarly or spell check before making a pull request. Other than that, you're off to a great start! :)

2023-10-12 06:27 UTC, Tusharrgrg commented
Hey @CBID2, thank you for pointing that out. I have now updated the description, so please take a look at it and merge it.

2023-10-12 06:28 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-12 06:29 UTC, Anmol-Baranwal commented on database/frontend/react.json
> +    "description": "In this tutorial series on Redux Toolkit for beginners, we dive into the what, why and the how.",
Done!

2023-10-12 09:38 UTC, rupali-codes approved these changes
lgtm

2023-10-12 09:39 UTC, merged