chore: add Neetcode in Competitive Programming category
rupali-codes/LinksHub pull request #1966
Opened 2023-10-12 12:52 UTC by singodiyashubham87

## Fixes Issue
Fixes #1918 

## Changes proposed

I have added the Neetcode youtube channel into the database of the Competitive Programming category and validated the JSON too.

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/93720428/6dae2e2e-007b-46e3-8558-206ced54ef1c)

2023-10-12 18:27 UTC, rupali-codes requested changes
@singodiyashubham87 please don't remove any existing resource, kindly add Tushar Roy back

2023-10-12 19:42 UTC, singodiyashubham87 commented
@rupali-codes I'm really sorry for the mistake, I have rectified my mistake, kindly check it once.

2023-10-13 07:47 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-14 14:38 UTC, Anmol-Baranwal commented
@CBID2 
Please review.

2023-10-14 16:44 UTC, CBID2 requested changes
Hi @singodiyashubham87. I just gave some tips on how you can improve your entry.

2023-10-14 16:44 UTC, CBID2 commented on database/competitive_programming/cp-tutorials.json
> +    "description": "This is a youtuber helps students and professional to become better in Competitive Programming and Tech Interviews.",
```suggestion
    "description": "This video helps students and professionals to become better in Competitive Programming and tech interviews.",
```

2023-10-15 05:36 UTC, singodiyashubham87 commented on database/competitive_programming/cp-tutorials.json
> +    "description": "This is a youtuber helps students and professional to become better in Competitive Programming and Tech Interviews.",
@CBID2 I have updated the description

2023-10-15 06:36 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-16 13:13 UTC, CBID2 approved these changes
Looks great to me

2023-10-17 08:19 UTC, rupali-codes approved these changes
lgtm

2023-10-17 08:19 UTC, merged