Add youtube link for complete Kubernetes tutorial issue #1889
rupali-codes/LinksHub pull request #1980
Opened 2023-10-13 19:00 UTC by alienishi

## Fixes Issue

## Changes proposed

## Note to reviewers

2023-10-13 19:09 UTC, alienishi commented
@Anmol-Baranwal, @rupali-codes, and @CBID2, can you also please add hacktoberfest-accepted label, such that this contribution of mine will also get counted there :)

2023-10-13 23:22 UTC, CBID2 commented on database/youtube/Kubernetes.json
> +        "description": "Edureka's Kubernetes YouTube tutorial offers a comprehensive and beginner-friendly guide to understanding and mastering Kubernetes, a powerful container orchestration platform
[proofreading] You can make this a bit shorter. 
```suggestion
        "description": "Edureka's Kubernetes YouTube tutorial offers a comprehensive and beginner-friendly guide to understanding and mastering Kubernetes.",
```

2023-10-13 23:23 UTC, CBID2 requested changes
Hi @alienishi! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-10-14 07:43 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-14 08:26 UTC, alienishi commented
Hi @CBID2 will surely keep in my mind your suggestions :)
Should I change it and create another Pull Request ?

2023-10-14 15:10 UTC, Anmol-Baranwal commented
@alienishi 
Yeah, it will be approved and merged.

2023-10-14 22:08 UTC, CBID2 approved these changes
Looks good to me!

2023-10-15 06:26 UTC, rupali-codes approved these changes
lgtm

2023-10-15 06:27 UTC, merged