[Added] System Design Primer Github RepoAdded]
rupali-codes/LinksHub pull request #1987
Opened 2023-10-14 20:28 UTC by khushminder270

## Fixes #1984 

## Changes proposed

## Screenshots

## Note to reviewers

2023-10-14 20:48 UTC, Anmol-Baranwal requested changes
@CBID2 @rupali-codes 

Someone else created this issue, and he made those changes in this PR when the issue was not even unlocked to get assigned.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/0332daa4-d91f-4070-bdcc-32117885562b)

@khushminder270 
Please do the changes that you have mentioned in the issue, and not regarding other issues.

2023-10-14 22:03 UTC, CBID2 requested changes
Hi @khushminder270. Your PR is off to a great start. I just gave some suggestions on how to improve it.

2023-10-14 22:03 UTC, CBID2 commented on database/languages/c-programming.json
> +        "description": "C Language Tutorial for Beginners (with Notes & Practice Questions)",
```suggestion
        "description": "This is a C Language tutorial for beginners. It contains notes for reference & questions for practice",
```

2023-10-14 22:36 UTC, Anmol-Baranwal commented
@CBID2 
He needs to completely remove the resource for C programming, so there is no changes for the need.

2023-10-14 22:37 UTC, CBID2 commented
> @CBID2 
> 
> He needs to completely remove the resource for C programming, so there is no need for the changes.

Ahh ok @Anmol-Baranwal

2023-10-15 05:34 UTC, khushminder270 commented
@Anmol-Baranwal @CBID2 
Removed the changes related to other issues

2023-10-15 05:59 UTC, khushminder270 commented
@Anmol-Baranwal @CBID2
Please add **hacktoberfest-accepted** label to the PR

2023-10-15 06:38 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-15 06:41 UTC, Anmol-Baranwal commented
@CBID2 @rupali-codes 
He raised a PR for a issue which isn't assigned to him.

I'm closing this.

2023-10-15 06:41 UTC, closed without merging

2023-10-15 06:44 UTC, CBID2 commented
> @CBID2 @rupali-codes 
> 
> He raised a PR for a issue which isn't assigned to him.
> 
> 
> 
> I'm closing this.

Sorry @Anmol-Baranwal. My mistake. @khushminder270, I suggest raising an issue.

2023-10-15 06:47 UTC, Anmol-Baranwal commented
I noticed it, when the original author raised a PR. I even approved this.

2023-10-15 15:20 UTC, khushminder270 commented
@Anmol-Baranwal @CBID2 
I am not getting why it is marked as SPAM?

2023-10-15 15:33 UTC, CBID2 commented
> @Anmol-Baranwal @CBID2 
> 
> I am not getting why it is marked as SPAM?

Sorry about that

2023-10-15 16:37 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal @CBID2 I am not getting why it is marked as SPAM?

I would have seriously marked this as spam. It is always recommended to go with the flow.

Create a issue, then let us assign it and make a PR.

You created a PR for a issue which was assigned to someone else, believe me 99% maintainers would mark it as spam.

@CBID2 is kind enough to remove it. Just make sure to do it in the future.

Let us know if you want to know, how to contribute properly.