chore: replace broken link with new discord icon source
rupali-codes/LinksHub pull request #1991
Opened 2023-10-15 05:34 UTC by oyepriyansh

## Fixes Issue
Closes #1990

2023-10-15 06:05 UTC, CBID2 approved these changes
Looks good to me

2023-10-15 07:15 UTC, Anmol-Baranwal commented
| Header | Header |
|--------|--------|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/79650b18-229c-4b67-b578-b8b09d47085a) | ![image](https://oyepriyansh.pages.dev/assets/github/readme/discord.svg) | 

I think the first one looks clean and better.

2023-10-15 07:20 UTC, CBID2 commented
> | Header | Header |
> 
> |--------|--------|
> 
> | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/79650b18-229c-4b67-b578-b8b09d47085a) | ![image](https://oyepriyansh.pages.dev/assets/github/readme/discord.svg) | 
> 
> 
> 
> I think the first one looks clean and better.
> 
> 
> 
> @CBID2 @rupali-codes 
> 
> What do you think?
> 
> 
> 
> He has included the second one in the readme.

The second one does look cleaner @Anmol-Baranwal

2023-10-15 08:10 UTC, oyepriyansh commented
I can do any

2023-10-15 10:10 UTC, Anmol-Baranwal commented
> The second one does look cleaner @Anmol-Baranwal

Okay, then we will go with the second one (current version)

2023-10-15 10:17 UTC, Anmol-Baranwal requested changes
It is always better to use relative links to the repository instead of direct URLs. In this way, even if the original link is removed, there will be no issues.

2023-10-15 10:17 UTC, Anmol-Baranwal commented on README.md
> +- Join the LinksHub community on [Discord](https://discord.com/invite/NvK67YnJX5) <img src="https://oyepriyansh.pages.dev/assets/github/readme/discord.svg" alt="Discord" width="17" height="17"  align
```suggestion
- Join the LinksHub community on [Discord](https://discord.com/invite/NvK67YnJX5) <img src="https://github.com/rupali-codes/LinksHub/assets/74038190/0a9bece0-8378-4620-bcf5-0f6e4b1aa6bd" alt="Discord" width="20" height="20"  align="center">.
```

2023-10-15 10:19 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-15 15:38 UTC, CBID2 approved these changes
Looks good to me

2023-10-17 08:18 UTC, rupali-codes approved these changes
lgtm

2023-10-17 08:19 UTC, merged