Fix(Sidebar and Content): Refactoring of side bar and fixing main con…
rupali-codes/LinksHub pull request #20
Opened 2023-01-16 10:56 UTC by Eugene44-hub

…tents on right side

2023-01-16 20:16 UTC, rupali-codes requested changes
Hey, just noticed a few changes for mobile or it to be responsive
1. sidebar is fixed, its not scrolling
2. it shud be closed when any element is clicked
3. content overlapping
![image](https://user-images.githubusercontent.com/78981177/212759265-1293cf57-29e3-4c24-b496-07bbfffc6d14.png)

2023-01-16 20:39 UTC, Aadarsh805 requested changes

2023-01-16 20:39 UTC, Aadarsh805 commented on components/SideNavbar/SideNavbar.tsx
> +        <Logo className="text-3xl mb-4" />
Should make the Logo into a link to the home route

2023-01-17 15:13 UTC, rupali-codes commented
Awesome,

2023-01-17 15:13 UTC, Eugene44-hub commented
> Hey, just noticed a few changes for mobile or it to be responsive
> 
> 1. sidebar is fixed, its not scrolling
> 2. it shud be closed when any element is clicked
> 3. content overlapping
>    ![image](https://user-images.githubusercontent.com/78981177/212759265-1293cf57-29e3-4c24-b496-07bbfffc6d14.png)

fixed

2023-01-17 15:14 UTC, merged