Added Freepic icons resource.
rupali-codes/LinksHub pull request #2000
Opened 2023-10-15 20:30 UTC by Hemant-Lohar

Updated json file for frontend/icons category.

![image](https://github.com/rupali-codes/LinksHub/assets/71497317/213ecaec-f141-40aa-a45e-3a3562e51387)

Review and merge @Anmol-Baranwal @CBID2

2023-10-15 20:32 UTC, CBID2 approved these changes
Looks good to me

2023-10-15 20:33 UTC, CBID2 commented
Did you raise this as an issue @Hemant-Lohar?

2023-10-15 20:45 UTC, Hemant-Lohar commented
@CBID2 It's my bad I didn't follow all the guidelines provided in the contributions guidelines. I will correct it. Should I create a new pull request?

2023-10-15 20:47 UTC, CBID2 commented
> @CBID2 It's my bad I didn't follow all the guidelines provided in the contributions guidelines. I will correct it. Should I create a new pull request?
> 
> 

Not yet, just raise the issue and I'll review it. If it gets approved, I'll reopen your PR. If not, you can create a new one.

2023-10-15 20:49 UTC, Hemant-Lohar commented
I had raised the issue it was #1993

2023-10-15 23:48 UTC, CBID2 commented
> I had raised the issue it was #1993 @CBID2

Great @Hemant-Lohar. Now just add it to the PR form. I highly recommend reading [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9) to help you fill it out.

2023-10-23 18:41 UTC, CBID2 commented on database/frontend/icons.json
> +    "url": "https://www.freepik.com/icons",
[proofreading] Don't forget to add the `category` and `subcategory` names. Refer to [this section of our Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#appending-new-links-) for more context. 
```suggestion
    "name": "Freepik Icons",
    "description": "The biggest free icon library in the world. Find icons that go together Fast. It has 10M+ ready-to-use, free license icons.",
    "url": "https://www.freepik.com/icons",
    "category": "frontend",
    "subcategory: "icons"
```

2023-10-23 18:42 UTC, CBID2 requested changes
Hi @Hemant-Lohar. I made some suggestions to improve your PR. Other than that you're off to a great start! :)

2023-10-25 12:42 UTC, Anmol-Baranwal commented
@Hemant-Lohar 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

2023-11-04 19:40 UTC, Anmol-Baranwal commented
@Hemant-Lohar 
Are you interested in contributing?
If not, please let me know so that I can close the issue.

2023-11-08 15:53 UTC, closed without merging