add: Free Programming Books to projects open source
rupali-codes/LinksHub pull request #2015
Opened 2023-10-17 11:11 UTC by codeOraaange

## Fixes Issue

Closes #1997 

## Changes proposed

Add Free Programming Books Github Repo.

## Screenshots

## Note to reviewers

2023-10-17 11:17 UTC, CBID2 requested changes
Hi @codeOraaange, your PR is off to a great start. I just gave some suggestions on how to improve your description.

2023-10-17 11:17 UTC, CBID2 commented on database/open_source/projects.json
> +    "description": "Freely available programming books.",
[suggestion] This description could use a bit more detail. Consider mentioning the purpose of this project and why people should contribute to it. That way, people would become more interested in contributing.
```suggestion
    "description": "Freely available programming books.",
```

2023-10-18 13:50 UTC, codeOraaange commented
Thanks for suggestion @CBID2, I've adjusted.

2023-10-18 14:39 UTC, CBID2 approved these changes
Looks great

2023-10-19 16:58 UTC, merged