Added solidity as a subcategory
rupali-codes/LinksHub pull request #2021
Opened 2023-10-17 20:20 UTC by TIDYMOUSE

## Fixes Issue
Closes #999 

## Changes proposed

1. Added subcategory solidity with links to some of the best resources
2. Made changes following CONTRIBUTING.md
3. Added an ending curly brace on line 207 of CONTRIBUTING.md

## Note to reviewers
Hello, this is my first ever open source contribution. I am open to conversation for any other changes required if any. Thank You.

2023-10-18 04:49 UTC, CBID2 commented
Hi @TIDYMOUSE! 😊 Welcome to LinksHub! 😊 I closed your PR for now because you've not been assigned to the issue that it addresses. Please comment your interest in issue [962](https://github.com/rupali-codes/LinksHub/issues/962). If it gets approved, tag me or the other maintainers so we can review it. If it doesn't give approved, refer to our Contributing Guide so you can learn how to contribute to effectively.

2023-10-18 05:57 UTC, Anmol-Baranwal commented
@TIDYMOUSE 
Please link the correct issue from next time. It generally confuses us, since either one of us assign you so most are not aware, there is a issue for this.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

2023-10-18 11:23 UTC, TIDYMOUSE commented
Hey @Anmol-Baranwal , thank you for pointing out my mistake. I will definitely keep this in mind from next time. I hope you can review my code soon and tell me if any further corrections are required.

2023-10-19 12:50 UTC, Anmol-Baranwal submitted a review, later dismissed
@TIDYMOUSE 
Thanks for fixing minor typo in contributing.md.

🚀 Looks good to me.

2023-10-19 13:34 UTC, TIDYMOUSE commented
@Anmol-Baranwal Thank You, this was a confidence boost. I hope @rupali-codes and @CBID2 can review this asap.

2023-10-19 13:39 UTC, CBID2 requested changes
Hi @TIDYMOUSE! :) Your PR is off to a great start! There are some things that need improvement. In the future, I suggest running your descriptions through a tool like Grammarly before submitting them as a PR.

2023-10-19 13:39 UTC, CBID2 commented on database/languages/solidity.json
> +    "description": "Teaches all solidity concepts with an example from beginner to intermediate level",
```suggestion
    "description": "This site teaches all Solidity concepts with examples from beginner to intermediate level",
```

2023-10-19 14:12 UTC, TIDYMOUSE commented
Done @CBID2 it must have been something I under-looked in search for some good resources.

2023-10-19 15:53 UTC, CBID2 requested changes
I added more suggestions. Keep it up!

2023-10-19 15:59 UTC, TIDYMOUSE commented
done @CBID2 Anything else?

2023-10-21 07:33 UTC, CBID2 approved these changes
Looks good now @TIDYMOUSE. @Anmol-Baranwal, @rupali-codes, your turn 😃

2023-10-21 08:26 UTC, rupali-codes approved these changes
looks good

2023-10-21 08:26 UTC, merged