Add: New ML Learning resource
rupali-codes/LinksHub pull request #2032
Opened 2023-10-18 16:29 UTC by Bratajit-03

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-10-20 07:20 UTC, CBID2 requested changes
Hi @Bratajit-03! :) I gave some feedback on your description. Other than that you're off to a great start

2023-10-20 07:20 UTC, CBID2 commented on database/youtube/machine-learning.json
> +    "description": "This channel provides a complete guide to Machine Learning from Beginner to Advanced and clearing all latest concepts and technologies related to Data Science.",
```suggestion
    "description": "This channel provides a complete guide to Machine Learning from beginner to advanced and teaches the latest concepts and technologies related to Data Science.",
```

2023-10-20 07:26 UTC, Bratajit-03 commented
@CBID2 sir, i have done the necessary changes. please give it a view and allow it to merge.

2023-10-20 12:16 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-20 12:17 UTC, Anmol-Baranwal commented
> Well done @Bratajit-03! Note: I go by she/her 😃

LOL! 🤣

2023-10-21 07:18 UTC, rupali-codes approved these changes

2023-10-21 07:18 UTC, merged