added neon db to database.json
rupali-codes/LinksHub pull request #2034
Opened 2023-10-18 19:06 UTC by Hrithik0112

## Fixes Issue

- Added Neon DB to into Database sub-category of Backend Category

Fixes #2023 

## Changes proposed
- updated database.json

## Screenshots

![Screenshot 2023-10-19 003314](https://github.com/rupali-codes/LinksHub/assets/122002784/e72eaf4c-7a8f-4299-a5b1-0909569a76db)

2023-10-19 12:57 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-20 04:47 UTC, CBID2 requested changes
Hi @Hrithik0112! 😊 There are merge conflicts that need to be solved and your description needs a bit more tweaking. Other than that, you're off to a great start! 😊

2023-10-20 04:47 UTC, CBID2 commented on database/backend/database.json
> +    "description": "Neon is Serverless Postgres built for the cloud. Neon separates compute and storage to offer modern developer features such as autoscaling, branching, bottomless storage, and more
```suggestion
    "description": "Neon is Serverless Postgres built for the cloud. It separates compute and storage to offer modern developer features such as autoscaling, branching, bottomless storage, and more.",
```

2023-10-20 06:18 UTC, Hrithik0112 commented
@CBID2  I understand the problem, I guess you solved the issue, aur am I wrong? 
if I am so what I need to do know?
thank you for assistance.

2023-10-20 06:24 UTC, CBID2 commented
> @CBID2  I understand the problem, I guess you solved the issue, aur am I wrong? 
> 
> if I am so what I need to do know?
> 
> thank you for assistance.

Hi @Hrithik0112. I just gave feedback on the description and pointed out that you had merge conflicts. These occur when two or more people are working on the same file and make changes to the exact same lines of code. It's basically a technical version of a car crash.

2023-10-20 10:44 UTC, Hrithik0112 commented
@CBID2 have a look, is there something more to do, or it's done

2023-10-20 10:47 UTC, Hrithik0112 commented
@CBID2 can you help me advising, should create a new branch and make a new PR?

2023-10-20 12:11 UTC, Anmol-Baranwal commented
@Hrithik0112 
You can literally search anywhere, how to solve the merge conflict. I will do it for you, but in good repositories. You may have to do it several times.

2023-10-20 12:13 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-20 12:54 UTC, CBID2 approved these changes
Well done @Hrithik0112

2023-10-21 07:17 UTC, rupali-codes approved these changes
lgtm

2023-10-21 07:18 UTC, merged