Added ThemesBerg to Themes&Templates under Frontend Section
rupali-codes/LinksHub pull request #2041
Opened 2023-10-19 15:06 UTC by surya-mu

## Fixes Issue #2027 

## Changes proposed

Added Themesberg to Themes&Templates section under Frontend Section.

## Note to reviewers

I am open to any suggestions regarding this PR.

2023-10-20 04:42 UTC, CBID2 requested changes
Hi @surya-mu! 😊 Your description could be improved. Other than that, you're off to a great start! 😊

2023-10-20 04:42 UTC, CBID2 commented on database/frontend/themes-templates.json
> +    "description": "Provides Free and Premium Templates, Themes from a wide variety of Web Developers and Software Companies",
```suggestion
    "description": "Provides free and premium templates and themes from a wide variety of web development and software companies",
```

2023-10-20 05:46 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-20 07:23 UTC, CBID2 approved these changes
Looks great to me! @rupali-codes, you're up!

2023-10-21 07:17 UTC, rupali-codes approved these changes

2023-10-21 07:17 UTC, merged