chore:Add new link to c++(#2040)
rupali-codes/LinksHub pull request #2049
Opened 2023-10-20 12:54 UTC by ankush-w17

## Fixes Issue
Closes #2040 

## Changes proposed
Added new c++ course to the category : language sub-category : c++

## Screenshots

![Screenshot 2023-10-20 181905](https://github.com/rupali-codes/LinksHub/assets/142745393/2583b818-1b80-40ef-9e2d-e8a455fd30c2)

## Note to reviewers

2023-10-21 08:12 UTC, rupali-codes commented on database/languages/cpp.json
> +    "description": "It is a full C++ programming course. It consists of many lectures whose goal is to take you from beginner to advanced programming level.",
```suggestion
    "description": "It's a complete C++ tutorials. It convers all of the fundamental topics of the C++ language.",
```

2023-10-21 10:13 UTC, Anmol-Baranwal submitted a review, later dismissed
🚀 Looks good to me.

2023-10-23 11:43 UTC, CBID2 commented on database/languages/cpp.json
> +    "description": "It's a complete C++ tutorials. It convers all of the fundamental topics of the C++ language.",
```suggestion
    "description": "This video covers all of the fundamental topics of the C++ language.",
```

2023-10-23 11:44 UTC, CBID2 requested changes
Hi @ankush-w17! :) I pointed out some [typos or proofreading errors] that could be improved. Other than that, you’re off to a great start! :)

2023-10-23 19:15 UTC, CBID2 approved these changes
Looks good to me! :)

2023-10-25 11:21 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-25 17:37 UTC, rupali-codes approved these changes
Lgtm

2023-10-25 17:37 UTC, merged