docs: added the resources for learning git
rupali-codes/LinksHub pull request #2056
Opened 2023-10-21 07:28 UTC by Sanchitbajaj02

## Fixes Issue

issue #2030 

## Changes proposed

Added 3 resources to learn about git

2023-10-21 07:44 UTC, rupali-codes approved these changes
looks good to me, but from next time, please make sure to keep your changes only related to your issue, don't overdo anything :)

2023-10-21 07:44 UTC, CBID2 requested changes
Made some suggestions to improve your descriptions. Other than that, you're off to a great start! :)

2023-10-21 07:44 UTC, CBID2 commented on database/other/git.json
> +    "description": "It is one of the great books to learn git. It contains expert Git guide with tutorials, code examples, and collaboration tips.",
```suggestion
    "description": "This is one of the great books to learn Git. It contains tutorials, code examples, and collaboration tips.",
```

2023-10-21 07:44 UTC, CBID2 commented on database/other/git.json
> +    "description": "It is a free course provided by 'Udacity' which covers the essentials of using version control system using git.",
```suggestion
    "description": "It is a free course provided by Udacity, which covers the essentials of using Git.",
```

2023-10-21 07:51 UTC, rupali-codes commented on database/other/git.json
> +    "description": "It is one of the great books to learn git. It contains expert Git guide with tutorials, code examples, and collaboration tips.",
i guess it looks fine

2023-10-21 07:52 UTC, rupali-codes commented on database/other/git.json
> +    "description": "It is a free course provided by 'Udacity' which covers the essentials of using version control system using git.",
also this

2023-10-21 08:20 UTC, Sanchitbajaj02 commented
> looks good to me, but from next time, please make sure to keep your changes only related to your issue, don't overdo anything :)

Sure I will keep that in mind 😊

2023-10-21 10:12 UTC, Anmol-Baranwal requested changes
@Sanchitbajaj02 
Please add a description.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a7236095-3f49-4284-980b-1d4863eb2655)

2023-10-21 20:11 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-22 11:28 UTC, rupali-codes approved these changes
Lgtm

2023-10-22 11:31 UTC, merged