add: UIColors to Colors under Frontend Section
rupali-codes/LinksHub pull request #2072
Opened 2023-10-22 14:03 UTC by haseebyousuf

## Fixes Issue

Closes: #2003

## Changes proposed

Added UiColors to Colors section under Frontend Section

## Note to reviewers

I am open to any suggestions regarding this PR.

2023-10-22 21:54 UTC, Anmol-Baranwal submitted a review, later dismissed
🚀 Looks good to me.

2023-10-23 11:31 UTC, CBID2 requested changes
Hi @haseebyousuf! :) Just had a few typos

2023-10-23 11:31 UTC, CBID2 commented on database/frontend/colors.json
> +    "description": "UIColors is a interactive Tailwind CSS Color Palette UI with real examples. Create your own palette or edit anything from the library. It also allows you to import the palette dir
```suggestion
    "description": "UIColors is a interactive Tailwind CSS color palette UI with real examples. Create your own palette or edit anything from the library. It also allows you to import the palette directly to Figma file and more.",
```

2023-10-23 18:33 UTC, CBID2 approved these changes
Looks good to me @haseebyousuf! :) @Anmol-Baranwal and @rupali-codes, you're up! :)

2023-10-25 17:36 UTC, rupali-codes approved these changes
Lgtm

2023-10-25 17:36 UTC, merged