Added exploitDB resource
rupali-codes/LinksHub pull request #2095
Opened 2023-10-24 07:07 UTC by dellucifer

## Fixes Issue
`Closes #2075 `

## Changes proposed

- I have updated the repo with an awesome and needful resource which is a whole database of publicly available exploits.
- This database is from offensive security.

## Screenshots

![Screenshot 2023-10-24 123236](https://github.com/rupali-codes/LinksHub/assets/84488210/cc3a82b9-b8a0-4b9b-946b-1660b352f411)

## Note to reviewers

According to my experience, this is a mandatory resource for cybersecurity geeks. It helps them to know more about the technical aspects of the vulnerabilities by analysing the exploits.

2023-10-24 07:09 UTC, dellucifer commented
@rupali-codes @Anmol-Baranwal @CBID2, kindly review my PR. Let me know if there are any changes.

2023-10-24 11:18 UTC, CBID2 requested changes
You're close @dellucifer. Just need to make a few more edits

2023-10-24 11:18 UTC, CBID2 commented on database/cybersecurity/offensive_security.json
> +    "description": "ExploitDB is a full-fledged database of publicly available exploits for the disclosed vulnerabilities till date.",
```suggestion
    "description": "ExploitDB is a full-fledged database of publicly available exploits for disclosed vulnerabilities.",
```

2023-10-24 11:24 UTC, dellucifer commented
Suggested edits are done.

2023-10-24 11:57 UTC, CBID2 approved these changes
Looks great! :) @Anmol-Baranwal & @rupali-codes, you're up! :)

2023-10-25 11:26 UTC, Anmol-Baranwal commented
@dellucifer 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c4ea5735-720c-4925-8c08-5642c2a14015)

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

2023-10-25 11:27 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-27 18:28 UTC, rupali-codes approved these changes
lgtm

2023-10-27 18:28 UTC, merged