Adding Hitesh Sir's YouTube Channel
rupali-codes/LinksHub pull request #2108
Opened 2023-10-25 12:54 UTC by Darkrider0007

## Fixes Issue 
Closes #2096

## Changes proposed

- Adding Hitesh Sir's YouTube Channel
## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/109970907/41713f8e-b8b5-4eab-8ec8-537fe0a2bbc9)

## Note to reviewers
Thank You this is a amazing resource

2023-10-25 14:03 UTC, CBID2 requested changes
Just needs a few tweaks

2023-10-25 14:03 UTC, CBID2 commented on database/youtube/web-development.json
> +    "language": "English"
[suggestion] This field is only for non-English sources 
```suggestion
    
```

2023-10-25 14:04 UTC, CBID2 requested changes
Just gave another comment

2023-10-25 14:04 UTC, CBID2 commented on database/youtube/web-development.json
> +    "description": "It is an underrated channel for web development, android development, DevOps and a lot",
```suggestion
    "description": "It is an underrated channel for Web Development, Android development, DevOps, and more",
```

2023-10-25 16:42 UTC, Anmol-Baranwal requested changes
@Darkrider0007 
Deployment might be failing due to empty line

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/d4d18285-a5a6-43ee-bb06-20a30cddeeca)

Check locally and fix it.

2023-10-25 18:01 UTC, Darkrider0007 commented
Please take a loo i fix the issue

2023-10-25 22:31 UTC, CBID2 commented on database/youtube/web-development.json
> +    "language": "english"
[suggestion] The language feature is only for non-English resources. 
```suggestion
```

2023-10-25 22:32 UTC, CBID2 requested changes
Hi @Darkrider0007. Your PR is off to a good start. It just needs some more tweaking.

2023-10-26 05:44 UTC, Anmol-Baranwal commented
@CBID2 
I found out it is not the case, even I missed it up to now. 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/af03534e-3554-4905-8c41-43680359f53a)

So, I don't think there is need to remove the `english` from the PR.

2023-10-26 05:46 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-26 06:25 UTC, Darkrider0007 commented
@CBID2 please approve if there is not any issue

2023-10-26 13:50 UTC, CBID2 approved these changes
LGTM

2023-10-27 17:53 UTC, rupali-codes approved these changes
lgtm

2023-10-27 17:53 UTC, merged