Add MLH to open source programs
rupali-codes/LinksHub pull request #2127
Opened 2023-10-26 11:55 UTC by vg300

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-10-26 22:15 UTC, CBID2 commented
Hi @vg300. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode for now. In the future, please raise an issue and wait until it has been approved and assigned to you before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

2023-10-27 18:47 UTC, CBID2 requested changes
You're off to a good start @vg300. I gave a suggestion on how to improve it a bit.

2023-10-27 18:47 UTC, CBID2 commented on database/open_source/os-programs.json
> +      "description": "The MLH Fellowship is a 12-week internship for aspiring software engineers to contribute to the type of Open Source projects that every company depends on.",
```suggestion
      "description": "The MLH Fellowship is a 12-week internship for aspiring software engineers to contribute to Open Source projects that companies depend on.",
```

2023-10-28 03:38 UTC, vg300 commented
Hi @CBID2, thanks for your review. I have incorporated your suggestion. Please let me know if anything else is required :)

2023-10-28 03:39 UTC, CBID2 approved these changes
Looks good to me. @Anmol-Baranwal, your turn 😊

2023-10-28 07:50 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-28 18:15 UTC, rupali-codes approved these changes

2023-10-28 18:15 UTC, merged