Created new sub category in resources
rupali-codes/LinksHub pull request #2132
Opened 2023-10-27 07:48 UTC by Amanmawar17

## Fixes Issue  #2107

## Changes proposed
Added a new sub-category in the resources tab which was self-paced courses.

I made a new JSON file in the resources folder named self-paced courses.
I committed changes data.ts and index.ts to import new self-paced-course.json for this to be shown in the category.
## Screenshots
![Screenshot 2023-10-27 125930](https://github.com/rupali-codes/LinksHub/assets/88235531/2a99ce75-6035-401b-a364-f4026fbddaea)

## Note to reviewers
Suggest any required changes!!
Thank You.

2023-10-27 10:23 UTC, Anmol-Baranwal commented
@Amanmawar17 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

Including it in title won't work. 

You can see here, if the issue is linked.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/dcceabbf-f206-4368-8723-df29acdfb31d)

I've done it for you.

Just a heads-up to help you link issue properly next time. Have a great day!

2023-10-27 10:27 UTC, Anmol-Baranwal requested changes
@Amanmawar17 
Please add the description of the subcategory.

It will be in `TopBar/CategoryDescriptions.ts`

2023-10-27 14:02 UTC, Amanmawar17 commented
> @Amanmawar17 Please add the description of the subcategory.
> 
> It will be in `TopBar/CategoryDescriptions.ts`

I resolved this issue but can you tell me how I made a PR for new changes?

2023-10-27 21:45 UTC, CBID2 requested changes
Hi @Amanmawar17. The descriptions in your PR needs more improvement, so I provided suggestions to help you. Other than that, you're off to a great start! 😊

2023-10-27 21:45 UTC, CBID2 commented on database/resources/self-paced-courses.json
> +    "description": "This website provides 67 programming languages support to develop fluency in their very own way.",
```suggestion
    "description": "This website provides 67 programming languages to help aspiring developers to develop fluency in their own way.",
```

2023-10-27 21:45 UTC, CBID2 commented on database/resources/self-paced-courses.json
> +    "description": "Learning and mastery the both languages and various tracks that available on this website.",
```suggestion
    "description": "Learning and master both languages in various tracks on this website.",
```

2023-10-27 21:45 UTC, CBID2 commented on database/resources/self-paced-courses.json
> +    "description": "We can learn various self paced beginner friendly courses in their own website code editor.",
```suggestion
    "description": "Learn how to code and in various self paced beginner friendly courses on Codecademy. You can also put your skills into practice with their own website code editor.",
```

2023-10-28 14:41 UTC, Anmol-Baranwal reviewed
It's advisable to use "e-book" or "ebook" to properly convey the meaning of an electronic book.

What do you think?  `e book`, `e-book`, `ebook`

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/059e6fe0-291c-40ae-9cfe-12017a8378fc)

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5d46fb4a-6f62-426b-8a69-ffcce3b42156)

I am confused about the extra change. The description is definitely fixed, but which one is more suitable?

2023-10-29 06:03 UTC, Amanmawar17 commented
if we choose E-book then the description would not be there, and also E-Book is also not there,  showing this 
![Screenshot 2023-10-29 112542](https://github.com/rupali-codes/LinksHub/assets/88235531/76c62437-5044-4161-a065-94d77bb996bc)

so what revert back this E-book change and then open another issue for it?

2023-10-29 17:13 UTC, Anmol-Baranwal submitted a review, later dismissed
🚀 Looks good to me. 

@Amanmawar17 
It's fine, we will change it if it feels odd later on.

2023-10-29 17:14 UTC, Anmol-Baranwal commented
@CBID2 
You're up for review!

2023-10-30 06:27 UTC, CBID2 submitted a review, later dismissed
Looks great

2023-10-30 14:51 UTC, CBID2 commented
Found some conflicts that need merging @Amanmawar17

2023-10-30 15:04 UTC, Anmol-Baranwal commented
@Amanmawar17 
You can see the changes, and push it accordingly if you want, it will fix merge conflicts in case you have trouble using command line for the same.

2023-10-31 12:10 UTC, rupali-codes approved these changes
lgtm

2023-10-31 12:11 UTC, rupali-codes commented
HI @Amanmawar17 please resolve the merge conflicts

2023-11-03 18:25 UTC, rupali-codes approved these changes
Lgtm

2023-11-06 17:34 UTC, rupali-codes commented
@Amanmawar17  please resolve merge conflicts

2023-11-15 08:03 UTC, Anmol-Baranwal commented
I'm closing this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.

2023-11-15 08:03 UTC, closed without merging