Added 2 Podcast resources
rupali-codes/LinksHub pull request #2135
Opened 2023-10-27 19:29 UTC by HVbajoria

## Changes proposed

Through this PR, I have added about two amazing Podcasts: Overpowered and WVFRM.

## Screenshots

## Note to reviewers

2023-10-27 20:21 UTC, Anmol-Baranwal commented
@CBID2 
The PR number is #2135 & issue number is #2136

I think people are taking it granted, that we are allowing these again and again.

2023-10-27 20:23 UTC, CBID2 commented
> @CBID2 
> 
> The PR number is #2135 & issue number is #2136
> 
> 
> 
> I think people are taking it granted, that we are allowing these again and again.

In this case @Anmol-Baranwal, do what you must.

2023-10-28 05:18 UTC, HVbajoria commented
Hello @Anmol-Baranwal @CBID2,
Please let me know if I have made a mistake. I am really sorry if I have caused an inconvenience I just tried to do what I saw with the past pull requests and then work accordingly to add some good content. 
Could you please guide me I would learn and not repeat it. 
Thank you

2023-10-28 05:32 UTC, HVbajoria commented
Hello team,
I have got my mistake. I had to first create an issue and then ask you to assign it before creating a pull request for the same.
I am closing this pull request. Sorry for the inconvenience and thank you for pointing my mistake.

2023-10-28 07:48 UTC, Anmol-Baranwal commented
@HVbajoria 
Don't delete the branch, we will reopen this when the issue is assigned. I don't mean to discourage you, but you see we are like getting so many PRs like this so it's frustrating. No need to apologize.

2023-10-28 07:50 UTC, HVbajoria commented
> @HVbajoria Don't delete the branch, we will reopen this when the issue is assigned. I don't mean to discourage you, but you see we are like getting so many PRs like this so it's frustrating. No need to apologize.

Thank you for understanding. I will wait for the issue to be assigned.

2023-10-28 08:12 UTC, Anmol-Baranwal requested changes
It is properly mentioned in the contributing guidelines to check validity of json structure.

2023-10-28 08:12 UTC, Anmol-Baranwal commented on database/other/podcasts.json
> +  },
```suggestion
  }
```

2023-10-28 08:14 UTC, Anmol-Baranwal submitted a review, later dismissed
🚀 Looks good to me. 

> @CBID2 
Please review this.

2023-10-29 15:54 UTC, CBID2 requested changes
Just needs some tweaking @HVbajoria

2023-10-29 15:54 UTC, CBID2 commented on database/other/podcasts.json
> +    "description": " In Overpowered, the hosts Varun Mayya & Tanmay Bhat talk about everything that you can imagine about AI helping you get insights into how AI can integrate in various domains.",
```suggestion
    "description": " In Overpowered, the hosts Varun Mayya & Tanmay Bhat talk about everything that you can imagine about AI, helping you get insights into how this piece of tech can be integrated in various domains.",
```

2023-10-29 17:25 UTC, Anmol-Baranwal submitted a review, later dismissed
🚀 Looks good to me. 

> @CBID2 Please review.

2023-10-30 02:33 UTC, HVbajoria commented
Thank you @Anmol-Baranwal

2023-11-04 19:47 UTC, aftabrehan commented on database/other/podcasts.json
> +    "description": " In Overpowered, the hosts Varun Mayya & Tanmay Bhat talk about everything that you can imagine about AI, helping you get insights into how this piece of tech can be integrated in
Good resource. Just this starting space could to be removed.

```suggestion
    "description": "In Overpowered, the hosts Varun Mayya & Tanmay Bhat talk about everything that you can imagine about AI, helping you get insights into how this piece of tech can be integrated in various domains.",
```

2023-11-08 16:09 UTC, aftabrehan approved these changes
Looks good to me! 👍

2023-11-10 20:56 UTC, Anmol-Baranwal commented
@CBID2 
The changes requested by you have been done. Please review.

2023-11-10 21:04 UTC, CBID2 approved these changes
LGTM

2023-11-11 14:06 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-11-11 14:06 UTC, merged