Added react resources
rupali-codes/LinksHub pull request #2138
Opened 2023-10-27 22:37 UTC by Srish-ty

## Fixes Issue #2137 

## Changes proposed
- Added resource for React js

## Screenshots

## Note to reviewers

2023-10-27 22:38 UTC, Srish-ty commented
@rupali-codes  , Please review the pr and add relevant label.
This contribution is under hacktoberfest.

2023-10-27 22:42 UTC, Srish-ty commented
@Anmol-Baranwal @CBID2 , Please review the PR.
And let me know if any changes are expected.
And add relevant labels.

2023-10-28 01:31 UTC, CBID2 requested changes
Looks good @Srish-ty.Just needs an improvement.

2023-10-28 01:31 UTC, CBID2 commented on database/frontend/reactjs.json
> +    "description": "React.js, a widely popular JavaScript library, empowers developers to build dynamic user interfaces with ease. It simplifies the creation of interactive web applications by provid
```suggestion
    "description": "React.js, a widely popular JavaScript library, empowers developers to build dynamic user interfaces with ease. It simplifies the creation of interactive web applications by providing a declarative and component-based approach, making it a go-to choice for developers looking to craft modern and efficient frontend experiences.",
```

2023-10-28 01:53 UTC, Srish-ty commented
> @Srish-ty.There seems to be a deployment failure.

I'd made changes in `data.ts`, probably that's why was getting error.

i've removed that part and now it's deployed successfully. [commit link](https://github.com/rupali-codes/LinksHub/pull/2138/commits/76cc37fcadcf62df8cd4e6185b96abda76af5ed3).

@CBID2 , please review the PR

2023-10-28 02:27 UTC, CBID2 approved these changes
Looks great to me! 😊 @Anmol-Baranwal, you're up! 😊

2023-10-28 08:04 UTC, Anmol-Baranwal requested changes
Creating a json file won't create the subcategory.

Follow contributing guidelines to add files.

2023-10-28 08:05 UTC, Anmol-Baranwal commented
> Looks great to me! 😊 @Anmol-Baranwal, you're up! 😊

The issue is not assigned 😑 to him

2023-10-28 08:08 UTC, Anmol-Baranwal commented
@Srish-ty 
Did you know that if we add a spam label, you won't be able to contribute to Hacktoberfest for a lifetime? This is because participants who are disqualified are not eligible to participate in the upcoming years.

At least comment for assigning the issue, how will someone know.

2023-10-28 08:12 UTC, Srish-ty commented
> @Srish-ty Did you know that if we add a spam label, you won't be able to contribute to Hacktoberfest for a lifetime? This is because participants who are disqualified are not eligible to participate in the upcoming years.
> 
> At least comment for assigning the issue, how will someone know.

Sorry sir, but I didn't actually get you. To assign the issue to me? 
Or to add issue to the pr.

2023-10-28 08:19 UTC, Anmol-Baranwal commented
> > @Srish-ty Did you know that if we add a spam label, you won't be able to contribute to Hacktoberfest for a lifetime? This is because participants who are disqualified are not eligible to participate in the upcoming years.
> > At least comment for assigning the issue, how will someone know.
> 
> Sorry sir, but I didn't actually get you. To assign the issue to me? Or to add issue to the pr. @Anmol-Baranwal , sorry if this has caused any frustration, but because of GitHub actions the comments in issues are locked and unable to comment 😕

Let me explain the process.

The issues are locked so that people don't tag us unnecessarily to assign the issue. We will always see it at our end and then we will assign the issues and unlock them if we need to clarify something or when we are assigning the issue.

You need to create an issue and allow us to assign you the issue before you start working and submit a PR. This is followed everywhere in Open Source.

This is outlined in the contributing guidelines.
![image](https://user-images.githubusercontent.com/74038190/271955538-4a4cf1b9-0dae-4fea-8b2e-1f57423c741f.png)

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. 

@CBID2 will tell you more about this.

2023-10-28 08:22 UTC, Srish-ty commented
> > > @Srish-ty Did you know that if we add a spam label, you won't be able to contribute to Hacktoberfest for a lifetime? This is because participants who are disqualified are not eligible to participate in the upcoming years.
> > > At least comment for assigning the issue, how will someone know.
> > 
> > 
> > Sorry sir, but I didn't actually get you. To assign the issue to me? Or to add issue to the pr. @Anmol-Baranwal , sorry if this has caused any frustration, but because of GitHub actions the comments in issues are locked and unable to comment 😕
> 
> Let me explain the process.
> 
> The issues are locked so that people don't tag us unnecessarily to assign the issue. We will always see it at our end and then we will assign the issues and unlock them if we need to clarify something or when we are assigning the issue.
> 
> You need to create an issue and allow us to assign you the issue before you start working and submit a PR. This is followed everywhere in Open Source.
> 
> This is outlined in the contributing guidelines. ![image](https://user-images.githubusercontent.com/74038190/271955538-4a4cf1b9-0dae-4fea-8b2e-1f57423c741f.png)
> 
> You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it.
> 
> @CBID2 will tell you more about this.

@Anmol-Baranwal , oh okay, sorry for that.
Actually for few projects they asked to not wait till assigned n start working.
But again, sorry.

2023-10-28 08:28 UTC, Srish-ty commented
> Creating a json file won't create the subcategory.
> 
> Follow contributing guidelines to add files.
Yeah in contributions.md , there are three types mentioned.
And I wanted to work on adding links/ resources part

2023-10-28 08:47 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal , oh okay, sorry for that. Actually for few projects they asked to not wait till assigned n start working. But again, sorry.

It's not your fault; this process is followed everywhere, from large organizational repositories (like Microsoft's) to smaller ones. Projects that don't follow this can lead to chaos. What if someone else makes a PR for the same issue, or if the PR doesn't align with the codebase, it may be closed, and that will reflect in your profile.

As I mentioned, maintainers of decent repositories will mark such PRs as spam. No worries, just make sure to read the contributing guidelines because it will always be mentioned.

2023-10-29 23:20 UTC, CBID2 commented
> > @Anmol-Baranwal , oh okay, sorry for that. Actually for few projects they asked to not wait till assigned n start working. But again, sorry.
> 
> It's not your fault; this process is followed everywhere, from large organizational repositories (like Microsoft's) to smaller ones. Projects that don't follow this can lead to chaos. What if someone else makes a PR for the same issue, or if the PR doesn't align with the codebase, it may be closed, and that will reflect in your profile.
> 
> As I mentioned, maintainers of decent repositories will mark such PRs as spam. No worries, just make sure to read the contributing guidelines because it will always be mentioned.

@Srish-ty's issue has been approved and assigned @Anmol-Baranwal. Now you can review it! :)

2023-10-30 13:37 UTC, Anmol-Baranwal requested changes
if you're creating a subcategory, then you need to update data.ts and index.ts as well.

It won't be created just by adding a json file. Follow contributing guidelines.

2023-11-04 19:46 UTC, closed without merging

2023-11-04 19:46 UTC, Anmol-Baranwal commented
@Srish-ty 
I'm closing this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.