Added new course
rupali-codes/LinksHub pull request #2142
Opened 2023-10-28 15:14 UTC by dalvishruti14

Closes #2140

2023-10-28 22:29 UTC, CBID2 commented on database/youtube/web-development.json
> +    "language": "Hindi"
```suggestion
    "language": "hindi"
```

2023-10-28 22:29 UTC, CBID2 requested changes
Looks good @dalvishruti14! :) Just needs some improvement.

2023-10-29 15:52 UTC, CBID2 approved these changes
Looks great to me @dalvishruti14

2023-10-29 17:32 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-10-30 05:32 UTC, dalvishruti14 commented
@rupali-codes can you please review it

2023-10-31 12:09 UTC, rupali-codes approved these changes
lgtm

2023-10-31 12:10 UTC, merged