feat: Add Swift Sub Category
rupali-codes/LinksHub pull request #2160
Opened 2023-10-31 10:44 UTC by ketanbaitule

## Fixes Issue

Closes #2148 

## Changes proposed

- Add Sub Category in `data.ts` , `index.ts`
- Create swift.json
- Added Sub Category Description For Swift in CategoryDescriptions.ts

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/111437670/66f75047-3c10-4751-a6bd-5460d6b47b27)

![image](https://github.com/rupali-codes/LinksHub/assets/111437670/f52dd554-91dd-49e1-b32f-bf94d5c8f381)

## Note to reviewers

Suggest any required changes!!
Thank You.

2023-10-31 20:00 UTC, CBID2 commented on database/languages/swift.json
> +        "description": "The official documentation of Swift Programming Language provides comprehensive information, guides, and resources for developers using Swift for iOS, macOS, watchOS, and tvOS
```suggestion
        "description": "The official documentation of Swift. It provides comprehensive information, guides, and resources for developers using Swift for iOS, macOS, watchOS, and tvOS application development. It also covers the language syntax, standard library, and various features of Swift.",
```

2023-10-31 20:01 UTC, CBID2 requested changes
Hi @ketanbaitule. Your PR is of to be a pretty good start! :) It just needs some revision.

2023-11-01 06:34 UTC, CBID2 approved these changes
Looks good to me @ketanbaitule

2023-11-01 09:38 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-11-03 18:22 UTC, rupali-codes approved these changes
Lgtm

2023-11-03 18:23 UTC, merged