feat: Added Side Pagination button #2071
rupali-codes/LinksHub pull request #2181
Opened 2023-11-08 05:36 UTC by Raj100679

Closes #2071 

## Fixes Issue
Added Pagination button on the Side

## Changes proposed

## Screenshots
![Screenshot (113)](https://github.com/rupali-codes/LinksHub/assets/85561967/d954b2e8-146c-405f-9f5a-eef46c1e1ae8)

## Note to reviewers

2023-11-08 16:22 UTC, rupali-codes reviewed
Hey @Raj100679, can we make it horizontal instead, just right above the cards, in top-right corner

2023-11-08 17:15 UTC, Raj100679 commented
So should I make it horizontal when screen size gets small or for every screen size

2023-11-09 07:03 UTC, Raj100679 commented
@rupali-codes @Anmol-Baranwal 
![topSide](https://github.com/rupali-codes/LinksHub/assets/85561967/7107173c-5395-450d-9801-ea70f955f6ab)

2023-11-09 08:40 UTC, Anmol-Baranwal commented
> @rupali-codes @Anmol-Baranwal 

@rupali-codes What do you think?

This somehow feels weird due to next and prev as far as I believe.

2023-11-10 09:41 UTC, rupali-codes commented
@Raj100679 & @Anmol-Baranwal can we make it smaller? and reduce the gap, then it would look better I guess

2023-11-10 16:32 UTC, Raj100679 commented
@rupali-codes @Anmol-Baranwal 
![Screenshot (117)](https://github.com/rupali-codes/LinksHub/assets/85561967/b7761649-5eaf-4385-8818-31409ff8d20b)
Is this weird?

2023-11-18 14:15 UTC, Raj100679 commented
@rupali-codes @Anmol-Baranwal can you check it?

2023-11-18 23:08 UTC, CBID2 commented
> @rupali-codes @Anmol-Baranwal can you check it?

It looks ok to me! :)

2023-11-22 12:51 UTC, rupali-codes commented
Looks fine to me.

2023-11-22 12:51 UTC, rupali-codes submitted a review, later dismissed

2023-11-22 12:52 UTC, rupali-codes commented
@Anmol-Baranwal and @CBID2 are you up?

2023-11-22 12:53 UTC, CBID2 approved these changes
LGTM

2023-11-22 12:54 UTC, Raj100679 commented
@rupali-codes I guess , I haven't pushed this changes to the PR will update the PR for merging purpose.

2023-11-22 13:04 UTC, Anmol-Baranwal commented
> @rupali-codes I guess , I haven't pushed this changes to the PR will update the PR for merging purpose.

Please do it. It is easier for review purpose.

2023-11-22 13:18 UTC, Raj100679 commented
@rupali-codes @Anmol-Baranwal I have pushed the changes , Thanks

2023-11-22 21:21 UTC, Anmol-Baranwal reviewed
@rupali-codes 
What do you think?

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/0be93433-7782-4a80-8aad-419b5fc5704f)

This may not be appropriate, it should be only at one place right.

2023-12-02 10:40 UTC, rupali-codes reviewed
@Anmol-Baranwal It looks fine to me,

2023-12-02 11:41 UTC, aftabrehan commented
> @rupali-codes What do you think?
> 
> ![image](https://private-user-images.githubusercontent.com/74038190/285045646-0be93433-7782-4a80-8aad-419b5fc5704f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTc0OTIsIm5iZiI6MTcwMTUxNzE5MiwicGF0aCI6Ii83NDAzODE5MC8yODUwNDU2NDYtMGJlOTM0MzMtNzc4Mi00YTgwLThhYWQtNDE5YjVmYzU3MDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExMzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzkwNzYyYmExODE1OTc2Y2E0Y2QxZGZhNDM1NjljZDA0MmVlNDA5NjM3NTdhMjc4ZTM3ZDE4Yzk2OTMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gioNrO1q59zipbmL4TKIR-36eFj_tGcDLr-0SMm9_vc)
> 
> This may not be appropriate, it should be only at one place right.

@Anmol-Baranwal, Why are there two Paginations?

2023-12-02 17:44 UTC, Anmol-Baranwal commented
> > @rupali-codes What do you think?
> > ![image](https://private-user-images.githubusercontent.com/74038190/285045646-0be93433-7782-4a80-8aad-419b5fc5704f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTc0OTIsIm5iZiI6MTcwMTUxNzE5MiwicGF0aCI6Ii83NDAzODE5MC8yODUwNDU2NDYtMGJlOTM0MzMtNzc4Mi00YTgwLThhYWQtNDE5YjVmYzU3MDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExMzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzkwNzYyYmExODE1OTc2Y2E0Y2QxZGZhNDM1NjljZDA0MmVlNDA5NjM3NTdhMjc4ZTM3ZDE4Yzk2OTMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gioNrO1q59zipbmL4TKIR-36eFj_tGcDLr-0SMm9_vc)
> > This may not be appropriate, it should be only at one place right.
> 
> @Anmol-Baranwal, Why are there two Paginations?

There isn't supposed to be, but no worries.

We can handle it quickly. The PR has been open for too long, and we shouldn't make the author wait any longer.

2023-12-02 18:13 UTC, aftabrehan commented
> > > @rupali-codes What do you think?
> > > ![image](https://private-user-images.githubusercontent.com/74038190/285045646-0be93433-7782-4a80-8aad-419b5fc5704f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTc0OTIsIm5iZiI6MTcwMTUxNzE5MiwicGF0aCI6Ii83NDAzODE5MC8yODUwNDU2NDYtMGJlOTM0MzMtNzc4Mi00YTgwLThhYWQtNDE5YjVmYzU3MDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExMzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzkwNzYyYmExODE1OTc2Y2E0Y2QxZGZhNDM1NjljZDA0MmVlNDA5NjM3NTdhMjc4ZTM3ZDE4Yzk2OTMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gioNrO1q59zipbmL4TKIR-36eFj_tGcDLr-0SMm9_vc)
> > > This may not be appropriate, it should be only at one place right.
> > 
> > @Anmol-Baranwal, Why are there two Paginations?
> 
> There isn't supposed to be, but no worries.
> 
> We can handle it quickly. The PR has been open for too long, and we shouldn't make the author wait any longer.

Okay, make sense.

2023-12-03 15:07 UTC, aftabrehan reviewed
Excellent PR, @Raj100679 💪 🚀 💯 

The PR is okay, it just needs minor adjustments and then we're good to go 🚀

2023-12-03 15:07 UTC, aftabrehan commented on components/Pagination/Pagination.tsx
> +          }>
`clsx` is supposed to render multiple classes. We don't need to render it multiple times.

```suggestion
          <div className={clsx(
            'flex items-center',
            toporbottom == true ? 'px-6 py-1 gap-4' : 'gap-2'
           )}>
```

2023-12-03 15:07 UTC, aftabrehan commented on pages/[category]/[...subcategory].tsx
> +        className=" relative min-h-[calc(100%-68px)]  w-full pt-[85px] pb-4 md:min-h-[calc(100%-76px)] md:px-10 md:pt-10"
Please, avoid adding extra spaces.

```suggestion
        className="relative min-h-[calc(100%-68px)] w-full pt-[85px] pb-4 md:min-h-[calc(100%-76px)] md:px-10 md:pt-10"
```

2023-12-14 18:48 UTC, Raj100679 commented on pages/[category]/[...subcategory].tsx
> +        <div className=" min-w-full h-10 py-5" />
@aftabrehan , can you suggest what changes do u need? 
I can still work on it, I just forgot about it

2023-12-15 02:02 UTC, aftabrehan commented on pages/[category]/[...subcategory].tsx
> +        <div className=" min-w-full h-10 py-5" />
Is this empty div still required? I mean there are still two paginations, we can remove one of them, right?

2023-12-22 13:49 UTC, CBID2 commented on pages/[category]/[...subcategory].tsx
> +        <div className=" min-w-full h-10 py-5" />
Are you still working on this @Raj100679?

2023-12-22 13:50 UTC, CBID2 commented on pages/[category]/[...subcategory].tsx
> +  const toporbottom = true
What do you think @Raj100679?

2023-12-22 13:51 UTC, Raj100679 commented on pages/[category]/[...subcategory].tsx
> +        <div className=" min-w-full h-10 py-5" />
Hey, I will work on this

2024-01-08 06:48 UTC, aftabrehan requested changes

2024-01-08 06:48 UTC, aftabrehan commented on components/Pagination/Pagination.tsx
> +          }
I think we can achieve this in a single `clsx` wrapper.

```suggestion
          className={clsx(
            toporbottom == true
              ?  'w-full z-20 flex lg:w-full items-center justify-center absolute bottom-2 right-0'
              : 'z-20 flex w-full lg:w-full items-center justify-end absolute top-0 right-0'
           )}
```

2024-01-12 07:36 UTC, CBID2 commented
@Raj100679, any updates?

2024-01-15 15:46 UTC, Raj100679 commented
@CBID2 I will work on it today surely, Sorry for not replying

2024-01-16 13:07 UTC, Anmol-Baranwal commented
> @CBID2 I will work on it today surely, Sorry for not replying

The PR has been stale for very long. Please try to finish it as soon as possible.

2024-01-16 19:28 UTC, Raj100679 commented
@CBID2 Created a new pr, Can you check it, closing it here

2024-01-16 19:28 UTC, closed without merging