Added a new project idea (Web development) in the project-ideas.json
rupali-codes/LinksHub pull request #2187
Opened 2023-11-15 17:55 UTC by the-shivam-gupta

## Fixes Issue
Closes #2088 

## Changes proposed

## Screenshots

## Note to reviewers

2023-11-15 18:44 UTC, Anmol-Baranwal commented
@the-shivam-gupta 
You should add a profile photo because these are default ones, and it gives off a vibe like the contributor is new to GitHub. So, adding a photo would be good since your profile is decent enough. (GitHub profile)

2023-11-15 18:56 UTC, the-shivam-gupta commented
> @the-shivam-gupta 
> You should add a profile photo because these are default ones, and it gives off a vibe like the contributor is new to GitHub. So, adding a photo would be good since your profile is decent enough. (GitHub profile)

Thanks for the compliment! I'll update my profile soon. Honestly, I don't have a great photo of myself, which is why it's missing 😅.

2023-11-15 20:04 UTC, Anmol-Baranwal commented
> > @the-shivam-gupta
> > You should add a profile photo because these are default ones, and it gives off a vibe like the contributor is new to GitHub. So, adding a photo would be good since your profile is decent enough. (GitHub profile)
> 
> Thanks for the compliment! I'll update my profile soon. Honestly, I don't have a great photo of myself, which is why it's missing 😅.

You don't need to add your own photo. Anything that you find cool 😅

You can check some avatars [here](https://github.com/Anmol-Baranwal/Cool-GIFs-For-GitHub/blob/main/README.md#--cool-avatars-for-github-profile--)

2023-11-17 22:29 UTC, CBID2 commented on database/resources/project-ideas.json
> +    "description": "These projects will help you grasp the skills of a full-stack developer, and you can also add these projects to your resume. ",
```suggestion
    "description": "These projects will help you learn the skills to become a full-stack developer. You can even reference them in your resume. ",
```

2023-11-17 22:33 UTC, CBID2 requested changes
Hi @the-shivam-gupta! :) Your PR is off to a great start! :) I pointed out some proofreading errors in your description that could be improved.

2023-11-18 16:38 UTC, the-shivam-gupta reviewed
@CBID2  done

2023-11-18 19:41 UTC, CBID2 approved these changes
Looks good to me @the-shivam-gupta! :) @Anmol-Baranwal, @aftabrehan, it's your turn.

2023-11-19 06:32 UTC, Anmol-Baranwal approved these changes
> There are few great projects.

🚀 Looks good to me.

2023-11-19 15:56 UTC, aftabrehan approved these changes
Helpful resource, good job @the-shivam-gupta!

2023-11-19 16:19 UTC, merged