Feat: add new design for categories page
rupali-codes/LinksHub pull request #2195
Opened 2023-11-25 18:44 UTC by gakshita

Closes #2177 

## Changes proposed
New design for category page implemented

2023-11-25 23:28 UTC, CBID2 reviewed
The page looks good @gakshita, but can you revert [the commits that don't pertain to the issue that your PR solves?](https://github.com/rupali-codes/LinksHub/pull/2195/commits)

2023-11-27 14:10 UTC, gakshita commented
> The page looks good @gakshita, but can you revert [the commits that don't pertain to the issue that your PR solves?](https://github.com/rupali-codes/LinksHub/pull/2195/commits)

Have removed the unecessary commits

2023-11-27 14:33 UTC, aftabrehan requested changes
Excellent PR, @gakshita 💪 🚀 💯 

Thanks for the contribution. It just needs minor adjustments and then we're good to go. 

However, I have only reviewed the code yet. I'll proceed with UI testing and provide my feedback in a while. Feel free to ask if you have any questions or want clarification on something.

2023-11-27 14:33 UTC, aftabrehan commented on assets/icons/AddIcon.tsx
> +const AddIcon = ({ ...rest }: SVGProps<SVGSVGElement>) => {
I don't think it's a better approach to create a simple SVG icon as a component. Can you please create `.svg` file and just simply import it? It'll work as a React component and will accept props (e.g. `className`).

2023-11-27 14:33 UTC, aftabrehan commented on pages/[category]/index.tsx
> +            <div className="flex mt-8 justify-between	">
Please, avoid unnecessary spaces.

```suggestion
            <div className="flex mt-8 justify-between">
```

2023-11-27 14:33 UTC, aftabrehan commented on pages/[category]/index.tsx
> +                <div className="text-md text-text-quinary hidden md:block">
Please, use a `span` tag if you don't need to render it in a new line.

```suggestion
                <span className="text-md text-text-quinary hidden md:block">
```

2023-11-27 14:33 UTC, aftabrehan commented on pages/[category]/index.tsx
> +                    className={`group flex border dark:border-theme-primary dark:border-opacity-8 rounded-xl bg-theme-tertiary  hover:bg-theme-quaternary hover:bg-opacity-25	 px-3 py-1 dark:hover:bor
Any specific reason for using template literals here?

2023-11-27 14:33 UTC, aftabrehan commented on pages/[category]/index.tsx
> +                        className={`dark:text-text-primary text-lg capitalize font-semibold	`}
Please, use template literals only when it's required and avoid extra spaces.

```suggestion
                        className="dark:text-text-primary text-lg capitalize font-semibold"
```

2023-11-27 14:33 UTC, aftabrehan commented on pages/[category]/index.tsx
> +                        {' '}
Do we really require this space, or it is added prettier when saving the file?

2023-11-27 14:33 UTC, aftabrehan commented on components/Breadcrumps/index.tsx
> +        <div className="text-2xl	mx-2.5 font-semibold varela">/</div>
Any specific reason for using `varela` font?

2023-11-29 18:20 UTC, gakshita commented
@aftabrehan @rupali-codes @CBID2 all changes have been fixed from my side!

2023-11-30 13:00 UTC, aftabrehan reviewed
Thanks @gakshita! The code looks much better now.

However, here are a few suggestions from my side.

2023-11-30 13:17 UTC, aftabrehan commented
It all looks super awesome 🙌. Great work @gakshita. Please, help to adjust these two things as well, and then we're good to merge this PR.

1. Can you please add the background on the parent element?
<div align="center">
<img width="383" alt="Screenshot 2023-11-30 at 6 06 59 PM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/2f51d511-5033-485e-aaab-22f5b6da088f">
</div>

3. Can you please use a full width for the tile on the mobile screen to cover extra space?
<div align="center">
<img width="378" alt="Screenshot 2023-11-30 at 6 14 45 PM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/8438476e-d5e7-4754-a9f6-9e37e53a3767">
</div>

2023-12-01 03:38 UTC, CBID2 commented on pages/[category]/index.tsx
>                          Explore {subcat.name} resources for learning and growth.
Good point @aftabrehan

2023-12-01 17:26 UTC, Anmol-Baranwal commented
@gakshita 
Are you facing any problems regarding the changes? Please let me know; I will gladly help you.

2023-12-03 12:20 UTC, gakshita commented
Couldn't find item description data i the object, rest changes have been pushed.

2023-12-17 17:33 UTC, CBID2 commented
Any updates @gakshita? 😁

2024-01-10 08:22 UTC, rupali-codes commented
@gakshita you still working on it?

2024-01-13 09:04 UTC, merged