Added navigation for mobile devices
rupali-codes/LinksHub pull request #2198
Opened 2023-11-30 20:23 UTC by MAXASSASSINS

## Fixes Issue #2196 

## Changes proposed

- Created a new component handling navigation in mobile devices.
- Added some css in general layout.
- Fixed the width of the linkshub description on home page.

## Screenshots
<img width="392" alt="Screenshot 2023-12-01 at 1 42 53 AM" src="https://github.com/rupali-codes/LinksHub/assets/97503316/e59d4026-6086-416b-aadf-eeb50f04c787">
  
<img width="392" alt="Screenshot 2023-12-01 at 1 44 41 AM" src="https://github.com/rupali-codes/LinksHub/assets/97503316/52a68b4f-4670-4433-b07e-6a82868a9760">

## Note to reviewers

2023-12-01 05:21 UTC, CBID2 approved these changes
Looks good to me! @Anmol-Baranwal, @rupali-codes, check this out! 😁

2023-12-01 10:33 UTC, aftabrehan requested changes
Excellent PR, @MAXASSASSINS 💪 🚀 💯 

It just needs minor adjustments and then we're good to go 🚀

2023-12-01 10:33 UTC, aftabrehan commented on components/MobileBottomNav/MobileBottomNav.tsx
> +                isActive ? 'text-primary dark:text-white' : 'text-gray-400'
These classes are repeated, can we extract this code?

2023-12-01 10:33 UTC, aftabrehan commented on layouts/GeneralLayout.tsx
> +        className={`row-start-2 row-end-3 overflow-y-scroll max-h-[calc(100vh-156px)] sm:max-h-[calc(100vh-72px)] w-full bg-gray-100 dark:bg-[#101623] ${
Could you please explain this change?

2023-12-01 10:33 UTC, aftabrehan commented on components/MobileBottomNav/MobileBottomNav.tsx
> +      label: 'Search',
We need to pass `onClick` function from here. 

so we can do:
```js
onClick 
   ? <button onClick={onClick} className={commonCls}>{...}</button>
   : <Link href={href} className={commonCls}>{...}</Link>
```

This approach is much better and simpler. What do you think?

2023-12-01 18:38 UTC, Anmol-Baranwal approved these changes
@MAXASSASSINS 

🚀 Looks good to me. 

> Thanks! It is deployed.

2023-12-03 14:27 UTC, aftabrehan approved these changes
Looks good to me! 👍

2023-12-05 04:37 UTC, Anmol-Baranwal commented
@rupali-codes 
Review and merge this :)

2023-12-05 12:16 UTC, rupali-codes approved these changes
looks perfect

2023-12-05 12:17 UTC, merged