added illustration resources
rupali-codes/LinksHub pull request #225
Opened 2023-02-19 22:20 UTC by swissjake

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-02-20 05:49 UTC, Eugene44-hub requested changes

2023-02-20 05:49 UTC, Eugene44-hub commented on database/frontend/illustrations.json
> +        "description": "Free Icons & Illustrations design freely with instant downloads and commercial licenses.",
Looks good, but please format json properly it'll look more nicer

2023-02-20 19:48 UTC, rupali-codes requested changes
Hi, looks good to me, but could you please resolve the merge conflicts?

2023-02-21 05:05 UTC, rupali-codes approved these changes
lgtm

2023-02-21 05:06 UTC, merged