fix: improve the light-theme
rupali-codes/LinksHub pull request #2256
Opened 2024-02-04 05:53 UTC by CBID2

## Fixes Issue
Closes #2247 

## Changes proposed
This PR changes the website's light theme, making it easier for people to navigate the site. Here's what's been done so far:

- [ ] Make the border of the searchbar's input darker and thicker (see the first screenshot for reference.)
- [ ] 

## Screenshots
1. Search input having a dark input
![screenshot of search input with a darker border](https://github.com/rupali-codes/LinksHub/assets/105683440/d0d72a08-26f3-4f64-a215-da8e9ec60163)

## Note to reviewers
This is a work-in-progress

2024-02-04 14:07 UTC, Anmol-Baranwal commented
@CBID2 

I know the draft PR isn't ready, but I would suggest these changes.

1. Even if you want a border in dark theme, use the light border that is used in the cards as shown.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/fde21ad4-f477-43a6-9835-fcd06914e5b7)

2. and the same for light background. Use a little light border if possible (use opacity). 
It shouldn't be the reason of distraction.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f7acd6e-65d8-4215-b713-cce07cb0b6e2)

2024-02-04 14:10 UTC, CBID2 commented
> @CBID2 
> 
> 
> 
> I know the draft PR isn't ready, but I would suggest these changes.
> 
> 
> 
> 1. Even if you want a border in dark theme, use the light border that is used in the cards as shown.
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/fde21ad4-f477-43a6-9835-fcd06914e5b7)
> 
> 
> 
> 2. and the same for light background. Use a little light border if possible (use opacity). 
> 
> It shouldn't be the reason of distraction.
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f7acd6e-65d8-4215-b713-cce07cb0b6e2)
> 
> 

@Anmol-Baranwal, so...something like this: https://github.com/rupali-codes/LinksHub/blob/main/components/Cards/Card.tsx

2024-02-04 14:21 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal, so...something like this: https://github.com/rupali-codes/LinksHub/blob/main/components/Cards/Card.tsx `border-light-white`

For light, I'm not sure if there is any. But for dark, using the one on the cards will avoid mismatch of theme.
You can check locally.

2024-02-04 17:48 UTC, sarava338 commented
In Dark theme, we have very dark color in background. But in Light theme, We did not. So I hope, the very light color in background and swap the with card's background color will do the trick.

Dark Theme
![image](https://github.com/rupali-codes/LinksHub/assets/93024887/a74cfa2e-8d81-4493-bade-cf548b8ccc32)

Light Theme
![image](https://github.com/rupali-codes/LinksHub/assets/93024887/93f3c1e7-485f-4f04-a606-3719951677e9)

2024-02-04 18:19 UTC, CBID2 commented
> In Dark theme, we have very dark color in background. But in Light theme, We did not. So I hope, the very light color in background and swap the with card's background color will do the trick.
> 
> 
> 
> Dark Theme
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/93024887/a74cfa2e-8d81-4493-bade-cf548b8ccc32)
> 
> 
> 
> Light Theme
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/93024887/93f3c1e7-485f-4f04-a606-3719951677e9)
> 
> 

So…you suggest that I use the dark theme’s background as a border for the light one @sarava338?

2024-02-04 18:29 UTC, Anmol-Baranwal commented
> So…you suggest that I use the dark theme’s background as a border for the light one @sarava338?

He is saying that in dark theme -> The cards are light color compared to the background color.

But it's the opposite in the light theme, so if we make background complete white and cards as the background color (which is lighter one). Then this problem would be fixed.

@rupali-codes 
Don't do this without consulting rupali.

2024-02-04 18:36 UTC, sarava338 commented
> > So…you suggest that I use the dark theme’s background as a border for the light one @sarava338?
> 
> He is saying that in dark theme -> The cards are light color compared to the background color.
> 
> But it's the opposite in the light theme, so if we make background complete white and cards as the background color (which is lighter one). Then this problem would be fixed.
> 
> @rupali-codes 
> Don't do this without consulting rupali.

Yes. And in the Light theme, the little dark color has to be a little darker.

2024-02-04 23:29 UTC, CBID2 commented
> > So…you suggest that I use the dark theme’s background as a border for the light one @sarava338?
> 
> He is saying that in dark theme -> The cards are light color compared to the background color.
> 
> But it's the opposite in the light theme, so if we make background complete white and cards as the background color (which is lighter one). Then this problem would be fixed.
> 
> @rupali-codes Don't do this without consulting rupali.

Ooh just saw this @Anmol-Baranwal after adding the new changes (see the updated photos in the screenshot section of my PR's form). Hopefully, @rupali-codes won't mind the changes.

2024-02-05 14:13 UTC, rupali-codes reviewed
I don't see any changes except the border on searchbar

This PR
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/170fb901-0891-4f16-9346-a47bfd52ea66)

Main site
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/f78a96bd-b08c-4e41-b8b3-dd13231ce311)

2024-02-05 14:15 UTC, CBID2 commented
> I don't see any changes except the border on searchbar
> 
> 
> 
> This PR
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/170fb901-0891-4f16-9346-a47bfd52ea66)
> 
> 
> 
> Main site
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/f78a96bd-b08c-4e41-b8b3-dd13231ce311)
> 
> 
> 
> 
> 
> 
> 
> 

It's a work-in-progress @rupali-codes. Still trying to figure out how to do the other parts.

2024-02-05 14:16 UTC, rupali-codes commented
@CBID2 alright, let us know if you need any help

2024-02-09 12:37 UTC, CBID2 commented
> @CBID2 alright, let us know if you need any help

Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?

2024-02-10 15:30 UTC, rupali-codes commented
> > @CBID2 alright, let us know if you need any help
> 
> Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?

where you wanna add border?

2024-02-10 15:48 UTC, CBID2 commented
> > > @CBID2 alright, let us know if you need any help
> 
> > 
> 
> > Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?
> 
> 
> 
> where you wanna add border?
> 
> 

The card components @rupali-codes

2024-02-11 08:02 UTC, rupali-codes commented
> > > > @CBID2 alright, let us know if you need any help
> > 
> > 
> > > 
> > 
> > 
> > > Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?
> > 
> > 
> > where you wanna add border?
> 
> The card components @rupali-codes

alright, it should be in `components/cards/card.tsx` file, then in the main `div` add border classes. 

What else are you struggling with?

2024-02-11 21:44 UTC, CBID2 commented
> > > > > @CBID2 alright, let us know if you need any help
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?
> > > 
> > > 
> > > where you wanna add border?
> > 
> > 
> > The card components @rupali-codes
> 
> alright, it should be in `components/cards/card.tsx` file, then in the main `div` add border classes.
> 
> What else are you struggling with?

Hi @rupali-codes. I added [the border to the main `div`](https://github.com/rupali-codes/LinksHub/blob/5acd6b910afed9f5bae2e1ff2582db0d6ab80390/components/Cards/Card.tsx#L31) like you suggested and nothing shows
 Did I do something wrong?

2024-02-14 09:31 UTC, rupali-codes commented
> > > > > > @CBID2 alright, let us know if you need any help
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Hey @rupali-codes and @Anmol-Baranwal, I’m struggling with adding the border to the card components. Can you help me please?
> > > > 
> > > > 
> > > > where you wanna add border?
> > > 
> > > 
> > > The card components @rupali-codes
> > 
> > 
> > alright, it should be in `components/cards/card.tsx` file, then in the main `div` add border classes.
> > What else are you struggling with?
> 
> Hi @rupali-codes. I added [the border to the main `div`](https://github.com/rupali-codes/LinksHub/blob/5acd6b910afed9f5bae2e1ff2582db0d6ab80390/components/Cards/Card.tsx#L31) like you suggested and nothing shows Did I do something wrong?

You've misplaced the double quotes 

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/42626834-40ba-4b07-89d3-92b3461f1da0)


It should be ` <div className="card-body border-light-silver border-2 border-opacity-75">`

2024-02-15 09:14 UTC, Anmol-Baranwal commented
@CBID2 
This is still in draft. Are the changes done.

2024-02-15 16:45 UTC, CBID2 commented
> @CBID2 
> 
> This is still in draft. Are the changes done.

No I have to do the footer @Anmol-Baranwal

2024-02-18 16:48 UTC, rupali-codes commented
> > @CBID2
> > This is still in draft. Are the changes done.
> 
> No I have to do the footer @Anmol-Baranwal

you need any help Chrissy?

2024-02-18 17:19 UTC, CBID2 commented
> > > @CBID2
> 
> > > This is still in draft. Are the changes done.
> 
> > 
> 
> > No I have to do the footer @Anmol-Baranwal
> 
> 
> 
> you need any help Chrissy?

Not yet @rupali-codes

2024-02-21 04:58 UTC, CBID2 commented
Hey @rupali-codes. A huge merge conflict happened. Did `git rebase`, a force push happened, so I had to do a redo. Trying to add the border to the breadcrumbs file but this happened:
## border 
![border](https://github.com/rupali-codes/LinksHub/assets/105683440/5e4b0d13-9a4d-471e-ac25-7fd459e83c61)
## No border
![no border](https://github.com/rupali-codes/LinksHub/assets/105683440/f6599535-a000-41fb-a22b-d41aaa9fee2d)

2024-02-21 09:44 UTC, rupali-codes commented
> Hey @rupali-codes. A huge merge conflict happened. Did `git rebase`, a force push happened, so I had to do a redo. Trying to add the border to the breadcrumbs file but this happened:
> 
> ## border
> ![border](https://private-user-images.githubusercontent.com/105683440/306501107-5e4b0d13-9a4d-471e-ac25-7fd459e83c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDg5MzIsIm5iZiI6MTcwODUwODYzMiwicGF0aCI6Ii8xMDU2ODM0NDAvMzA2NTAxMTA3LTVlNGIwZDEzLTlhNGQtNDcxZS1hYzI1LTdmZDQ1OWU4M2M2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwOTQzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmNkNjg5NTQxNGNlNDk3OGI5MjBiMGRlZDE0MzlhNGViMTdiNjdiMjg0YjNjMWRhMTViMzY3YmY3ZjkzYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f7J80xLiav5r-uI7LBouER6hOWiOCbbrI8n4cm73Wj8)
> 
> ## No border
> ![no border](https://private-user-images.githubusercontent.com/105683440/306501310-f6599535-a000-41fb-a22b-d41aaa9fee2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDg5MzIsIm5iZiI6MTcwODUwODYzMiwicGF0aCI6Ii8xMDU2ODM0NDAvMzA2NTAxMzEwLWY2NTk5NTM1LWEwMDAtNDFmYi1hMjJiLWQ0MWFhYTlmZWUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwOTQzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWIzOWJlOWEyZThlMWU2MTQ2YjliZjRjMmFmNjA1NDkzYTlmMmY0YjVhMDQ3MmVhYmJmMDFjMjE4YjBkNDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1amDaAxOrv5GYBdVrzzvyXdKYYG4XaYGYYY16FFXN48)

i think it looks fine with no border

2024-02-23 09:16 UTC, rupali-codes commented
@CBID2 why is it showing like this 😅

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/6ae88739-b526-4601-a42d-50416a897168)

2024-02-23 13:43 UTC, CBID2 commented
> @CBID2 why is it showing like this 😅
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/6ae88739-b526-4601-a42d-50416a897168)
> 
> 

Made an error lol

2024-02-26 16:31 UTC, CBID2 commented
> @CBID2, let me know if you need any help with this?

Thanks @aftabrehan. I can't remove the larger border in the card list: https://github.com/rupali-codes/LinksHub/pull/2256#issuecomment-1961351849

2024-02-26 16:34 UTC, aftabrehan commented
> > @CBID2, let me know if you need any help with this?
> 
> Thanks @aftabrehan. I can't remove the larger border in the card list: [#2256 (comment)](https://github.com/rupali-codes/LinksHub/pull/2256#issuecomment-1961351849)

Let me have a look.

2024-02-26 16:46 UTC, aftabrehan commented on components/Cards/CardsList.tsx
> +      <ul className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 justify-items-stretch border-dark-silver border-2 border-opacity-75 shadow-lg shadow-silver">
@CBID2, here is the fix.

```suggestion
      <ul className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 justify-items-stretch">
```

2024-02-26 16:47 UTC, aftabrehan commented
@CBID2, please make sure to pull the latest changes before making any adjustments.

2024-02-26 16:49 UTC, aftabrehan commented
@rupali-codes, can you help deploy the changes?

2024-03-03 04:53 UTC, CBID2 commented
Hey @rupali-codes. I finished everything. Can you authorize the deployment so you, @Anmol-Baranwal, and @aftabrehan can review the latest changes?

2024-03-03 06:48 UTC, aftabrehan requested changes

2024-03-03 06:48 UTC, aftabrehan commented on components/Cards/Card.tsx
> +      <div className="card-body border-light-silver border-2 border-opacity-75">
@CBID2, I think we should add the border on the card parent wrapper.

```suggestion
    <article className="z-10 h-full w-full rounded-3xl dark:bg-slate-800 dark:text-text-primary dark:shadow-sm bg-light-white border-light-silver border-2 border-opacity-75">
      <div className="card-body">
````

<img width="1217" alt="Screenshot 2024-03-03 at 11 44 10 AM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/0d186b88-bbce-4cd9-b19f-e5739cea57b8">

2024-03-03 06:48 UTC, aftabrehan commented on components/Searchbar/Searchbar.tsx
> +        <div className="relative w-full h-12 flex items-center justify-between border-light-silver border-2 border-opacity-75">
@CBID2, Please, remove the border from here and add on the input element.

2024-03-03 06:58 UTC, CBID2 commented
Made the changes @aftabrehan

2024-03-03 07:14 UTC, aftabrehan approved these changes

2024-03-03 12:15 UTC, rupali-codes reviewed
This issue isn't getting fixed, been long ha,
when you try to fix it for light theme it gets weird for dark theme

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/b777c161-51c4-4019-8626-2037fe18bf47)

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/d651b3e4-7f40-42dd-8c4a-dc640531eb7a)

@CBID2 please let me know if you need any help, wanna close this ASAP

2024-03-03 12:16 UTC, CBID2 commented
> This issue isn't getting fixed, been long ha,
> 
> when you try to fix it for light theme it gets weird for dark theme
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/b777c161-51c4-4019-8626-2037fe18bf47)
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/d651b3e4-7f40-42dd-8c4a-dc640531eb7a)
> 
> 
> 
> @CBID2 please let me know if you need any help, wanna close this ASAP

Ok can you help @rupali-codes

2024-03-03 12:17 UTC, rupali-codes commented
@CBID2 yes of course, where are you getting troubles?

2024-03-03 12:19 UTC, CBID2 commented
I'm not sure how to make it less weird looking in light mode @rupali-codes. From the photos you posted, it looks fine.

2024-03-03 17:54 UTC, CBID2 commented
What do you think @Anmol-Baranwal?

2024-03-04 11:36 UTC, Anmol-Baranwal commented
> What do you think @Anmol-Baranwal?

I've no problem if others are okay with it.

2024-03-07 09:05 UTC, rupali-codes commented
> @rupali-codes, I really think we should merge this.

Can you remove the border for dark theme and keep it only for light theme?

2024-03-07 12:22 UTC, CBID2 commented
> > @rupali-codes, I really think we should merge this.
> 
> 
> 
> Can you remove the border for dark theme and keep it only for light theme?

Ok

2024-03-15 18:49 UTC, CBID2 commented
Hey @rupali-codes. Can you do another deployment? I made the changes to light theme but I can't see them locally.

2024-03-24 18:31 UTC, CBID2 commented
@rupali-codes, can you deploy this please?

2024-04-12 12:02 UTC, Anmol-Baranwal commented
@CBID2 
Should I create a new PR for this? It's urgent because the current live light theme (live) is far from good.

2024-04-12 15:40 UTC, CBID2 commented
> @CBID2 
> 
> Should I create a new PR for this? It's urgent because the current live light theme (live) is far from good.

Ok @Anmol-Baranwal

2024-04-12 15:41 UTC, closed without merging