Add CSS games subcategory under Frontend category.
rupali-codes/LinksHub pull request #2264
Opened 2024-02-12 15:46 UTC by JuanPabloDiaz

## Fixes Issue

Closes #2258: Add CSS Games subcategory under Frontend

## Changes proposed

- Create a new subcategory called **CSS Games** under the frontend _category_.
- Modify the `CategoryDescriptions.ts` file to include CSS Games.
- Create a new file called `css-games.json` in the frontend database folder to include all the URLs related to CSS Games.
- Modify the `sitemap.xml` file to include CSS Games.
- Modify the `index.ts` file in the database folder to include CSS Games.
- Modify the `data.ts` file in the database folder to include CSS Games.

### Learn CSS Grid, Flex and more by **Playing Games**

- [css grid garden](https://cssgridgarden.com/)
- [flex box froggy](https://flexboxfroggy.com/)
- [flukeout](https://flukeout.github.io/)
- [coding fantasy](https://codingfantasy.com/)

## Screenshots

![cssGames](https://github.com/rupali-codes/LinksHub/assets/25883220/a103b59a-a193-467d-ada1-7b19ebcedd29)

## Note to reviewers

2024-02-12 15:57 UTC, CBID2 requested changes
Hi @JuanPabloDiaz. Your Pull Request is off to a great start. I'm thinking it'd be best to call the subcategory games instead of separating them by language. It creates more cohesiveness.

2024-02-12 15:57 UTC, CBID2 commented on components/TopBar/CategoryDescriptions.ts
> +    'CSS games are a fun way to learn and practice CSS. They are a great way to learn new CSS properties and techniques, and they can help you improve your skills in a fun and interactive way.',
```suggestion
    'Games are a fun way to learn and practice your FrontEnd development skills. They can help you learn new properties, techniques, and expand your coding knowledge.',
```

2024-02-12 15:57 UTC, CBID2 commented on database/data.ts
> +      { name: 'css games', url: '/css-games', resources: DB.cssGames },
```suggestion
      { name: 'games', url: '/games', resources: DB.games },
```

2024-02-12 15:57 UTC, CBID2 commented on database/frontend/css-games.json
> +    "subcategory": "css-games"
```suggestion
    "subcategory": "games"
```

2024-02-12 15:57 UTC, CBID2 commented on database/frontend/css-games.json
> +    "subcategory": "css-games"
```suggestion
    "subcategory": "games"
```

2024-02-12 15:57 UTC, CBID2 commented on database/frontend/css-games.json
> +    "subcategory": "css-games"
```suggestion
    "subcategory": "games"
```

2024-02-12 15:57 UTC, CBID2 commented on database/index.ts
> +export { default as cssGames } from './frontend/css-games.json'
```suggestion
export { default as games } from './frontend/games.json'
```

2024-02-12 15:57 UTC, CBID2 commented on public/sitemap.xml
> +        <loc>https://www.linkshub.dev/css-games</loc>
```suggestion
        <loc>https://www.linkshub.dev/games</loc>
```

2024-02-12 16:07 UTC, rupali-codes reviewed
@CBID2 why have you renamed to `games`? won't this be confusing for other people?

2024-02-12 17:47 UTC, Anmol-Baranwal commented
> @CBID2 why have you renamed to `games`? won't this be confusing for other people?

@rupali-codes Please deploy.

I second this, it can be `games` too but considering it is in frontend -> `css games` would be better because most of the game platforms are related to CSS.

2024-02-12 17:48 UTC, CBID2 commented
> > @CBID2 why have you renamed to `games`? won't this be confusing for other people?
> 
> 
> 
> @rupali-codes Please deploy.
> 
> 
> 
> I second this, it can be `games` too but considering it is in frontend -> `css games` would be better because most of the game platforms are related to CSS.

Oh I see.

2024-02-12 17:50 UTC, CBID2 commented
@rupali-codes & @Anmol-Baranwal, I approved the PR.

2024-02-12 20:51 UTC, JuanPabloDiaz commented
NP, thank you!

2024-02-13 07:31 UTC, aftabrehan approved these changes
Excellent PR, @JuanPabloDiaz 👍

2024-02-14 09:22 UTC, rupali-codes approved these changes
lgtm

2024-02-14 09:22 UTC, merged