naukri-link-added
rupali-codes/LinksHub pull request #2280
Opened 2024-02-25 16:42 UTC by parma1111

## Fixes Issue

 Closes #2271 

## Changes proposed

It's a platform that helps you get the job and place the job

## Screenshots

n/a

## Note to reviewers

2024-02-29 06:07 UTC, CBID2 requested changes
Hi @parma1111. Your PR is off to a good start. The description of your chosen resource could use some work, so I provided some advice on how to improve it. :)

2024-02-29 06:07 UTC, CBID2 commented on database/placement_prep/job-portals.json
> +    "description": "It's a platform that helps you get the job and place the job.",
[proofreading]: there was a part of the description that was unclear. Consider describing the source in the suggestion below
```suggestion
    "description": "It's a platform that helps you find and get the job.",
```

2024-02-29 06:28 UTC, parma1111 commented
> Hi @parma1111. Your PR is off to a good start. The description of your chosen resource could use some work, so I provided some advice on how to improve it. :)

> Now review the PR @CBID2

2024-02-29 06:29 UTC, CBID2 approved these changes
Looks good to me! :) You're turn @Anmol-Baranwal

2024-02-29 08:17 UTC, Anmol-Baranwal commented
@rupali-codes 
Deployment!

2024-03-02 07:08 UTC, rupali-codes approved these changes
lgtm

2024-03-03 06:53 UTC, aftabrehan reviewed
I can't access this website.

<img width="550" alt="Screenshot 2024-03-03 at 11 52 07 AM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/03237923-9548-4ee7-bea0-d41d2c13d81c">

2024-03-03 07:07 UTC, CBID2 commented
> I can't access this website.
> 
> 
> 
> <img width="550" alt="Screenshot 2024-03-03 at 11 52 07 AM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/03237923-9548-4ee7-bea0-d41d2c13d81c">
> 
> 

It works for me @aftabrehan 
![screenshot of naurki.com](https://github.com/rupali-codes/LinksHub/assets/105683440/cc56c565-a8c4-4d95-8164-24657a2a2f4a)

2024-03-03 07:09 UTC, aftabrehan commented
I guess it's an issue from my side. Feel free to merge it then.

2024-03-03 07:09 UTC, aftabrehan approved these changes

2024-03-03 07:15 UTC, CBID2 commented
@rupali-codes, we got a merge issue here

2024-03-03 12:09 UTC, rupali-codes commented
> @rupali-codes, we got a merge issue here

what's it

2024-03-03 12:21 UTC, CBID2 commented
> > @rupali-codes, we got a merge issue here
> 
> 
> 
> what's it

For some odd reason, we can't merge this Pull Request despite approving it.

2024-03-03 12:28 UTC, rupali-codes commented
> > > @rupali-codes, we got a merge issue here
> > 
> > 
> > what's it
> 
> For some odd reason, we can't merge this Pull Request despite approving it.

what is it showing? screenshot please

2024-03-05 07:16 UTC, rupali-codes commented
> > > > > @rupali-codes, we got a merge issue here
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > what's it
> > 
> > 
> > > 
> > 
> > 
> > > For some odd reason, we can't merge this Pull Request despite approving it.
> > 
> > 
> > what is it showing? screenshot please
> 
> ![image](https://private-user-images.githubusercontent.com/105683440/309551955-7cf62baa-1210-4183-ba76-09dd6167ec93.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjMyMjUsIm5iZiI6MTcwOTYyMjkyNSwicGF0aCI6Ii8xMDU2ODM0NDAvMzA5NTUxOTU1LTdjZjYyYmFhLTEyMTAtNDE4My1iYTc2LTA5ZGQ2MTY3ZWM5My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDcxNTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY1MmVjZGMwMzA2MmYyNmE4YTUxOTQ0ZmYyYzU0NjEyNzkyMDg3MmE3YzM3MmVjNWQ2ODVkNWYyNGQ4MDhlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cz8CmbuNgwoNQaCWAW50MpfGj-TKQiHk8UTjDV-8ek0)

Well, i don't know why is it showing this, but let me merge it for now

2024-03-05 07:17 UTC, merged