Add Float UI #2268
rupali-codes/LinksHub pull request #2282
Opened 2024-02-29 15:03 UTC by JuanPabloDiaz

## Fixes Issue

#2268

## Changes proposed

- Add Float UI 

- Fix subcategory for Material Tailwind

## Screenshots

## Note to reviewers

2024-03-10 04:02 UTC, CBID2 commented on database/frontend/ui-libraries.json
> +    "description": "Move faster with beautiful, responsive UI components and website templates with modern design, 100% free and open-source.",
```suggestion
    "description": "Move faster with beautiful, responsive UI components and website templates with modern design that are 100% free and open-source.",
```

2024-03-10 04:04 UTC, CBID2 requested changes
Hi @JuanPabloDiaz! :) You’re pull request looks great. I found a typo that needs fixing, so you just need to work on that.

2024-03-10 08:03 UTC, JuanPabloDiaz commented on database/frontend/ui-libraries.json
> +    "description": "Move faster with beautiful, responsive UI components and website templates with modern design, 100% free and open-source.",
I fixed it

2024-03-15 14:32 UTC, rupali-codes approved these changes
lgtm

2024-03-15 14:32 UTC, merged