ADD email in CODE_OF_CONDUCT.md
rupali-codes/LinksHub pull request #2332
Opened 2024-03-29 11:06 UTC by JuanPabloDiaz

## Fixes Issue

fixes #2325

## Changes proposed

The Code of conduct now has @rupali-codes email: [rupali.codes@gmail.com](http://rupali.codes@gmail.com/)

## Screenshots

## Note to reviewers

2024-03-29 11:54 UTC, CBID2 approved these changes
LGTM. @rupali-codes or @aftabrehan, it's your turn

2024-04-01 16:38 UTC, aftabrehan approved these changes

2024-04-03 12:03 UTC, rupali-codes reviewed
can you please replace the email with `linkshub.opensource@gmail.com`

2024-04-04 12:55 UTC, CBID2 requested changes
Hi @JuanPabloDiaz. It turns out the email you put is incorrect. Please fix and tag me and @rupali-codes for another review

2024-04-04 12:55 UTC, CBID2 commented on CODE_OF_CONDUCT.md
> +rupali.codes@gmail.com.
[typo]: this the correct email 
```suggestion
linkshub.opensource@gmail.com.
```

2024-04-04 23:05 UTC, CBID2 approved these changes
Looks good @JuanPabloDiaz! :) In the future, click on the “Commit” button when you see an embedded suggestion in your pull requests.

2024-04-06 13:47 UTC, merged