feat: add Abbreve project link to open_source/projects.json
rupali-codes/LinksHub pull request #2503
Opened 2024-09-24 15:58 UTC by sahajj11

## Fixes Issue
Closes #2502 

## Changes proposed
-Added  Abbreve open source project link to open_source/projects.json.

-Abbreve is an open-source dictionary for slang. With Abbreve, you'll never have to feel left out of a conversation or unsure of the meaning of an abbreviation again.

## Screenshots
![linkhub](https://github.com/user-attachments/assets/c58eddae-1007-4c24-b9ab-39796da6b179)

## Note to reviewers
- No major changes to functionality, only data addition.

2024-09-25 04:41 UTC, Jay-Karia commented on package.json
No need to change the versions of deps

2024-09-25 06:25 UTC, sahajj11 commented on package.json
Hi, it looks like package.json was flagged by the automated compliance checks, but I can confirm that no changes were made to this file in this PR.

2024-09-26 20:21 UTC, Jay-Karia requested changes

2024-09-26 20:21 UTC, Jay-Karia commented on package.json
It's the same issue here.

2024-09-26 20:21 UTC, Jay-Karia commented on pnpm-lock.yaml
And here

2024-09-30 07:05 UTC, rupali-codes approved these changes
lgtm

2024-09-30 07:06 UTC, merged