Linkadded
rupali-codes/LinksHub pull request #277
Opened 2023-02-27 07:00 UTC by parma1111

## Fixes Issue

fixes issue #264

## Changes proposed

add-sub-category css

## Screenshots

![Screenshot (741)](https://user-images.githubusercontent.com/101566294/221495053-eb2fea1a-2793-46b1-a54c-5a7f77f3185e.png)

## Note to reviewers
now I have fix the issue you can review the PR.

2023-02-27 18:22 UTC, rupali-codes requested changes
Hi, thanks for rising the PR. could you please add this category in YouTube section?

2023-02-27 19:34 UTC, CBID2 commented on database/frontend/css.json
> +        "language": "english"
Add a comma after "english".

2023-02-28 06:26 UTC, rupali-codes commented on database/frontend/css.json
> +        "language": "english"
No, it will cause errors

2023-02-28 06:28 UTC, CBID2 approved these changes
LGTM! 👍🏾

2023-02-28 06:36 UTC, parma1111 commented on database/frontend/css.json
> +        "language": "english"
Ok I will change

2023-02-28 07:17 UTC, parma1111 commented
now I updated in youtube css category
![Screenshot (742)](https://user-images.githubusercontent.com/101566294/221781489-8a68064c-4e71-4219-b653-f87c82a5df50.png)

2023-02-28 19:37 UTC, rupali-codes approved these changes
thanks for the changes, lgtm

2023-02-28 19:38 UTC, merged