Bug fix
rupali-codes/LinksHub pull request #305
Opened 2023-03-04 16:47 UTC by ujjawaltyagii

## Fixes Issue
- fixed overflow of homepage when there is : less content and no content
- made footer go scroll at end if there is more scrollable content
- responsiveness : adjusted media queries for footer to make it look good on small screens as well
- changed bg-blur of footer so on scrolling it wont show scrolling content going down (In Dark theme )

Closes #255 

## Screenshots

![image](https://user-images.githubusercontent.com/115401171/222918125-452afa2f-df2b-49a5-a105-45691f2c36c3.png)

![image](https://user-images.githubusercontent.com/115401171/222918095-c4e51012-ce43-4ea3-89dd-aa9ef04ff975.png)

![image](https://user-images.githubusercontent.com/115401171/222918146-6bbe03cb-cd11-4a4e-b70a-4b52eab6f2e9.png)

2023-03-04 16:53 UTC, ujjawaltyagii commented
@rupali-codes

2023-03-04 18:37 UTC, rupali-codes commented
It's still overflowing when there's even less content. could you fix that? 

![image](https://user-images.githubusercontent.com/78981177/222923094-c7e13875-1acd-4946-9a33-f120de88fcf0.png)

2023-03-05 09:31 UTC, ujjawaltyagii commented
@rupali-codes oh ! On other pages issue was resolved so I missed to check on homepage...my bad. I made the necessary changes and I guess the issue is resolved now.

2023-03-05 10:22 UTC, ujjawaltyagii commented
Updated PR !

2023-03-05 13:34 UTC, rupali-codes commented
thanks for the changes. but still overflowing other components

![image](https://user-images.githubusercontent.com/78981177/222963632-a488b55c-3842-4c2c-989b-3294036a8139.png)

2023-03-05 16:11 UTC, ujjawaltyagii commented
@rupali-codes any idea why it's happening ???  Because on my system (in chrome and opera) it's working fine
 
adding pic :

![image](https://user-images.githubusercontent.com/115401171/222972040-931403e4-d656-404b-a87b-4bb56af27ef6.png)

2023-03-05 17:26 UTC, rupali-codes commented
@ujjawaltyagii i'm having in both chrome and brave.

2023-03-16 05:38 UTC, rupali-codes commented
hey @ujjawaltyagii could you please resolve conflicts?

2023-04-01 02:44 UTC, CBID2 commented on components/Footer/Footer.tsx
> +    <div className="bottom-4 dark:bg-[#101623] bg-gray-100 transition-all ease-in duration-300 w-full flex items-baseline justify-center z-10 gap-1 rounded-lg bg-[#ffffff0a] backdrop-blur-md sm:py-3
```suggestion
    <article className="bottom-4 dark:bg-[#101623] bg-gray-100 transition-all ease-in duration-300 w-full flex items-baseline justify-center z-10 gap-1 rounded-lg bg-[#ffffff0a] backdrop-blur-md sm:py-3 py-2 px-1 md:mt-[1.9rem]">
```

2023-04-01 02:59 UTC, CBID2 commented on layouts/GeneralLayout.tsx
> +      <div className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```suggestion
      <article className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```

2023-04-01 02:59 UTC, CBID2 commented on layouts/GeneralLayout.tsx
>        </div>
```suggestion
      </article>
```

2023-04-01 03:00 UTC, CBID2 commented on pages/index.tsx
>              <div className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```suggestion
        <article className=" m-auto flex flex-col  items-start gap-2">
            <div className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```

2023-04-01 03:00 UTC, CBID2 commented on components/cards/index.tsx
>      <div
```suggestion
    <article 
```

2023-04-01 03:03 UTC, CBID2 commented on layouts/GeneralLayout.tsx
> +      <div className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```suggestion
      <article className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```

2023-04-01 03:04 UTC, CBID2 commented on layouts/GeneralLayout.tsx
>        </div>
```suggestion
      </article>
```

2023-04-01 03:04 UTC, CBID2 commented on pages/index.tsx
>              <div className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```suggestion
        <article className=" m-auto flex flex-col  items-start gap-2">
            <article className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```

2023-04-01 03:04 UTC, CBID2 commented on pages/index.tsx
>              <div className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```suggestion
        <article className=" m-auto flex flex-col  items-start gap-2">
            <article className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```

2023-04-01 03:05 UTC, CBID2 commented on components/Footer/Footer.tsx
> +    <div className="bottom-4 dark:bg-[#101623] bg-gray-100 transition-all ease-in duration-300 w-full flex items-baseline justify-center z-10 gap-1 rounded-lg bg-[#ffffff0a] backdrop-blur-md sm:py-3
```suggestion
    <article className="bottom-4 dark:bg-[#101623] bg-gray-100 transition-all ease-in duration-300 w-full flex items-baseline justify-center z-10 gap-1 rounded-lg bg-[#ffffff0a] backdrop-blur-md sm:py-3 py-2 px-1 md:mt-[1.9rem]">
```

2023-04-01 03:05 UTC, CBID2 commented on components/cards/index.tsx
>      <div
```suggestion
    <article
```

2023-04-01 03:06 UTC, CBID2 commented on layouts/GeneralLayout.tsx
> +      <div className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```suggestion
      <article className="mx-auto mt-[4rem] min-h-[calc(100vh-85px)] bg-gray-100 px-4 pb-[1rem] transition-all duration-300 ease-in dark:bg-[#101623] lg:mt-0 lg:pl-[290px]">
```

2023-04-01 03:06 UTC, CBID2 commented on layouts/GeneralLayout.tsx
>        </div>
```suggestion
      </article>
```

2023-04-01 03:06 UTC, CBID2 commented on pages/index.tsx
>              <div className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```suggestion
        <article className=" m-auto flex flex-col  items-start gap-2">
            <article className="m-auto md:text-7xl text-5xl gap-2 flex items-center justify-center">
```

2023-04-01 03:09 UTC, CBID2 requested changes
Hi @ujjawaltyagii! 😄 I made some suggestions on how to improve your pull request. In the future, I highly recommend using more semantic HTML elements instead of `<div>`. They'll make your code more accessible. Other than that, great work! 😄 👍🏾

2023-04-01 07:12 UTC, rupali-codes commented
This PR have conflicts that must be resolved :)

2023-04-16 06:57 UTC, rupali-codes commented
@ujjawaltyagii Are you still working on this?

2023-05-21 18:18 UTC, rupali-codes commented
@ujjawaltyagii are you still working on it?

2023-05-21 19:15 UTC, ujjawaltyagii commented
@rupali-codes sorry for being inactive on this PR, actually i was expecting someone to review the responsiveness as earlier things were working fine on my side but there were some issues of overflowing on your side. But as far as I remember this issue has already been resolved in a different PR because I actually reviewed the code of that PR. 
So, mind if I close this PR now ? because I don't think we need these changes anymore (correct me if I'm wrong)

2023-05-21 19:17 UTC, closed without merging