Add design inspirations
rupali-codes/LinksHub pull request #307
Opened 2023-03-05 14:31 UTC by Oyebolade

## Fixes Issue

Closes #242 

## Changes proposed
I added SaaS Interface to Design inspiration category under frontend category

## Screenshots
![Saasinterface added](https://user-images.githubusercontent.com/57053389/222966648-869d2eb0-c3ab-488f-a900-1b1b57864adb.PNG)

## Note to reviewers

2023-03-05 17:20 UTC, rupali-codes commented
Conflicts. Could you please just stage the files u have made changes in?

2023-03-05 17:22 UTC, Oyebolade commented
How will I stage in the files?

2023-03-05 17:24 UTC, Oyebolade commented
I  used "git add database/frontend/design-inspirations.json'

2023-03-05 17:36 UTC, rupali-codes commented
> I used "git add database/frontend/design-inspirations.json'

yeah, that's the way, but it added all the files, now it's causing conflicts

2023-03-06 00:09 UTC, Oyebolade commented
Do you have any suggestions about it?

2023-03-06 04:58 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +    "description": "Get inspired and keep up with the latest landing page design trends.",
Great start @Oyebolade! However, I am curious about what makes Page Collective distinctive and more beneficial than the other sites you mentioned. Consider adding this to your description.

2023-03-06 04:59 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +    "description": "Landingfolio features the best landing page designs, templates, component and more on teh web.",
Fix the spelling error (e.g., "teh").

2023-03-06 05:00 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +    "description": "Find the best hand-picked website design inspiration.",
This could use a bit more detail. What makes Land-book distinctive from websites like Carrd or Behance?

2023-03-06 05:02 UTC, CBID2 commented on database/frontend/images.json
> +    "description": "it allows to search pictures by color, and  it provides a complementary palette of colors in the photo.",
Capitalize the first "It"

2023-03-06 05:04 UTC, CBID2 requested changes
Hi @Oyebolade! 😄 I left you some feedback in your commits. I hope they help you! 😄

2023-03-06 05:04 UTC, CBID2 commented on database/frontend/animations.json
> +    "description": "LottieFiles takes away the complexity from Motion Design. It lets you Create, Edit, Test, Collaborate and Ship a Lottie in the easiest way possible.",
Lowercase the words that don't begin the second sentence.

2023-03-06 16:35 UTC, Oyebolade commented
All right,
Thanks, I will make the changes

2023-03-06 16:51 UTC, rupali-codes commented
This PR have a so much conflicts to be resolved. @Oyebolade i dont know how are u staging (adding) files. You should just add the files you are making changes in. Are you using `git add .`?

2023-03-07 04:28 UTC, CBID2 commented
> I only added changed file
> Is there anything we can do about it?

The formatting of the JSON could be improved

2023-03-07 06:29 UTC, rupali-codes commented
it's the space formats again. Here is what u can do
* close this PR
* create a new branch in your local repo
* make your changes
* add just those modified files
* commit your changes
* push your changes to the new branch.

hope it helps

2023-04-20 16:27 UTC, closed without merging