Master
rupali-codes/LinksHub pull request #329
Opened 2023-03-08 18:43 UTC by darkweb907

Added spline design tools for interactive 3D experiences or animations

2023-03-08 23:41 UTC, CBID2 commented on database/frontend/themes-templates.json
> +        "description": "fully responsive UI Kits, Templates and Dashboards built on top of Bootstrap, React",
```suggestion
        "description": "Fully responsive UI kits, templates, and dashboards that are built on top of Bootstrap and React",
```

2023-03-08 23:43 UTC, CBID2 commented on database/youtube/android.json
> +    "description": "This channel provides free programming languages for Android  development and more.",
```suggestion
    "description": "This channel provides free programming courses on Android development and more.",
```

2023-03-08 23:45 UTC, CBID2 commented on database/youtube/web-development.json
> +        "description": "This channel will provide and take you from zero to a fullstack developer.you will learn UI/UX, Frontend Dev",
```suggestion
        "description": "This channel will take you from zero to a fullstack developer. You will also learn UI/UX and Frontend Dev languages",
```

2023-03-08 23:46 UTC, CBID2 commented on database/youtube/web-development.json
> +        "description": "This channel is dedicated on providing free education on coding tutorial for both beginners and pro",
```suggestion
        "description": "This channel is dedicated to providing free coding tutorials for both beginners and pros",
```

2023-03-08 23:47 UTC, CBID2 requested changes
Hey @darkweb907! I just added some suggestions to improve your PR! 😄 I hope you find them helpful! 👍🏾

2023-03-09 00:07 UTC, CBID2 approved these changes
Looks great! :) LGTM

2023-03-09 05:22 UTC, rupali-codes commented
Thank you chrissy. 
@darkweb907 could you please resolve conflicts

2023-03-09 17:31 UTC, merged