Fix typos and add design inspirations links
rupali-codes/LinksHub pull request #330
Opened 2023-03-09 04:40 UTC by Oyebolade

## Fixes Issue

Closes #242 

## Changes proposed

## Screenshots
![Animation typos](https://user-images.githubusercontent.com/57053389/223915312-3c3200cd-2f86-439a-af23-76f4a15c06db.PNG)
![Fix-typos](https://user-images.githubusercontent.com/57053389/223915318-fb3a3d28-5602-4d8b-8299-e56cdcf57c17.PNG)
![Image typos](https://user-images.githubusercontent.com/57053389/223915322-b013d193-98b9-4211-8eaf-c1b23bc4d631.PNG)

## Note to reviewers
Hi reviewers,
1. I added SaaS interface link to design inspirations.
2. Made a distinctive description to page collective link.
3. Fixes spelling error i.e Landingfolio link.
4. I also gave more details about land-book link.
5. Capitalize the first "it" in Kaboompics link under image subcategories.
6.

2023-03-09 04:44 UTC, Oyebolade commented
I've created another branch
There is still conflict

2023-03-16 18:20 UTC, ujjawaltyagii reviewed
I would recommend resolving merge conflict first and one more thing, on deploying I can see that card's property of scaling on hover and on click property of cards isn't working ! so could you review your code 

![image](https://user-images.githubusercontent.com/115401171/225716179-eb41d18f-7315-4e06-bd1c-ace587e80e21.png)

(both mouse pointer on hover and card scaling on hover isn't working properly)

2023-03-17 05:21 UTC, rupali-codes commented
Yeah, this branch is not updated with main branch

2023-03-17 07:23 UTC, Oyebolade commented
Yes, I'm supposed to have a section with Rupali on it. I don't know how to go about the conflicts

2023-03-30 01:41 UTC, CBID2 commented on database/frontend/animations.json
> +    "description": "A JavaScript particle based animation engine. Which provides you tones of animated elements.",
```suggestion
    "description": "A JavaScript particle-based animation engine that provides tons of animated elements.",
```

2023-03-30 01:44 UTC, CBID2 requested changes
Hi @Oyebolade! :) I made some suggestions to improve your descriptions! :) I hope you find them helpful! :) Keep up the good work! :)

2023-04-20 15:52 UTC, parma1111 commented
> Yeah, this branch is not updated with main branch

This PR is merged by #448 , now you may close it

2023-04-20 16:27 UTC, closed without merging