New Links Added for Icons
rupali-codes/LinksHub pull request #335
Opened 2023-03-09 17:45 UTC by Ajay84sia

New Links Added for Icons

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-03-09 18:38 UTC, rupali-codes commented
@Ajay84sia can we use these icons in other projects too not just react?

2023-03-09 18:40 UTC, Ajay84sia commented
Only for react projects

2023-03-10 04:28 UTC, CBID2 commented on database/frontend/icons.json
> +  "description": "Free, high quality, open source icon library for React Projects with over lots of icons.",
```suggestion
  "description": "Free, high quality, open source icon library for React Projects.",
```

2023-03-10 04:29 UTC, CBID2 requested changes
Hi @Ajay84sia! 😄 I made a suggestion for you. I hope you find it helpful! 😄 👍🏾

2023-03-10 04:38 UTC, Ajay84sia commented
Hi, @CBID2  I made the changes as you suggested 😄 👍🏾

2023-03-10 04:40 UTC, CBID2 approved these changes
LGTM! 👍🏾

2023-03-10 18:27 UTC, rupali-codes commented
> @rupali-codes Only for react projects

thanks

2023-03-10 18:28 UTC, merged