Master
rupali-codes/LinksHub pull request #340
Opened 2023-03-10 23:30 UTC by darkweb907

updating site error

2023-03-11 00:36 UTC, CBID2 approved these changes
LGTM! 👍🏾 😄

2023-03-11 18:28 UTC, rupali-codes reviewed
Hey, why have you removed the resources from design-inspiration.json?

2023-03-11 20:14 UTC, CBID2 requested changes
Hi @darkweb907! 😄 I provided a suggestion to improve the description. I hope you find it helpful! 😄

2023-05-25 06:37 UTC, CBID2 commented
Hi @darkweb907. Fix the branch conflicts please.

2023-05-25 07:09 UTC, rupali-codes requested changes
You have resolved conflicts incorrectly, please checkout the file carefully. Let' us know if you need any help

2023-05-28 06:16 UTC, rupali-codes commented
@darkweb907 are you still working on this?

2023-05-28 07:59 UTC, darkweb907 commented
> @darkweb907 are you still working on this?

Sorry will get back to it soon but currently writing exam now

2023-05-28 08:32 UTC, rupali-codes commented
> > @darkweb907 are you still working on this?
> 
> Sorry will get back to it soon but currently writing exam now

Okay, good luck!

2023-06-11 18:38 UTC, rupali-codes commented
@darkweb907 hey, are you done with your exams?

2023-06-11 19:25 UTC, darkweb907 commented
Yea

On Sun, Jun 11, 2023, 7:38 PM Rupali Haldiya ***@***.***>
wrote:

> @darkweb907 <https://github.com/darkweb907> hey, are you done with your
> exams?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rupali-codes/LinksHub/pull/340#issuecomment-1586277160>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASQZKQVLWTDQEBVRCADMKGTXKYGEDANCNFSM6AAAAAAVXBW5LY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-11 21:16 UTC, darkweb907 commented
Yes, I am!
Done check it

On Sun, Jun 11, 2023, 10:09 PM Christine Belzie ***@***.***>
wrote:

> Yea
>
> On Sun, Jun 11, 2023, 7:38 PM Rupali Haldiya *@*.***>
>
> wrote:
>
> @darkweb907 <https://github.com/darkweb907> https://github.com/darkweb907
> hey, are you done with your
>
> exams?
>
> —
>
> Reply to this email directly, view it on GitHub
>
> #340 (comment)
> <https://github.com/rupali-codes/LinksHub/pull/340#issuecomment-1586277160>
> ,
>
> or unsubscribe
>
>
> https://github.com/notifications/unsubscribe-auth/ASQZKQVLWTDQEBVRCADMKGTXKYGEDANCNFSM6AAAAAAVXBW5LY
>
> .
>
> You are receiving this because you were mentioned.Message ID:
>
> *@*.***>
>
> Are you still working on this @darkweb907 <https://github.com/darkweb907>?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rupali-codes/LinksHub/pull/340#issuecomment-1586337546>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASQZKQSWZDAMY53HDVTOPETXKYXZ3ANCNFSM6AAAAAAVXBW5LY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-11 21:16 UTC, darkweb907 commented
Check it now

2023-06-11 21:25 UTC, CBID2 submitted a review, later dismissed
LGTM! :)

2023-06-12 10:29 UTC, rupali-codes commented
@darkweb907 hey your vercel deployment is getting failed bcz of the following issue

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/c86106ff-10b8-4def-8794-8ead06390383)

2023-06-13 16:33 UTC, rupali-codes commented
@darkweb907 does that PR resolves any issue? if so, please reference that here

2023-06-13 16:35 UTC, rupali-codes requested changes

2023-06-13 16:35 UTC, rupali-codes commented on database/frontend/design-inspirations.json
> +
```suggestion
```

2023-06-13 16:35 UTC, rupali-codes commented on database/frontend/design-inspirations.json
> +
```suggestion
```

2023-06-13 16:35 UTC, rupali-codes commented on database/frontend/design-inspirations.json
> +        "name": "Dribble" ,
```suggestion
        "name": "Dribble",
```

2023-06-13 17:20 UTC, darkweb907 commented on database/frontend/design-inspirations.json
> +        "name": "Dribble" ,
Resolve

2023-06-13 23:50 UTC, CBID2 commented
@darkweb907, you have some merge conflicts that need to be resolved.

2023-06-18 01:41 UTC, closed without merging

2023-06-18 01:42 UTC, CBID2 commented
I closed this pull request since it's becoming stale. When you're ready to work on it again @darkweb907, let us know. 😄  👍🏾