testing.json file filled with data
rupali-codes/LinksHub pull request #342
Opened 2023-03-12 07:19 UTC by prabhattopi

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-03-12 07:20 UTC, prabhattopi commented
this is database file of backend of testing

2023-03-12 09:20 UTC, rupali-codes requested changes
Hey, thanks
Could please create a new subcategory and `json` file under `youtube` category, named `testing` and then add your resources in `database/youtube/testing.json`

Let us know for any kinda help.

2023-03-12 10:59 UTC, prabhattopi commented
ok sure

2023-03-12 12:36 UTC, rupali-codes reviewed
Thanks, i can not see it in the site. 
Now you will have to modify `data.ts` and `index.ts` files under `database` folder. Add this `testign` subcategory just like other components. Let's know for any kinda help :)

2023-03-12 14:42 UTC, prabhattopi commented
done
please review once

2023-03-12 18:33 UTC, rupali-codes commented on database/youtube/testing.json
> +        "description": "This channel is beginner friendly as well take you up to advanced level in automation with almost every everyframework",
```suggestion
        "description": "This channel is beginner friendly as well take you up to advanced level in automation with almost every framework",
```

2023-03-13 01:55 UTC, prabhattopi commented
please review once thanks if any help regarding the backend frontend or optimizing please give me a flow I will definitely do that on weekends thanks once again

2023-03-13 12:54 UTC, rupali-codes approved these changes
lgtm

2023-03-13 12:59 UTC, merged