GitHub section added
rupali-codes/LinksHub pull request #349
Opened 2023-03-15 16:39 UTC by ujjawaltyagii

## Changes proposed
- Added a new section named "Github" with sub-category "Readme" which contains resources regarding <b>creation of readme files for github projects</b>.
- Also, I plan to <b>add more sub-categories</b> with more resources to help people who are New to Github, with <b>various docs, cheatsheets and other useful tools</b>.

Closes : #267 

## Screenshots

![image](https://user-images.githubusercontent.com/115401171/224542487-d0839bba-bb79-46d7-86bd-0cf19e0032df.png)

![image](https://user-images.githubusercontent.com/115401171/224542397-b08b6770-37ba-4288-8796-b49a4ef4deeb.png)

![image](https://user-images.githubusercontent.com/115401171/224542416-2ccdc248-5f87-4682-8b8a-58bf125fd072.png)

## Changes
1. Created new file ``readme.json``
2. Made changes to ``>database>index.ts`` , ``>types>index.ts`` , ``data.ts``

2023-03-15 17:19 UTC, ujjawaltyagii commented
@rupali-codes fixed it ! Actually i accidently deleted folder on my system :) so I was setting up environment so that's why it happened.

2023-03-15 22:11 UTC, CBID2 commented on database/Other/Github.json
> +        "description": "It can generate readme.md and contribute.md file with pre-built template and suggestions.",
```suggestion
        "description": "It can generate readme. md and contribute.md files with pre-built templates and suggestions.",
```

2023-03-15 22:14 UTC, CBID2 requested changes
Hey @ujjawaltyagii! 😄 I just made a suggestion to help you improve one of the descriptions of your recommended sources.

2023-03-16 11:43 UTC, ujjawaltyagii commented
@CBID2 done !!

2023-03-16 14:37 UTC, rupali-codes approved these changes
lgtm

2023-03-17 14:22 UTC, ujjawaltyagii commented
@CBID2 I have made the necessary changes and Rupali has also approved form her side so just waiting for you review in order to be make PR-merge

2023-03-17 15:17 UTC, CBID2 approved these changes
LGTM! 😊👍🏾

2023-03-17 17:56 UTC, merged