Add favicon
rupali-codes/LinksHub pull request #364
Opened 2023-03-21 14:21 UTC by stupiddint

## Fixes Issue
I enhanced the website's visual appeal and user-friendliness by adding favicons to each website in the container. The small but important visual elements make it easier for users to quickly distinguish between different websites.

Closes #258  

## Changes proposed

1. added a favicon image property to each website object in the JSON file.
2. created a img tag to add icon in container and popup card.
## Screenshots
![Screenshot from 2023-03-21 19-05-47](https://user-images.githubusercontent.com/94122792/226632686-1476e82e-b3b3-4d5c-8199-954f549b21a7.png)
![image](https://user-images.githubusercontent.com/94122792/226633167-3a7762e6-25a4-49b3-848b-af89e93b286b.png)

## Note to reviewers
Thank you for helping me to solve this issue @priyankarpal and assigning me this @rupali-codes 
if you have any suggestions for further improving the visual appeal or user-friendliness of the website, please feel free to share them. Thank you for taking the time to review this change.

2023-03-21 15:51 UTC, rupali-codes commented
Hey, do we have to add it manually for each resource or link?

2023-03-21 16:18 UTC, stupiddint commented
yes, in the json file to image property

2023-03-21 16:43 UTC, ujjawaltyagii reviewed
There are merge conflicts in PR so it would be great if you resolve them, it looks pretty good though but I was wondering that whenever a user wants to add new resource so they have to choose a fevicon image too so i was thinking if we could make a standard fevicon image so if a user doesn't have any fevicon image related to resource so a default image will be added.                   What do you think about it ??

2023-03-22 02:34 UTC, stupiddint commented
the conflicts have been resolved and the changes are ready to be merged.
Are users allowed here to add new resource? if Yes, we might assign the image property a default URL,  Until something new is added.

2023-03-22 04:00 UTC, priyankarpal commented
> the conflicts have been resolved and the changes are ready to be merged. Are users allowed here to add new resource? if Yes, we might assign the image property a default URL, Until something new is added.

ok also share a demo

2023-03-22 04:12 UTC, stupiddint commented
[https://linkshub-7gfgwjo54-rupali-codes.vercel.app/animations](url)
![image](https://user-images.githubusercontent.com/94122792/226800101-c8aff0b5-4eeb-4a82-94d0-a9c0f7e9c2c3.png)
![image](https://user-images.githubusercontent.com/94122792/226800158-48b03bb3-1186-455d-9d72-8fa0254c5aa4.png)

2023-03-22 04:16 UTC, priyankarpal commented
Users can add links. We need to mention how users can add a favicon is there is no Favicon present then add the default LinksHub Favicon.

2023-03-22 04:24 UTC, priyankarpal requested changes
There are lots of changes needed.

2023-03-22 04:24 UTC, priyankarpal commented on database/Other/Github.json
> +    "image": "https://linkshub.vercel.app/icon.png"
Change to 

``` suggestion
    "image": "https://readme.so/icons/icon-96x96.png"
```

2023-03-22 04:24 UTC, priyankarpal commented on database/Other/Github.json
> +    "image": "https://linkshub.vercel.app/icon.png"
```suggestion
    "image": "https://www.makeareadme.com/images/favicon.ico"
```

2023-03-22 04:24 UTC, priyankarpal commented on database/Other/Github.json
> +    "image": "https://linkshub.vercel.app/icon.png"
```suggestion
    "image": "https://rahuldkjain.github.io/gh-profile-readme-generator/favicon-32x32.png"
```

2023-03-22 04:38 UTC, stupiddint commented
@priyankarpal  yes, I am searching and adding respective website favicon in my localhost, and after I'm done, I'll push it.
can you tell me  where  the option of adding links by user is?

2023-03-22 04:55 UTC, priyankarpal commented
> @priyankarpal yes, I am searching and adding respective website favicon in my localhost, and after I'm done, I'll push it. can you tell me where the option of adding links by user is?

I thought that we can fetch favicon like how we fetch github avatar. `https://github.com/your-github-username.png` but in this case favicons are different. So this would not work.

If there are any idea share

2023-03-22 04:56 UTC, priyankarpal commented
> > @priyankarpal yes, I am searching and adding respective website favicon in my localhost, and after I'm done, I'll push it. can you tell me where the option of adding links by user is?
> 
> I thought that we can fetch favicon like how we fetch github avatar. `https://github.com/your-github-username.png` but in this case favicons are different. So this would not work.
> 
> If there are any ideas please share

2023-03-22 05:51 UTC, rupali-codes commented
> > @priyankarpal yes, I am searching and adding respective website favicon in my localhost, and after I'm done, I'll push it. can you tell me where the option of adding links by user is?
> 
> I thought that we can fetch favicon like how we fetch github avatar. `https://github.com/your-github-username.png` but in this case favicons are different. So this would not work.
> 
> If there are any ideas please share

I guess it would be confusing for beginners to add resources, and same link might not work everytime, like there would be different path for favicon in respective sites

2023-03-22 14:35 UTC, stupiddint commented
yes it happens in some sites like Cubic Bezier, it was difficult to find favicon.
There is an extension in chrome 'get favicon' that displays current websites favicon's url and dimensions.

2023-03-22 14:36 UTC, priyankarpal commented
> yes it happens in some sites like Cubic Bezier, it was difficult to find favicon. There is an extension in chrome 'get favicon' that displays current websites favicon's url and dimensions.

ok ok

2023-03-22 16:04 UTC, rupali-codes commented
Can u resolve this error? 

![image](https://user-images.githubusercontent.com/78981177/226966289-acfc6a61-14e7-482c-b4b9-bec7dd2ed8a2.png)

2023-03-22 16:29 UTC, stupiddint commented
this error is appearing because I think the image property in json file is empty.

2023-03-22 17:45 UTC, rupali-codes commented
> this error is appearing because I think the image property in json file is empty.

Oh, how can we resolve this then?

2023-03-23 04:12 UTC, stupiddint commented
We must create at least an empty image property because we have no backend and are writing the json file ourself. 
We must list every key in every json file since we are using the map method to display every json file.

2023-03-23 04:14 UTC, stupiddint commented
can someone help me to push the changes
![image](https://user-images.githubusercontent.com/94122792/227101380-bf7235bf-f06b-4684-8112-14a8958d7b48.png)

2023-03-23 06:02 UTC, rupali-codes commented
@stupiddint run this
git pull origin main

2023-03-23 13:55 UTC, stupiddint commented
appearing this error
I will start pushing in different branch, leave it.
![image](https://user-images.githubusercontent.com/94122792/227225769-a7fffcb3-7b4d-4264-8a6c-117e00983525.png)

2023-03-24 09:11 UTC, priyankarpal commented
@stupiddint  This branch has some conflict errors. Please resolve it.

2023-03-24 09:12 UTC, priyankarpal commented
> > appearing this error I will start pushing in different branch, leave it. ![image](https://user-images.githubusercontent.com/94122792/227225769-a7fffcb3-7b4d-4264-8a6c-117e00983525.png)
> You have to rebase the branch
> yes. paste `git config pull.rebase true`

2023-03-31 05:02 UTC, CBID2 commented on components/LinksContainer/LinkContainer.jsx
> +          <img className="h-[1.2rem] mr-3" src={image} /> {name}
```suggestion
          <img className="h-[1.2rem] mr-3" src={image} alt=""/> {name}
```

2023-03-31 05:03 UTC, CBID2 commented on components/LinksContainer/LinkContainer.jsx
>          <div className="card-actions justify-end">
```suggestion
        <article className="card-actions justify-end">
```

2023-03-31 05:03 UTC, CBID2 commented on components/LinksContainer/LinkContainer.jsx
>          <div className="card-actions justify-end">
```suggestion
        <article className="card-actions justify-end">
```

2023-03-31 05:03 UTC, CBID2 commented on components/LinksContainer/LinkContainer.jsx
>        </div>
```suggestion
        </article>
      </article>
```

2023-03-31 05:04 UTC, CBID2 commented on components/popup/index.tsx
>          <div
```suggestion
        <article
```

2023-03-31 05:04 UTC, CBID2 commented on components/popup/index.tsx
>              <div className="flex justify-between items-center">
```suggestion
          <article className="flex flex-col gap-5">
            <article className="flex justify-between items-center">
```

2023-03-31 05:05 UTC, CBID2 commented on components/popup/index.tsx
> +                <img className="h-[1.2rem] mr-3" src={currentCard?.image} />{' '}
```suggestion
                <img className="h-[1.2rem] mr-3" src={currentCard?.image} alt="" />{' '}
```

2023-03-31 05:05 UTC, CBID2 commented on components/popup/index.tsx
>              </div>
```suggestion
            </article>
```

2023-03-31 05:06 UTC, CBID2 commented on database/Other/Github.json
> +    "description": "It can generate readme.md and contribute.md files with pre-built templates and suggestions.",
```suggestion
    "description": "It can quickly generate readme.md and contribute.md files with pre-built templates and suggestions.",
```

2023-03-31 05:07 UTC, CBID2 commented on database/Other/Github.json
> +    "description": "One of the best and efficient site to generate Readme file for your project.",
```suggestion
    "description": "One of the best and most efficient sites to generate Readme files for your project.",
```

2023-03-31 05:07 UTC, CBID2 commented on database/Other/Github.json
> +    "description": "This site will help you to generate markdowns for your GitHub profile",
```suggestion
    "description": "This site will help you to generate Markdown files for your GitHub profile",
```

2023-03-31 05:10 UTC, CBID2 requested changes
Hi @stupiddint! 😄  I just made some suggestions for your PR. I highly recommend not using `<div>` tags so much because they can make the code inaccessible. Other than that, good job! 👍🏾

2023-04-03 11:53 UTC, stupiddint commented
@rupali-codes @priyankarpal can you help me resolve the issues.
Guide me once.

2023-04-03 12:01 UTC, priyankarpal commented
> @rupali-codes @priyankarpal can you help me resolve the issues. Guide me once.

let me check

2023-04-03 12:17 UTC, priyankarpal commented
@stupiddint could you create a fresh PR? 😢

2023-04-16 06:58 UTC, rupali-codes commented
@stupiddint Are you still working on it? any updates?

2023-05-10 12:52 UTC, priyankarpal commented
I think we should close this PR

2023-05-10 16:42 UTC, rupali-codes commented
> I think we should close this PR

Yeah, i think so

2023-05-10 16:42 UTC, closed without merging