added lang sub-categories
rupali-codes/LinksHub pull request #377
Opened 2023-03-24 17:15 UTC by ujjawaltyagii

### Added subcategories for languages like ``Go, JavaScript  and Python``. Also, added some resources in ``javascript`` category

- Made changes to ``database>index.ts`` , ``types>index.ts`` , ``data.ts`` and created files ``python.json`` , ``javascript.json`` , ``golang.json``

### Closes #341 

## Screenshots
![image](https://user-images.githubusercontent.com/115401171/227594079-a5c1c585-0b95-42cd-8621-e9b177c07255.png)

![image](https://user-images.githubusercontent.com/115401171/227594273-5e2d473a-6033-413c-ad58-e3f5da207aab.png)

## Note to reviewers
- You are free to add more resources in provided categories and if you want to add any other language in sub-category then feel free to do so or just msg me I will do it :)

2023-03-24 17:18 UTC, ujjawaltyagii commented
@rupali-codes done !

2023-03-24 18:22 UTC, rupali-codes reviewed
I would like to suggest some changes, I guess we should create a new category for it, something like `documentory`, 'documentations' or `programming languages`, you can suggest names, and then add this resources in there

2023-03-25 15:47 UTC, ujjawaltyagii commented
okay :)

2023-03-25 16:44 UTC, ujjawaltyagii commented
@rupali-codes done with the changes !

2023-03-26 09:33 UTC, rupali-codes approved these changes
looks great to me! thanks a lot

2023-03-26 14:24 UTC, CBID2 requested changes
Great start! 😀 I just made some suggestions to clean up your descriptions a bit.

2023-03-26 14:24 UTC, CBID2 commented on database/languages/javascript.json
> +        "description": "It helps you learn the JavaScript programming language from scratch quickly and effectively.",
```suggestion
        "description": "It helps you quickly and effectively learn JavaScript.",
```

2023-03-26 14:24 UTC, CBID2 commented on database/languages/javascript.json
> +        "description": "It provides Modern JavaScript Tutorial with detailed explanations with examples and tasks.",
```suggestion
        "description": "It is a modern JavaScript tutorial that provides detailed explanation, examples, and tasks.",
```

2023-03-26 19:03 UTC, ujjawaltyagii commented
@CBID2 thanks for the feedback !

2023-03-26 20:10 UTC, CBID2 approved these changes
Well done! 😊 LGTM! 😁

2023-03-27 07:03 UTC, merged