<Link>Added eloquent javascript
rupali-codes/LinksHub pull request #382
Opened 2023-03-27 09:34 UTC by jayk-gupta

## Fixes Issue

## Changes proposed
Added eloquent javascript in the languages sections

## Screenshots

![el](https://user-images.githubusercontent.com/100681165/227902850-c200fbe8-19b0-48c4-b1a9-765c2a083cdf.png)

2023-03-27 13:33 UTC, CBID2 requested changes
Hi there. I fixed the description a bit. Other that, good job! 😊👍🏽

2023-03-27 13:33 UTC, CBID2 commented on database/languages/javascript.json
> +        "description": "This is a book about JavaScript,it explains concepts of javascript with real-life examples",
```suggestion
        "description": "This  book explains the concepts of JavaScript with real-life examples",
```

2023-03-27 13:44 UTC, jayk-gupta commented
> Hi there. I fixed the description a bit. Other that, good job! 😊👍🏽

Thanks!
I will add more resources in the languages section soon.

2023-03-27 13:45 UTC, jayk-gupta commented on database/languages/javascript.json
> +        "description": "This is a book about JavaScript,it explains concepts of javascript with real-life examples",
> 

resolved

2023-03-28 03:35 UTC, CBID2 requested changes
Hi @jayk-gupta! :) I just made a few suggestions in the description section of your PR. You're getting close! 👍🏾 Keep it up! 😄

2023-03-28 03:35 UTC, CBID2 commented on database/languages/javascript.json
> +        "description": "Learn javascript in an interactive environment.Read short lessons, take notes, and complete challenges directly in your browser.",
```suggestion
        "description": "This website teaches Javascript in an interactive way. You can read short lessons, take notes, and complete challenges directly in your browser.",
```

2023-03-28 04:51 UTC, jayk-gupta commented
> Hi @jayk-gupta! :) I just made a few suggestions in the description section of your PR. You're getting close! 👍🏾 Keep it up! 😄

Commited the changes!
Thanks

2023-03-28 11:06 UTC, CBID2 approved these changes
Yay you did it, you did it @jayk-gupta! 😁 LGTM! 👍🏾

2023-03-28 12:44 UTC, rupali-codes commented
Thank you @CBID2 and @jayk-gupta :)

2023-03-28 12:45 UTC, merged