added new resource
rupali-codes/LinksHub pull request #383
Opened 2023-03-27 17:12 UTC by ujjawaltyagii

### Closes : #378 

- Added new resource in category ``Design Inspiration`` in Frontend.

## Screenshots
![image](https://user-images.githubusercontent.com/115401171/228015579-1d85ee60-0757-4d6c-83be-531abccf85bc.png)

2023-03-28 03:37 UTC, CBID2 requested changes
Hi @ujjawaltyagii! :) I made some suggestions on how to improve the description. You're doing a great job! 😄 Keep it up! 👍🏾

2023-03-28 03:37 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +        "description": "Find app screens, landing pages, user flow inspirations and keep up with the latest mobile UI design trends.",
```suggestion
        "description": "You can find app screens, landing pages, user flow inspirations, and keep up with the latest mobile UI design trends.",
```

2023-03-29 00:04 UTC, CBID2 approved these changes
Well done @ujjawaltyagii! LGTM! 😄  👍🏾

2023-03-30 01:35 UTC, CBID2 approved these changes
Looks great @ujjawaltyagii! LGTM! 😄

2023-03-30 10:05 UTC, ujjawaltyagii commented
@rupali-codes

2023-03-30 11:35 UTC, rupali-codes approved these changes
Hey Thanks, lgtm

2023-03-30 11:36 UTC, merged