Update images.json
rupali-codes/LinksHub pull request #387
Opened 2023-03-30 07:23 UTC by Ajay84sia

Added SVG Backgrounds

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-03-30 11:34 UTC, rupali-codes reviewed
Could you please remove that extra line? line-50

2023-03-30 11:39 UTC, Ajay84sia commented
done, extra line? line-50 removed

2023-04-01 15:23 UTC, ujjawaltyagii approved these changes
LGTM 👍

2023-04-02 00:30 UTC, CBID2 commented on database/frontend/images.json
> +        "description": "This website provide you customize svg background for your projects",
```suggestion
        "description": "This website provides you customized SVG backgrounds for your projects",
```

2023-04-02 00:34 UTC, CBID2 requested changes
Hi @Ajay84sia! 😄 I added a suggestion to make your description clearer! 😄 For future reference, I highly recommend using [Grammarly](https://www.grammarly.com/about). It's a great tool for proofreading and revising the content you write! 😄 Keep it up! 👍🏾

2023-04-02 04:20 UTC, Ajay84sia commented
Thanks, @CBID2 for your suggestion. I will use Grammarly

2023-04-02 04:22 UTC, CBID2 approved these changes
Well done @Ajay84sia! 😄 LGTM! 👍🏾

2023-04-02 06:22 UTC, rupali-codes commented
Thanks

2023-04-02 06:22 UTC, merged