add: stackblitz in online code editor category
rupali-codes/LinksHub pull request #388
Opened 2023-03-30 13:40 UTC by ParasSolanki

## Fixes Issue

Closes #385 

## Changes proposed

Added StackBlitz in online code editor category

## Screenshots

![image](https://user-images.githubusercontent.com/62164346/228853897-a1fae639-e04f-461d-bad9-c894354c8ef3.png)

2023-03-31 13:53 UTC, rupali-codes commented on database/frontend/online-code-editors.json
> +    "description": "StackBlitz is an online code editor powered by WebContainers that allows users to create, collaborate, and deploy web applications in their web browser.",
```suggestion
    "description": "StackBlitz is an online code editor powered by WebContainers that allows users to create, collaborate, and deploy web applications..",
```

2023-03-31 15:36 UTC, ParasSolanki commented
We can use this description?

![image](https://user-images.githubusercontent.com/62164346/229165602-4f872a73-59d4-4910-9510-93c04e4a176c.png)

2023-03-31 15:46 UTC, rupali-codes approved these changes
lgtm, thanks

2023-03-31 15:54 UTC, ParasSolanki commented
sorry not that the one above this

2023-03-31 16:22 UTC, CBID2 requested changes
Hi @ParasSolanki! I made a tweak to your description. Overall, great job! 🙂

2023-03-31 16:22 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "StackBlitz is an online code editor powered by WebContainers that allows users to create, collaborate, and deploy web applications.",
```suggestion
    "description": "StackBlitz is an online code editor powered by WebContainers that allow users to create, collaborate, and deploy web applications.",
```

2023-04-01 03:18 UTC, CBID2 approved these changes
Great job @ParasSolanki! 😄 LGTM! 👍🏾

2023-04-01 07:14 UTC, rupali-codes commented
Thank you @CBID2 & @ParasSolanki

2023-04-01 07:14 UTC, merged