<Added link> Added python and css resources
rupali-codes/LinksHub pull request #389
Opened 2023-03-31 02:40 UTC by jayk-gupta

## Changes proposed
Added resources to the languages section: added python and css resources

## Screenshots
![python](https://user-images.githubusercontent.com/100681165/229009166-5bc0fa37-d8c3-43d3-b617-e78cdf6bf5b4.png)
![css](https://user-images.githubusercontent.com/100681165/229009177-1cfb05fa-a250-4fd9-b98a-9f9b515342ac.png)

2023-03-31 14:00 UTC, rupali-codes requested changes
Hey Jay, category should be `Languages`, also it's not showing in the panel

2023-03-31 15:03 UTC, CBID2 requested changes
Hi @jayk-gupta! I have a couple of edits on the descriptions of the sources you picked. Other than that, great work! 😊👍🏾

2023-03-31 15:03 UTC, CBID2 commented on database/languages/python.json
> +         "description": "This website teaches Python in an interactive way by providing in browser code editor with examples.",
```suggestion
         "description": "This website teaches Python in an interactive way by providing a browser code editor with examples.",
```

2023-03-31 15:03 UTC, CBID2 commented on database/languages/python.json
> +         "description": "This website teaches Python in an concise and interactive way by providing in browser code editor with examples.",
```suggestion
         "description": "This website teaches Python in an concise and interactive way by providing a browser code editor with examples.",
```

2023-03-31 16:18 UTC, jayk-gupta commented
> Hey Jay, category should be `Languages`, also it's not showing in the panel

Updated category.
Not showing means?

2023-03-31 17:30 UTC, ujjawaltyagii reviewed
- Resources are not visible on panel, kindly re-check and test the code on your local system too.
- Also there is no such sub-category as ``CSS`` in ``languages`` category so add that sub-category first before adding a different resource. 

Let me know if you are facing any issue in adding new sub-category I will help you or I will directly add that for you.

![image](https://user-images.githubusercontent.com/115401171/229188735-b68bb36f-20b6-446f-a568-24bc23a57cc6.png)

2023-04-01 07:00 UTC, rupali-codes approved these changes

2023-04-01 07:10 UTC, rupali-codes requested changes
We already have a category named _css_ in youtube category, can we name it something else?

2023-04-01 10:13 UTC, jayk-gupta commented
> * Resources are not visible on panel, kindly re-check and test the code on your local system too.
> * Also there is no such sub-category as `CSS` in `languages` category so add that sub-category first before adding a different resource.
> 
> Let me know if you are facing any issue in adding new sub-category I will help you or I will directly add that for you.
> 
> ![image](https://user-images.githubusercontent.com/115401171/229188735-b68bb36f-20b6-446f-a568-24bc23a57cc6.png)

okay, I will let you know.

2023-04-01 10:14 UTC, jayk-gupta commented
> We already have a category named _css_ in youtube category, can we name it something else?

That's youtube channel for css and these are websites, so what can we name it then?

2023-04-01 16:07 UTC, CBID2 commented on database/languages/css.json
> +        "description": "This website teaches CSS in with illustrations and examples which you can edit on CodePen.",
```suggestion
        "description": "This website teaches CSS with illustrations and examples that you can edit on CodePen.",
```

2023-04-01 16:10 UTC, CBID2 requested changes
Hi @jayk-gupta! 😊 I just left you a suggestion on how you can improve of the descriptions. Keep it up! 😁 👍🏾

2023-04-02 06:16 UTC, rupali-codes reviewed
@jayk-gupta CSS is not a language, better we can add this in _frontend_ category, but since we already have a subcategory it would lead to confusion to have 2 difference subcategories with same name. I guess we should call it _cascading style sheet_.

2023-04-02 15:53 UTC, CBID2 requested changes
Hi @jayk-gupta! I helped you created the suggestion that @rupali-codes made.

2023-04-02 15:53 UTC, CBID2 commented on database/languages/css.json
> +    "category": "languages",
```suggestion
    "category": "frontend",
```

2023-04-10 00:41 UTC, jayk-gupta commented
> Hey Jay, category should be `Languages`, also it's not showing in the panel

I tried adding new json file in the languages subcategory, but it's not showing in the site idk why?
What else do I need to do so that it shows on the site?

2023-04-10 00:42 UTC, jayk-gupta commented
> * Resources are not visible on panel, kindly re-check and test the code on your local system too.
> * Also there is no such sub-category as `CSS` in `languages` category so add that sub-category first before adding a different resource.
> 
> Let me know if you are facing any issue in adding new sub-category I will help you or I will directly add that for you.
> 
> ![image](https://user-images.githubusercontent.com/115401171/229188735-b68bb36f-20b6-446f-a568-24bc23a57cc6.png)

Yeah, adding new json file but it is not showing on the site?

2023-04-10 04:52 UTC, rupali-codes commented
> > Hey Jay, category should be `Languages`, also it's not showing in the panel
> 
> I tried adding new json file in the languages subcategory, but it's not showing in the site idk why? What else do I need to do so that it shows on the site?

You will also have to update `database/index.ts` and `database/data.ts` files accordingly.

2023-04-10 05:32 UTC, jayk-gupta commented
> > > Hey Jay, category should be `Languages`, also it's not showing in the panel
> > 
> > 
> > I tried adding new json file in the languages subcategory, but it's not showing in the site idk why? What else do I need to do so that it shows on the site?
> 
> You will also have to update `database/index.ts` and `database/data.ts` files accordingly.

ohh, ohk I will update there also then.
Thanks!

2023-04-10 06:01 UTC, jayk-gupta commented
> > > Hey Jay, category should be `Languages`, also it's not showing in the panel
> > 
> > 
> > I tried adding new json file in the languages subcategory, but it's not showing in the site idk why? What else do I need to do so that it shows on the site?
> 
> You will also have to update `database/index.ts` and `database/data.ts` files accordingly.

Updated the files as you said.
In python in the language subcategory the coming soon needs to be removed.

2023-04-11 07:25 UTC, rupali-codes commented on database/languages/golang.json
> +        "url": "   https://go.dev/learn/",
```suggestion
        "url":  "https://go.dev/learn/",
```

2023-04-11 07:26 UTC, rupali-codes commented on database/languages/java.json
> +        "category": "Other",
```suggestion
        "category": "languages",

```

2023-04-11 07:26 UTC, rupali-codes commented on database/languages/golang.json
> +        "category": "Other",
```suggestion
        "category": "languages",
```

2023-04-28 16:53 UTC, rupali-codes commented
@jayk-gupta could you please resolve the conversations?

2023-04-28 18:05 UTC, rupali-codes commented
It's not showing the languages you have added as well as resources in python

2023-04-28 18:08 UTC, rupali-codes commented on database/languages/python.json
P of Python should be lowercase (_python_)

2023-04-29 06:10 UTC, jayk-gupta commented
> Also, not showing java in the languages category
I have made the changes, now it is showing.
Will add more resources soon.
And Sorry, I just forgot about it.

2023-04-29 08:06 UTC, rupali-codes approved these changes
Looks perfect to me, thanks 😄

2023-04-29 08:56 UTC, jayk-gupta commented
> Looks perfect to me, thanks 😄

You're welcome! 😊
Will add more resources in 2-3 days in languages category.

2023-04-29 12:27 UTC, CBID2 requested changes
Well done so far @jayk-gupta! :) I just made some suggestions to improve your hair descriptions.

2023-04-29 12:27 UTC, CBID2 commented on database/languages/java.json
> +        "description": "It is a website to learn java with good examples and excercises.",
```suggestion
        "description": "This website provides good examples and exercises to learn Java.",
```

2023-04-29 12:27 UTC, CBID2 commented on database/languages/golang.json
> +        "description": "This webiste teaches step by step with proper explanation.",
```suggestion
        "description": "This webiste teaches Golang with detailed explanations and step by step directions.",
```

2023-04-29 12:27 UTC, CBID2 commented on database/languages/python.json
> +    "description": "This website teaches Python in an interactive way. It has examples, in browser code editor and excercises.",
```suggestion
    "description": "This website teaches Python in an interactive way. It has an online code editor where you go do the exercises alongside the lesson.",
```

2023-04-29 12:27 UTC, CBID2 commented on database/languages/python.json
> +    "description": "This website teaches Python in a concise way with examples and also has in browser videos.",
```suggestion
    "description": "This website teaches Python in a concise way with videos and examples.",
```

2023-04-29 12:41 UTC, jayk-gupta commented
> Well done so far @jayk-gupta! :) I just made some suggestions to improve your hair descriptions.

Committed all requested changes!

2023-05-20 14:38 UTC, closed without merging

2023-05-20 18:03 UTC, rupali-codes commented
@jayk-gupta why did you close the PR?

2023-05-20 18:26 UTC, jayk-gupta commented
By mistake I closed it!

2023-05-20 18:44 UTC, rupali-codes commented
> By mistake I closed it!

can u reopen it?

2023-05-21 06:54 UTC, jayk-gupta commented
I will created a new PR!
May be I have also discarded the changes in the forked repo.

2023-05-21 11:52 UTC, rupali-codes commented
> I will created a new PR! May be I have also discarded the changes in the forked repo.

Ohh, okay, awaiting :)