chore: migrated to pnpm
rupali-codes/LinksHub pull request #391
Opened 2023-03-31 14:52 UTC by priyankarpal

migrated to pnpm #372

2023-03-31 15:43 UTC, rupali-codes approved these changes
Thanks Priyankar, lgtm

2023-04-02 05:40 UTC, CBID2 commented on README.md
> +> - Before getting into it make you sure you have [pnpm](https://nodejs.org/download) installed.
```suggestion
> - Before getting into, it make you sure you have [pnpm](https://nodejs.org/download) installed.
```

2023-04-02 05:41 UTC, CBID2 commented on README.md
> +> - Also make sure to follow [CONTRIBUTING guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
```suggestion
> - Also, make sure to follow [CONTRIBUTING guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
```

2023-04-02 05:44 UTC, CBID2 commented on README.md
>  <img src="https://user-images.githubusercontent.com/78981177/215495029-ff9d4d24-a626-494a-859d-293cb9925f63.png"/>
```suggestion
<img src="https://user-images.githubusercontent.com/78981177/215495029-ff9d4d24-a626-494a-859d-293cb9925f63.png"/ alt=“”>
```

2023-04-02 05:45 UTC, CBID2 commented on README.md
>  </div><hr>
```suggestion
</article><hr>
```

2023-04-02 05:50 UTC, CBID2 requested changes
Hi @priyankarpal! 😄 I made some suggestions on your PR. In the future, consider using `<div>`tags sporadically and instead use semantic Html tags like `<article>`. It’ll help the code more accessible for people with disabilities that use screen readers. Other than that, well done! 😄

2023-04-02 06:23 UTC, rupali-codes commented on README.md
>  <img src="https://user-images.githubusercontent.com/78981177/215495029-ff9d4d24-a626-494a-859d-293cb9925f63.png"/>
Better if we could add some text

2023-04-02 06:58 UTC, priyankarpal commented
@CBID2 I resolved it as you said.

2023-04-02 13:04 UTC, CBID2 approved these changes
Well done @priyankarpal! 😀 LGTM! 👍

2023-04-03 11:32 UTC, rupali-codes reviewed
@priyankarpal shouldn't we remove package-lock.json file?

2023-04-04 17:16 UTC, ujjawaltyagii approved these changes
Looks good to me !! 👍

2023-04-05 17:23 UTC, rupali-codes commented
Thanks @ujjawaltyagii

2023-04-05 17:23 UTC, merged