Closes #403 Added JavaScript Mastery
rupali-codes/LinksHub pull request #404
Opened 2023-04-07 09:17 UTC by accodes21

## Fixes Issue
Adds JavaScript Mastery 

## Changes proposed

## Screenshots

## Note to reviewers
Closes #403 to add JavaScript Mastery in youtube category.

2023-04-07 16:52 UTC, rupali-codes commented on database/youtube/web-development.json
> +      "description": "This channel provides projects based on JavaScript and it's frameworks like ReactJS, NextJS, NodeJS along with API management. It also covers full stack projects with real life
```suggestion
      "description": "This channel provides projects based on JavaScript and it's frameworks like ReactJS, NextJS, NodeJS along with API management. It also covers full stack projects with real life applications.",
```

2023-04-08 03:09 UTC, CBID2 commented on database/youtube/web-development.json
> +      "description": "This channel provides projects based on JavaScript and it's frameworks like ReactJS, NextJS, NodeJS along with API management. It also covers full stack projects with real life
```suggestion
      "description": "This channel provides projects based on JavaScript and its frameworks like ReactJS, NextJS, NodeJS as well as API management. It also covers full stack projects with real life applications.",
```

2023-04-08 03:11 UTC, CBID2 requested changes
Hi @accodes21! 😁 I made some suggestions to improve the description. Other than that, well done. 🙂

2023-04-08 04:01 UTC, accodes21 commented
Made the required changes, its an amazing project💯✨

2023-04-08 05:46 UTC, CBID2 approved these changes
Well done @accodes21! 😄 LGTM! 😄 👍🏾

2023-04-08 08:29 UTC, rupali-codes approved these changes
Thank you for the changes

2023-04-08 08:30 UTC, merged