Fixed Coming Soon: Closes #409
rupali-codes/LinksHub pull request #424
Opened 2023-04-11 13:18 UTC by JA-26-01

## Fixes Issue  #409

## Changes proposed

Issue 2 in of #409 

It modifies the coming soon message which is displayed when there is no content to be shown. The message has been modifed to "Be the first to add by creating a github issue **here**", with a link to create and contribute to the same. The text has also been shifted to the centre of the screen for better visibility and user experience. 

## Screenshots

Before:

![image](https://user-images.githubusercontent.com/108082336/231175050-6a55a6b6-39ad-4178-a4f4-619998534c76.png)

After proposed changes:

![image](https://user-images.githubusercontent.com/108082336/231175123-b3ad5d89-18ab-4be0-b660-1fe4e0bc061e.png)

2023-04-11 15:27 UTC, rupali-codes requested changes
Thanks, i've 2 suggestions
1. Open link in new tab
2. Update `ComingSoon` file name

2023-04-11 15:29 UTC, rupali-codes commented on components/ComingSoon/ComingSoon.tsx
> +      <span className="text-2xl font-semibold">Be the first to add by creating a GitHub issue</span>{" "}
```suggestion
      <span className="text-2xl">Be the first to add by creating a GitHub issue</span>{" "}
```

2023-04-11 15:29 UTC, rupali-codes commented on components/ComingSoon/ComingSoon.tsx
>        <span className="animate-pulse text-2xl font-semibold text-purple-500">
```suggestion
      <span className="animate-pulse text-2xl text-purple-500">
```

2023-04-11 16:57 UTC, JA-26-01 commented
@rupali-codes I have included the suggestions as well as the reviews you made. You can go through it once.

2023-04-12 06:09 UTC, rupali-codes approved these changes
Looks good to me, thanks

2023-04-14 06:07 UTC, merged