Fixed Card List Positioning
rupali-codes/LinksHub pull request #430
Opened 2023-04-13 09:56 UTC by JA-26-01

## Fixes Issue #409 

## Changes proposed

This pull request addressed issue 1 in Enhancements, which was to shift the card list to the center for better visuals.

## Screenshots

Older layout:

![image](https://user-images.githubusercontent.com/108082336/231724241-3f115b17-7438-4a9c-94ec-8eb65204058f.png)

Proposed layout:

1. with many elements

![image](https://user-images.githubusercontent.com/108082336/231723392-6caad3dd-b569-4d14-8662-ab99bb2bb31d.png)

2. with a single row of elements

![image](https://user-images.githubusercontent.com/108082336/231723526-0a84ccfb-aa20-4ed2-a1b8-595a67b5a3af.png)

3. with a single card

![image](https://user-images.githubusercontent.com/108082336/231723741-5f35a03c-654e-47c5-ad8c-0a2113f51113.png)

4. with a single element on new row

![image](https://user-images.githubusercontent.com/108082336/231723977-d591f512-24e5-4f28-998c-e479b6ee2bd2.png)

5. for smaller screens

![image](https://user-images.githubusercontent.com/108082336/231724085-678358cb-886f-46bb-aa04-564516f8ae4a.png)

2023-04-13 14:21 UTC, rupali-codes reviewed
Hey it's breaking down:

![image](https://user-images.githubusercontent.com/78981177/231788658-0cc12532-b871-4955-9eb7-4f492fd84772.png)

2023-04-13 14:32 UTC, JA-26-01 commented
can you tell me what exactly are you facing? Like breaking down as in?

2023-04-14 06:20 UTC, rupali-codes commented
> can you tell me what exactly are you facing? Like breaking down as in?

It's showing a scrollbar for small screen (14 inches) also the color is breaking down

2023-04-14 06:20 UTC, rupali-codes commented
> > can you tell me what exactly are you facing? Like breaking down as in?
> 
> Looks like we have overflow along X as it seems from the screenshot

Yeah, it needs to be fixed for different screen, as one may not work for each screen

2023-04-14 09:37 UTC, JA-26-01 commented
> > can you tell me what exactly are you facing? Like breaking down as in?
> 
> Looks like we have overflow along X as it seems from the screenshot



> > > can you tell me what exactly are you facing? Like breaking down as in?
> > 
> > 
> > Looks like we have overflow along X as it seems from the screenshot
> 
> Yeah, it needs to be fixed for different screens, as one may not work for each screen

Oh okay got it. Let me look into it.

2023-04-14 09:54 UTC, JA-26-01 commented
@rupali-codes can you check the new commit once and let me know? I have made the changes and its working fine for me now.

![image](https://user-images.githubusercontent.com/108082336/232012015-0cd25f0d-e849-4725-9528-f96ad19dffa8.png)

2023-04-14 14:43 UTC, rupali-codes commented
> > > can you tell me what exactly are you facing? Like breaking down as in?
> > 
> > 
> > Looks like we have overflow along X as it seems from the screenshot
> 
> > > > can you tell me what exactly are you facing? Like breaking down as in?
> > > 
> > > 
> > > Looks like we have overflow along X as it seems from the screenshot
> > 
> > 
> > Yeah, it needs to be fixed for different screens, as one may not work for each screen
> 
> Oh okay got it. Let me look into it.

Nope, 
![image](https://user-images.githubusercontent.com/78981177/232076225-594946bc-7a71-4abf-9ca7-03c56f31b3b8.png)

I guess it would be better if you can re-position the cards in your way, like make it from scratch, just the design should be similar to the current design. What do you think?

2023-04-15 10:46 UTC, JA-26-01 commented
> 

Okay sure. Let me try it.

2023-04-19 22:59 UTC, CBID2 commented on components/Cards/CardsList.tsx
> +      </div>
```suggestion
      </article>
```

2023-04-19 22:59 UTC, CBID2 commented on components/Cards/CardsList.tsx
> +      </div>
```suggestion
      </article>
```

2023-04-19 23:00 UTC, CBID2 commented on components/Cards/CardsList.tsx
> +    <div className="cardlist">
```suggestion
    <article className="cardlist">
```

2023-04-19 23:00 UTC, CBID2 commented on components/Cards/CardsList.tsx
> +    <div className="cardlist">
```suggestion
    <article className="cardlist">
```

2023-04-19 23:00 UTC, CBID2 commented on components/Cards/CardsList.tsx
> +    <div className="cardlist">
```suggestion
    <article className="cardlist">
```

2023-04-19 23:03 UTC, CBID2 requested changes
Hi @JA-26-01! 😄 I've made some suggestions on how to make your cards more semantic. I hope you find them helpful! 😄 Also, avoid pushing the PR to the main branch. It'll make the PR process difficult. Other than that, well done! 😄

2023-04-21 13:28 UTC, JA-26-01 commented
> Hi @JA-26-01! 😄 I've made some suggestions on how to make your cards more semantic. I hope you find them helpful! 😄 Also, avoid pushing the PR to the main branch. It'll make the PR process difficult. Other than that, well done! 😄

Oh thank you so much. This looks much more structured. And yes, will keep that it mind! Actually my exams are going on so could not give it a go right now.

2023-04-21 16:28 UTC, rupali-codes commented
> > Hi @JA-26-01! 😄 I've made some suggestions on how to make your cards more semantic. I hope you find them helpful! 😄 Also, avoid pushing the PR to the main branch. It'll make the PR process difficult. Other than that, well done! 😄
> 
> Oh thank you so much. This looks much more structured. And yes, will keep that it mind! Actually my exams are going on so could not give it a go right now.

Sure, you can take your time and good luck for the exams :)

2023-05-21 13:45 UTC, CBID2 commented
Hey @JA-26-0! 😄 Are you still working on this?

2023-05-28 06:16 UTC, rupali-codes commented
Closing this PR because of inactivity, feel free to open a new PR whenever you are back!

2023-05-28 06:16 UTC, closed without merging