Capitalised CSS (subcategory) & FreeCodeCamp(YouTube>Web3)
rupali-codes/LinksHub pull request #439
Opened 2023-04-14 13:04 UTC by TreciaKS

## Fixes Issue
Closes #438 

## Changes proposed
- Capitalised CSS
- Capitalised 'f' in FreeCodeCamp

## Screenshots

-  Location: LinksHub/database/data.ts
<img width="485" alt="Screenshot 2023-04-14 at 14 57 29" src="https://user-images.githubusercontent.com/82657928/232050017-32443474-4c2f-4d26-9439-f9b80f0e7c1e.png">

- Location: LinksHub/database/youtube/web3-metaverse.json
<img width="489" alt="Screenshot 2023-04-14 at 14 59 32" src="https://user-images.githubusercontent.com/82657928/232050516-80d821c3-9e3f-405c-a0da-6edc6dbe5538.png">

## Note to reviewers

2023-04-14 14:49 UTC, rupali-codes commented on database/youtube/web3-metaverse.json
> +        "description": "FreeCodeCamp is a superb weebsite that aims at providing quality ontent for free across all domains and it provides quality content for this domain too.",
```suggestion
        "description": "FreeCodeCamp is a superb weebsite that aims at providing quality ontent for free across all domains and it provides quality content for this domain too.",
```
```suggestion
        "description": "FreeCodeCamp is a superb website that aims at providing quality content for free across all domains and it provides quality content for this domain too.",
```

2023-04-14 14:50 UTC, rupali-codes reviewed
hey @TreciaKS just fixed some typos, then we are good to go!

2023-04-14 16:25 UTC, TreciaKS commented
@rupali-codes Done ✅

2023-04-14 17:19 UTC, ujjawaltyagii requested changes
Hi @TreciaKS , you are doing great but there is still a typo in ``Web3 & Metaverse`` category in ``FreeCodeCamp.org`` you can update your PR after doing the necessary changes.
(content instead of ontent)
![image](https://user-images.githubusercontent.com/115401171/232113388-f749a906-d0fc-42e5-b0b3-bcd0227cb6a1.png)

2023-04-14 18:27 UTC, TreciaKS commented
@ujjawaltyagii Thanks! I've fixed necessary spelling and grammar.

2023-04-15 03:17 UTC, CBID2 commented on database/youtube/web3-metaverse.json
> +        "description": "FreeCodeCamp is a superb website that aims at providing quality content for free across all domains and it provides quality content for this domain too.",
```suggestion
        "name": "FreeCodeCamp.org",
        "description": "FreeCodeCamp is a superb website that aims to provide free high-quality tech content across all domains.",
```

2023-04-15 03:18 UTC, CBID2 commented on database/youtube/web3-metaverse.json
> +        "description": "Eat the Block is yet another YouTube channel with some in depth content on various topics on Web3 and Blockchain. It is one of those channels that you should definitely give a
```suggestion
        "description": "Eat the Block is yet another YouTube channel with some in depth content on various topics on Web3 and Blockchain. It is one of those channels that you should definitely give a try if you want to step into this emerging field of tech.",
```

2023-04-15 03:19 UTC, CBID2 commented on database/youtube/web3-metaverse.json
> +        "description": "Francesco's YouTube channel discusses topics about being in DevRel, Docker, Web3 and Bloackchain.",
```suggestion
        "description": "Francesco's YouTube channel discusses a wide range of tech topics such as DevRel, Docker, Web3, and Blockchain.",
```

2023-04-15 03:23 UTC, CBID2 requested changes
Hi @TreciaKS! 😄 I made a few suggestions on how to make your descriptions clearer. In the future, I highly recommend you run them through [Grammarly](https://www.grammarly.com/browser)before doing a PR. Other than that great work! 😄

2023-04-15 11:48 UTC, TreciaKS commented
Hey Christine! Thank you! Your suggestions are pretty awesome. Committed the changes ✅

2023-04-15 14:14 UTC, CBID2 approved these changes
Congratulation, You just made your first PR!🥳 LGTM! 😁

2023-04-16 06:51 UTC, rupali-codes approved these changes
Looks perfect to me, thanks @TreciaKS

2023-04-16 06:51 UTC, merged