Appshots#402
rupali-codes/LinksHub pull request #441
Opened 2023-04-14 19:40 UTC by Divyansh-0

#410 

Added UXarchive to Other section under DevTools

2023-04-15 04:51 UTC, CBID2 commented on database/backend/architecture.json
> +    "description": "Best practices and patterns for building applications on Microsoft Azure. Also provides suggestions for architecting solutions on Azure by using established patterns and practices
```suggestion
    "name": "Microsoft Architecture Center",
    "description": "This guide provides best practices and patterns for building applications on Microsoft Azure. It also provides suggestions for architecting solutions on Azure by using established patterns and practices.",
```

2023-04-15 04:52 UTC, CBID2 commented on database/backend/architecture.json
> +    "description": "Get Started Architecting on AWS. It provides reference architecture diagrams, vetted architecture solutions, Well-Architected best practices, patterns, icons, and more.",
```suggestion
    "description": "Getting started on architecting in AWS? Then check out this source, it provides reference architecture diagrams, vetted architecture solutions, best practices, patterns, icons, and more.",
```

2023-04-15 04:54 UTC, CBID2 commented on database/backend/architecture.json
> +  }
Is this a duplicate @Divyansh-0? If not, I highly recommend adding detail to the description to make them more distinctive.

2023-04-15 04:57 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +    "description": "AppShots is a pure, easy-to-use screenshot production tool for App Store applications. You can create beautiful application screenshots for the App Store application screenshots,
```suggestion
    "description": "AppShots is an easy-to-use screenshot production tool for App Store applications. You can create beautiful application screenshots, promote, and share your apps.",
```

2023-04-15 04:59 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +    "subcategory": "design-inspiration"
```suggestion
    "description": "The smarter way to research user interface flows, screen, and email best practices, and get unstuck is by learning from proven products.",
    "url": "https://pageflows.com/",
    "category": "frontend",
    "subcategory": "design-inspiration"
```

2023-04-15 05:00 UTC, CBID2 requested changes
Hi @Divyansh-0! 😄 I made some suggestions on how to improve your descriptions. Other than that, great work! 😄 👍🏾

2023-04-15 08:24 UTC, Divyansh-0 commented
> Hi @Divyansh-0! 😄 I made some suggestions on how to improve your descriptions. Other than that, great work! 😄 👍🏾

Hey Thanks for the changes suggested I ll improve all those in a bit.

2023-04-15 08:43 UTC, Divyansh-0 commented
@CBID2 Made the suggested changes can you review once?

2023-04-15 13:50 UTC, CBID2 approved these changes
LGTM! 😊

2023-04-16 06:48 UTC, rupali-codes reviewed
Thanks

2023-04-16 06:48 UTC, merged