hacker news site added
rupali-codes/LinksHub pull request #467
Opened 2023-04-21 13:45 UTC by Stroller15

## Changes proposed

hacker news site added

solved issue #455

2023-04-21 13:47 UTC, Stroller15 commented
@TreciaKS pls review my PR

2023-04-21 22:49 UTC, TreciaKS reviewed
@Stroller15 it seems you modified over 11 files just to add one site URL to the PR. Why is that? I believe this is the reason your PR is resulting in this error:https://github.com/orgs/community/discussions/25706. Otherwise the Hacker News object added looks great to me. You'll have to wait for the approval of your PR.

2023-04-21 22:49 UTC, TreciaKS commented
@CBID2 May you suggest something?

2023-04-21 23:06 UTC, CBID2 commented on database/frontend/design-inspirations.json
> +        "url": "https://pageflows.com/",
```suggestion
        "description": "The smarter way to research user interface flows, screen, email best practices, and getting unstuck is by learning from proven products.",
        "url": "https://pageflows.com/",
```

2023-04-21 23:08 UTC, CBID2 requested changes
Hi @Stroller15! 😄 The Hacker News addition looks pretty good. In regards to the other sources, I just added a suggestion to improve one of the descriptions.

2023-04-21 23:09 UTC, TreciaKS reviewed
@Stroller15 I just realised that the changes you've made here you've also made in this [PR](https://github.com/rupali-codes/LinksHub/pull/467) for issue #467 

I feel this would cause conflcts. @CBID2 What do you think about this? (Forgive me for being on a pinging spree this evening for you 😓 )

2023-04-21 23:21 UTC, CBID2 commented
> @Stroller15 I just realised that the changes you've made here you've also made in this [PR](https://github.com/rupali-codes/LinksHub/pull/467) for issue #467
> 
> I feel this would cause conflcts. @CBID2 What do you think about this? (Forgive me for being on a pinging spree this evening for you 😓 )

I don'

> @Stroller15 I just realised that the changes you've made here you've also made in this [PR](https://github.com/rupali-codes/LinksHub/pull/467) for issue #467
> 
> I feel this would cause conflcts. @CBID2 What do you think about this? (Forgive me for being on a pinging spree this evening for you 😓 )

According to [this](https://github.com/github/codeql/issues/8843), this seems to be more associated with the GitHub Actions.

2023-04-21 23:25 UTC, TreciaKS commented
Ohh I see, thanks for the link. I read through it.

I've learned something 👍

2023-04-21 23:26 UTC, CBID2 commented
> Ohh I see, thanks for the link. I read through it.
> 
> I've learned something 👍

Great! 👍🏾 Keep me and @rupali-codes posted! 😄

2023-04-22 07:06 UTC, rupali-codes reviewed
Please add the ONLY files you've made changes in :)

2023-04-23 07:36 UTC, rupali-codes commented
Hey, could you open a fresh PR containing the only changes you have made directly to MAIN branch?

2023-04-23 08:40 UTC, Stroller15 commented
>Hey, could you open a fresh PR containing the only changes you have made directly to MAIN branch?
hey @rupali-codes I made changes in dev branch as @TreciaKS said earlier

2023-04-23 13:18 UTC, closed without merging