added railway.app hosting site link
rupali-codes/LinksHub pull request #470
Opened 2023-04-21 19:07 UTC by Stroller15

added railway.app hosting site link

2023-04-21 19:09 UTC, Stroller15 commented
@TreciaKS pls review my PR

2023-04-21 20:56 UTC, CBID2 commented on README.md
> +  - [_Want to add your favorite links into the Hub? make sure to follow CONTRIBUTING guidelines._](#want-to-add-your-favorite-links-into-the-hub-make-sure-to-follow-contributing-guidelines)
```suggestion
  - [_Want to add your favorite links to the Hub? Follow the CONTRIBUTING guidelines._](#want-to-add-your-favorite-links-into-the-hub-make-sure-to-follow-contributing-guidelines)
```

2023-04-21 21:29 UTC, CBID2 requested changes
Hi @Stroller15! 😄 You're off to a great start! 😄 I made some suggestions on how to improve your descriptions. Well done! 👍🏾

2023-04-21 21:29 UTC, CBID2 commented on README.md
> +LinksHub is a Hub of Links `For Developers By Developers`. Here, we've gathered a collection of all the best and most useful resources, both free and paid, to aid in the development journey.
```suggestion
LinksHub is a Hub of Links `For Developers By Developers`. Here, we've gathered a collection of all the best and most useful resources, both free and paid, to aid developers of all levels in their development journey.
```

2023-04-21 21:29 UTC, CBID2 commented on README.md
>  We recognize that there's a wealth of information available, but often, it's a matter of knowing where to find it. That's why we've made it our mission to bring the right resources to the right devel
```suggestion
We recognize that there's a wealth of information available. However, what's important is _knowing_ where to find it. That's why we've made it our mission to bring the right resources to the right developers.
```

2023-04-21 21:29 UTC, CBID2 commented on database/resources/e-book.json
> +        "description":"The Deep Learning textbook is a resource intended to help students and practitioners enter the field of machine learning in general and deep learning in particular. The online
```suggestion
        "description":"The Deep Learning textbook is a resource intended to help students and practitioners enter the field of machine learning in general and deep learning in particular. The online version of the book is now complete and will remain online for free.",

```

2023-04-21 21:29 UTC, CBID2 commented on database/youtube/css.json
> +        "description": "A wide range of educational videos covering various topics such as animation, Motion Graphic Design, 3D animation, responsive website design, HTML, CSS, JavaScript, UX/UI desi
```suggestion
        "description": "This site has educational videos that cover various topics such as animation, Motion Graphic Design, 3D animation, responsive website design, HTML, CSS, JavaScript, UX/UI design, After Effects, Photoshop, Adobe Illustrator, and more.",
```

2023-04-21 21:29 UTC, CBID2 commented on database/youtube/machine-learning.json
> +        "description":"Free online course for learning tensorflow for Deep learning",
```suggestion
        "description":"Free online course for learning TensorFlow for Deep learning",
```

2023-04-21 21:29 UTC, CBID2 commented on database/youtube/machine-learning.json
> +        "description": "3Blue1Brown, by Grant Sanderson, is a combination of math and entertainment, depending on your disposition. The goal is for difficult problems to be made simple with changes i
```suggestion
        "description": "3Blue1Brown, by Grant Sanderson, is a combination of math and entertainment. The goal is for difficult problems to be made simple with changes in perspective.",
```

2023-04-21 21:29 UTC, CBID2 commented on database/youtube/machine-learning.json
> +        "description":"Learn Machine Learning in a way that is accessible to absolute beginners. You will learn the basics of Machine Learning and how to use TensorFlow to implement many different co
```suggestion
        "description": "In this beginner-level course, you will learn the basics of Machine Learning and how to use TensorFlow to implement different techniques.",
```

2023-04-22 07:04 UTC, rupali-codes reviewed
@Stroller15 did you use `git add .` after updating your branch? 
 Please only stage the files you have made changes in, not more than that✨

2023-04-23 13:45 UTC, Stroller15 commented
> @Stroller15 did you use `git add .` after updating your branch? Please only stage the files you have made changes in, not more than that✨

no i added only blogs.json and I thing prblm is dev branch

2023-04-23 16:04 UTC, closed without merging