Create SECURITY.md
rupali-codes/LinksHub pull request #472
Opened 2023-04-22 10:07 UTC by raghav1030

I have documented the security policy for the project. Please tell if there's any room improvement.

(I have added only one email id that I knew , but we can add more mail ids of the maintainers who can review the proposed vulnerabilities in this project)

## Fixes #460 

## Changes proposed

## Screenshots

## Note to reviewers

2023-04-22 20:02 UTC, CBID2 requested changes
Hi @raghav1030! 😊 Just made some suggestions. Great start 👍🏾

2023-04-22 20:02 UTC, CBID2 commented on SECURITY.md
> +The security policy includes a legal disclaimer that limits the liability of the project maintainers and contributors for any security vulnerabilities or incidents that occur as a result of using the
```suggestion
The security policy includes a legal disclaimer that limits the liability of the project maintainers and contributors for any security vulnerabilities or incidents that occur as a result of using[Linkshub's](https://linkshub.vercel.app/) website or any of the linked sources.
```

2023-04-22 20:02 UTC, CBID2 commented on SECURITY.md
> +By implementing this security policy, we aim to ensure that vulnerabilities are addressed in a timely and responsible manner, and that users and contributors can use the [Linkshub](https://linkshub.v
```suggestion
By implementing this security policy, we aim to ensure that vulnerabilities are addressed in a timely manner, and that users and contributors can use [Linkshub](https://linkshub.vercel.app/) and its linked sources safely and securely.
```

2023-04-23 18:30 UTC, raghav1030 commented on SECURITY.md
> +The project will follow a coordinated disclosure policy, which means that vulnerabilities will be disclosed publicly only after they have been remediated. The project may work with external website o
committed all changes

2023-04-23 18:40 UTC, raghav1030 commented
committed all the suggestion.
If anything more is to be done from my side then please tell?

2023-04-25 04:35 UTC, CBID2 approved these changes
LGTM! 😊

2023-04-25 15:06 UTC, rupali-codes commented on SECURITY.md
> +If you have any questions or concerns about the security policy or any security vulnerabilities in the project, please contact us at rupali7487@gmail.com.
```suggestion
If you have any questions or concerns about the security policy or any security vulnerabilities in the project, please contact us at _linkshub.opensource@gmail.com_.
```

2023-04-25 15:07 UTC, rupali-codes reviewed
Please update the email address, rest looks great to me

2023-04-26 13:56 UTC, CBID2 commented
> Please update the email address, rest looks great to me

Hey @rupali-codes! 😄  I added your suggestion. I just need your approval so I can merge it

2023-04-26 19:26 UTC, rupali-codes approved these changes
lgtm

2023-04-26 19:26 UTC, merged