Issue #477
rupali-codes/LinksHub pull request #482
Opened 2023-04-26 05:54 UTC by Harsh-2909

## Fixes Issue #477 

## Changes proposed
- Added a new subcategory for backend: system-design
- Added a new link for Gaurav Sen

## Screenshots

## Note to reviewers

2023-04-26 06:18 UTC, rupali-codes commented on database/backend/system-design.json
> +        "description": "Gaurav Sen has a youtube channel where he talks about system design concepts and interview preparation.",
```suggestion
        "description": "This channel is focused on teaching System design but they also provide content related to other computer science concepts such as Algorithm design, Dynamic programming, Software engineering, Competitive programming and more.",
```

2023-04-26 12:42 UTC, Harsh-2909 commented
I have made the changes. 
But seriously, I am always bad at writing these things

2023-04-26 13:51 UTC, CBID2 commented on database/backend/system-design.json
> +        "description": "This channel is focused on teaching System design but they also provide content related to other computer science concepts such as Algorithm design, Dynamic programming, Softw
```suggestion
        "description": "This channel teaches System Design and other computer science concepts such as Algorithm design, Dynamic programming, Software engineering, Competitive programming,and more.",
```

2023-04-26 13:53 UTC, CBID2 requested changes
Hey @Harsh-2909! 😄 I just made some edits to the Description section. Other than that, great job! :smiling

2023-04-27 05:52 UTC, Harsh-2909 commented
Made the changes

2023-04-29 08:25 UTC, Harsh-2909 commented
Just an update to merge this PR as I have made the requested changes

2023-04-29 14:51 UTC, rupali-codes commented
Thanks, looks good to me :)

2023-04-29 14:52 UTC, merged