Update react.json
rupali-codes/LinksHub pull request #496
Opened 2023-04-30 13:34 UTC by parma1111

## Fixes Issue

Closes #490 

## Changes proposed

It will give you more design and make your coding journey very fast.

## Screenshots

![Screenshot (790)](https://user-images.githubusercontent.com/101566294/235355721-9499dd47-98c3-430b-815f-8e2a2dca8c3b.png)

## Note to reviewers

Any kind of feedback would be appreciated

2023-04-30 17:06 UTC, rupali-codes commented on database/frontend/react.json
> +        "description":"This site will give you a every type of design with code. From this you can make your coding journey very fast.",
Could make the description a bit larger? it looks so small

2023-04-30 17:27 UTC, parma1111 reviewed
everything is ok

2023-05-02 04:14 UTC, CBID2 requested changes
Great start so far @parma1111! 😀  I just made some suggestions on how you can improve it.

2023-05-02 04:14 UTC, CBID2 commented on database/frontend/react.json
> +        "description":"This site will give you a every type of design with code. From this you can make your coding journey very fast.You can filter your design by framework,dependiences and tags.",
```suggestion
        "description":"This IDE will make it easier for you to code. You can get any design you want as well as filter it by framework,dependiences, and tags.",
```

2023-05-02 04:14 UTC, CBID2 commented on database/frontend/react.json
>          "subcategory":"react",
I'd put it in the "Dev tools" category since it's an IDE.

2023-05-02 12:11 UTC, rupali-codes commented
@CBID2 could you review the PR once again 😅

2023-05-03 05:57 UTC, rupali-codes approved these changes
looks good to me too

2023-05-03 05:58 UTC, merged