Fixes issue#493
rupali-codes/LinksHub pull request #499
Opened 2023-05-01 18:40 UTC by nbkju9b

Fixes issue #493

2023-05-01 19:29 UTC, nbkju9b commented
hi,

2023-05-02 03:06 UTC, nbkju9b reviewed
removed the comma.

2023-05-02 04:05 UTC, CBID2 approved these changes
Well done @nbkju9b! 😁

2023-05-02 06:12 UTC, nbkju9b commented
Thanks a ton Christine 😊

2023-05-02 11:10 UTC, nbkju9b reviewed
fixed the issue #493 , it is now showing the correct content

2023-05-02 12:13 UTC, rupali-codes commented on database/languages/python.json
> +        "category": "Other",
Should be languages

2023-05-02 13:10 UTC, CBID2 approved these changes
Well done @nbkju9b! :)

2023-05-02 13:11 UTC, CBID2 requested changes
Sorry I made a mistake. Fix this one

2023-05-02 13:11 UTC, CBID2 commented on database/languages/python.json
> +        "category": "Other",
```suggestion
        "category": "languages",
```

2023-05-02 13:12 UTC, CBID2 approved these changes
Now, we can merge! 😀

2023-05-02 14:30 UTC, nbkju9b reviewed
Thanks Rupali and Christine for the quick review and correction on category. Please see if this can be merged now

2023-05-02 23:11 UTC, ujjawaltyagii approved these changes
Looks good to me ! 👍

2023-05-03 06:15 UTC, rupali-codes approved these changes
thanks

2023-05-03 06:16 UTC, merged