Added MUI icons to database and a Javascript course in Spanish
rupali-codes/LinksHub pull request #537
Opened 2023-05-12 00:30 UTC by franciscoluna-28

After a long time, I finally implemented these changes correctly. Here are the things I added to the project:

![image](https://github.com/rupali-codes/LinksHub/assets/87947841/72343d4b-6c07-4043-aaf9-06c62c8ba6d9)
![image](https://github.com/rupali-codes/LinksHub/assets/87947841/0338aa01-f850-4aa0-b5e1-76ee190d851e)

Hopefully the commit will work well.

2023-05-12 00:37 UTC, franciscoluna-28 commented
Also, my apologies for misunderstanding git add before... I was trying to merge ALL the changes at once because of a mistake that I did before and implemented those changes. This time, I decided to start from scratch and read the documentation slowly since I'm new to contributing to open source. Anyway, fortunately the changes I've made will help the project a bit :)

2023-05-12 07:31 UTC, rupali-codes commented on database/languages/javascript.json
'category' should be **languages** not **other**

2023-05-12 18:54 UTC, franciscoluna-28 reviewed
Updated "Others" to "Languages"

2023-05-12 18:54 UTC, franciscoluna-28 commented on database/languages/javascript.json
Fixed the issue

2023-05-12 23:55 UTC, CBID2 requested changes
Hi @franciscoluna-28! :) There are some conflicts that need to be solved.

2023-05-13 18:10 UTC, rupali-codes approved these changes
lgtm, thanks

2023-05-13 18:10 UTC, rupali-codes commented
@franciscoluna-28 could you please resolve the conflicts so we can merge this PR :)

2023-05-13 20:29 UTC, franciscoluna-28 reviewed
Added the new course and fixed the existent conflict

2023-05-14 05:28 UTC, rupali-codes commented
@franciscoluna-28 Still have conflicts

2023-05-28 06:14 UTC, rupali-codes commented
@franciscoluna-28 are you still working on this?

2023-06-01 21:34 UTC, CBID2 commented
Hey @franciscoluna-28! :) Are you still working on this PR?

2023-06-03 16:58 UTC, franciscoluna-28 commented
I'm taking a break on Open source. My apologies for the late response. I need to learn more about Github before contributing again.

2023-06-03 16:58 UTC, closed without merging