Boxicons
rupali-codes/LinksHub pull request #540
Opened 2023-05-13 06:10 UTC by parma1111

## Fixes Issue

Closes #539

## Changes proposed

Boxicons: 2,000+ elegant vector icons for websites, apps, and digital projects. Clean lines, easy customization.

## Screenshots

## Note to reviewers

Any kind of feedback would be appreciated

2023-05-13 17:38 UTC, parma1111 commented
@rupali-codes @CBID2

2023-05-13 17:46 UTC, CBID2 requested changes
Hey @parma1111! :) You're off to a great start! :) I just made a little change to your description. :)

2023-05-13 17:46 UTC, CBID2 commented on database/frontend/icons.json
> +    "description": "Boxicons offer 2,000+ elegant vector icons for websites, apps, and digital projects. Clean lines, easy customization.",
```suggestion
    "description": "Boxicons offer 2,000+ elegant vector icons for websites, apps, and digital projects. Clean lines and easy customization.",
```

2023-05-13 18:18 UTC, ujjawaltyagii approved these changes
Lgtm !!

2023-05-13 19:25 UTC, parma1111 reviewed
done

2023-05-14 05:26 UTC, rupali-codes approved these changes
lgtm

2023-05-14 14:21 UTC, CBID2 approved these changes
LGTM!

2023-05-14 16:17 UTC, merged