chore: added AsaKatsu in OpenSource Projects
rupali-codes/LinksHub pull request #549
Opened 2023-05-17 14:59 UTC by parma1111

## Fixes Issue

Closes #547 

## Changes proposed

A project where you can keep track of your goal's progress, and contribute to open source in the same time.

## Screenshots

## Note to reviewers

Any kind of feedback would be appreciated.

2023-05-17 15:56 UTC, rupali-codes approved these changes
Thank you Parma, looks good to me

2023-05-17 18:08 UTC, ujjawaltyagii approved these changes
Lgtm 👍

2023-05-18 03:13 UTC, parma1111 commented
@CBID2

2023-05-18 03:17 UTC, CBID2 requested changes
Looks pretty good so far @parma1111! :) I just made a suggestion on how to improve your description.

2023-05-18 03:17 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "A project where you can keep track of your goals' progress. 'AsaKatsu' is a Japanese term for waking up a little early to do something productive, aligned with a specific goal.",
```suggestion
    "description": 'AsaKatsu' is a Japanese term for waking up a little early to do something productive, aligned with a specific goal. With this philosophy in mind, this product helps you keep track of your goals' progress.",
```

2023-05-18 03:31 UTC, parma1111 commented
> Looks pretty good so far @parma1111! :) I just made a suggestion on how to improve your description.

> Hey @CBID2! :) I have changed the description, now you can review the PR.

2023-05-18 03:35 UTC, CBID2 approved these changes
LGTM! 😊

2023-05-18 03:37 UTC, CBID2 commented
@rupali-codes, for some reason, I can’t merge it

2023-05-18 06:41 UTC, rupali-codes commented
> @rupali-codes, for some reason, I can’t merge it

You aren't seeing the option again?

2023-05-18 07:43 UTC, rupali-codes commented
@CBID2 could you try now?

2023-05-18 19:06 UTC, parma1111 commented
@rupali-codes @CBID2

2023-05-18 19:08 UTC, CBID2 commented
> @rupali-codes @CBID2

Still can't merge it

2023-05-18 19:44 UTC, CBID2 commented
> > > @rupali-codes @CBID2
> > 
> > 
> > Still can't merge it. Apparently, it is missing successful Preview and Production deployments @rupali-codes .
> 
> it has deployed successfully

I agree with you @rupali-codes, but the issue remains(see below screenshot)
![screenshot of issue](https://github.com/rupali-codes/LinksHub/assets/105683440/35d9cac4-aa23-4cf2-94ce-c9e42755bcf0)

2023-05-19 06:17 UTC, parma1111 commented
Now, what should I change in this PR - @rupali-codes @CBID2

2023-05-19 08:17 UTC, rupali-codes commented
@CBID2 I'm merging this PR by bypassing the rules and let's look for a solution

2023-05-19 08:18 UTC, merged