added Fontesk to frontend database under subcategory fonts
rupali-codes/LinksHub pull request #563
Opened 2023-05-19 19:50 UTC by jjxrry

## Fixes Issue

Closes #562

## Changes proposed

Added Fontesk to frontend database under subcategory fonts
 

## Screenshots

Located under "fonts" in the "frontend" folder
![8acd88734246c979aa252889f87899f5](https://github.com/rupali-codes/LinksHub/assets/114961129/b2a145ec-2cf4-412b-beca-34c8132a63e6)

## Note to reviewers

2023-05-20 03:18 UTC, CBID2 commented on database/frontend/fonts.json
> +        "description": "Curated web platform font library of the best high quality free fonts to download for commercial and personal use.",
[Proofreading] The description was a bit unclear due to its use of the preposition "of". 
```suggestion
        "description": "Curated web platform font library that contains the best high-quality free fonts to download for commercial and personal use.",
```

2023-05-20 03:21 UTC, CBID2 requested changes
Hi @jjxrry! :) You're off to a great start! :) There were a few typos in the description, so refer to the inline comment to fix them! :) Keep it up! :)

2023-05-20 18:43 UTC, rupali-codes submitted a review, later dismissed
looks good

2023-05-20 18:43 UTC, rupali-codes commented
@jjxrry are you a gssoc contributor?

2023-05-20 18:58 UTC, jjxrry commented
@rupali-codes no unfortunately I did not make this year's application deadline as I found out about it recently.

2023-05-20 19:03 UTC, jjxrry commented
@rupali-codes are you referencing the announcement you made in the discord? if so, can anyone contribute as I would love to be involved

2023-05-21 03:26 UTC, CBID2 commented
> @rupali-codes are you referencing the announcement you made in the discord? if so, can anyone contribute I would love to be involved.
Yes that's the one @jjxrry. If you are in GSSOC, you'd have to check the GSOC checkmark when you raise an issue(see screenshot below)

![GSSOC check mark](https://github.com/rupali-codes/LinksHub/assets/105683440/2731361d-942b-4fb3-b24c-88f111074256)

2023-05-21 04:52 UTC, jjxrry reviewed
fixed grammar for Fontesk JSON resource

2023-05-21 12:00 UTC, rupali-codes commented
> @rupali-codes are you referencing the announcement you made in the discord? if so, can anyone contribute as I would love to be involved

I'm just confirming so we can add the _gssoc23_ label :)

2023-05-25 06:33 UTC, CBID2 commented on database/frontend/fonts.json
> +        "description": "Curated web platform font library that contains the best high-quality free fonts to download for commercial and personal use.",
[Proofreading]
```suggestion
        "description": "Curated online font library that contains the best high-quality free fonts to download for commercial and personal use.",
```

2023-05-25 06:34 UTC, CBID2 requested changes
Hi @jjxrry! :) I pointed out a proofreading error that needs the be fixed.

2023-05-28 06:13 UTC, rupali-codes commented
@jjxrry could you please make the suggested changes?

2023-05-28 06:52 UTC, jjxrry commented
apologies for the delay, just made changes and requested reviews

2023-05-28 06:55 UTC, rupali-codes approved these changes
looks good to me

2023-06-03 07:15 UTC, merged