Firebase-Authentication guide added to backend/authentication.json
rupali-codes/LinksHub pull request #584
Opened 2023-05-20 19:15 UTC by SoumyadeepOSD

## Fixes Issue: #574 

## Changes proposed: `Add Firebase Authentication guide`

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/115442240/45750de1-d5aa-4875-ad75-0e23e9851f5f)

## Note to reviewers: Review and give your feedback to me

2023-05-21 12:03 UTC, rupali-codes commented
@SoumyadeepOSD are you a gssoc contributor?

2023-05-21 12:12 UTC, SoumyadeepOSD commented
> @SoumyadeepOSD are you a gssoc contributor?

yes

2023-05-21 13:50 UTC, CBID2 commented on database/backend/authentication.json
> +        "description": "This guide provides best practices and patterns for building applications ny using Firebase.",
```suggestion
        "description": "This guide provides information on best practices and patterns for building applications using Firebase.",
```

2023-05-21 13:52 UTC, CBID2 requested changes
Hey @SoumyadeepOS! You’re off to a great start! :) Just refer to my inline comment and you're good to go! :)

2023-05-21 20:19 UTC, CBID2 approved these changes
Looks good @SoumyadeepOSD! :) LGTM! :)

2023-05-21 22:51 UTC, CBID2 commented
@rupali-codes, we need a force push here.

2023-05-22 05:52 UTC, rupali-codes approved these changes
lgtm

2023-05-22 06:48 UTC, merged