Feature: Dark mode support
rupali-codes/LinksHub pull request #59
Opened 2023-01-20 08:53 UTC by gangadharbenni

changes to support dark mode support

- Darkmode config for Tailwind
- Dark mode Toggle button
- Topbar component to add Darkmode Toggler
- -Add dark mode contrast color in relevant components

![Screenshot (865)](https://user-images.githubusercontent.com/122692727/213654336-73a296fd-eb3b-40a0-90cc-b3e9ecda5936.png)

![Screenshot (866)](https://user-images.githubusercontent.com/122692727/213654521-08d8cf77-315f-498c-9d82-6374fbe50a87.png)

2023-01-20 09:16 UTC, rupali-codes commented
please attack an issue and also follow the [CONTRIBUTING guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)

2023-01-20 09:32 UTC, rupali-codes commented
@gangadharbenni its not working, i'm not able see any effects. Can you record a video instead?

2023-01-20 09:32 UTC, gangadharbenni commented
@rupali-codes I have linked the issue let me know for any more changes..

2023-01-20 09:42 UTC, rupali-codes commented on components/TopBar/TopBar.tsx
> +            <span className="mx-10 py-5">
increase icon size by `2xl`

2023-01-20 09:53 UTC, rupali-codes requested changes
- change title color in `LinksContainer` based on the theme, currently its white for all.

![image](https://user-images.githubusercontent.com/78981177/213664627-da152f53-1af7-419f-b4bb-b60ad949d6cb.png)

- also change the border color of sidenav elements. you can use `border-[rgba(0,0,0,0.3)]`

![image](https://user-images.githubusercontent.com/78981177/213664906-5d58328b-69da-4544-8796-8fa6a06b6615.png)
 
- it's not showing anywhere in mobile view, make sure it's located inside the menu

![image](https://user-images.githubusercontent.com/78981177/213665498-f8238c47-d0ca-4708-8bc2-e15fd885ef5b.png)

2023-01-20 16:39 UTC, rohitdasu commented
<img width="1440" alt="Screenshot 2023-01-20 at 10 08 46 PM" src="https://user-images.githubusercontent.com/48400770/213753837-e2b5c77e-03c0-42fd-9a5f-ebc136319bb2.png">
could you check why light mode is not showing up? maybe for browser settings?

2023-01-20 17:59 UTC, gangadharbenni commented
> <img alt="Screenshot 2023-01-20 at 10 08 46 PM" width="1440" src="https://user-images.githubusercontent.com/48400770/213753837-e2b5c77e-03c0-42fd-9a5f-ebc136319bb2.png">
> 
> could you check why light mode is not showing up? maybe for browser settings?


Looks like its issue because of Daisy UI plugin.

https://github.com/saadeghi/daisyui/discussions/640

2023-01-20 18:08 UTC, gangadharbenni commented
@rohitdasu  pls try now made fix for plugin issue..

2023-01-20 20:05 UTC, rupali-codes commented
@gangadharbenni i'm not able see logo, kindly fix
![image](https://user-images.githubusercontent.com/78981177/213795837-06ef8d6d-2c05-4e4e-b6d4-ef9b11a0581f.png)

Thank you

2023-01-21 05:54 UTC, anupam42 commented
> @gangadharbenni i'm not able see logo, kindly fix ![image](https://user-images.githubusercontent.com/78981177/213795837-06ef8d6d-2c05-4e4e-b6d4-ef9b11a0581f.png)
> 
> Thank you

I think i found the issue

2023-01-21 17:40 UTC, rupali-codes commented on components/SideNavbar/SideNavbarElement.tsx
> +      className={`${ router.asPath === url ? 'bg-slate-300 text-slate-700 transition-all pl-5' : ''} collapse py-3 w-full text-start border-b border-base-100 hover:bg-slate-300 hover:pl-5 hover:text-
add `border-gray-600`

2023-01-21 17:43 UTC, rupali-codes reviewed
make it dark by default, 
and also update this logo (Links) color based on the theme chosen
![image](https://user-images.githubusercontent.com/78981177/213879930-a04bef16-8b55-488a-bb85-681f19ed6745.png)

2023-01-21 18:23 UTC, gangadharbenni commented on components/SideNavbar/SideNavbarElement.tsx
> +      className={`${ router.asPath === url ? 'bg-slate-300 text-slate-700 transition-all pl-5' : ''} collapse py-3 w-full text-start border-b border-base-100 hover:bg-slate-300 hover:pl-5 hover:text-
updated

2023-01-21 18:30 UTC, gangadharbenni commented
> make it dark by default, and also update this logo (Links) color based on the theme chosen ![image](https://user-images.githubusercontent.com/78981177/213879930-a04bef16-8b55-488a-bb85-681f19ed6745.png)

@rupali-codes
Updated Dark as default on very first visit of site.
There on for next load of site it will use previous set theme in local storage..

Regarding logo color change my thought is like logo is theme independent
hence it should be same between mode changes..

2023-01-22 07:57 UTC, rohitdasu approved these changes

2023-01-22 08:06 UTC, rupali-codes commented
@gangadharbenni thanks for quick changes, we appreciate your time and efforts. keep contributing :)

2023-01-22 08:07 UTC, rupali-codes approved these changes

2023-01-22 08:07 UTC, merged