#GSSoC2023 1.Added section 'ml,ai and data' and provided links for ml…
rupali-codes/LinksHub pull request #611
Opened 2023-05-21 21:13 UTC by Grogu22

…, dl and data science'

2. also added a section for DeepLearningAI in ```database/youtube/machine-learning.json```

3. fixed a bug in displaying the ```golang``` section in main branch

4. added a new blog card for ```blogs.json```

5. modified the ```types/index.ts```, ```data.ts``` and ```index.ts``` sections for displaying the changes

## Changes proposed
1. Created a new category **ML, AI & DATA**
2. Created subcategories for _Machine Learning_, _Deep Learning_ and _Data Science_
3. Created a new entry in the `blogs.json` file for _Andrew Ng's blog_ on AI, ML and Deep Learning
4. Created a new entry in `machine-learning.json` file for DeepLearningAI's youtube channel
5. Added a link in `database/languages/golang.json` file, which was empty [🙃](https://emojipedia.org/upside-down-face/)

## Screenshots

<img width="210" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/d429167f-0c11-47c5-9b3e-8352e6a8b592">

<img width="699" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/c5ccae71-79ae-462f-a7dc-12620a2a4bcb">

<img width="308" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/9c00fad1-f160-4cc5-b701-63e38f8374b7">

<img width="508" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/d88de3ca-0e87-4071-a417-fcd5aecbb440">

<img width="508" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/43ee7717-e05c-4f81-b41a-3353f5645444">
<img width="314" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/de5fae8b-107b-40b6-912c-b0eaf3710a20">
<img width="549" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/83173038/d518e92f-7f9f-4bc7-907a-97737e6f7d6e">

## Note to reviewers

Please comment if some issues persist.. will fix them ASAP !!

2023-05-21 21:21 UTC, Grogu22 commented
@rupali-codes @CBID2  , created a _ML, Deep Learning, Data Science_ related category and added a few other stuff !!
Thought it was important ..

2023-05-21 22:09 UTC, CBID2 commented
> @rupali-codes @CBID2  , created a _ML, Deep Learning, Data Science_ related category and added a few other stuff !!
> 
> Thought it was important ..

Good job @Grogu22! 😊

2023-05-21 22:11 UTC, Grogu22 commented
> > @rupali-codes @CBID2  , created a _ML, Deep Learning, Data Science_ related category and added a few other stuff !!
> > Thought it was important ..
> 
> Good job @Grogu22! 😊

also, can I get write access to the repo please.. [😢](https://emojipedia.org/crying-face/)
cannot add a GSSoC'23 label !!

2023-05-21 22:14 UTC, CBID2 requested changes
Hey @Grogu22! 😊 Aside from the one typo I mentioned in my inline comment, your PR is off to a great start! 😊

2023-05-21 22:14 UTC, CBID2 commented on database/youtube/machine-learning.json
> +        "description":"Access the lectures of Andrew Ng on Deep Learning and Machine Learning",
[Typo]
```suggestion
        "description": "Access the lectures of Andrew Ng on Deep Learning and Machine Learning",
```

2023-05-21 22:16 UTC, CBID2 commented
> > > @rupali-codes @CBID2  , created a _ML, Deep Learning, Data Science_ related category and added a few other stuff !!
> 
> > > Thought it was important ..
> 
> > 
> 
> > Good job @Grogu22! 😊
> 
> 
> 
> also, can I get write access to the repo please.. [😢](https://emojipedia.org/crying-face/)
> 
> cannot add a GSSoC'23 label !!

Sorry @Grogu22. Only the maintainers can have write access to the repo.

2023-05-21 22:25 UTC, Grogu22 commented
yup.. committed the changes @CBID2

2023-05-21 22:41 UTC, CBID2 approved these changes
Looks great @Grogu22! 😄 LGTM! 😄

2023-05-21 22:44 UTC, CBID2 commented
> yup.. committed the changes @CBID2

Link the issue that your PR pertains to as well

2023-05-21 22:50 UTC, Grogu22 commented
Did not open an issue.. did a direct PR!! Should I open one now? @CBID2

2023-05-21 22:54 UTC, CBID2 commented
> Did not open an issue.. did a direct PR!! Should I open one now? @CBID2

Yes @Grogu22. I'm going to close this PR for now. Once you create the issue, I'll open it right back up! 👍🏾 In the future, please thoroughly review the [Contributing.md](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) before you contribute to LinksHub again.

2023-05-22 05:19 UTC, Grogu22 commented
This PR solves the issue #614.
Maybe merge it @CBID2 @rupali-codes ?

2023-05-22 06:13 UTC, rupali-codes commented on database/data.ts
> +console.log(database)
```suggestion
```

2023-05-22 06:16 UTC, rupali-codes commented on database/data.ts
> +      { name: 'ml', url: '/ml' },
```suggestion
      { name: 'machine learning', url: '/ml' },
```

2023-05-22 06:16 UTC, rupali-codes commented on database/data.ts
> +      { name: 'data-science', url: '/data-science'},
```suggestion
      { name: 'data-science', url: '/data-science'},
```
```suggestion
      { name: 'data science', url: '/data-science'},
```

2023-05-22 06:16 UTC, rupali-codes commented on database/data.ts
> +      { name: 'deep-learning', url : '/deep-learning'},
```suggestion
      { name: 'deep learning', url : '/deep-learning'},
```

2023-05-22 14:53 UTC, Grogu22 commented
Hey, @CBID2 @rupali-codes, did the following:
1. Added issue to PR
2. Resolved conversations
3. Resolved a merge conflict

2023-05-22 16:19 UTC, CBID2 approved these changes
LGTM! 😊

2023-05-23 06:37 UTC, rupali-codes approved these changes
looks good

2023-05-23 06:38 UTC, merged