New Frontend Resource - CSS In JS
rupali-codes/LinksHub pull request #615
Opened 2023-05-22 03:14 UTC by itsaakashpatel

## Fixes Issue : Closes [#610](https://github.com/rupali-codes/LinksHub/issues/610)

## Changes proposed

- Added a new Frontend Subcategory: Css In Js libraries
- Added emotion and styled-components.

## Screenshots

![Xnip2023-05-21_23-13-44](https://github.com/rupali-codes/LinksHub/assets/20282826/5e62ab02-f137-4def-a9d4-9de8003b541e)

## Note to reviewers

2023-05-22 04:00 UTC, CBID2 requested changes
You’re close @itsaakashpatel!!😊 Just fix the typo I mentioned in the inline comment and you’re good to go! 😊

2023-05-22 06:23 UTC, rupali-codes requested changes
Hey, please add this in _ui generator_ instead creating a new subcategory

2023-05-24 19:41 UTC, itsaakashpatel commented on database/frontend/css-in-js.json
> +        "description": "Emotion is a library designed for writing css styles with JavaScript. It provides powerful and predictable style composition.",
Corrected! Thank you!

2023-05-24 20:05 UTC, itsaakashpatel commented
@rupali-codes I added the required changes and rebased the PR with the `main` branch. Thanks!

2023-05-25 00:08 UTC, CBID2 approved these changes
Great job @Oyebolade! 😄 LGTM! 😄

2023-05-25 07:14 UTC, rupali-codes approved these changes
looks perfect

2023-05-25 07:15 UTC, merged