Gssoc
rupali-codes/LinksHub pull request #617
Opened 2023-05-22 05:17 UTC by coder-chahal

## Fixes Issue
Closes #612 

## Changes proposed

Add new resource in Python, Subcategory of "Languages".

## Screenshots

![issue](https://github.com/rupali-codes/LinksHub/assets/110322061/ded246fb-3629-4a0f-b437-7efb487ae1c4)

## Note to reviewers

2023-05-22 06:29 UTC, rupali-codes commented
Hey, please update title of your PR (ex. chore: added python programmiz in Python Languages). Also, read contributing guidelines for more information :)

2023-05-22 08:24 UTC, coder-chahal commented
@rupali-codes title updated.

2023-05-22 18:09 UTC, CBID2 commented on database/languages/python.json
> +        "description": "This Python course cover all the fundamental concepts of Python.",
[Proofreading] 
```suggestion
        "description": "This course covers all the fundamental concepts of Python.",
```

2023-05-22 18:10 UTC, CBID2 requested changes
Hi @coder-chahal! 😄  You're off to a great start! :) Just fix the proofreading error that I mentioned in my inline comment and you're good to go! 😄 👍🏾

2023-05-22 18:20 UTC, coder-chahal commented
thank you @CBID2!!

2023-05-22 18:29 UTC, coder-chahal commented
hey @CBID2 proofreading error fixed. Please merge the PR.

2023-05-22 18:51 UTC, CBID2 approved these changes
Great job @coder-chahal! 😊 LGTM! 😊

2023-05-23 06:43 UTC, rupali-codes approved these changes
looks good

2023-05-23 06:47 UTC, merged