Added 'Database' feature to 'BACKEND'
rupali-codes/LinksHub pull request #621
Opened 2023-05-22 07:23 UTC by Rutujeet

Closes #597 

Added 'Database' feature to 'BACKEND' as requested

<img width="2559" alt="Screenshot 2023-05-22 at 12 50 49 PM" src="https://github.com/rupali-codes/LinksHub/assets/91902893/4df4f1b2-180c-41b2-ac20-c125940c4ab9">

2023-05-22 18:13 UTC, CBID2 submitted a review, later dismissed
Looks great @Rutujeet! :) LGTM! :)

2023-05-23 07:58 UTC, rupali-codes commented
@Rutujeet Please resolve the conflicts carefully and don't **Close** the PR. You can learn how to resolve conflicts in [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

2023-05-23 18:02 UTC, CBID2 commented
@Rutujeet, please resolve the branch conflicts

2023-05-24 14:12 UTC, Rutujeet commented
> hey, could you please resolve merge conflicts?

I'll resolve it asap, I'm away

2023-05-28 06:27 UTC, rupali-codes commented on database/backend/database.json
> +    "language": "english"
```suggestion
```

2023-05-28 06:31 UTC, rupali-codes commented
@CBID2 what did you do 😂

2023-05-28 06:31 UTC, rupali-codes commented on database/backend/database.json
>      "subcategory": "database",
```suggestion
    "subcategory": "database"
```

2023-05-28 06:31 UTC, CBID2 commented
> @CBID2 what did you do 😂

I made a commit @rupali-codes. Proofreading issue.

2023-05-28 06:32 UTC, rupali-codes commented
> > @CBID2 what did you do 😂
> 
> I made a commit @rupali-codes. Proofreading issue.

Oh okay

2023-05-28 06:32 UTC, CBID2 requested changes
So close. Still needs more improvement.

2023-05-28 06:32 UTC, CBID2 commented on database/backend/database.json
> +    "description": "MongoDB is a source-available cross-platform document-oriented NoSQL database program",
[Proofreading]
```suggestion
    "description": "MongoDB is a source cross-platform document-oriented NoSQL database program",
```

2023-05-28 06:33 UTC, CBID2 approved these changes
LGTM

2023-05-28 06:35 UTC, rupali-codes approved these changes
lgtm too

2023-05-28 06:35 UTC, CBID2 commented
> > > @CBID2 what did you do 😂
> 
> > 
> 
> > I made a commit @rupali-codes. Proofreading issue.
> 
> 
> 
> Oh okay

- I think we need another review from you @rupali-codes.

2023-05-28 06:35 UTC, merged