chore: added dsa resource
rupali-codes/LinksHub pull request #625
Opened 2023-05-22 08:42 UTC by Akshatbhardwaj15

Added Algorithm tutorial in data structures section of Database.
![image](https://github.com/rupali-codes/LinksHub/assets/45891464/de94f71c-d719-4020-9764-fa56d380e12e)

2023-05-22 13:50 UTC, CBID2 commented
Hey @Akshatbhardwaj1! :) I closed this pull request because it's missing the issue number that it closes. Please add this information per the [CONTRIBUTING.MD](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and then I’ll reopen your PR.

2023-05-22 16:23 UTC, CBID2 requested changes
Hi @Akshatbhardwaj15! 😊 I mentioned a typo to fix in my suggestion, so just work on that and you're ready to go! :)

2023-05-22 16:23 UTC, CBID2 commented on database/youtube/data-structures.json
> +    "description": "Explanation of Algorithms concepts. The resources for Algorithm are limited but this course is one of the best Algorithm resource available on Web.",
[Typo]
```suggestion
    "description": "Explanation of Algorithms concepts. The resources for Algorithm are limited but this course is one of the best Algorithm resources available on the Web.",
```

2023-05-23 01:03 UTC, Akshatbhardwaj15 commented
i have fixed the typo, pls review it.

2023-05-23 01:53 UTC, CBID2 approved these changes
Well done @Akshatbhardwaj15! 😊 LGTM! 😊

2023-05-23 16:01 UTC, merged