chore: added multiple links
rupali-codes/LinksHub pull request #649
Opened 2023-05-22 17:35 UTC by akkshayTandon

## Fixes Issue

Closes #640 

## Changes proposed

added multiple links as per mentioned in the issue

## Screenshots

nil

## Note to reviewers

nil

2023-05-22 17:55 UTC, CBID2 commented on database/frontend/online-code-editors.json
> +    "description": "Learn to program with our beginner-friendly tutorials and examples. Read tutorials, try examples, write code and learn to program.",
[Proofreading]
```suggestion
    "description": "Learn to program with our beginner-friendly tutorials and examples. Read tutorials, try examples, write code, and learn to program.",
```

2023-05-22 17:56 UTC, CBID2 requested changes
Hi, @akkshayTandon! :) Aside from the proofreading error I mentioned in my inline comment, you're off to a great start! :) Keep it up! :)

2023-05-22 22:27 UTC, CBID2 approved these changes
Looks great @akkshayTandon! :) LGTM! :)

2023-05-23 16:17 UTC, rupali-codes commented
@akkshayTandon hey thanks, could you please conflicts? (NOTE - please don't close the PR, you can learn to resolve conflicts [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

2023-05-27 11:48 UTC, CBID2 submitted a review, later dismissed
Great job @akkshayTandon! 😄 LGTM! 😄

2023-05-28 06:05 UTC, rupali-codes commented on database/frontend/react.json
> +        "language":"english"
```suggestion
```

2023-05-28 06:05 UTC, rupali-codes commented on database/frontend/react.json
> +        "language":"english"
```suggestion
```

2023-05-28 06:06 UTC, rupali-codes commented on database/languages/csharp.json
> +        "category": "Languages",
```suggestion
        "category": "languages",
```

2023-05-28 06:06 UTC, rupali-codes commented on database/languages/csharp.json
> +        "category": "Languages",
```suggestion
        "category": "languages",
```

2023-05-28 06:09 UTC, rupali-codes commented on database/languages/python.json
this category is to ad Python tutorials such as blog posts or articles, for adding a youtube channel, please create a new subcategory named **python-youtube** . let us know if you any kinda help

2023-05-28 06:09 UTC, rupali-codes commented on database/opensource/projects.json
> +    "category": "opensource",
```suggestion
    "category": "open source",
```

2023-05-28 06:09 UTC, rupali-codes commented on database/opensource/projects.json
> +    "subcategory": "projects"
```suggestion
    "subcategory": "open-source-projects"
```

2023-05-29 16:03 UTC, rupali-codes commented
@akkshayTandon could you please make the suggested changes and resolve merge conflicts?

2023-06-03 07:16 UTC, rupali-codes commented
@akkshayTandon are you still working on this?

2023-06-04 14:05 UTC, akkshayTandon commented
@rupali-codes yep, actually i was busy in another event(khelo india) so didn't got the time to see this

2023-06-04 15:01 UTC, CBID2 approved these changes
LGTM!

2023-06-04 17:43 UTC, rupali-codes approved these changes
lgtm too

2023-06-04 17:43 UTC, merged