chore: added new resource in illustrations
rupali-codes/LinksHub pull request #668
Opened 2023-05-23 05:00 UTC by Nilesh9106

## Fixes Issue

Closes #664 

## Changes proposed
- added new resource in illustrations

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/97864081/f782fde7-3159-4fae-9c9c-ddcf9b5bb656)

2023-05-23 15:13 UTC, CBID2 commented on database/frontend/illustrations.json
> +    "description": "Free SVG illustrations are available for any idea you can imagine. You can change the primary and secondary colors of the illustrations to match your project's style guide. Downlo
[Typo]
```suggestion
    "description": "Free SVG illustrations are available for any idea you can imagine. You can change the primary and secondary colors of the illustrations to match your project's style guide. Download the illustrations in either PNG or SVG format. Premount illustrations are also available.",
```

2023-05-23 15:14 UTC, CBID2 requested changes
Hi @Nilesh9106! :) Just fix the typo and you’ll be ready to merge! :)

2023-05-27 08:32 UTC, Nilesh9106 commented
hii @CBID2. I have fixed the requested changes. can you please review PR?

2023-05-28 06:29 UTC, rupali-codes approved these changes
looks good

2023-05-28 06:29 UTC, merged