CSS libraries added
rupali-codes/LinksHub pull request #686
Opened 2023-05-23 14:05 UTC by noobtuber20103152

issue #637 

Please review @rupali-codes @CBID2

2023-05-23 14:45 UTC, CBID2 commented on database/frontend/css-library.json
> +    "description": "MUI offers a comprehensive suite of UI tools to help you ship new features faster. Start with Material UI, our fully-loaded component library, or bring your own design system to o
[Proofreading]
```suggestion
    "description": "MUI offers a comprehensive suite of UI tools to help you ship new features faster. You can also bring your own design system to its production-ready components.",
```

2023-05-23 14:47 UTC, CBID2 requested changes
Hey @noobtuber20103152! :) Aside from the proofreading errors I mention, you’re off to a great start! :)

2023-05-23 17:08 UTC, rupali-codes requested changes
looks good though, but can you please name it _CSS Libraries_ instead :)

2023-05-24 09:46 UTC, noobtuber20103152 commented
@rupali-codes @CBID2  done check it again

2023-05-24 12:27 UTC, noobtuber20103152 commented
done @CBID2

2023-05-24 12:47 UTC, CBID2 requested changes
Hi @noobtuber20103152! :) Keep on proofreading this PR. There is still some ambiguity in one of your descriptions.

2023-05-24 12:47 UTC, CBID2 commented on database/frontend/css-libraries.json
> +    "description": "Ant Financial has a large number of enterprise-level products. With complex scenarios, designers and developers often need to respond fast due to frequent changes in product deman
[Proofreading] I'm still confused by the last sentence. What is significant about it in regard to developers using this source?
```suggestion
    "description": "Ant Financial has a large number of enterprise-level products. With complex scenarios, designers and developers often need to respond fast due to frequent changes in product demands and concurrent R&D workflow. Many similar contents exist in the process.",
```

2023-05-26 08:11 UTC, closed without merging