added competitive programming section under Youtube
rupali-codes/LinksHub pull request #687
Opened 2023-05-23 14:26 UTC by harshit-002

## Fixes Issue 
Closes #650 

## Changes proposed

- added a competitive programming section under Youtube
- added 3 channels under that category.

## Screenshots
<img width="940" alt="Screenshot 2023-05-23 193714" src="https://github.com/rupali-codes/LinksHub/assets/95224348/c83414f9-5093-4806-a43c-7d1d3cf94413">

## Note to reviewers

2023-05-23 14:56 UTC, CBID2 commented on database/youtube/competitive-programming.json
> +    "description": "This channel provides competitive programming tactics and thought process for advanced alogrithms .",
[Typo]
```suggestion
    "description": "This channel provides competitive programming tactics and thought process for advanced algorithms.",
```

2023-05-23 14:58 UTC, CBID2 commented on database/youtube/competitive-programming.json
> +    "description": "This channel provides free video solutions of coding contests of codeforces, codechef etc.",
[Proofreading] This description is a bit unclear. What do you mean by “ free video solutions of coding contests of codeforces, codechef, etc“?
```suggestion
    "description": "This channel provides free video solutions of coding contests of codeforces, codechef, etc."
```

2023-05-23 15:03 UTC, CBID2 requested changes
Hi @harshit-002! :) I just provided some suggestions to improve your descriptions. In the future, I highly recommend running them through Grammarly or spellcheck before you submit your PR.

2023-05-23 16:23 UTC, harshit-002 commented
> Hi @harshit-002! :) I just provided some suggestions to improve your descriptions. In the future, I highly recommend running them through Grammarly or spellcheck before you submit your PR.

Sorry about that, I will make sure to double-check spellings.

2023-05-23 17:59 UTC, harshit-002 reviewed
Removed typos and made the descriptions clear.

2023-05-23 17:59 UTC, CBID2 approved these changes
LGTM! 😊

2023-05-25 07:21 UTC, rupali-codes approved these changes
looks good

2023-05-25 07:21 UTC, merged