Added TypeScript to the Language Section
rupali-codes/LinksHub pull request #692
Opened 2023-05-23 18:23 UTC by abhijeetnishal

## Fixes Issue
Closes #622

## Changes proposed
1. Added TypeScript as a prominent language in the language section.
2. Added a list of curated resources for learning TypeScript, including official documentation, and community-driven learning platforms.
3. Ensured that the resource links are up-to-date and accessible to provide the most relevant and reliable learning material for developers.

## Screenshots
<img width="1439" alt="Screenshot 2023-05-23 at 11 48 11 PM" src="https://github.com/rupali-codes/LinksHub/assets/83833440/73a216c2-8e5b-4299-a723-19cc5e14841e">

2023-05-23 21:09 UTC, CBID2 commented on database/languages/typescript.json
> +        "name": "Beginners Guide",
[Typo]
```suggestion
        "name": "Typescript Beginners Guide",
```

2023-05-23 21:10 UTC, CBID2 commented on database/languages/typescript.json
> +        "description": "This is a comprehensive and accessible resource designed to introduce beginners to the fundamentals of TypeScript programming.",
[Typo]
```suggestion
        "description": "This is a comprehensive and accessible resource designed to introduce beginners to the fundamentals of TypeScript.",
```

2023-05-23 21:11 UTC, CBID2 commented on database/languages/typescript.json
> +        "name": "TypeScript Official",
[Typo]
```suggestion
        "name": "Official TypeScript Guide",
```

2023-05-23 21:15 UTC, CBID2 requested changes
Hi @abhijeetnishal! :) I pointed out some typos in my inline comments. Fix those and you're good to go! :)

2023-05-23 21:22 UTC, CBID2 requested changes
Hi @abhijeetnishal! :) I pointed out some typos that could be improved. Fix those and you're good to go! :)

2023-05-24 14:14 UTC, abhijeetnishal commented
Hey @CBID2 i have fixed the typos you have described.

2023-05-24 14:17 UTC, CBID2 approved these changes
Well done @abhijeetnishal! :) LGTM! :)

2023-05-24 14:52 UTC, rupali-codes commented on database/languages/typescript.json
> +    "category": "Languages",
```suggestion
    "category": "languages",
```

2023-05-24 14:52 UTC, rupali-codes commented on database/languages/typescript.json
> +    "category": "Languages",
```suggestion
    "category": "languages",
```

2023-05-24 15:22 UTC, abhijeetnishal commented
Hey @rupali-codes i have fixed the category typos you have described.

2023-05-25 07:22 UTC, rupali-codes approved these changes
lgtm :)

2023-05-25 07:23 UTC, merged