Create CODEOWNERS
rupali-codes/LinksHub pull request #695
Opened 2023-05-23 20:17 UTC by CBID2

## Fixes Issue
#694 

## Changes proposed

## Screenshots

## Note to reviewers

@rupali-codes, I'd love to have your review on this.

2023-05-24 19:47 UTC, mocdaniel requested changes

2023-05-24 19:47 UTC, mocdaniel commented on .github/CODEOWNERS
> +# .env: @rupali-codes
Right now, all of those entries in the `CODEOWNERS` file are commented out (that's what the `#` in the beginning of each line does).

In order to follow the `CODEOWNERS` file's specific syntax, you'll need to adapt it as follows:

```suggestion
README.md @CBID2
.gitignore @CBID2 @rupali-codes
LICENSE @rupali-codes
.github/workflows/ @rupali-codes
app/ @rupali-codes
components/ @CBID2 @rupali-codes
lib/ @CBID2 @rupali-codes
tests/ @rupali-codes

## Directories
.github/ @rupali-codes @CBID2
node_modules/ @rupali-codes 
public/ @CBID2 @rupali-codes
.env/ @rupali-codes
```

You can read more about the `CODEOWNERS` file and its syntax [in the official GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax)

Feel free to tag me should you have additional questions.

2023-05-25 06:16 UTC, mocdaniel approved these changes

2023-05-25 12:03 UTC, CBID2 commented
> oh, thanks, can we also add _database_ dir to it?

I think so @rupali-codes. Add that on there.

2023-05-27 07:46 UTC, rupali-codes commented
> Reference

I'm not sure though, but let's merge it :)

2023-05-27 07:46 UTC, merged