Brachforlinksadd
rupali-codes/LinksHub pull request #708
Opened 2023-05-24 12:11 UTC by dhrumilpatel30

## Fixes Issue

Closes #679 
Closes #680 
Closes #681 
Closes #683

## Changes proposed

added the following resources:

RIP Tutorial
best Resource Collection
Awesome Certificates list
AI search engine for developers

## Screenshots

## Note to reviewers

as per instructed I have worked on four addition of a link in one pull request, if you find it difficult to manage I will make each PR for each issue listed above.
Thanks

2023-05-24 12:36 UTC, CBID2 requested changes
Hi @dhrumilpatel30! I just gave some feedback on how to improve your descriptions. As I have said in your other PRs, run your descriptions through Grammarly or Spellcheck to ensure that they are clear.

2023-05-24 12:36 UTC, CBID2 commented on database/Other/websites.json
> +        "description": "RIP Tutorial is a practical free learning tool. Website contains plenty of eBook resources and examples for learning help to developers.",
[Proofreading]
```suggestion
        "description": "RIP Tutorial is a free website that contains plenty of eBook resources and examples that can be helpful to developers.",
```

2023-05-24 12:36 UTC, CBID2 commented on database/Other/websites.json
> +        "description": "List containing hundreds of best learning resources available for programmers. Categorised in languages and technologies for easy navigation.",
[Proofreading]
```suggestion
        "description": "This is a list containing the best learning resources available for programmers. It is categorized by language and technology for easy navigation.",
```

2023-05-24 12:36 UTC, CBID2 commented on database/Other/websites.json
> +        "description": "A curated of list of IT, computer science and business courses with certificates & digital badges to earn upon completion. Each course on the list is free to take as well as t
[Proofreading]
```suggestion
        "description": "A curated of list of IT, computer science, and business courses with certificates & digital badges to earn upon completion. Each course on the list is free.",
```

2023-05-24 12:36 UTC, CBID2 commented on database/Other/websites.json
> +        "description": "Phind is a search engine that simply tells users what the answer is. Optimized for developers and technical questions.",
[Proofreading]
```suggestion
        "description": "Phind is a search engine that simply tells users what the answer is. It is optimized for developers and technical questions.",
```

2023-05-24 15:23 UTC, dhrumilpatel30 reviewed
thanks I have made changes according to your suggestions

2023-05-25 07:52 UTC, rupali-codes requested changes
* Since RIP tutorial is an e-book, it could be placed under _resources/e-book_ category
* AI search engine, could be added in _others/dev-tools_ category

And for Resources collection and Awesome certificates, you rename this subcategory from **websites** to **other resources**

2023-05-25 08:25 UTC, dhrumilpatel30 commented
> * Since RIP tutorial is an e-book, it could be placed under _resources/e-book_ category
> * AI search engine, could be added in _others/dev-tools_ category
> 
> And for Resources collection and Awesome certificates, you rename this subcategory from **websites** to **other resources**

hi @rupali-codes, thanks for review. I have made changes hope it will solve it.

2023-05-25 08:28 UTC, rupali-codes requested changes
otherresources getting hard to read, could you make it _other-resources_

2023-05-25 10:31 UTC, dhrumilpatel30 commented
> otherresources getting hard to read, could you make it _other-resources_

hi @rupali-codes, I have just changed it. please suggest if any more changes needed.

2023-05-25 22:39 UTC, CBID2 commented
Hey, @dhrumilpatel30. Can you resolve these branch conflicts, please?

2023-05-26 03:22 UTC, dhrumilpatel30 commented
> Hey, @dhrumilpatel30. Can you resolve these branch conflicts, please?

yes sure

2023-05-26 04:21 UTC, dhrumilpatel30 commented
hi @CBID2, I have resolved conflicts.

2023-05-26 07:31 UTC, rupali-codes approved these changes
looks good

2023-05-28 06:36 UTC, rupali-codes commented
@CBID2 could you please review this PR?

2023-05-28 06:37 UTC, CBID2 approved these changes
LGTM!

2023-05-28 06:38 UTC, CBID2 commented
> @CBID2 could you please review this PR?

Done @rupali-codes

2023-05-28 06:42 UTC, rupali-codes approved these changes
lgtm too

2023-05-28 06:42 UTC, merged