Added new resources in React Js ( Frontend )
rupali-codes/LinksHub pull request #711
Opened 2023-05-24 16:20 UTC by mhdamaan79

## Fixes Issue 

Closes (#706)

## Changes proposed
- [Add] React Official Documentation and Mosh's React tutorial

## Screenshots
![LinksHub-React-resources](https://github.com/rupali-codes/LinksHub/assets/118375524/6efe685b-90da-4091-b6ac-28c499ddea4c)

2023-05-24 17:54 UTC, CBID2 commented on database/frontend/react.json
> +        "description":"The go-to resource for React JS, offering comprehensive guides, tutorials, and API references to help you learn and master React development.",
[Proofreading] This seems like this came from the website. Consider describing this source in your own words
```suggestion
        "description": "The go-to resource for React JS, offering comprehensive guides, tutorials, and API references to help you learn and master React development.",

```

2023-05-24 17:56 UTC, CBID2 commented on database/frontend/react.json
> +        "description":"Mosh's React tutorial: beginner-friendly, well-structured, hands-on, builds solid React foundation.",
[Proofreading]
```suggestion
        "description": This tutorial is beginner-friendly, well-structured, hands-on, and is helpful in understanding React",

```

2023-05-24 17:57 UTC, CBID2 requested changes
Hi @mhdamaan79! :) I pointed out some proofreading errors in my inline comments.

2023-05-25 00:44 UTC, CBID2 approved these changes
Great job @mhdamaan79! 😄 LGTM! 😄

2023-05-25 00:44 UTC, CBID2 approved these changes
Great job @mhdamaan79! 😄 LGTM! 😄

2023-05-25 03:48 UTC, CBID2 requested changes
Hi @mhdamaan79! :) I noticed that some JSON errors popped up during the test run. Here's some information on it: https://github.com/rupali-codes/LinksHub/actions/runs/5072148109/jobs/9115441401?pr=711
Fix them and then ping me and @rupali-codes to review your pull request again.

2023-05-25 11:08 UTC, mhdamaan79 commented
> Hi @mhdamaan79! :) I noticed that some JSON errors popped up during the test run. Here's some information on it: https://github.com/rupali-codes/LinksHub/actions/runs/5072148109/jobs/9115441401?pr=711 Fix them and then ping me and @rupali-codes to review your pull request again.

Based on the changes you provided, I believe it's best to create a new pull request. Shall I proceed?

2023-05-25 11:28 UTC, mhdamaan79 commented
> Hi @mhdamaan79! :) I noticed that some JSON errors popped up during the test run. Here's some information on it: https://github.com/rupali-codes/LinksHub/actions/runs/5072148109/jobs/9115441401?pr=711 Fix them and then ping me and @rupali-codes to review your pull request again.

Take a look and let me know if anything else needs to be changed, Thanks! e2fa8c343acd9e97147589c2b25e1560d060a8ab
@CBID2 @rupali-codes

2023-05-27 14:00 UTC, mhdamaan79 commented
> > Hi @mhdamaan79! :) I noticed that some JSON errors popped up during the test run. Here's some information on it: https://github.com/rupali-codes/LinksHub/actions/runs/5072148109/jobs/9115441401?pr=711 Fix them and then ping me and @rupali-codes to review your pull request again.
> 
> Take a look and let me know if anything else needs to be changed, Thanks! [e2fa8c3](https://github.com/rupali-codes/LinksHub/commit/e2fa8c343acd9e97147589c2b25e1560d060a8ab) @CBID2 @rupali-codes

Kindly review the changes. Thank you! @CBID2

2023-05-28 06:39 UTC, rupali-codes approved these changes
lgtm

2023-05-28 06:40 UTC, CBID2 approved these changes
LGTM!

2023-05-28 06:43 UTC, merged