New links
rupali-codes/LinksHub pull request #734
Opened 2023-05-25 18:26 UTC by Oyebolade

## Fixes Issue
Closes #733

## Changes proposed
Happy Hues link was added to colors subcategory.

## Screenshots
![Happy Hues](https://github.com/rupali-codes/LinksHub/assets/57053389/c7fca8b3-2e67-4837-b5bd-d4639b65f780)

## Note to reviewers

2023-05-25 20:52 UTC, CBID2 commented on database/frontend/colors.json
> +    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real world example as to how the colors could be us
[Proofreading]
```suggestion
    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used in your design projects.",
```

2023-05-25 20:52 UTC, CBID2 requested changes
Hi @Oyebolade! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-05-26 04:46 UTC, Oyebolade commented on database/frontend/colors.json
> +    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real world example as to how the colors could be us
All right, I will fix it.
Thank you

2023-05-26 15:26 UTC, Oyebolade commented
> Hi @Oyebolade! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

The errors has been fixed.
Thanks.

2023-05-26 17:03 UTC, rupali-codes commented on database/frontend/colors.json
> +    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used
```suggestion
    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used in your design projects.",
```
```suggestion
    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used in your projects.",
```

2023-05-26 17:56 UTC, Oyebolade commented on database/frontend/colors.json
> +    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used
All right

2023-05-27 12:10 UTC, Oyebolade commented on database/frontend/colors.json
> +    "description": "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real-world example of how the colors could be used
Corrected

2023-05-28 06:04 UTC, rupali-codes approved these changes
looks good

2023-05-28 06:47 UTC, rupali-codes commented
@CBID2 ☺️

2023-05-29 16:04 UTC, merged