Three new links are added in open source projects file
rupali-codes/LinksHub pull request #738
Opened 2023-05-26 00:26 UTC by Isha988

## Fixes Issue
Closes #31

## Changes proposed
Three websites are added
1. **GSoC Organizations:** https://www.gsocorganizations.dev/
2. **Up for grabs:** https://up-for-grabs.net/
3. **CodeTriage:** https://www.codetriage.com/

2023-05-26 04:55 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "This is a list of projects which have curated tasks specifically for new contributors. These are a great way to get started with a project, or to help share the load of working on
[Typo]
```suggestion
    "description": "This is a list of projects which have curated tasks specifically for new contributors. These are a great way to get started with a project, or help share the load of working on open source projects. ",
```

2023-05-26 04:56 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "Pick your favorite repos to receive a different open issue in your inbox every day. Fix the issue and everybody wins. 71,669 developers are working on 7,712 open source repos usin
[Proofreading]
```suggestion
    "description": "Pick your favorite repos and receive a different open issue in your inbox every day. Fix the issue and everybody wins! 71,669 developers are working on 7,712 open source repos using CodeTriage.",
```

2023-05-26 04:58 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "A site for viewing and analysing the info of the organizations participating in Google Summer of Code and filtering them by various factors like years of participation, categories
[Proofreading]
```suggestion
    "description": "A site that views and analyzed information on the organizations participating in Google Summer of Code, filtering them by various factors like years of participation, categories, etc.",
```

2023-05-26 05:00 UTC, CBID2 requested changes
Hi @Isha988! :) I pointed out a few proofreading errors and typos in my inline comments. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-05-26 05:04 UTC, CBID2 commented
Hi @Isha988! 😊 The linked issue refers to something that has already been solved, so I’m going to close your pull request for now. Refer to the [Contributing file](https://github.com/rupali-codes/linkshub/blob/main/CONTRIBUTING.md#issues) to help you create an issue that correlates to this PR. Once that’s done, tag me and it will be opened! 😊

2023-05-26 06:14 UTC, Isha988 commented
@CBID2 I had linked the wrong issue by mistake, but now that I have tagged the right issue, would you please reopen this PR so that I can make suggested changes?

2023-05-26 12:42 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "A site that views and analyzed information on the organizations participating in Google Summer of Code, filtering them by various factors like years of participation, categories,
```suggestion
    "description": "A site that views and analyzes information on the organizations participating in Google Summer of Code, filtering them by various factors like years of participation, categories, etc.",
```

2023-05-26 12:43 UTC, CBID2 requested changes
So close @Isha988.

2023-05-26 12:49 UTC, Isha988 commented
> So close @Isha988.

I copied the description from their respective websites, but still, it has such errors.

2023-05-26 12:53 UTC, CBID2 approved these changes
Great job @Isha988! 😄 LGTM! 😄

2023-05-26 17:06 UTC, rupali-codes requested changes
Hey Isha, we have just added a new category named _tools_, could you please add _up for grabs_ & _codeTriage_ in there? thanks

2023-05-26 17:11 UTC, CBID2 requested changes
Hi @Isha988! @rupali-codes requested some changes so add some inline comments to help you.

2023-05-26 17:11 UTC, CBID2 commented on database/opensource/projects.json
> +    "subcategory": "projects"
[Proofreading] 
```suggestion
    "subcategory": "tools"
```

2023-05-26 17:11 UTC, CBID2 commented on database/opensource/projects.json
> +    "subcategory": "projects"
```suggestion
    "subcategory": "tools"
```

2023-05-26 23:05 UTC, Isha988 commented
> Hey Isha, we have just added a new category named _tools_, could you please add _up for grabs_ & _codeTriage_ in there? thanks

Ok, will do

2023-05-27 00:07 UTC, CBID2 approved these changes
Great job @Isha988! 😄 LGTM! 😄

2023-05-27 00:09 UTC, Isha988 commented
> Great job @Isha988! 😄 LGTM! 😄

Finally 😁😅

2023-05-27 00:09 UTC, CBID2 requested changes
Hi @Isha988! :)
Ignore my previous comment. There’s conflicts in your branch that need to be solved.

2023-05-27 00:10 UTC, Isha988 commented
> Hi @Isha988! :) Ignore my previous comment. There’s conflicts in your branch that need to be solved.

How to resolve them?

2023-05-27 00:20 UTC, CBID2 commented
> > Hi @Isha988! :) Ignore my previous comment. There’s conflicts in your branch that need to be solved.
> 
> How to resolve them?

I'm not too sure 🤔 @Isha988.

2023-05-27 00:22 UTC, Isha988 commented
> Hi @Isha988! :) Ignore my previous comment. There’s conflicts in your branch that need to be solved.

I have resolved the conflicts of database/index.ts and database/data.ts files but in remaining two file it is showing the changes that I have made as conflicts.

2023-05-27 07:14 UTC, rupali-codes commented
@Isha988 i can not see the option to resolve conflicts could you please enable that so i can help you with that

2023-05-27 07:52 UTC, Isha988 commented
> @Isha988 I can not see the option to resolve conflicts could you please enable that so I can help you with that

@rupali-codes  is it enabled now?

2023-05-27 17:40 UTC, Isha988 commented
> Hi @Isha988! :) Ignore my previous comment. There’s conflicts in your branch that need to be solved.

Hey, @CBID2 and @rupali-codes Now that I have resolved all the conflicts, and I think we are good to go with this.

2023-05-27 17:42 UTC, CBID2 approved these changes
Great job @Isha988! 😄 LGTM! 😄

2023-05-28 06:50 UTC, rupali-codes approved these changes
looks perfect, thanks Isha

2023-05-28 06:51 UTC, merged