Added 3 resources in 2 different categories
rupali-codes/LinksHub pull request #748
Opened 2023-05-26 11:19 UTC by ayushkumarbhadani

## Fixes Issue #739 

## Changes proposed
Added 3 resources in 2 different categories

1. Computer Science: 
  > 5 Minutes Engineering
  > Jenny's Lectures CS IT

2. Competitive Programming:
  > Luv

2023-05-26 12:16 UTC, CBID2 requested changes
Hi @ayushkumarbhadani! I just made some proofreading suggestions in my inline comments. In the future, try to describe the source in your own words and run the descriptions through Spellcheck or Grammarly before submitting them as pull requests.

2023-05-26 12:16 UTC, CBID2 commented on database/youtube/computer-science.json
> +    "description": "On 5 Minutes Engineering you can find EASIEST explanations for all following mentioned subjects in HINDI: Aptitude, Machine Learning, Deep Learning, C, R and Python Programming La
[Proofreading]
```suggestion
    "description": "On 5 Minutes Engineering, you can find EASIEST explanations for all following mentioned subjects in HINDI: Aptitude, Machine Learning, Deep Learning, C, R and Python Programming Languages, Discrete Mathematics (DM), Theory Of Computation (TOC), Artificial Intelligence(AI), Database Management System(DBMS), Software Modeling and Designing(SMD), Software Engineering and Project Planning(SEPM), Data mining and Warehouse(DMW), Data analytics(DA), Mobile Communication(MC), Computer networks(CN), High performance Computing(HPC), Operating system, System programming (SPOS), Internet of things(IOT), and Design and analysis of algorithm(DAA)",
```

2023-05-26 12:16 UTC, CBID2 commented on database/youtube/computer-science.json
> +    "description": "Jenny’s Lectures CS IT is a Free YouTube Channel providing Computer Science / Information Technology / Computer-related tutorials including NET & JRF Coaching Videos, GATE Coachin
[Proofreading]
```suggestion
    "description": "Jenny’s Lectures CS IT is a Free YouTube Channel providing Computer Science / Information Technology / Computer-related tutorials, including NET & JRF Coaching Videos, GATE Coaching Videos, UGC NET, NTA NET, JRF, BTech, MTech, Ph.D., tips and other helpful videos for Computer Science / Information Technology students.",
```

2023-05-26 12:27 UTC, ayushkumarbhadani commented
Hey @CBID2, Kindly re-review it, please. Hope I didn't make any mistakes this time.

2023-05-26 12:44 UTC, CBID2 approved these changes
Great job @ayushkumarbhadani ! 😄 LGTM! 😄

2023-05-28 07:06 UTC, rupali-codes requested changes
hey, could you please add the playlist link instead? because these youtube channel has also been added in different categories

2023-05-28 10:08 UTC, ayushkumarbhadani commented
Sure @rupali-codes

2023-05-28 12:10 UTC, rupali-codes approved these changes

2023-05-28 12:12 UTC, merged