Requesting to merge: chore:added open-source guide in category,subcategory
rupali-codes/LinksHub pull request #749
Opened 2023-05-26 11:48 UTC by devasyarajguru

## Fixes Issue #674 

## Changes proposed
Added a blog link to Opensource section with proper Name , description, url , category , subcategory

## Screenshots

<img width="960" alt="blog link" src="https://github.com/rupali-codes/LinksHub/assets/84851506/eb157220-1ec2-4a47-9c72-f6b69f0afd69">

## Note to reviewers

None

2023-05-26 12:46 UTC, CBID2 approved these changes
Great job @devasyarajguru! 😄 LGTM! 😄

2023-05-26 13:18 UTC, devasyarajguru commented
I have to fix the changes you have told above? I have to fix it again in my local setup(VS Code) and again add, commit, push changes ?? That's it? @CBID2

2023-05-26 13:34 UTC, devasyarajguru commented
> > I have to fix the changes you have told above? I have to fix it again in my local setup(VS Code) and again add, commit, push changes ?? That's it? @CBID2
> 
> Have you checked the Contributing file before making this PR @devasyarajguru?

Yes I have checked it. Why?

2023-05-26 13:38 UTC, devasyarajguru commented
Hey @CBID2 I just misunderstand the comment. Actually I thought I have to fix the change but it's already changed by you. I hope it is fine?

2023-05-26 14:06 UTC, CBID2 commented
> Hey @CBID2 I just misunderstand the comment. Actually I thought I have to fix the change but it's already changed by you. I hope it is fine?

It's fine @devasyarajguru! :) Rupali just needs to approve your pull request.

2023-05-26 16:28 UTC, devasyarajguru commented
> > Hey @CBID2 I just misunderstand the comment. Actually I thought I have to fix the change but it's already changed by you. I hope it is fine?
> 
> It's fine @devasyarajguru! :) Rupali just needs to approve your pull request.

Thank you very much @CBID2 @rupali-codes . You both are very supportive and active. It was great to contribute! Looking forward to do more!

2023-05-26 17:30 UTC, CBID2 requested changes
Hi @devasyarajguru! :) There are some branch conflicts that need to be solved.

2023-05-27 06:21 UTC, devasyarajguru commented
For solving the conflicting branch , do I have to perform [git pull upstream main] ?? and then git push?

2023-05-27 18:37 UTC, devasyarajguru commented
Please checked this. I have resolved the issues @CBID2

2023-05-27 18:39 UTC, CBID2 submitted a review, later dismissed
Great job @devasyarajguru!😄 LGTM! 😄

2023-05-27 18:42 UTC, devasyarajguru commented
> Great job @devasyarajguru!😄 LGTM! 😄

Thanks @CBID2 . When will be my PR merged?

2023-05-27 18:43 UTC, CBID2 commented
> > Great job @devasyarajguru!😄 LGTM! 😄
> 
> Thanks @CBID2 . When will be my PR merged?

When you get an approved review by @rupali-codes @devasyarajguru! 😊

2023-05-27 18:48 UTC, devasyarajguru commented
> > > Great job @devasyarajguru!😄 LGTM! 😄
> > 
> > 
> > Thanks @CBID2 . When will be my PR merged?
> 
> When you get an approved review by @rupali-codes @devasyarajguru! 😊

Okay no problem. But just tell me that I have resolved conflicts properly or not?

2023-05-28 07:08 UTC, rupali-codes reviewed
This site was already added in [open-source-tools](https://www.linkshub.dev/open-source-tools) 👀

2023-05-28 08:10 UTC, devasyarajguru commented
> This site was already added in [open-source-tools](https://www.linkshub.dev/open-source-tools) 👀

Does that count my contribution? @CBID2 @rupali-codes , and will this PR will remain open? Please explain it as I am a beginner.

2023-05-28 08:20 UTC, devasyarajguru commented
> > This site was already added in [open-source-tools](https://www.linkshub.dev/open-source-tools) 👀
> 
> Does that count my contribution? @CBID2 @rupali-codes , and will this PR will remain open? Please explain it as I am a beginner.

Also I have done valid contribution should'nt my PR gets merged??

2023-05-28 08:31 UTC, rupali-codes commented
> > > This site was already added in [open-source-tools](https://www.linkshub.dev/open-source-tools) 👀
> > 
> > 
> > Does that count my contribution? @CBID2 @rupali-codes , and will this PR will remain open? Please explain it as I am a beginner.
> 
> Also I have done valid contribution should'nt my PR gets merged??

Yes your PR is completely valid, but the resource has already been added. Could you please work on some other issues and close this PR? I really appreciate your time and commitment, but we can not have duplicate resources for the same thing.

2023-05-28 09:01 UTC, devasyarajguru commented
Subject: Disappointment Regarding Unmerged Pull Request

Dear @CBID2 @rupali-codes ,

I hope this message finds you well. Firstly, I want to express my sincere appreciation for the opportunity to contribute to the project and for the efforts you all put into maintaining it. I understand that you receive numerous pull requests on a regular basis, making the task of managing and merging them quite challenging.

I am writing to you today with a sense of disappointment regarding the unmerged pull request (PR) I recently submitted. I had worked diligently on addressing an issue that was assigned to me, and I firmly believed that my proposed solution was both valid and beneficial to the project.

I would like to remind you that the project follows the "First Come First Serve" principle when it comes to assigning and resolving issues. In accordance with this principle, I had made a considerable effort to understand the problem thoroughly, brainstorm a solution, and implement it in a way that adhered to the project's guidelines and best practices. I dedicated significant time and energy to ensure the quality and correctness of the code in my PR.

To my surprise, upon submitting my PR, I discovered that a similar solution had already been merged into the project. I understand that situations like this can arise due to various factors, including oversight or lack of visibility on my part. Nevertheless, I genuinely believed that my contribution would bring value to the project and that it deserved careful consideration.

Once again, I want to express my gratitude for the opportunity to contribute to this project and for your ongoing commitment to its maintenance. I sincerely hope that we can engage in a constructive dialogue regarding my concerns, as I am eager to learn and grow as a member of this community.

Thank you for your time and consideration.

Yours sincerely,

Devasya

2023-05-28 09:36 UTC, rupali-codes commented
If you don't want to close the PR unmerged, kindly refere replacing the resources with something else.
You may add [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

2023-05-28 10:11 UTC, devasyarajguru commented
> If you don't want to close the PR unmerged, kindly refer replacing the resources with something else. You may add [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

Ohkay so can I replace this resource in this PR only?

2023-05-28 12:13 UTC, rupali-codes commented
> > If you don't want to close the PR unmerged, kindly refer replacing the resources with something else. You may add [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
> 
> Ohkay so can I replace this resource in this PR only?

yeah

2023-05-31 06:28 UTC, devasyarajguru commented
> > > If you don't want to close the PR unmerged, kindly refer replacing the resources with something else. You may add [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
> > 
> > 
> > Ohkay so can I replace this resource in this PR only?
> 
> yeah, can also do in the issue, so it won't create confusions

Updated the website link as mentioned by @rupali-codes . Also updated issue which closes #674. Title and Description updated of PR #749

2023-05-31 11:05 UTC, rupali-codes requested changes
Hey, just remove the empty line, other than that, looks great to me

2023-05-31 17:40 UTC, CBID2 commented on database/opensource/blogs.json
> +      "description": "This blog will help you to resolve merge conflict on Github",
[Proofreading]
```suggestion
      "description": "This blog will help you to resolve merge conflicts on GitHub",
```

2023-05-31 17:41 UTC, CBID2 requested changes
Hi @devasyarajguru! :) I pointed out some proofreading errors that could be improved.

2023-05-31 17:54 UTC, rupali-codes commented
> Hi @devasyarajguru! :) I pointed out some proofreading errors that could be improved.

let's merge it, 😄

2023-05-31 17:55 UTC, rupali-codes commented
@CBID2 could you approve the PR please :)

2023-05-31 17:55 UTC, rupali-codes approved these changes

2023-05-31 18:52 UTC, devasyarajguru commented
> Hi @devasyarajguru! :) I pointed out some proofreading errors that could be improved.

What are proofreading errors? I don't know , I am contributing first time. And No problem , it would be great for me to improve this particular thing and then afterwards you can merge my PR. It would be great for me if you help me pointing out my improvements! Thanks! @rupali-codes @CBID2

2023-05-31 18:54 UTC, CBID2 approved these changes
LGTM!

2023-05-31 19:11 UTC, CBID2 commented
> Hey @CBID2 and @rupali-codes . Thanks for co-operating and supporting me. I want to know is there any improvement to do in this PR? Also @CBID2 I want to make sure that I will improve upon the last comment you gave me about proofreading errors. I want to know is there anything from my side on this now?

You’re welcome @devasyarajguru! We just need @rupali-codes to force push your PR. As far as improving on this pull request, not necessary

2023-06-01 06:24 UTC, merged

2023-06-01 06:44 UTC, devasyarajguru commented
Thank You very much @rupali-codes and @CBID2 . You guys are very supportive and active. It was great collaborating with you!😊

2023-06-03 09:01 UTC, rupali-codes commented
> Thank You very much @rupali-codes and @CBID2 . You guys are very supportive and active. It was great collaborating with you!😊

Its great to have you :)
Thanks