[fix] Create issue template for proposing new categories
rupali-codes/LinksHub pull request #760
Opened 2023-05-26 18:19 UTC by CBID2

## Issues
Closes [757(https://github.com/rupali-codes/LinksHub/issues/757)

## Changes proposed
Per @Anmol-Baranwal's suggestion in [757](https://github.com/rupali-codes/LinksHub/issues/757), I created a new issue template to make it easier for contributors to suggest new categories. 

## Screenshots

![screenshot for PR](https://github.com/rupali-codes/LinksHub/assets/105683440/92a1cd8e-2792-4cf5-9475-8b3035d422e6)

## Note to reviewers
Hey @Anmol-Baranwal, here's the issue template for the new category. Feel free to make the necessary changes.

2023-05-26 18:42 UTC, Anmol-Baranwal commented
This is in markdown `(.md)` format, and it is pretty outdated. Additionally, new contributors face several challenges in creating a proper issue due to the lack of strict guidelines. As a result, it can be difficult for maintainers to review and handle these issues, especially when they receive pull requests with different styles.

To address this, we should consider adding an issue template in `.yml` format, similar to what has been done in the repository at: https://github.com/rupali-codes/LinksHub/tree/main/.github/ISSUE_TEMPLATE.

> I will provide the necessary changes by tomorrow morning.

2023-05-26 18:45 UTC, CBID2 commented
> This is in markdown `(.md)` format, and it is pretty outdated. Additionally, new contributors face several challenges in creating a proper issue due to the lack of strict guidelines. As a result, it can be difficult for maintainers to review and handle these issues, especially when they receive pull requests with different styles.
> 
> To address this, we should consider adding an issue template in `.yml` format, similar to what has been done in the repository at: https://github.com/rupali-codes/LinksHub/tree/main/.github/ISSUE_TEMPLATE.
> 
> > I will provide the necessary changes by tomorrow morning, specifically before 10 AM.

Ok thanks @Anmol-Baranwal! :)

2023-05-27 04:55 UTC, Anmol-Baranwal requested changes
As discussed before, please change the template from markdown to issue form (i.e., YAML). Additionally, add a label with `goal: new-category`. Please review them, and feel free to ask me any questions you may have.

Please assign this issue to me as well :)

```yml
name: "Category Request ⚡"
description: I would like to request a feature.
title: "[ADD] <write the name of category/subcategory>"
labels: ["chore", "goal: new-category"]
body:
  - type: input
    id: concise_category
    attributes:
      label: "Category Name"
      description: "If you are adding to an existing category, please write 'none'"
      placeholder: "Enter the name of the category."
    validations:
      required: true
  - type: input
    id: concise_subcategory
    attributes:
      label: Subcategory Name
      description: Please write the relevant subcategory that can be added for the category.
      placeholder: For example "images", "fonts", "colors", "illustrations"
    validations:
      required: true
  - type: textarea
    id: additional_context_category
    attributes:
      label: "Additional Context"
      description: If you have any additional context or information that may help us understand the category/subcategory better, please provide it here
      placeholder: You can write why this category should be included in the LinksHub.
    validations:
      required: false
  - type: checkboxes
    id: terms_checklist
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rupali-codes/LinksHub/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have checked that this category does not exist
          required: false
        - label: I have checked that this subcategory does not exist
          required: true
        - label: I am willing to work on this issue (optional)
          required: false
        - label: "I am a GSSoC'23 contributor"
          required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to suggest a new request! Your input is greatly appreciated.
```

<br>

![Issue Form](https://github.com/rupali-codes/LinksHub/assets/74038190/bf7d4382-38f8-4096-90de-05c6f135b5e8)

2023-05-27 04:58 UTC, CBID2 commented
> As discussed before, please change the template from markdown to issue form (i.e., YAML). Additionally, add a label with `goal: new-category`. Please review them, and feel free to ask me any questions you may have.
> 
> 
> 
> Please assign this issue to me as well :)
> 
> 
> 
> ```yml
> 
> name: "Category Request ⚡"
> 
> description: I would like to request a feature.
> 
> title: "[ADD] <write the name of category/subcategory>"
> 
> labels: ["chore", "goal: new-category"]
> 
> body:
> 
>   - type: input
> 
>     id: concise_category
> 
>     attributes:
> 
>       label: "Category Name"
> 
>       description: "If you are adding to an existing category, please write 'none'"
> 
>       placeholder: "Enter the name of the category."
> 
>     validations:
> 
>       required: true
> 
>   - type: input
> 
>     id: concise_subcategory
> 
>     attributes:
> 
>       label: Subcategory Name
> 
>       description: Please write the relevant subcategory that can be added for the category.
> 
>       placeholder: For example "images", "fonts", "colors", "illustrations"
> 
>     validations:
> 
>       required: true
> 
>   - type: textarea
> 
>     id: additional_context_category
> 
>     attributes:
> 
>       label: "Additional Context"
> 
>       description: If you have any additional context or information that may help us understand the category/subcategory better, please provide it here
> 
>       placeholder: You can write why this category should be included in the LinksHub.
> 
>     validations:
> 
>       required: false
> 
>   - type: checkboxes
> 
>     id: terms_checklist
> 
>     attributes:
> 
>       label: Checklist
> 
>       description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rupali-codes/LinksHub/blob/main/CODE_OF_CONDUCT.md)
> 
>       options:
> 
>         - label: I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
> 
>           required: true
> 
>         - label: I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> 
>           required: true
> 
>         - label: I have checked that this category does not exist
> 
>           required: false
> 
>         - label: I have checked that this subcategory does not exist
> 
>           required: true
> 
>         - label: I am willing to work on this issue (optional)
> 
>           required: false
> 
>         - label: "I am a GSSoC'23 contributor"
> 
>           required: false
> 
>   - type: markdown
> 
>     attributes:
> 
>       value: Thank you for taking the time to suggest a new request! Your input is greatly appreciated.
> 
> ```
> 
> 
> 
> <br>
> 
> 
> 
> ![Issue Form](https://github.com/rupali-codes/LinksHub/assets/74038190/bf7d4382-38f8-4096-90de-05c6f135b5e8)
> 
> 
> 
> 

Done @Anmol-Baranwal! :)

2023-05-27 05:05 UTC, CBID2 commented
> As discussed before, please change the template from markdown to issue form (i.e., YAML). Additionally, add a label with `goal: new-category`. Please review them, and feel free to ask me any questions you may have.
> 
> 
> 
> Please assign this issue to me as well :)
> 
> 
> 
> ```yml
> 
> name: "Category Request ⚡"
> 
> description: I would like to request a feature.
> 
> title: "[ADD] <write the name of category/subcategory>"
> 
> labels: ["chore", "goal: new-category"]
> 
> body:
> 
>   - type: input
> 
>     id: concise_category
> 
>     attributes:
> 
>       label: "Category Name"
> 
>       description: "If you are adding to an existing category, please write 'none'"
> 
>       placeholder: "Enter the name of the category."
> 
>     validations:
> 
>       required: true
> 
>   - type: input
> 
>     id: concise_subcategory
> 
>     attributes:
> 
>       label: Subcategory Name
> 
>       description: Please write the relevant subcategory that can be added for the category.
> 
>       placeholder: For example "images", "fonts", "colors", "illustrations"
> 
>     validations:
> 
>       required: true
> 
>   - type: textarea
> 
>     id: additional_context_category
> 
>     attributes:
> 
>       label: "Additional Context"
> 
>       description: If you have any additional context or information that may help us understand the category/subcategory better, please provide it here
> 
>       placeholder: You can write why this category should be included in the LinksHub.
> 
>     validations:
> 
>       required: false
> 
>   - type: checkboxes
> 
>     id: terms_checklist
> 
>     attributes:
> 
>       label: Checklist
> 
>       description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rupali-codes/LinksHub/blob/main/CODE_OF_CONDUCT.md)
> 
>       options:
> 
>         - label: I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
> 
>           required: true
> 
>         - label: I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> 
>           required: true
> 
>         - label: I have checked that this category does not exist
> 
>           required: false
> 
>         - label: I have checked that this subcategory does not exist
> 
>           required: true
> 
>         - label: I am willing to work on this issue (optional)
> 
>           required: false
> 
>         - label: "I am a GSSoC'23 contributor"
> 
>           required: false
> 
>   - type: markdown
> 
>     attributes:
> 
>       value: Thank you for taking the time to suggest a new request! Your input is greatly appreciated.
> 
> ```
> 
> 
> 
> <br>
> 
> 
> 
> ![Issue Form](https://github.com/rupali-codes/LinksHub/assets/74038190/bf7d4382-38f8-4096-90de-05c6f135b5e8)
> 
> 
> 
> 

Ugh I keep getting the formatting wrong @Anmol-Baranwal

2023-05-27 07:44 UTC, rupali-codes commented
@CBID2 you'll have to write the keys in side double-quotes, just like this one 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/a7fb160e-6e70-4774-a0c1-24bb751549f5)

2023-05-27 09:34 UTC, Anmol-Baranwal commented
@CBID2 
I apologize for not checking the notification earlier as I was tired.

Anyway, here is the code after incorporating the changes suggested by Rupali. 

> Please consult with her regarding the direct issue link without the 'is: open' filter.

```yml
name: "Category Request ⚡"
description: I would like to request a feature.
title: "[ADD] <write the name of category/subcategory>"
labels: ["chore", "goal: new-category"]
body:
  - type: input
    id: concise_category
    attributes:
      label: "Category Name"
      description: "If you are adding to an existing category, please write 'none'"
      placeholder: "Enter the name of the category."
    validations:
      required: true
  - type: input
    id: concise_subcategory
    attributes:
      label: "Subcategory Name"
      description: "Please write the relevant subcategory that can be added for the category."
      placeholder: "For example 'images', 'fonts', 'colors', 'illustrations'"
    validations:
      required: true
  - type: textarea
    id: additional_context_category
    attributes:
      label: "Additional Context"
      description: "If you have any additional context or information that may help us understand the category/subcategory better, please provide it here"
      placeholder: "You can write why this category should be included in the LinksHub."
    validations:
      required: false
  - type: checkboxes
    id: terms_checklist
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rupali-codes/LinksHub/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)"
          required: true
        - label: "I have checked that this category does not exist"
          required: false
        - label: "I have checked that this subcategory does not exist"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
        - label: "I am a GSSoC'23 contributor"
          required: false
  - type: markdown
    attributes:
      value: "Thank you for taking the time to suggest a new request! Your input is greatly appreciated."
```

> You can create a private repository, then create a branch, and work on it because the preview feature doesn't function properly in this case.

2023-05-27 09:40 UTC, Anmol-Baranwal commented
I am here to assist you. If you need any help, feel free to ask. What I have done is:

- Set the label as: "I am willing to work on this issue (optional)"

I have used double quotes to enclose the values of the keys. In this case, the key is "label" and the value is the sentence itself.

2023-05-27 09:45 UTC, Anmol-Baranwal commented
I have noticed a slight mistake. The issue states that it is a level 2 category for GSSOC, while the PR suggests a level 3 category for GSSOC. Please make the necessary adjustments to fix this discrepancy.

2023-05-27 11:09 UTC, CBID2 commented
> @CBID2 I apologize for not checking the notification earlier as I was tired.
> 
> Anyway, here is the code after incorporating the changes suggested by Rupali.
> 
> > Please consult with her regarding the direct issue link without the 'is: open' filter.
> 
> ```yaml
> name: "Category Request ⚡"
> description: I would like to request a feature.
> title: "[ADD] <write the name of category/subcategory>"
> labels: ["chore", "goal: new-category"]
> body:
>   - type: input
>     id: concise_category
>     attributes:
>       label: "Category Name"
>       description: "If you are adding to an existing category, please write 'none'"
>       placeholder: "Enter the name of the category."
>     validations:
>       required: true
>   - type: input
>     id: concise_subcategory
>     attributes:
>       label: "Subcategory Name"
>       description: "Please write the relevant subcategory that can be added for the category."
>       placeholder: "For example 'images', 'fonts', 'colors', 'illustrations'"
>     validations:
>       required: true
>   - type: textarea
>     id: additional_context_category
>     attributes:
>       label: "Additional Context"
>       description: "If you have any additional context or information that may help us understand the category/subcategory better, please provide it here"
>       placeholder: "You can write why this category should be included in the LinksHub."
>     validations:
>       required: false
>   - type: checkboxes
>     id: terms_checklist
>     attributes:
>       label: "Checklist"
>       description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rupali-codes/LinksHub/blob/main/CODE_OF_CONDUCT.md)"
>       options:
>         - label: "I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)"
>           required: true
>         - label: "I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)"
>           required: true
>         - label: "I have checked that this category does not exist"
>           required: false
>         - label: "I have checked that this subcategory does not exist"
>           required: true
>         - label: "I am willing to work on this issue (optional)"
>           required: false
>         - label: "I am a GSSoC'23 contributor"
>           required: false
>   - type: markdown
>     attributes:
>       value: "Thank you for taking the time to suggest a new request! Your input is greatly appreciated."
> ```
> 
>  > You can create a private repository, then create a branch, and work on it because the preview feature doesn't function properly in this case.
> 
> I am here to assist you. If you need any help, feel free to ask. What I have done is:
> 
> * Set the label as: "I am willing to work on this issue (optional)"
> 
> I have used double quotes to enclose the values of the keys. In this case, the key is "label" and the value is the sentence itself.

Hey @Anmol-Baranwa. It still does not work. Could you maybe add the changes via inline comments like I do for your suggestions?

2023-05-27 17:56 UTC, Anmol-Baranwal requested changes
I believe that after these changes, the template will be ready for use :)

2023-05-27 17:56 UTC, Anmol-Baranwal commented on .github/ISSUE_TEMPLATE/---category-suggestion.yml
> +---
This will not be present, and is likely the reason for the error.

2023-05-27 17:56 UTC, Anmol-Baranwal commented on .github/ISSUE_TEMPLATE/---category-suggestion.yml
> +---
This will not be present, and is likely the reason for the error.

2023-05-27 17:56 UTC, Anmol-Baranwal commented on .github/ISSUE_TEMPLATE/---category-suggestion.yml
> +description: "I would like to request a feature."
```suggestion
description: "Use this to add new category/subcategory into the Hub"
```

This description aligns with the format used in other issue forms within the repository, ensuring consistency.

2023-05-27 18:00 UTC, CBID2 commented
> I believe that after these changes, the template will be ready for use :)

Done @Anmol-Baranwal

2023-05-27 19:49 UTC, Anmol-Baranwal approved these changes

2023-05-28 07:24 UTC, rupali-codes commented
Looks good though, but idk why it's showing links like this

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/a9a66771-ec6d-44e2-aca3-a60a0bf5ea46)

2023-05-28 07:36 UTC, Anmol-Baranwal commented
@rupali-codes 
I have already mentioned earlier:

>Please consult with her regarding the direct issue link without the 'is: open' filter.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/93305446-cf33-47fe-921e-d6953b6ba2a7)

The issue is that people typically search for open issues, but that is not always the case. It's up to your preference whether you want to include the direct issue link: `https://github.com/rupali-codes/LinksHub/issues`.
Since it is a YAML issue form, the link will be visible in the preview but not when someone submits the issue.


Issue link without the `is: open` filter: `https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+`
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/8259c2ea-dd83-494b-a687-549fb50c2706)

2023-05-28 07:39 UTC, rupali-codes commented
> @rupali-codes I have already mentioned earlier:
> 
> > Please consult with her regarding the direct issue link without the 'is: open' filter.
> 
> ![image](https://user-images.githubusercontent.com/74038190/241518216-93305446-cf33-47fe-921e-d6953b6ba2a7.png)
> 
> The issue is that people typically search for open issues, but that is not always the case. It's up to your preference whether you want to include the direct issue link: `https://github.com/rupali-codes/LinksHub/issues`. Since it is a YAML issue form, the link will be visible in the preview but not when someone submits the issue.
> 
> Issue link without the `is: open` filter: `https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+` ![image](https://user-images.githubusercontent.com/74038190/241518914-8259c2ea-dd83-494b-a687-549fb50c2706.png)

Okay, thanks,, we are ready to merge then :)

2023-05-28 07:40 UTC, rupali-codes approved these changes
looks good to me

2023-05-28 07:40 UTC, merged