Full stack Web Development YT link added
rupali-codes/LinksHub pull request #773
Opened 2023-05-27 11:18 UTC by khushbumaheshwarii

## Fixes Issue #761 

 
## Changes proposed

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/81244936/1088a687-5c0d-4dfd-b5c1-2567aeeaaf17)

2023-05-27 14:28 UTC, navharsh approved these changes
LGTM! 😄

2023-05-27 16:55 UTC, pratyushmp approved these changes

2023-05-27 17:09 UTC, ujjawaltyagii approved these changes
Lgtm 👍

2023-05-28 07:38 UTC, rupali-codes commented
@khushbumaheshwarii could you please resolve merge conflicts?

2023-05-28 09:00 UTC, khushbumaheshwarii commented
> @khushbumaheshwarii could you please resolve merge conflicts?
 i will do it soon give me some time

2023-05-28 09:34 UTC, rupali-codes commented
> > @khushbumaheshwarii could you please resolve merge conflicts?
> > i will do it soon give me some time

Sure, also please reference the respective issue

2023-05-28 10:08 UTC, khushbumaheshwarii commented
> > > @khushbumaheshwarii could you please resolve merge conflicts?
> > > i will do it soon give me some time
> 
> Sure, also please reference the respective issue

can you please review conflicts changes

2023-05-28 15:51 UTC, CBID2 commented on database/youtube/web-development.json
> +    "description": "This is one of the Best Free Beginner to Advance course for all those people who wants to learn Full Stack Web Development",
[Proofreading]
```suggestion
    "description": "This is one of the best free beginner to advanced course for people who want to learn Full Stack Web Development",
```

2023-05-28 15:52 UTC, CBID2 requested changes
Hi @khushbumaheshwarii! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-05-29 06:19 UTC, CBID2 approved these changes
LGTM!

2023-05-29 16:43 UTC, rupali-codes commented on database/youtube/web-development.json
> +    "language": "Hindi"
```suggestion
    "language": "hindi"
```

2023-05-29 16:55 UTC, khushbumaheshwarii reviewed
made changes

2023-05-29 17:05 UTC, rupali-codes approved these changes
lgtm

2023-05-29 17:08 UTC, merged