Added the links in the youtube section sucessfully
rupali-codes/LinksHub pull request #787
Opened 2023-05-27 19:31 UTC by Soumyajit2825

Added 2 resources in the youtube section under web-development. 

This closes #783 and #782 

## Screenshots

![Screenshot 2023-05-28 010059](https://github.com/rupali-codes/LinksHub/assets/100519291/31f935ec-3f1c-4477-ab06-593d5a3c03db)

2023-05-27 19:52 UTC, ujjawaltyagii approved these changes
Looks good to me 👍

2023-05-28 04:16 UTC, CBID2 approved these changes
Great job @Soumyajit2825! 😄 LGTM! 😄

2023-05-28 07:44 UTC, rupali-codes requested changes
@Soumyajit2825 could you please format the code?

2023-05-28 07:57 UTC, Soumyajit2825 commented
> @Soumyajit2825 could you please format the code?

Can you please brief me 
Which I have to format in the code?? @rupali-codes

2023-05-28 08:23 UTC, rupali-codes commented
> > @Soumyajit2825 could you please format the code?
> 
> Can you please brief me Which I have to format in the code?? @rupali-codes

This file 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/1a088ebd-c332-4bc5-b983-4bd0c5cfba4d)

2023-05-28 08:34 UTC, Soumyajit2825 commented
@rupali-codes It's already formatted
You're viewing the soft-wrap view 
Switch to no-wrap view then you can see that the code is formatted already

2023-05-28 09:29 UTC, rupali-codes commented on database/youtube/web-development.json
> +    {
```suggestion
   {
```

2023-05-28 09:30 UTC, rupali-codes approved these changes

2023-05-28 09:31 UTC, merged