Chore: add Accessibility subcategory and resources to Frontend
rupali-codes/LinksHub pull request #799
Opened 2023-05-28 10:12 UTC by ha-anna

Closes #794 

## Changes proposed

- Added `accessibility.json` to frontend folder
- Added resources to the `accessibility.json` 
- Added ` { name: 'accessibility', url: '/accessibility' }` to `database/data.ts`
- Added `export { default as accessibility } from './frontend/accessibility.json'` to `database/index.ts`

## Screenshots

![Screen Shot 2023-05-28 at 7 09 29 PM](https://github.com/rupali-codes/LinksHub/assets/83631167/a8013437-dc6f-40df-9930-9615e671163c)
![Screen Shot 2023-05-28 at 7 09 43 PM](https://github.com/rupali-codes/LinksHub/assets/83631167/0f95513c-ff52-405a-8ae0-5d442baeb0c9)
![Screen Shot 2023-05-28 at 7 09 20 PM](https://github.com/rupali-codes/LinksHub/assets/83631167/09762979-96f7-4dfe-b156-be9d6ed59a99)

## Note to reviewers

Hope everything checks out, thanks.

2023-05-28 12:16 UTC, rupali-codes submitted a review, later dismissed
lgtm

2023-05-28 15:34 UTC, CBID2 commented on database/frontend/accessibility.json
> +    "description": "Accessibility Checklist made by The A11y Project. It uses The Web Content Accessibility Guidelines (WCAG) as a reference point, which is a shared standard for web content accessib
[Proofreading]
```suggestion
    "description": “ This checklist uses The Web Content Accessibility Guidelines (WCAG) as a reference point, which is a shared standard for web content accessibility for individuals, organizations, and governments.",
```

2023-05-28 15:35 UTC, CBID2 requested changes
Hi @ha-anna! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-05-28 19:17 UTC, CBID2 submitted a review, later dismissed
LGTM! 😊

2023-05-29 02:50 UTC, ha-anna commented
> Hi @ha-anna! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

Oops, my bad! Thank you for fixing that, will make sure to not make the same mistake again. 🙆🏻‍♀️

2023-05-29 16:50 UTC, rupali-codes commented
Your vercel deployment is getting failed because of the following errors, could you please resolve them?

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/575aa4a2-d8f6-4d4b-aac5-3754fca858c0)

2023-05-30 02:27 UTC, ha-anna commented
> Your vercel deployment is getting failed because of the following errors, could you please resolve them?
> 
> ![image](https://user-images.githubusercontent.com/78981177/241776767-575aa4a2-d8f6-4d4b-aac5-3754fca858c0.png)

Sure, seems something went wrong after the changes were made, I'll look into it!

2023-05-30 02:30 UTC, ha-anna commented
@rupali-codes Seems everything is working now!

2023-05-30 04:54 UTC, rupali-codes approved these changes
lgtm

2023-05-30 04:54 UTC, rupali-codes commented
> @rupali-codes Seems everything is working now!

Thanks

2023-05-30 04:55 UTC, merged