chore: add eloquent javascript e-book to resources
rupali-codes/LinksHub pull request #805
Opened 2023-05-28 13:33 UTC by 0xabdulkhalid

## Fixes Issue

- Closes #800

## Changes proposed

- Added '*Eloquent JavaScript*' e-book for resources at `e-book.js` file

## Screenshots

![Screenshot 2023-05-28 at 18-59-44 LinksHub A hub of ready-to-use tech resources](https://github.com/rupali-codes/LinksHub/assets/92252895/f27b617b-caae-47e8-8e4f-b12b55964016)

## Note to reviewers

2023-05-28 15:29 UTC, CBID2 commented on database/resources/e-book.json
> +        "description": "Eloquent JavaScript is all about JavaScript, programming, and the wonders of the digital. You can read it online it's completely revised and updated, one of the best-selling e
```suggestion
        "description": "Eloquent JavaScript is an e-book that describes the wonders of Javascript andd provides exercises on creating real applications.",

```

2023-05-28 15:30 UTC, CBID2 requested changes
Hi @0xabdulkhalid! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-05-28 15:37 UTC, 0xabdulkhalid commented
Yeah @CBID2, i have resolved the typo!

Here's the updated typo: `"Eloquent JavaScript is an e-book that describes the wonders of Javascript and provides exercises on creating real world applications."`

2023-05-28 15:41 UTC, CBID2 approved these changes
LGTM!

2023-05-29 08:56 UTC, 0xabdulkhalid commented
Greetings @rupali-codes, please consider to review this PR so that i can create another issue to work on it

Regards

2023-05-29 17:11 UTC, rupali-codes approved these changes
lgtm

2023-05-29 17:12 UTC, merged