Added new open source project
rupali-codes/LinksHub pull request #807
Opened 2023-05-28 15:31 UTC by ujjawaltyagii

### Added a project which helps user to connect with experienced maintainers, and find collaborators to work with !

## Fixes Issue

Closes : #735 

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/115401171/0f934767-29ae-42ea-86ad-267717c149b0)

2023-05-28 15:38 UTC, CBID2 commented on database/opensource/projects.json
> +    "description": "It's a open-source platform to connect with experienced maintainers, and collaborate with a community of passionate contributors.",
[Proofreading]
```suggestion
    "description": "It's an open source platform where new maintainers can connect with experienced maintainers, and collaborate with a community of passionate contributors.",
```

2023-05-28 15:40 UTC, CBID2 requested changes
Hi @ujjawaltyagii! :) I just made a proofreading suggestion in my inline comment. You’re off to a great start! :)

2023-05-28 16:28 UTC, ujjawaltyagii commented
@CBID2 done !!

2023-05-28 16:50 UTC, CBID2 approved these changes
LGTM! :)

2023-05-29 06:25 UTC, pratyushmp approved these changes
Looks good to me!

2023-05-29 06:27 UTC, merged