Add Hello World DSA
rupali-codes/LinksHub pull request #857
Opened 2023-05-31 12:49 UTC by Vidip-Ghosh

## Fixes Issue
Closes #837 

## Changes proposed

Added Hello World DSA playlist. 

## Screenshots

## Note to reviewers

2023-05-31 14:17 UTC, navharsh requested changes
You should remove firebase commit of PR #849 added here as well.

2023-05-31 14:28 UTC, Vidip-Ghosh commented
> You should remove firebase commit of PR #849 added here as well.

Yes, I have removed.

2023-05-31 15:11 UTC, navharsh submitted a review, later dismissed
LGTM!

2023-06-01 01:19 UTC, CBID2 commented on database/youtube/data-structures.json
> +    "description":"Hello World youtube channels provides C++ specific DSA Course focused on explanation of Algorithms.",
[Proofreading]
```suggestion
    "description": "This channel provides C++ specific DSA content. This course also provides explanations of Algorithms.",
```

2023-06-01 01:20 UTC, CBID2 requested changes
Hi @Vidip-Ghosh! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-06-01 04:39 UTC, Vidip-Ghosh commented
> Hi @Vidip-Ghosh! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

Yes I made changes

2023-06-01 21:56 UTC, CBID2 submitted a review, later dismissed
LGTM! :)

2023-06-02 08:10 UTC, rupali-codes approved these changes

2023-06-03 19:54 UTC, CBID2 approved these changes
LGTM!

2023-06-03 19:55 UTC, CBID2 commented
@rupali-codes and @ujjawaltyagii, for some reason, this PR is missing successful preview deployment.

2023-06-04 07:53 UTC, rupali-codes approved these changes

2023-06-04 07:54 UTC, merged