added geekrepos in open source tools
rupali-codes/LinksHub pull request #875
Opened 2023-06-01 08:38 UTC by Bhanuteja01

## Fixes Issue #834

## Changes proposed
added geeksrepo in open source tools

## Screenshots

## Note to reviewers

2023-06-01 17:28 UTC, rupali-codes commented on database/opensource/tools.json
>      }
```suggestion
    },
```

2023-06-01 17:29 UTC, rupali-codes requested changes
hey, please a _comma_ in line 29 after closing the curly braces

2023-06-01 17:37 UTC, rupali-codes commented
also, please update the description and add just _closes #834_ instead _closes issue #834_

2023-06-01 18:28 UTC, Bhanuteja01 commented
@rupali-codes 
can you tell me description to update in json or i need to mention  "updated the description" in PR template

2023-06-01 20:12 UTC, CBID2 requested changes
Hi @Bhanuteja01! I just commented on a proofreading error in my inline comment. In the future, consider checking the descriptions of your sources through a proofreading tool like Grammarly or spellcheck before making them your PRs.

2023-06-01 20:12 UTC, CBID2 commented on database/opensource/tools.json
> +        "description": "This site will help you to get different open source project to contribute in. You will get open-source project repos from beginner to advanced level.",
[Proofreading]
```suggestion
        "description": "Whether you're a beginner or experienced,this site will help you to find different open source projects to start your journey.",
```

2023-06-01 21:24 UTC, CBID2 submitted a review, later dismissed
LGTM! :)

2023-06-02 08:06 UTC, rupali-codes commented on database/opensource/tools.json
> +    },
```suggestion
    }
```

2023-06-02 08:08 UTC, rupali-codes approved these changes
@Bhanuteja01 please be careful about adding and removing commas :)

2023-06-02 08:09 UTC, merged

2023-06-02 08:17 UTC, Bhanuteja01 commented
@rupali-codes   @CBID2 
Thanks for guiding me 
Next time I make sure thing to be right

2023-06-03 08:59 UTC, rupali-codes commented
> @rupali-codes @CBID2 Thanks for guiding me Next time I make sure thing to be right

😊 sure, please let us know if you need any kinda help :)