chore: add AI Colors under the frontend/colors subcategory
rupali-codes/LinksHub pull request #877
Opened 2023-06-01 08:55 UTC by Anmol-Baranwal

## Fixes Issue

Closes #862 

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/24d5af86-03ec-431f-b2bb-74fc6936b100)

2023-06-01 21:31 UTC, CBID2 commented on database/frontend/colors.json
> +    "description": "Generate stunning, validated color palettes generated based on text prompts and witness their practical application as they dynamically come to life on a generated user interface,
[Proofreading] 
```suggestion
    "description": "Generate stunning, validated color palettes  based on text prompts and witness their practical application as they dynamically come to life on a generated user interface, allowing you to visualize and explore the impact of colors in real-time.",
```

2023-06-01 21:32 UTC, CBID2 requested changes
Hi @Anmol-Baranwal! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-06-02 04:23 UTC, Anmol-Baranwal commented
> Hi @Anmol-Baranwal! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

As you can see, I have checked it on Grammarly, and there were no errors. 

Anyways, I have made the changes.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3de1da62-29ee-43f9-b5a0-7d0160589e69)

2023-06-02 05:27 UTC, rupali-codes approved these changes
lgtm

2023-06-02 08:22 UTC, ujjawaltyagii approved these changes
LGTM !

2023-06-03 07:24 UTC, rupali-codes commented on database/frontend/colors.json
> +    "description": "Generate stunning, validated color palettes generated based on text prompts and witness their practical application as they dynamically come to life on a generated user interface,
ty Chirssy

2023-06-03 07:24 UTC, merged