java resources
rupali-codes/LinksHub pull request #880
Opened 2023-06-01 11:10 UTC by P766-spec

Hello @rupali-codes , I have done with adding java resources from which I particularly learned java, not just resources added youtube channels also!
So if you found it valuable contribution so please accept it.
Thank you!

2023-06-01 17:59 UTC, rupali-codes commented
@P766-spec hey could you please reference the issue correctly? please add _closes #703_ in the description of your PR

2023-06-01 19:07 UTC, P766-spec commented
Done!

2023-06-01 19:08 UTC, P766-spec commented
I have done nothing with .vscode , could you please specify what exactly I got to do??

2023-06-01 19:16 UTC, P766-spec commented
Okay got with .vscode wala , Donw with uncommit
now could you please review it and let me know if there is any other thing? @rupali-codes

2023-06-01 20:18 UTC, CBID2 requested changes
Hi @P766-spec! :) I found some typos and proofreading errors in your descriptions. In the future, consider proofreading your descriptions with a tool like Grammarly before submitting them as a pull request. :)

2023-06-01 20:18 UTC, CBID2 commented on database/languages/java.json
> +        "description": "This playlist contains all the fundamental concepts that every Java learner should know, Bro code teaches it in a simple manner with visualization",
[Proofreading]
```suggestion
        "description": "This playlist contains all the fundamental concepts that every Java learner should know. Bro code teaches these concepts in a simple manner with visuals",
```

2023-06-01 20:18 UTC, CBID2 commented on database/languages/java.json
> +        "description": "This site provides all basic as well some advanced topic of DSA using Java with examples",
[Proofreading]
```suggestion
        "description": "This site provides all basic and advanced lessons on DSA and Java with examples",
```

2023-06-01 20:18 UTC, CBID2 commented on database/languages/java.json
> +        "description": "This playlist covers the DSA concepts with good number of problems as well as porblems to solve DSA by yuor own",
[Typos]
```suggestion
        "description": "This playlist covers the DSA concepts with good number of problems as well as DSA exercises you solve on your own",
```

2023-06-02 03:13 UTC, P766-spec commented
Ouhhh okayyy Sorry!, will do it @rupali-codes @CBID2

2023-06-02 17:29 UTC, P766-spec commented
Done with the suggested changes! @CBID2

2023-06-02 17:31 UTC, CBID2 approved these changes
LGTM

2023-06-03 07:27 UTC, rupali-codes requested changes
@P766-spec please uncommit your changes under .vscode dir, other than that, looks good to me

2023-06-03 08:21 UTC, P766-spec commented
> @P766-spec please uncommit your changes under .vscode dir, other than that, looks good to me

I have done it already ?? didn't understood what exactly your are talking about
![Screenshot (617)](https://github.com/rupali-codes/LinksHub/assets/90417642/c0f40bd2-94e0-4269-bc0a-8044a507a673)

2023-06-03 08:56 UTC, rupali-codes commented
> > @P766-spec please uncommit your changes under .vscode dir, other than that, looks good to me
> 
> I have done it already ?? didn't understood what exactly your are talking about ![Screenshot (617)](https://user-images.githubusercontent.com/90417642/243069883-c0f40bd2-94e0-4269-bc0a-8044a507a673.png)

I can still see that in _filechanges_. I'm asking you to remove that from the PR 😊

2023-06-03 14:08 UTC, ujjawaltyagii reviewed
@P766-spec I don't think we have `Java` sub-category in `languages` section. So you basically just added bunch of resources to the database with no frontend to show those resources !

1. Try creating a new sub-category first if any category doesn't exist
2. Run and test things on your local system to see if your changes are being reflected or not and ADD screenshots in the PR description as it will save a lot of time while reviewing PR :)

2023-06-03 14:10 UTC, P766-spec commented
Okayyy sure will do it

On Sat, 3 Jun 2023, 19:38 Ujjawal Tyagi, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> @P766-spec <https://github.com/P766-spec> I don't think we have Java
> sub-category in languages section. So you basically just added bunch of
> resources to the database with no frontend to show those resources !
>
>    1. Try creating a new sub-category first if any category doesn't exist
>    2. Run and test things on your local system to see if your changes are
>    being reflected or not and ADD screenshots in the PR description as it will
>    save a lot of time while reviewing PR :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rupali-codes/LinksHub/pull/880#pullrequestreview-1459460719>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVR2T2XBTHTNPZW3PWNLMFLXJNAOFANCNFSM6AAAAAAYWYGCJM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-04 16:43 UTC, P766-spec commented
> 

I am Sorry but could you please tell me how to remove it?

2023-06-04 18:00 UTC, rupali-codes commented
@P766-spec checkout [this](https://gist.github.com/gunjanpatel/18f9e4d1eb609597c50c2118e416e6a6)

2023-06-04 18:54 UTC, P766-spec commented
> @P766-spec checkout [this](https://gist.github.com/gunjanpatel/18f9e4d1eb609597c50c2118e416e6a6)

![Screenshot (621)](https://github.com/rupali-codes/LinksHub/assets/90417642/79fd6d2e-0f63-4cd2-9064-6d0cb8133685)
what shall I do now I am new to this revert one please tell

2023-06-05 19:53 UTC, rupali-codes commented on .vscode/settings.json
> +
```suggestion
```

2023-06-06 05:51 UTC, P766-spec commented on .vscode/settings.json
> +
ok

2023-06-19 08:25 UTC, merged