update: typo for greetings.yml workflow script
rupali-codes/LinksHub pull request #892
Opened 2023-06-02 05:31 UTC by 0xabdulkhalid

## Fixes Issue
- #871 

## Changes proposed
- Some minor changes in typo of `greetings.yml` workflow script
- Changed typo for both `issue` & `pull request`

### Screenshot:
| | |
| :---: | :---: |
| **CURRENT** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/857efa4e-b10c-4733-8e07-a56998c4a5fa)| 
| **PROPOSED CHANGES** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/26849e50-5a8b-4ce3-a3b3-e06519618c12) | 

## Note to reviewers
- The required labels like `gssoc23` and necessary `level` labels are not added for the merged PR: #870.
- I'm note this here because the `GSSoC`'s Backend can't count this PR without necessary labels.
- Please make sure to add those necessary labels, Thanks!

2023-06-03 03:41 UTC, CBID2 requested changes
Just made a few tweaks @0xabdulkhali! :)

2023-06-03 03:41 UTC, CBID2 commented on .github/workflows/greetings.yml
> +          issue-message: "Hello @${author}! \n Thank you for raising this issue, your contribution is valuable to us. \n\nPlease make sure to follow our [Contributing Guidelines. 💪🏻](https://github.c
[Proofreading]
```suggestion
          issue-message: "Hello @${author}! \n Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊 \n\nPlease make sure to follow our [Contributing Guidelines. 💪🏻](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) \n\nOur review team will carefully assess the issue and reach out to you soon! 😇 \n We appreciate your patience! "
```

2023-06-03 08:00 UTC, 0xabdulkhalid commented
The typo has been updated as per your request @CBID2 !

2023-06-03 08:15 UTC, rupali-codes approved these changes

2023-06-03 13:48 UTC, CBID2 requested changes
Just made another tweak @0xabdulkhalid.

2023-06-03 13:48 UTC, CBID2 commented on .github/workflows/greetings.yml
> +          pr-message: "Thank you, @${author}, for creating this pull request and contributing to LinksHub! 💗\n\n The maintainers will review this Pull Request and provide feedback as soon as possible
[Proofreading]
```suggestion
          pr-message: "Thank you, @${author}, for creating this pull request and contributing to LinksHub! 💗\n\n The maintainers will review this Pull Request and provide feedback as soon as possible! 😇\nWe appreciate your patience and contribution, Keep up the great work! 😀"
```

2023-06-04 03:13 UTC, 0xabdulkhalid commented
Done @CBID2 !

2023-06-04 03:25 UTC, CBID2 approved these changes
LGTM! :)

2023-06-04 07:57 UTC, rupali-codes approved these changes

2023-06-04 07:57 UTC, merged