[FEATURE] Add Github link to the site #7
rupali-codes/LinksHub pull request #9
Opened 2023-01-10 20:52 UTC by JoshHargreaves

#7

Created a hard-coded GitHub link and placed it with an icon below the sidebar navigation elements.
Please let me know if you would like this to be moved.

Is the plan to have a site config model where this data could be stored rather than hard coding the link ref?

2023-01-11 08:12 UTC, rupali-codes requested changes
can u make this static as well, so user won't have to scroll and they can directly see this?

2023-01-11 08:21 UTC, rohitdasu commented
also i believe it should open in new tab rather than closing the current user session. what you think @rupali-codes

2023-01-11 20:22 UTC, JoshHargreaves commented
I have made the link open a new tab and updated the title to specify that this is an external link to make it as accessible as possible.

In terms of making the icon static, this will require a refactoring of the sidebar which I think is something that should be discussed first. It will need a fixed height and overflow added to statically display link items at the bottom. Are you sure you want to do that? 

I am not sure it is a great user experience to have a scrolling sidebar with tons of links and there are not many examples of other sites doing that.

2023-01-12 05:58 UTC, rupali-codes commented
okay, can we put it somewhere else where user can see it without scrolling the page?

2023-01-13 19:07 UTC, JoshHargreaves commented
![linkshub](https://user-images.githubusercontent.com/20206340/212399146-f46e8014-5516-401d-8cc5-4d45c64202f9.png)

2023-01-14 19:28 UTC, JoshHargreaves commented
@rupali-codes Could you let me know why the build is failing please.

2023-01-14 20:26 UTC, rupali-codes commented
@JoshHargreaves I have resolved that. now its LGTM. What are your thoughts on this @rohitdasu

2023-01-15 16:08 UTC, rohitdasu approved these changes
LGTM!

2023-01-15 17:50 UTC, rupali-codes approved these changes
good job

2023-01-15 17:52 UTC, merged