Chore: Add Muzli Colors link to colors subcategory.
rupali-codes/LinksHub pull request #942
Opened 2023-06-04 13:11 UTC by Oyebolade

## Fixes Issue
Closes #941

## Changes proposed
I added Muzli Colors link to colors subcategory

## Screenshots

![Muzlicolors](https://github.com/rupali-codes/LinksHub/assets/57053389/fe3a47dc-f0c0-44fc-8c58-65ee3d2bea9b)

## Note to reviewers

2023-06-04 18:40 UTC, rupali-codes requested changes
You have made changes in your preview commit, could you please update branch with `linkshub:main`

2023-06-05 03:51 UTC, Oyebolade commented
> You have made changes in your preview commit, could you please update branch with `linkshub:main`

Do you mean I should add the message to the PR?
I don't understand you clearly.

2023-06-06 00:24 UTC, ujjawaltyagii reviewed
It looks good to me but Ig there was some issue in your initial workflow as when I was trying to see your changes. I was getting this after reloading i saw the real changes-
![image](https://github.com/rupali-codes/LinksHub/assets/115401171/866849f9-e61b-4c43-b3dc-c48e3bd8884b)

To avoid this : Try making all the changes in your local system first and then make final commit.

2023-06-06 01:13 UTC, Oyebolade commented
> It looks good to me but Ig there was some issue in your initial workflow as when I was trying to see your changes. I was getting this after reloading i saw the real changes- ![image](https://user-images.githubusercontent.com/115401171/243513099-866849f9-e61b-4c43-b3dc-c48e3bd8884b.png)
> 
> To avoid this : Try making all the changes in your local system first and then make final commit.

Thanks @ujjawaltyagii I've pulled the request before I saw the issue.

2023-06-13 21:42 UTC, CBID2 submitted a review, later dismissed
LGTM! :)

2023-06-22 07:49 UTC, rupali-codes commented on database/frontend/colors.json
> +   {
```suggestion
  {
```

2023-06-24 11:56 UTC, ujjawaltyagii commented
Please resolve merge conflicts !

2023-06-29 14:09 UTC, k-deepak04 commented
@Oyebolade please resolve the conflicts, so that we can merge this or else let us know if you want to close this one

2023-07-02 07:03 UTC, k-deepak04 commented
@Oyebolade please resolve the conlflict

2023-07-03 03:45 UTC, CBID2 approved these changes
LGTM! :)

2023-07-03 17:22 UTC, rupali-codes approved these changes
thanks, lgtm

2023-07-03 17:22 UTC, merged