Added new youtube playlist
rupali-codes/LinksHub pull request #945
Opened 2023-06-04 16:39 UTC by Abhinavcode13

Added a new resource

## Fixes Issue
fixes issue number #869 

## Changes proposed

Added new yt playlist for learning tensorflow

2023-06-04 16:45 UTC, Abhinavcode13 commented
Please review the PR @CBID2 & @rupali-codes

2023-06-04 18:13 UTC, CBID2 requested changes
You're so close @Abhinavcode13. I just pointed out a proofreading error in my inline comment.

2023-06-04 18:13 UTC, CBID2 commented on database/youtube/tensorflow.json
> +        "description": "A complete playlist for learning Tensorflow from beginning.",
[Proofreading]
```suggestion
        "description": "A complete playlist for learning Tensorflow.",
```

2023-06-04 18:14 UTC, Abhinavcode13 commented
thanks @CBID2

2023-06-04 18:42 UTC, rupali-codes commented on database/youtube/tensorflow.json
> +        {
format this braces :)

2023-06-05 16:40 UTC, Abhinavcode13 commented
@rupali-codes & @CBID2 please check now

2023-06-06 11:11 UTC, Abhinavcode13 commented
@rupali-codes @CBID2 ??

2023-06-06 14:11 UTC, rupali-codes commented
@Abhinavcode13 could you please add _closes #issuebumber_ in the description of this PR?

2023-06-06 18:35 UTC, ujjawaltyagii approved these changes
lgtm !

2023-06-06 18:36 UTC, Abhinavcode13 commented
Can you merge @ujjawaltyagii ?

2023-06-07 05:19 UTC, merged