added codewars
rupali-codes/LinksHub pull request #947
Opened 2023-06-04 18:42 UTC by Bhanuteja01

## Fixes Issue
closes #911 

## Changes proposed
added codewars site in frontend 

## Screenshots

## Note to reviewers

2023-06-04 19:03 UTC, Bhanuteja01 commented
@CBID2  @rupali-codes 
waiting for review

2023-06-06 14:21 UTC, rupali-codes requested changes
your code doesn't follow the structure, please update it accordingly

2023-06-07 05:22 UTC, rupali-codes commented
> I apologize for my mistake

Its fine,
You don't have to remove programimz, just add the resource right after that

2023-06-07 05:33 UTC, Bhanuteja01 commented
Ok 

> > I apologize for my mistake
> 
> Its fine, You don't have to remove programmiz, just add the resource right after that

****

2023-06-08 06:21 UTC, rupali-codes commented on database/frontend/online-code-editors.json
> +    "description": "Codewars serves as an online platform offering coding challenges suited for individuals across diverse programming proficiency levels.",
```suggestion
    "description": "Codewars is an online platform that offers coding challenges suitable for individuals with diverse programming proficiency levels.",
```

2023-06-09 20:05 UTC, rupali-codes approved these changes
looks perfect, thanks

2023-06-09 20:09 UTC, merged