Added the Blockchain Projects related to issue-935
rupali-codes/LinksHub pull request #948
Opened 2023-06-04 19:14 UTC by SargamPuram

PR fixes an open issue , Closes #935 
It adds Blockchain projects in project-ideas of resources .
Kindly review this
Screenshot
![LH4](https://github.com/rupali-codes/LinksHub/assets/130867468/38061a62-f0d8-420c-868a-d874b34ad14e)

2023-06-12 21:17 UTC, CBID2 requested changes
Hi @SargamPuram! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

2023-06-13 17:54 UTC, SargamPuram commented on database/resources/project-ideas.json
> +    "description": "This website provides free fifteen Blockchain projects for beginners to advanced level with source code.",
@CBID2 thanks for pointing the error . Will make sure I won't repeat them. And will use Grammarly or Spellcheck  
I have made the changes kindly review them .

2023-06-13 23:37 UTC, CBID2 approved these changes
Great job @SargamPuram! 😄 LGTM! 😄

2023-06-15 07:29 UTC, rupali-codes approved these changes

2023-06-15 07:29 UTC, merged