Added C++ language
rupali-codes/LinksHub pull request #957
Opened 2023-06-05 14:41 UTC by anjaliSilawat

Added C++ language and its resources 
resolve issue #629

2023-06-06 14:47 UTC, rupali-codes requested changes
I have addressed a few things:
* please update your code with `linkshub:main`
* the description should be at least 15 words long
* your changes are not reflected on the site, please read & follow our [CONTRIBUTING guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) carefully

2023-06-06 20:46 UTC, anjaliSilawat commented
> I have addressed a few things:
> 
> * please update your code with `linkshub:main`
> * the description should be at least 15 words long
> * your changes are not reflected on the site, please read & follow our [CONTRIBUTING guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) carefully

@rupali-codes  I have updated the description also I update my code hope so changes are visible now on the site

2023-06-09 20:17 UTC, rupali-codes commented
@anjaliSilawat hey, please resolve the merge conflicts and your vercel deployment is getting bcz the of the following issues, kindly fix them
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/86a90cff-bc76-489f-8de6-90df4c31633f)

2023-06-11 23:04 UTC, CBID2 commented
@anjaliSilawat, can you mention the issue number that your PR solves per the [Contributing files](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#making-pull-requests) please?

2023-06-12 08:12 UTC, anjaliSilawat commented
> @anjaliSilawat, can you mention the issue number that your PR solves per the [Contributing files](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#making-pull-requests) please?

done

2023-06-12 11:52 UTC, rupali-codes commented
@anjaliSilawat can you please resolve merge conflicts

2023-06-13 06:51 UTC, anjaliSilawat commented
> @anjaliSilawat can you please resolve merge conflicts


Yes, I'll give me a little bit of time. @rupali-codes

2023-06-13 16:39 UTC, rupali-codes commented
> > @anjaliSilawat can you please resolve merge conflicts
> 
> Yes, I'll give me a little bit of time. @rupali-codes

Sure, take your time

2023-06-19 07:59 UTC, rupali-codes commented
@anjaliSilawat are you ready to work on it now?

2023-06-20 01:54 UTC, CBID2 commented on database/languages/c++.json
> +        "description": " Learn the basics of C++ it is a popular programming language.C++ is used to create computer programs, and is one of the most used language in game development.",
[Recommendation] This description mostly describes what C++ is. While helpful, I highly suggest describing **why** people in tech should use this source. 
```suggestion
        "description": " Learn the basics of C++ it is a popular programming language.C++ is used to create computer programs, and is one of the most used languages in game development.",
```

2023-06-20 01:56 UTC, CBID2 commented on database/languages/c++.json
> +        "subcategory": "C++"
[Recommendation] Use my feedback in the [previous lines](https://github.com/rupali-codes/LinksHub/pull/957/files#r1234652002) to improve these descriptions. 
```suggestion
        "name": "C++ Recent Articles! ",
        "description": "Recent Articles on C++",
        "url": "https://www.geeksforgeeks.org/category/cpp/",
        "category": "Languages",
        "subcategory": "C++"
    },
    {
        "name": "C++ Interview Questions",
        "description": "Top 50 C++ Interview Questions and Answers (2023)",
        "url": "https://www.geeksforgeeks.org/cpp-interview-questions/",
        "category": "Languages",
        "subcategory": "C++"
```

2023-06-20 01:57 UTC, CBID2 requested changes
Hi @anjaliSilawat! :) I resolved the merge conflicts from your branch. What's left to do now is revising the descriptions per my advice in my in-line comments(keep this advice in mind as you submit more pull requests to LinksHub).

2023-06-20 07:21 UTC, rupali-codes commented
@anjaliSilawat i'm closing this PR bcz you have resolved conflicts improperly, please make fresh PR and before that make sure to update your branch with `linkshub:main`.

2023-06-20 07:21 UTC, closed without merging