Add Befonts to the font category
rupali-codes/LinksHub pull request #965
Opened 2023-06-06 11:28 UTC by AhorIsaac

## Fixes Issue
#943 

## Changes proposed

Add Befonts to the font category

## Screenshots

## Note to reviewers

2023-06-06 15:49 UTC, rupali-codes commented
Please add _closes #issuenumber_ in the description of this PR as the issue is not referenced properly

2023-06-07 14:34 UTC, AhorIsaac commented
I added **closes** #issuenumber in the description of the pull request.

2023-06-09 20:15 UTC, rupali-codes commented
> I added **closes** #issuenumber in the description of the pull request.

Thanks, could you please make the suggested changes?

2023-06-09 22:48 UTC, CBID2 commented on database/frontend/fonts.json
> +        "description": "Befonts is a platform when you can download the best fonts, free fonts for personal or commercial use.",
[Proofreading]
```suggestion
        "description": "Befonts is a platform where you download the best fonts, free fonts for personal or commercial use.",
```

2023-06-09 22:53 UTC, CBID2 requested changes
Hi @AhorIsaac! I agree with @rupali-codes’ suggestion.

2023-06-10 13:12 UTC, AhorIsaac commented
I did precisely as you instructed!

2023-06-11 18:46 UTC, rupali-codes requested changes
could you please undo your changes in .gitignore file as its not the part of your issue?

2023-06-11 18:46 UTC, rupali-codes commented
Also, please resolve the merge conflicts

2023-06-13 18:13 UTC, AhorIsaac commented
Done

2023-06-13 18:16 UTC, ujjawaltyagii approved these changes
lgtm

2023-06-13 21:45 UTC, CBID2 approved these changes
LGTM! :)

2023-06-15 07:27 UTC, rupali-codes approved these changes

2023-06-15 07:28 UTC, merged