chore: Add New Resources
rupali-codes/LinksHub pull request #973
Opened 2023-06-07 13:12 UTC by Shiva-Sai-ssb

## Fixes Issue

Closes #940

## Changes proposed

I have included the following resources in their respective categories.

* Images
1) Free Photos : https://freephotos.cc/en
2) Moose : https://icons8.com/photos
3) Burst : https://burst.shopify.com/
4) Barn Images : https://barnimages.com/
5) Vecteezy : https://www.vecteezy.com/
6) Pikwizard : https://pikwizard.com/

* Icons
1) CSS Icons : https://css.gg/
2) Feather Icons : https://feathericons.com/
3) IconHub : https://iconhub.io/

* Fonts
1) FontShare : https://www.fontshare.com/

* Animations
1) AnimXYZ : https://animxyz.com/
2) Animista : https://animista.net/

* Database
1) SupaBase : https://supabase.com/
2) SurrealDB : https://surrealdb.com/

* Youtube (Web Dev)
1) Codevolution : https://www.youtube.com/@Codevolution/videos
2) Easy Tutorials : https://www.youtube.com/@EasyTutorialsVideo/videos
3) Coding Nepal : https://www.youtube.com/@CodingNepal/videos
4) Mr.Web Designer : https://www.youtube.com/@MrWebDesignerAnas/videos
5) CodingLab : https://www.youtube.com/@CodingLabYT/videos
6) dotWebDesign : https://www.youtube.com/@dotWebdesigns/videos
7) Codewithsadee : https://www.youtube.com/@codewithsadee/videos

* Youtube (Web3)
1) Alchemy : https://www.youtube.com/@AlchemyPlatform/videos
2) Daulat Hussain : https://www.youtube.com/@daulathussain/videos

## Screenshots

## Note to reviewers

2023-06-09 22:57 UTC, CBID2 commented on database/youtube/web3-metaverse.json
> +    "language": "english"
[Proofreading]
```suggestion
    "language": "hindi"
```

2023-06-09 22:58 UTC, CBID2 requested changes
Hi @Shiva-Sai-ssb! :)  I pointed out a proofreading error in my inline comment. In the future, consider checking if you’re describing the source accurately before making a pull request. Other than that, you're off to a great start! :)

2023-06-10 07:59 UTC, Shiva-Sai-ssb commented
Hello @CBID2 , I believe I have successfully resolved the conflicts in the branch. Since this is my first time handling such a task, I'm unsure if I have done it correctly. Please inform me if the conflicts have been resolved. Additionally, I did not include the CodeEater channel, and the changes occurred automatically. However, I made the changes as per your request.

2023-06-10 11:01 UTC, ujjawaltyagii approved these changes
Lgtm! Reviewing this whole lot of resources was a task in itself o_o

2023-06-11 04:21 UTC, CBID2 approved these changes
LGTM!

2023-06-11 18:42 UTC, rupali-codes approved these changes
lgtm too, thanks a lot!

2023-06-11 18:44 UTC, merged