Add : New resource in Icon subcategory
rupali-codes/LinksHub pull request #974
Opened 2023-06-07 14:16 UTC by ujjawaltyagii

## Fixes Issue

Closes : #910 

## Changes proposed

#### Added new resource in `frontend > icons`

## Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/115401171/31ba256a-85bb-4135-9250-1e3d699020d2)

2023-06-08 13:14 UTC, ujjawaltyagii reviewed
It looks good to me ! @CBID2  @rupali-codes could you review my PR :)

2023-06-09 20:30 UTC, rupali-codes commented
@ujjawaltyagii please resolve merge conflicts 😄

2023-06-10 01:25 UTC, CBID2 requested changes
Just made some edits to the description @ujjawaltyagii.

2023-06-10 01:25 UTC, CBID2 commented on database/frontend/icons.json
> +    "description": "The Vertex website offers a collection of freely available 3D icons that can be fully customized and utilized without any cost.",
[Proofreading]
```suggestion
    "description": "The Vertex website offers a collection of freely available 3D icons that can be fully customized and used for free.",
```

2023-06-10 11:18 UTC, ujjawaltyagii commented
Done with all the changes ! @rupali-codes @CBID2

2023-06-11 04:20 UTC, CBID2 approved these changes
LGTM!

2023-06-11 16:35 UTC, ujjawaltyagii commented
@rupali-codes could you review my PR

2023-06-11 18:47 UTC, rupali-codes approved these changes
looks good

2023-06-11 18:48 UTC, merged