Added Glassmorphism CSS Generator
rupali-codes/LinksHub pull request #977
Opened 2023-06-07 17:26 UTC by mohitbhusal11

## Changes proposed
Added new website (Glassmorphism CSS Generator) in Frontend UI-generator ssection

2023-06-09 20:28 UTC, rupali-codes submitted a review, later dismissed
lgtm, thanks

2023-06-09 20:29 UTC, rupali-codes commented
@ujjawaltyagii could you please review it? :)

2023-06-10 01:01 UTC, CBID2 requested changes
Hi @mohitbhusal11! :) I just made a suggestion on how to improve your description.

2023-06-10 01:01 UTC, CBID2 commented on database/frontend/ui-generators.json
> +    "description": "Glassmorphism is a new design trend which is primarely based on the blurry effect of an element and a background.",
[Proofreading]
```suggestion
    "description": "Glassmorphism is a new design technique which is primarely based on the blurry effect of an element and a background.",
```

2023-06-10 10:49 UTC, ujjawaltyagii approved these changes
Lgtm ! just commit the changes suggested by CBID2

2023-06-11 04:45 UTC, CBID2 approved these changes
LGTM!

2023-06-11 18:50 UTC, rupali-codes approved these changes
lgtm

2023-06-11 18:50 UTC, merged