Chore: added subcategory events under resource
rupali-codes/LinksHub pull request #987
Opened 2023-06-08 17:09 UTC by ayushh1804

## Fixes Issue
Fixed issue #636 Under the Resources section, add another row Hackathons and include relevant information

## Changes proposed

## Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/88641651/1e22a217-5384-42c5-bbbf-d1264401c981)

## Note to reviewers

2023-06-10 08:12 UTC, rupali-codes requested changes
@ayushh1804 it doesn't match with the category, please put this under _other_ category

2023-06-10 08:13 UTC, rupali-codes reviewed
Also, seems like your base branch is not updated, please update it with `linkshub:main`

2023-06-11 04:38 UTC, CBID2 requested changes
Hi @ayushh1804! I just commented on a description that needs improvement. 😀

2023-06-11 04:38 UTC, CBID2 commented on database/resources/events.json
> +    "description": "Getting started for a hackathon? Here is an article for your reference.This guide provides the best practices for your first Hackathon.",
[Proofreading] 
```suggestion
    "description": "Are you attending your first hackathon? Check out this article! It provides tips to help you get started.",
```

2023-06-16 08:42 UTC, ayushh1804 commented
> Hi @ayushh1804! I just commented on a description that needs improvement. 😀

done...thanks for the suggestion😊

2023-06-16 08:43 UTC, ayushh1804 commented
> @ayushh1804 it doesn't match with the category, please put this under _other_ category

done

2023-06-16 11:00 UTC, CBID2 approved these changes
Lgtm

2023-06-17 09:45 UTC, rupali-codes approved these changes
thanks, looks good to me

2023-06-17 12:54 UTC, CBID2 approved these changes
LGTM!

2023-06-18 09:03 UTC, merged