Frontendmentor
rupali-codes/LinksHub pull request #995
Opened 2023-06-10 04:52 UTC by parma1111

## Fixes Issue

Closes #990 

## Changes proposed

Solve real-world HTML, CSS and JavaScript challenges whilst working to professional designs. Join 632,729 developers building projects, reviewing code, and helping each other get better.

## Screenshots

## Note to reviewers

Any kind of feedback would be appreciated.

2023-06-10 09:57 UTC, rupali-codes requested changes
Please update the description to what the site actually provides :)

2023-06-10 11:39 UTC, parma1111 commented
> Please update the description to what the site actually provides :)

> Hey @rupali-codes :) It's done, now review the PR.

2023-06-11 04:19 UTC, CBID2 requested changes
Hi @parma1111! :) I made a suggestion on how to one of your descriptions.

2023-06-11 04:19 UTC, CBID2 commented on database/frontend/ui-generators.json
> +    "description": "This site solve real-world HTML, CSS and JavaScript challenges whilst working to professional designs.",
[Proofreading]
```suggestion
    "description": "This site solve real-world HTML, CSS, and JavaScript challenges whilst working to professional designs.",
```

2023-06-11 05:05 UTC, parma1111 commented on database/frontend/ui-generators.json
> +    "description": "This site solve real-world HTML, CSS and JavaScript challenges whilst working to professional designs.",
Hey @CBID2 :) done , now review the PR

2023-06-11 14:00 UTC, CBID2 approved these changes
LGTM!

2023-06-11 17:01 UTC, ujjawaltyagii approved these changes
lgtm !

2023-06-11 18:52 UTC, rupali-codes approved these changes

2023-06-11 18:53 UTC, merged