added Django Forbid
rupali-codes/LinksHub pull request #998
Opened 2023-06-10 07:08 UTC by Bhanuteja01

## Fixes Issue
closes #946 

## Changes proposed
added Django forbid in the backend

## Screenshots

## Note to reviewers

2023-06-10 10:02 UTC, ArtyomVancyan commented on database/backend/security.json
> +    "description": "Django Forbid provides documentation for a growing OSS tool forbidding geolocated individuals in forbidden countries, regions, and territories.",
```suggestion
    "description": "Secure your Django app by controlling the access - grant or deny user access based on device and location, including VPN detection.",
```

2023-06-10 10:05 UTC, ArtyomVancyan commented on database/backend/security.json
> +    "description": "Django Forbid provides documentation for a growing OSS tool forbidding geolocated individuals in forbidden countries, regions, and territories.",
Hey @Bhanuteja01, thanks for adding [Django Forbid](https://github.com/pysnippet/django-forbid). Could you please change the description of the project as it is in its GitHub repository?

2023-06-11 04:25 UTC, CBID2 requested changes
Hi there @Bhanuteja01. I provided a suggestion on how improve the description! 😀

2023-06-11 04:25 UTC, CBID2 commented on database/backend/security.json
> +    "description": "Secure your Django app by controlling the access - grant or deny user access based on device and location, including VPN detection.",
[Proofreading]
```suggestion
    "description": "This source helps grant or deny user access to Django apps based on device and location, including VPN detection.",
```

2023-06-11 14:01 UTC, CBID2 approved these changes
LGTM!

2023-06-11 16:45 UTC, ujjawaltyagii approved these changes
LGTM

2023-06-11 18:55 UTC, rupali-codes approved these changes

2023-06-11 18:56 UTC, merged